### PR TITLE
Clear the cache in when editing GrantsCLR Admin

### LINKED ISSUE #7903: admin: add cache burst command to GrantCLR
Allow admins to bust the GrantCLR cache (so they have confidence in the admin is working)

Have an button within 
https://gitcoin.co/_administrationgrants/grantclr/
which runs 

```
        create_grant_type_cache()
        create_grant_clr_cache()
        create_grant_category_size_cache()
        create_grant_active_clr_mapping()
```

which is defined in create_page_cache
code link: https://github.com/gitcoinco/web/blob/master/app/perftools/management/commands/create_page_cache.py#L387-L390

reason for doing this :
when admin changes certain data in grants CLR -> they have to wait for page cache to run for the UI to be updated
having an option there -> makes it quicker / less panicky for admin to make changes

### PR DESCRIPTION
**Pull request by corydickson**
##### Description

Whenever a user edits or adds a new grantclr they can click a button to clear the cache to refresh the UI.

##### Refers/Fixes

Fixes #7903 

##### Testing
Create a CLR in the admin panel add set it to active. Then modify a relevant field like start or end date to view the change in the front-end after reloading the page.

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@corydickson could you throw in a video as well ?

**Comment by corydickson** [comment]
> @corydickson could you throw in a video as well ?


https://www.dropbox.com/s/oxbksnxlf293rbi/Screen%20Recording%202020-12-10%20at%208.09.56%20PM.mov?dl=0

**Review by thelostone-mc — APPROVED** [review]

**Review by chibie — APPROVED** [review]

**Comment by octavioamu** [comment]
@thelostone-mc what about this comment? https://github.com/gitcoinco/web/issues/7903#issuecomment-730417501
Each time someone press the button will do a heavy work on the server. We are ok with that?

**Comment by apbendi** [comment]
> Each time someone press the button will do a heavy work on the server. We are ok with that?

After discussing this on the call today, we decided that it is OK for the button to clear the full cache, with one caveat: @thelostone-mc is going to test locally what happens if the button is pressed twice in quick succession.

**Review by danlipert — APPROVED** [review]

**Comment by thelostone-mc** [comment]
Closing this out as we've gotten the individual function as admin buttons

**Pull request closed without merging**
