### PR TITLE
metamask gas price preview

### PR DESCRIPTION
**Pull request by owocki**
# what

https://twitter.com/owocki/status/948304738306605056

# still TODO

## integrations

* do the 'new bounty' form.  (i've already done the claiming, clawback, and process page)
* do the 'tips' form.

# functionality

* do an estimate of how much ETH / USD it will cost on the page.
* allow user to update gas price and see an estimate of confirmation times and price on the page.
* see a warning when network conditions are clogged.

### CODE REVIEW

**Comment by owocki** [comment]
another idea:  I think bringing in a a simplified description (immediate info needed to take action) of the gas concept (from the github page) into a tooltip on the Claim Funds page is another way to solve this. It will help keep all of the information in context to the experience.

**Comment by owocki** [comment]
hat tip @pixelantdesign

**Comment by owocki** [comment]
just pushed some changes
screen recording 2018-01-02 at 11 49 pm

**Comment by mkosowsk** [comment]
I have submitted funding for this issue with a 

Gas Limit: 649619
Gas Price: 0.000000021 Ether (21 Gwei)

The gas limit I used from what Gitcoin recommended and found a suitable gas price via https://ethgasstation.info/predictionTable.php (I increased the Gas Price from 10 -> 21 Gwei because it was taking too long)

Looking forward to seeing it fund 👍🏻👍🏻👍🏻

**Comment by mkosowsk** [comment]
Hmm I may have borked this up.

This was the initial transaction that I used to try to fund this issue:

https://etherscan.io/tx/0xa43401b3701cc6b54b8bff27bef2ae13a84441ac09ab84287c7dfdf9d645d55b

But when it was taking too long I bumped up the gas price via MetaMask. It looks like that created a new tx?

https://etherscan.io/tx/0x85a6f56096f34d8d0443d49790c13f810aeb5cb9287f36f3bf50dd87b0f54c3e

Not sure if this issue will be funded properly now 😓

**Comment by owocki** [comment]
thanks for the funding @mkosowsk!  

i think im actually pretty close to merging this... let me know what else you think should be in order for the scope of this issue

**Comment by owocki** [comment]
this could be something cool to work in https://github.com/gitcoinco/skunkworks/issues/34

**Comment by owocki** [comment]
just added a nice little page to show gas data :) 
screencapture-localhost-8080-gas-1515075087776

**Comment by mkosowsk** [comment]
LGTM! Feel free to claim issue at your earliest convenience. 

This should help clear a lot of user confusion and provide a great boost to the UX 👍🏻

**Comment by mkosowsk** [comment]
Hmm when I try to Accept this claim I am seeing

screen shot 2018-01-04 at 10 21 57 am

**Comment by owocki** [comment]
hmm a caching issue i wonder?  if you hard refresh (apple shirt R) does it go away?

i just tried busting the cloudfront cache

**Comment by mkosowsk** [comment]
Yep, that was it probably left over cache when I was messing around with things! 

Sending it over 👍🏻 thanks for the help

**Comment by owocki** [comment]
hmm... i wonder if i need to revisit the cache busting strategy for gitcoin.. i had assumed that busting the cloudfront cache would do the trick... but i guess not

**Comment by mkosowsk** [comment]
Not to keep hammering you, but submitted the claim ~30 minutes and still seeing the blue alert on top of the gitcoin page

screen shot 2018-01-04 at 11 20 43 am

And when I check out the etherscan I see "Sorry, we are unable to locate this Transaction Hash
"

https://etherscan.io/tx/0x73d7d211e330b7bfedd66df6688eeb6fd9596205e8ddc382b6e591a755dc2da2

What generally happens after accepting a claim? I set a gas price of something like 23 Gwei so I think this should probably be sent over pretty quick 🤔

**Comment by owocki** [comment]
https://etherscan.io/tx/0x73d7d211e330b7bfedd66df6688eeb6fd9596205e8ddc382b6e591a755dc2da2

damn, looks like this tx is _STILL_ pending.  hard to believe it, but considering the gas price is only 5 gwei and the network has been going parabolic.. its also not that surprising.  

do you see the tx in metamask?  might be worth submitting with a higher gas price value.. 

screen shot 2018-01-08 at 5 37 00 pm

**Comment by vs77bb** [comment]
@owocki Is this one still in your hands?

**Comment by owocki** [comment]
looks like the claim finally did go through.. https://etherscan.io/tx/0x73d7d211e330b7bfedd66df6688eeb6fd9596205e8ddc382b6e591a755dc2da2

 @mkosowsk could you pay it out?

**Comment by mkosowsk** [comment]
Took a quick look and saw this, bumped Gas Price to 4 Gwei to get a 10 min confirmation

gitcoin screenshot

But after I click Accept, I see this warning:

after accepting

I have Web3 enabled and looks like I have enough Eth, so not sure where I'm messing up or if this is a bug? 🤔🤔🤔

**Comment by owocki** [comment]
oh shoot.. it looks like you actually already remitted the funds... my bad

**Comment by owocki** [comment]
running the DB sync script now

**Comment by mkosowsk** [comment]
No worries, I can only assume that this means you are getting so much cashflow from Gitcoin that it's hard to keep track 😂

@owocki irl?

https://i.ytimg.com/vi/bEmjiCoZ6e4/hqdefault.jpg

🤔

**Pull request merged**
