### PR TITLE
limit maximum input in the comments 500 chars

### PR DESCRIPTION
**Pull request by x5engine**
limit maximum input in the comments otherwise, you will get something like this

https://gitcoin.co/townsquare?tab=activity:273525

image

so better allow maximum 500 chararacters

### CODE REVIEW

**Comment by x5engine** [comment]
yeaah but where is my 1 eth :D @thelostone-mc

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#monetization-policy

**Comment by x5engine** [comment]
okay then it means, I get nothing for contributing?

**Comment by owocki** [comment]
did you read the above monetization policy

**Comment by x5engine** [comment]
okay sure

**Pull request merged**
