### PR TITLE
Add SMS validation

### PR DESCRIPTION
**Pull request by zoek1**
##### Refers/Fixes
https://github.com/gitcoinco/web/issues/6549

### CODE REVIEW

**Comment by owocki** [comment]
@zoek1 is this ready for review? i see its still in draft status. if not, pls add the testing part of the PR.  if so, pls list TODOs and expected completion date.  round 6 is coming up in only 2 weeks!

**Comment by owocki** [comment]
@zoek1 bump. we have exactly 12 days to get this tested + live...

**Comment by zoek1** [comment]
Ok, I'll give priority to this and after to #6548. :mechanical_arm:
I'll have ready ASAP, no worries :smile:

**Comment by owocki** [comment]
closing this as its already merged int he scopelift remote

**Pull request closed without merging**
