### PR TITLE
Send one mail instead of n mail to supporter on checkout of n grants

### PR DESCRIPTION
**Pull request by tarunbhm**
##### Description

- Made process_grant_contribution task return grant and created subscription objects
- Added batch_process_grant_contributions task to process multiple grants in one task
- Added batch_thank_you_for_supporting method to render and send email for multiple grant subscriptions
- Added batch_thank_you_for_supporting.html and batch_thank_you_for_supporting.txt templates
- Updated grants/views.py to use new batch_process_grant_contributions task

##### Refers/Fixes

Fixes: https://github.com/gitcoinco/web/issues/8238

### CODE REVIEW

**Comment by thelostone-mc** [comment]
could you add a video @tarunbhm ?

**Review by thelostone-mc — COMMENTED** [review]
@tarunbhm code wise this make sense !
Although as opposed to adding new email template, could we replace the old ones ?
`thank_you_for_supporting` is used in one more place  in `helper.py`

This is when grants are created using CELO / ZIL address

**Comment by tarunbhm** [comment]
@thelostone-mc Do you want to see mail in the video? I had tested by adding logs for generated mails and had verified that only one mail was generated. I wan to avoid creating an account on sendgrid.

**Comment by thelostone-mc** [comment]
@tarunbhm the email being sent out is new code added ->. they does qualify as having frontend changes
Plus having a video attached -> make it easier for the non-engineers to review the flow as well

> I had tested by adding logs for generated mails and had verified that only one mail was generated.

I would be a lot more comfortable if we could have this tested out as well cause having to rollback in cause is something was wrong in the email is painful

**Comment by tarunbhm** [comment]
> I would be a lot more comfortable if we could have this tested out as well cause having to rollback in cause is something was wrong in the email is painful

I had tested by logging rendered email body both txt and html so we are covered there.

As you mentioned video is required for non tech people, I will create a video with mail in inbox.

**Review by aamustapha — APPROVED** [review]

**Review by thelostone-mc — APPROVED** [review]
image


Tested multiple ETH grants + 1 cross chain grants
Flow seems to work without any issues

**Pull request merged**
