### PR TITLE
feat: add project pages for hackthon projects 

### LINKED ISSUE #6622: Single project page
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a contributor I want a single project page with a friendly url so I can link people to my project + have the project "looking for members" flag there.
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Because there is no way to link my project to find new members or people read the full description. 
### Description
The design proposal, still need some additions for:
Links to quick chat with people
"Looking for team area"
Edit button (will open the edit modal used today) 
Post activity need to be posted to the hackathon townsquare. (like kudos, grants etc)
Card metatags need to show the project logo. 
v2:
Looking for team button to request join the team.
image

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
none 
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
url : `https://gitcoin.co/hackathon/[hackathon-slug]/projects/[project-id]/[project-slug]
### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

### PR DESCRIPTION
**Pull request by developerfred**
##### Description

-  [x] new hackathon project slug
-  [x] Project Page
-   [ ]  activity feature
 

##### Refers/Fixes
#6622

### CODE REVIEW

**Comment by PixelantDesign** [comment]
@developerfred I'll payout for the work you've done. @zoek1 has agreed to finish it up. Thank you!

**Comment by developerfred** [comment]
thank you! @pixelantdesign

**Comment by frankchen07** [comment]
is there a quick video on where this stands currently? just so I can view the feature development?

**Comment by developerfred** [comment]
Hi @frankchen07, @zoek1  working on this feature can close the pull request.

**Pull request closed without merging**
