### PR TITLE
massively simplifies (and corrects) Personas calc logic

### PR DESCRIPTION
**Pull request by owocki**
##### Description

massively simplifies (and corrects) Personas calc logic

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/4901

##### Testing

tested locally by running `./manage.py set_user_personas` locally

### CODE REVIEW

**Comment by danlipert** [comment]
What are y'all thinking with this one? Looks good to me @frankchen07 will be quite a bit faster to process as well

**Comment by owocki** [comment]
i'm in favor of this for simplicity reasons..  we can still use frank's query on the metabase side.

**Comment by frankchen07** [comment]
just so I understand, we're using

```
is_hunter |= self.interested.exists()
is_hunter |= self.received_tips.exists()
is_hunter |= self.grant_admin.exists()

is_funder |= self.fulfilled.exists()
is_funder |= self.sent_tips.exists()
is_funder |= self.grant_contributor.exists()
```

we're using these parameters to determine the persona (so hunters would be interested in bounties / receive tips, or start a grant, versus funders who fulfill bounties, send tips, or contribute to a grant. Aren't contributors also ones fulfilling bounties and contribute to a grant? I'm less concerned with contributing to a grant and more concerned with `fulfilled` - maybe I'm getting the definition wrong. 

Otherwise, I'm always a fan of simplifying using the data model.

**Comment by owocki** [comment]
> Aren't contributors also ones fulfilling bounties and contributing to a grant?

i think of those who are contributing to a grant as being funder.  but we should decide if we want to treat funders of grants as funders of bounties, or if we cant to have more of a matrix of personas (one for each product)

**Comment by owocki** [comment]
57deb18b60576ce553c8f57f7129bd1220ee33e9 fixes the `fulfilled` thing, good catch @frankchen07 !

**Comment by frankchen07** [comment]
dope - my last comment will be, is it possible to make a comparison between this new simplified version and the metabase version? I think as long as we have generally > 90% similarity, it'll be LGTM. Of course, there might be some lift on that but easiest would be to pull profile IDs and just make a comparison.

**Comment by thelostone-mc** [comment]
@owocki ^

**Comment by frankchen07** [comment]
sorry missed this LGTM

**Comment by owocki** [comment]
cool;  @danlipert should i merge, or just leave it for u guys in your next release cycle?

**Comment by owocki** [comment]
actually this has been merged into https://github.com/gitcoinco/web/pull/5093 ; so we'll just manage it via that pr/branch

**Pull request closed without merging**
