### PR TITLE
Fix rare `is_metamask_approved is not defined` race condition.

### LINKED ISSUE #2813: ReferenceError: is_metamask_approved is not defined
**Describe the bug**
Once in a while ```Reference error is_metamask_approved is not defined in console.log```. It does not show any network in the gitcoin page also.

**To Reproduce**
Run into some bad luck

screencast from wednesday 14 november 2018 08_54_19 ist

**Desktop:**

- OS: Ubuntu 18.04
- Browser Chrome

### PR DESCRIPTION
**Pull request by pinkiebell**
Sometimes, the window's `load` handler get executed in another order
which breaks variable lookup.
Fix that by explicit declaring `is_metamask_approved` and `is_metamask_unlocked`.

Fixes #2813

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@pinkiebell not sure if this is right ! 
Would it make sense to just declare the variable once and let it have global scope cause it's used throughout the app ?

**Comment by pinkiebell** [comment]
@thelostone-mc Sure, I just added that for redundancy. I will drop the declarations from `shared.js`.

**Comment by thelostone-mc** [comment]
Also wouldn't `var is_metamask_approved = is_metamask_approved;` still throw an undefined error ? 
Would it make more sense to just leave it as `var is_metamask_approved` ?

**Comment by pinkiebell** [comment]
@thelostone-mc 
Nah, thats perfectly valid. I intentionally wrote it that way to signal that it might be used elsewhere,
so we don't overwrite the variables if that happens.
Just paranoia 😆

**Comment by thelostone-mc** [comment]
Haha this makes me a lot more comfortable :P

**Pull request merged**
