### PR TITLE
[WIP] Add button down and hawaiian shirt

### PR DESCRIPTION
**Pull request by Ricky-N**
[NOT READY FOR MERGE] 

##### Description
I'm opening this to get an early progress update and see if anyone has ideas to help unblock local testing!

This is to help out with #2684. I wanted to add a Hawaiian shirt so I could have a very tropical Christmas avatar, but ended up also needing to add a short sleeve button down shirt to base it off of. I believe I may need to switch from a hardcoded second color to an opacity overlay for the django pattern to work out, but I'm holding off on testing that until I can get local dev to work. 

Progress is currently blocked because of issues with the GitHub integration during local testing documented in #2761. 

Here's a screen of the current orange version of the `buttondown`: 
image

And here's the `hawaiianshirt`: 
image

##### Testing

I still need to add the django template and test this!

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@Ricky-N these looks sweet
Btw before you call in for review do run `svgo` to compress the svgs ^_^

**Comment by owocki** [comment]
@Ricky-N this is dope.. lets get it merged soon!

**Comment by mbeacom** [comment]
@Ricky-N Any update on this?  Is there anything you need from us?

Thanks!

**Comment by mbeacom** [comment]
Closing for now.  Please feel free to re-open when you're ready for review @Ricky-N!

**Pull request closed without merging**
