### PR TITLE
[WIP] migrate gitcoin from web3js 0.2 to 1.0

### LINKED ISSUE #2370: migrate gitcoin from web3js 0.2 to 1.0
the objective of this ticket its to migrate gitcoin from web3js 0.2 to 1.0

i've started a base branch at https://github.com/gitcoinco/web/commit/13bc312dd50b587197932bb7bc8c053b974d68f1 which you can use.

success criteria:
* repo is upgraded to web3js 1.0
* all references to web3.eth.coinbase updated
* BOUNTIES: a funder can post a new bounty
* BOUNTIES: user can fulfill a bounty
* BOUNTIES: funder can increase payout
* BOUNTIES: funder can accept a fulfillment (basic payout)
* BOUNTIES: advanced payout works
* TIPS: a user can post a new tip
* TIPS: a user can receive a tip
* ENS: a user can register an ENS subdomain at /ens
* FAUCET: User can submit a new faucet page
* FAUCET: admin can fund a faucet distribution.
* REQUESTS: User can submit a new requests request

replaces https://github.com/gitcoinco/web/issues/2369

### PR DESCRIPTION
**Pull request by usmanmuhd**
Fixes #2370 
- [x] repo is upgraded to web3js 1.0
- [ ] all references to web3.eth.coinbase updated
- [ ] BOUNTIES: a funder can post a new bounty
- [ ] BOUNTIES: user can fulfill a bounty
- [ ] BOUNTIES: funder can increase payout
- [ ] BOUNTIES: funder can accept a fulfillment (basic payout)
- [ ] BOUNTIES: advanced payout works
- [ ] TIPS: a user can post a new tip
- [ ] TIPS: a user can receive a tip
- [ ] ENS: a user can register an ENS subdomain at /ens
- [x] FAUCET: User can submit a new faucet page
- [x] FAUCET: admin can fund a faucet distribution.
- [ ] REQUESTS: User can submit a new requests request

### CODE REVIEW

**Comment by usmanmuhd** [comment]
@owocki Currently I added the feature to know the current network it is on. Will be adding more in a day or two.

**Comment by owocki** [comment]
😍

**Comment by mbeacom** [comment]
@usmanmuhd Are you still interested in working on this?

**Comment by usmanmuhd** [comment]
> @usmanmuhd Are you still interested in working on this?

Yes. Sorry, I was stuck with quite a bit of work today. Will try my best to push in changes by tomorrow.

**Comment by usmanmuhd** [comment]
@mbeacom In /tips , web3js 0.2 is being loaded instead of 1.0
And also how do I test the [promptForAuth function](https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/shared.js#L886) with a custom token?

**Comment by owocki** [comment]
> @mbeacom In /tips , web3js 0.2 is being loaded instead of 1.0. How do I fix this?

add the code to load web3js 1.0 to the template for tips

**Comment by usmanmuhd** [comment]
@owocki I am not able to locate where the present web3.js is being loaded from in `/tips`

**Comment by mbeacom** [comment]
Do we want this branch based on `kevin/kevin-demo` or `master` ? 🤔

**Comment by mbeacom** [comment]
@usmanmuhd Anything we can help you with here?

cc @gitcoinco/frontend

**Comment by usmanmuhd** [comment]
@mbeacom I have stopped work as I did not have enough time to work on this. Forgot to close the PR. Hope @pinkiebell can take over the changes made in this PR and push it past the finish line!

**Comment by mbeacom** [comment]
Thanks for the update @usmanmuhd !

**Pull request closed without merging**
