### PR TITLE
[DO NOT MERGE] Set gas price to 10% for grants metatxs

### PR DESCRIPTION
**Pull request by danlipert**
This PR sets the MetaTX gas price to 10% to add a fee for grants

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@danlipert thoughts on making this as a draft PR to avoid a merging by mistake ?

**Comment by danlipert** [comment]
Creating a new draft PR and closing this one

**Comment by danlipert** [comment]
https://github.com/gitcoinco/web/pull/4242

**Comment by owocki** [comment]
@danlipert special ask for the next deploy, can we get in sync with the content/marketing team about the messaging on the new fees so we dont accidently release it without the needed air cover / marketing messaging?  cc @vs77bb @PixelantDesign

**Pull request closed without merging**
