### PR TITLE
Fixing "Build your Avatar redirect"

### PR DESCRIPTION
**Pull request by Solexplorer**
##### Refers/Fixes

#5401

### CODE REVIEW

**Comment by Solexplorer** [comment]
Explaining the last commit.

When the user was saving a 3d avatar, it redirected to `/profile` which is the gitcoin profile of a user called [profile](https://gitcoin.co/profile), refer to #5359 .
Instead, it should redirect to `/profile/`

**Comment by danlipert** [comment]
Hey @Solexplorer thanks for the PR! In the PR description, theres a space to describe how your changes were tested. Please either put some screenshots or a video showing that the changes work as expected, or just describe how you tested it. Thanks again!

**Comment by Solexplorer** [comment]
@danlipert I was going to add screenshots to it, but I messed the local web repo adding more features(not related to this PR).
I am going to show it whenever I get back to it, for now, it's better to close it until I don't give any update about it.
My bad!

**Comment by Solexplorer** [comment]
@danlipert Maybe I should make the PR to a different branch so you can test it ?

**Comment by danlipert** [comment]
I think this PR is so small its probably fine but good to remember for the future - also you could just pull this repo to a separate folder etc.

**Pull request closed without merging**
