### PR TITLE
Fix @mention recognition in Townsquare

### LINKED ISSUE #6298: Townsquare feed should recognize links
### What 
Townsquare feed should recognize links - make link clickable

### Why
not clickable

Screen Shot 2020-03-25 at 8 51 18 AM

### PR DESCRIPTION
**Pull request by sebastiantf**
##### Description

The existing regex to identify @mentions was also identifying the same that could occur in URLs like from medium: https://medium.com/@shevski/how-decentralised-are-you-a6539eeb27ff

The regex has been modified to correctly identify intended @mentions and not those in URLs.

##### Refers/Fixes

Fixes #6298 

##### Testing

Original input to status update:
```
@shevski @shevski @shevski

Although the article is published over one year ago. It’s a must read for anyone involved in tech related businesses. https://medium.com/@shevski/how-decentralised-are-you-a6539eeb27ff
```

**Before:**

Screenshot 2020-04-22 at 1 15 39 AM

Also see: https://github.com/gitcoinco/web/issues/6298#issuecomment-612713914

**After:**

Screenshot 2020-04-22 at 1 16 07 AM

### CODE REVIEW

**Comment by octavioamu** [comment]
Cool
Can you please cleanup the PR? there are not related commits also.

**Comment by sebastiantf** [comment]
Yes @octavioamu I'm working on it rn. I only realized it after creating the PR. My bad. Sorry.

**Comment by octavioamu** [comment]
ohh you don't need to close it just force with the right commits will be fine I believe

**Comment by sebastiantf** [comment]
I kinda deleted the branch

**Comment by octavioamu** [comment]
hahaha ok ok, feel free to open a new one, this is a good fix

**Comment by sebastiantf** [comment]
I opened a new one at #6485 

Sorry about messing this up.

**Pull request closed without merging**
