### PR TITLE
Add help bot to navbar

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
image

### CODE REVIEW

**Comment by owocki** [comment]
@zoek1 what ticket is this for?

i think its a good idea as it puts our support reuests down the github path more often (people will stop emailing founders@) but @PixelantDesign had some concerns

**Comment by owocki** [comment]
can ya fix travis / merge conflicts pls! !?

the merge conflicts on stable should be mostly indentiation/formatting

**Comment by PixelantDesign** [comment]
@zoek1 does the help text display on hover or is it always there?

@octavioamu @willsputra what do you think?  I'm curious if this will decrease the number of support requests.

**Comment by thelostone-mc** [comment]
We already have a lot going on in the nav ! Do we really add one more to that list ?

**Comment by zoek1** [comment]
@PixelantDesign only on hover

**Comment by PixelantDesign** [comment]
if it's only on hover people might not know that it's for help

**Comment by thelostone-mc** [comment]
If the information is useful for the user -> making it visible would defeat the purpose 
cause the user has to hover on the nav to see that and aka it would be an accidental discovery 

I think we need to find out a cleaner solution to this 🤔

**Comment by danlipert** [comment]
closing this out for now

**Pull request closed without merging**
