### PR TITLE
new avatar items

### PR DESCRIPTION
**Pull request by owocki**
further just trying to understand sketch and add a shirt

adds an eth-trek logo to the avatar builder

screen recording 2018-10-09 at 02 36 pm

jack o lantern 
46696271-05c0f280-cbcf-11e8-973a-73b161e4e09c

robe and parrot
screen shot 2018-10-09 at 7 04 33 pm
screen shot 2018-10-09 at 7 04 21 pm

### CODE REVIEW

**Comment by owocki** [comment]
when u want to market to nerds, you do something star trek inspired: 

screen recording 2018-10-09 at 02 43 pm

**Comment by thelostone-mc** [comment]
compressed and fixed linting ^_^
@owocki we would need the `.txt` too

**Comment by owocki** [comment]
hey @thelostone-mc @mbeacom i see [this example](https://github.com/gitcoinco/web/pull/2373/files#diff-faf11e51bd81bc677889901a41e73642) of the dynamic .txts -- whats the different between `futuristic_pony_back.txt` and `futuristic_pony_front.txt`?   where is `futuristic_pony_back` and `futuristic_pony_front` linked in the app? i.e. how does the backend know that `futuristic_pony_*` is the same as `app/assets/v2/images/avatar/HairStyle/9-front-F0E6FF.svg` ?

**Comment by owocki** [comment]
@mbeacom @thelostone-mc i figured it out... fix is in =>  14d6707da97c7f70abf81f6bf0239ef2e0c0d85c

**Comment by owocki** [comment]
9c3c7992b4a9b098a24cc0a72b582391307e501c
fixes merge conflcits

**Comment by dhimanparamjeet** [comment]
I add new items in clothing. Please check my work @owocki PR#3855
canva-photo-editor 1
canva-photo-editor

**Pull request merged**
