### PR TITLE
Update Faucet html and styles

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
This PR adds styling and responsiveness to the faucet page

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
UI

##### Refers/Fixes

#407

### CODE REVIEW

**Comment by owocki** [comment]
gas.png image is huge. can we pare it down?

**Comment by owocki** [comment]
this page looks funny to me, doesnt match the design either 
screencapture-localhost-8080-faucet-1519690200707

**Comment by owocki** [comment]
any way we can update this to work with the designs taht @PixelantDesign provided? https://github.com/gitcoinco/web/issues/173#issuecomment-354392850

**Comment by owocki** [comment]
hey @KennethAshley -- hows it going?  let us know if we can unblock at all :)

**Comment by KennethAshley** [comment]
@owocki remaining issues were to get pixelant thoughts on alert states. Which I believe will be a different issue. So this might be done.

**Comment by KennethAshley** [comment]
Let me update this with updated inputs

**Comment by owocki** [comment]
last i checked the PR didnt have the designs applied from https://github.com/gitcoinco/web/issues/173#issuecomment-354392850 

i think we decided to not include the alert states... no?

**Comment by owocki** [comment]
250 commits?  this might need a rebase

**Comment by KennethAshley** [comment]
@owocki I think i might close this and create a new PR.

**Pull request closed without merging**
