### PR TITLE
tip page sender param

### PR DESCRIPTION
**Pull request by KirkBallou**
##### Description

Adds send_user param that can be passed via url to the tip page send2.html and tip_view.py updated.

### CODE REVIEW

**Comment by danlipert** [comment]
@KirkBallou What issue is this PR referring to and how was this tested? Thanks!

**Comment by danlipert** [comment]
Hey @KirkBallou - hope I didn't scare you away! Did you mean to close this?

**Comment by KirkBallou** [comment]
Dan, it was to add ability for passing send to address to tip page.

Part of Etheral project I was working on. No need now unless y’all want
that feature.

**Comment by octavioamu** [comment]
@KirkBallou sound like a nice improvement to me.

**Comment by danlipert** [comment]
yeah could be cool @octavioamu - what do you think we could use this for?

**Comment by octavioamu** [comment]
Maybe some quick actions from new kudos from dashboard, crossing the bounty completed keywords with kudos keywords.

**Comment by danlipert** [comment]
@thelostone-mc let us know what you think once you return :)

**Pull request closed without merging**
