### PR TITLE
Base livestream sessions tracking and redirect

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description
The goal of this PR is to implement livestream session user tracking and a mechanism of gating access to the livestream to gitcoin authenticated users only.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by owocki** [comment]
i love this idea!

1. any way we can tie the zoom account to github username?  in the case of trolls, it'd be
2. how do we updathe zoom id on a weekly basis?  it'll be important to get that info to @vs77bb 
3. should we manage the livestream agenda via this system?

**Comment by mbeacom** [comment]
@owocki

1. This pr introduces tracking of attendees by their Gitcoin profile. I'm tracking them on the attendees m2m and creating a useraction.
2. I was thinking we could add a recurring job, slack command, and/or some admin functionality to schedule unique livestreamsession entries or tie into the zoom api to schedule these and retrieve the relevant zoom ID and password.
3. We could add the agenda as the description and maybe create something like a list view to display all historical and upcoming livestreams. I figured we can upload the recorded stream and have those available for past streams.

**Comment by owocki** [comment]
1. ya i just wonder what vivek and i would do if someone is a troll -- i guess we'd have to go to their admin page and slash them
2 and 3 make sense to me

**Comment by thelostone-mc** [comment]
Do we need this level of tracking ? it is a nice thing to have

**Pull request closed without merging**
