### PR TITLE
payout: added autocomplete

### PR DESCRIPTION
**Pull request by thelostone-mc**
- Ported `truncate-hash.js`
- Adds autocomplete feature to bulk payout
- Shows address if available
- introduced flag to ensure the address shows up only in payout and not tip

x

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@octavioamu / @SaptakS / @mbeacom  Do I fix up the stickler errors now for `truncate_hash.js` or just silence for this file until we merge the other repo ?

**Comment by PixelantDesign** [comment]
Looks great!!!!!!!!!!!!!!

**Comment by thelostone-mc** [comment]
@mbeacom / @SaptakS / @owocki  you guys good with this ?

**Comment by thelostone-mc** [comment]
Throwing in the tooltip : 
screen shot 2018-10-05 at 5 06 13 pm

**Pull request merged**
