### PR TITLE
bounty: fixed avatar url + tooltip style

### PR DESCRIPTION
**Pull request by thelostone-mc**
###### Tooltip update
screen shot 2018-04-04 at 3 23 52 pm

###### If owners github info is not found
screen shot 2018-04-04 at 3 16 57 pm

###### Owners profile photo 
screen shot 2018-04-04 at 3 17 42 pm

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- bounty.js

##### Refers/Fixes
- #779

### CODE REVIEW

**Comment by owocki** [comment]
looks good so far! 

personally id like to see the repo avatar in the top left next to the issue title bc i think it helps visually identify the repo that the bounty hunter will be working for... but i dont know if the design allows for that and/or  if @PixelantDesign would agree

**Comment by PixelantDesign** [comment]
I think we can add the repo icon in the upper left. @owocki 
@thelostone-mc Looking great!!!! Don't hate us, we're almost there!

The activity feed is meant to be a history, could we follow the accept bounty model for the stop work?
screen shot 2018-04-04 at 2 08 20 pm

screen shot 2018-04-04 at 2 08 08 pm

Here is a mock with the avatar up top...
screen shot 2018-04-04 at 2 13 39 pm

**Comment by thelostone-mc** [comment]
I'll add the org avatar here!
I'll shoot out Accept Button -> Dropdown as another PR @mbeacom ?

**Comment by owocki** [comment]
> I'll add the org avatar here!
awesome!

> I'll shoot out Accept Button -> Dropdown as another PR @mbeacom ?
makes sense to me

**Pull request merged**
