### PR TITLE
Update link on image

### LINKED ISSUE #14: Tip page link 404s
Linking to `index.html` which isn't working. Will submit a quick PR...

gitcoin-404

### PR DESCRIPTION
**Pull request by bransbury**
Fixes #14

### CODE REVIEW

**Comment by owocki** [comment]
Thanks for hte pr @bransbury !

Mind updating these other two files too?

```
/Users/kevinowocki/Sites/gitcoin/web/app/dashboard/templates/yge/receive.html:
   25      <header>
   26          <span class="avatar">
   27:             <a href='index.html'>
   28                  <img src="/static/v2/images/helmet.png" style="background-color: white; max-width: 100px; max-height: 100px;" />
   29              </a>

/Users/kevinowocki/Sites/gitcoin/web/app/dashboard/templates/yge/send1.html:
   16  	<header>
   17  		<span class="avatar">
   18:             <a href='index.html'>
   19                  <img src="/static/v2/images/helmet.png" style="background-color: white; max-width: 100px; max-height: 100px;" />
   20              </a>

/Users/kevinowocki/Sites/gitcoin/web/app/dashboard/templates/yge/send2.html:
   19      <header>
   20          <span class="avatar">
   21:             <a href='index.html'>
   22                  <img src="/static/v2/images/helmet.png" style="background-color: white; max-width: 100px; max-height: 100px;" />
   23              </a>

3 matches across 3 files
```

**Comment by bransbury** [comment]
No problem, @owocki - updated those now 👍

**Comment by owocki** [comment]
🔥 🔥

**Comment by bransbury** [comment]
🎉🎉🎉 😄

**Pull request merged**
