### PR TITLE
Feature/hackatho prizes

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
- [X] Implement the headers and sidebar of the new hackathons design
- [X] Implement design for prizes list
- [X] Implement projects views

##### Refers/Fixes
No issue

### Hackathon prizes
Image Pasted at 2020-3-30 01-00

### Projects view
Image Pasted at 2020-3-31 01-52

## Responsive View
image

### CODE REVIEW

**Comment by thelostone-mc** [comment]
This is already live so closing this out ^_^

**Comment by zoek1** [comment]
@thelostone-mc the current implementation doesn't meet the proposed design in Figma. So this could be reopened and integrate into the current implementation but this time with Vue.

**Comment by thelostone-mc** [comment]
@zoek1 could you resolve the conflicts ?

**Comment by zoek1** [comment]
Sure, no problem :)

**Pull request closed without merging**
