### PR TITLE
only english versions - updated ToU

### PR DESCRIPTION
**Pull request by NukeManDan**
##### Description

Fixes: #3344
(for English speakers)

note: 
`npm run eslint:fix; npm run stylelint:fix; isort -rc --atomic` => `... web/app/dashboard/apps.py File contains syntax errors.
Skipped 78 files
`

I did not edit this file :point_up:  

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [x] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

UI

##### Refers/Fixes

Fixes: #3344 

##### Testing and Sign-off

LGTM

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by NukeManDan** [comment]
Forgive me if I didn't get all the checks passes :sweat_smile: new to this! More deets in #3344

**Comment by NukeManDan** [comment]
second commit has django files edited

**Comment by thelostone-mc** [comment]
@NukeManDan ah no worries mate ^_^
Could you resolve the conflicts? and we can get your PR in

PS : congrats on the first PR! Glad to have you contributing :)

**Comment by thelostone-mc** [comment]
@NukeManDan yes sir. thanks for your contribution ^_^

**Pull request merged**
