### PR TITLE
replaces twitter cards across the site from the og video with new images

### PR DESCRIPTION
**Pull request by owocki**
TODO - figure out why they arent showing up in the validator
https://bits.owocki.com/Apuj8glg

more todos here too => https://gitcoincore.slack.com/archives/CS0G19D7Y/p1586994321125300?thread_ts=1586817943.109600&cid=CS0G19D7Y

### CODE REVIEW

**Comment by owocki** [comment]
@zoek1 any chance u wanna take this over the finish line? i just need the cards for each of these pages validated in the twitter card validator. can tip ya of course for your time

**Comment by owocki** [comment]
note that some other twitter card designs maybe incoming from @guistf

**Comment by zoek1** [comment]
Sure @owocki, can you give me access to gitcoincore to see the message?

**Comment by owocki** [comment]
@zoek1 unfortunately i cant.  the message isnt important actually, all the files are actually in the PR already

**Comment by zoek1** [comment]
:ok_hand: i need to finish a banner but after that I'll start to debug this

**Comment by danlipert** [comment]
@owocki @zoek1 this is still a WIP for now until Zoek does some addons?

**Comment by zoek1** [comment]
https://github.com/gitcoinco/web/pull/6488 @owocki

**Comment by thelostone-mc** [comment]
Got @zoek1 PR in and merging this to master!

**Comment by owocki** [comment]
awesome!  

guist is sending more twitter cards today for the rest of the pages.  will pass along when i get it

**Pull request merged**
