### PR TITLE
fix broken email urls for admin

### PR DESCRIPTION
**Pull request by chibie**
##### Description

this PR fixes broken email urls in admin

- [x] **/bounty_expire_warning** - _Cannot resolve keyword 'fulfiller_email' into field_

- [x] **/start_work_expire_warning** - _django.template.exceptions.TemplateSyntaxError: 'blocktrans' doesn't allow other block tags (seen "url 'slack'") inside it_

- [x] **/start_work_expired** - _django.template.exceptions.TemplateSyntaxError: 'blocktrans' doesn't allow other block tags (seen "url 'slack'") inside it_
 
- [x] **/bounty_feedback** - _unknown persona_

- [x] **/tribe_hackathon_prizes** _'NoneType' object has no attribute 'sponsor_profiles'_

##### Testing

https://www.loom.com/share/dc11741934f544cd992a5a8bc05ca774

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Has this also been tested using the mgmt command to ensure the right data is populated ?

**Comment by chibie** [comment]
> Has this also been tested using the mgmt command to ensure the right data is populated for the right bounty?

i get this locally while running the mgmt command `not active in non prod environments`

but it should work just right cause i didn't change the logic, only refactored + used `fulfiller_email` property rightly

**Comment by thelostone-mc** [comment]
comment out that code which throws and test it out at least once as emails are something which if sent out incorrectly could annoy users

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
comment out that code which throws and test it out at least once as emails are something which if sent out incorrectly could annoy users

**Comment by chibie** [comment]
closing this in favour of #8413

**Pull request closed without merging**
