### PR TITLE
Fixes #4292 - Better Test Data Fixtures

### LINKED ISSUE #4292: As a Gitcoin contributor, I want better and updated data fixtures, so that QAing my changes and getting started is easier.
### User Story

As a Gitcoin contributor, I want better and updated data fixtures, so that QAing my changes and getting started is easier.

### Why Is this Needed

There are currently some fixtures which help bootstrap the process of creating test data when running Gitcoin locally. These fixtures are automatically added when you run Gitcoin via docker, and include things like creating users and adding tokens. Adding fixtures to include newer features like Grants, and updating the current fixtures will make developers' lives easier.

More info: https://docs.djangoproject.com/en/2.2/howto/initial-data/

### Description

*Type*: Feature

### Current Behavior
 Booting the Gitcoin app via docker for the first time adds some initial data.

### Expected Behavior
Booting the Gitcoin app via docker should add more data to cover the new features that have been integrated into the app. 

### Definition of Done
Additional fixtures are present when booting the app for the first time. Every feature in the app contains a variety of data on a fresh build, including Bounties. For each feature, there should be different model instances that demonstrate the variations of models we see in the production app. For example: in Grants, there should be grants that are set to various funding levels, which grant contributions already in place from various test users. For Bounties, there should be a combination of both public and private bounties, a demonstration Hackathon event set up, etc. For users, there should be a variety of test users already set up that have initiated various activities, such as applying to work on bounties, setting up their profile, sending Kudos, etc. These are just examples and are in no way comprehensive. All test data should be on the Rinkeby testnet if applicable.

### Data Requirements
The success of the new fixture data can be measured in how many more community contributions we receive, as well as decreasing the amount of bugs in PRs and deploy regressions.

### PR DESCRIPTION
**Pull request by acolytec3**
##### Description

Add a variety of test data outlined below as a quickstart for general development on the Gitcoin app:
* Default superuser
* ~20 test users, some with profiles set up, feedback received, and a couple of tips sent
* A smattering of kudos available to send around and a few already sent
* 2+ bounties in various types in all statuses (open, work started, work submitted, completed, expired, canceled)
* 3 grants setup with various statuses
* A simple hackathon with a couple of bounties set up

##### Refers/Fixes

Fixes #4292 

##### Testing

This is new test data - no code changes

### CODE REVIEW

**Comment by acolytec3** [comment]
@danlipert @kuhnchris 

I've pushed some additional fixtures for more of the tables.  This is still a fair ways from being complete but I'm starting to get something that looks like a representative (though not really complete) set.  The thing I'm currently struggling the most with is keeping bounty activity in sync.  As I noted in my previous comment, if I do run the sync_geth command after loading the bounties data, it always seems to throw something out of whack and the bounty activities table refuses to load thereafter citing mysterious "user not found" key errors that I haven't been able to track down yet.

So, my question is this, is it  important that we be able to run the sync_geth command after loading all of this data?  The reason I ask is that doing so always seems to muck up any bounty activity I've created (users applying for, being approved for, starting/submitting work) locally and saved.  If the bounty activity gets recorded to rinkeby, you will see that the user submitted work but no activity.
fulfilledbountynoactivity

If the answer is no and we want devs to be able to boot up and go, that should make things easier.  I'll keep working on this but would love any feedback on approach.

**Comment by danlipert** [comment]
@acolytec3 You definitely don't need to worry about sync_geth 👍 that's out of scope for this issue I think. The goal is to get people up and running as fast as possible as you said :)

**Comment by acolytec3** [comment]
@danlipert Got it. I'll keep plugging away at adding more to the fixtures
(when I'm not fixing all the stuff I broke on my other PRs
🤪).

**Comment by acolytec3** [comment]
@danlipert @kuhnchris At this point, this should be getting close to having some data for all of the areas of the site.  Does one of you have some bandwidth to verify that the data loading works in your lohe cal environment?  Seems to work fine for me and travis likes it but I'd love to verify that everything I've built out so far works.  

I also added a section to the getting started readme to describe loosely what is contained in the fixtures.

**Comment by danlipert** [comment]
> @danlipert @kuhnchris At this point, this should be getting close to having some data for all of the areas of the site. Does one of you have some bandwidth to verify that the data loading works in your lohe cal environment? Seems to work fine for me and travis likes it but I'd love to verify that everything I've built out so far works.
> 
> I also added a section to the getting started readme to describe loosely what is contained in the fixtures.

@kuhnchris do you have any time to check this out?

**Comment by kuhnchris** [comment]
I can check it out, sure @danlipert.
May need to give me until tomorrow tho.

**Comment by danlipert** [comment]
Thanks man, appreciate it!

**Comment by kuhnchris** [comment]
Just FYI i tried to get my local env up, but I had problems cleaning it up, so I will try to re-setup a new env. May need to give me over the weekend, sorry.

**Comment by acolytec3** [comment]
I think this covers all of the areas of the site where I'm able to easily replicate data.  @kuhnchris Were you able to build this PR and confirm you can see all the data?  What am I missing that would be useful to add in?

**Comment by acolytec3** [comment]
@danlipert @kuhnchris any chance of getting this reviewed?

**Comment by danlipert** [comment]
@kuhnchris can you take a look at this anytime soon? Otherwise I'll do it

**Comment by kuhnchris** [comment]
@danlipert if you got resources to do it, please test - I haven't managed to get it up and running yet. (currently rebuilding my images)

**Comment by acolytec3** [comment]
@danlipert, Disregard all the additional stuff that got pulled in. I was working on another PR and used the test data i created for this one and noticed there were some changes y'all made in the models that broke my profile data so I rebased off master over the weekend. That said, it now doesn't all load correctly so I'd need to make some updates to the fixtures for this to be worth merging. Are you still planning to review this at some point? If so, I'll figure out which fixtures are no longer loading correctly and update the PR.

**Comment by danlipert** [comment]
@acolytec3 just letting you know @androolloyd is going to be doing the final testing on this one and then we should be all set to get it in

**Comment by acolytec3** [comment]
Sounds good.  I've pushed some tweaks to get my initial set of fixtures
loading again.  That said, 2 things I've noticed when revisiting this:

1) Seems like something's either changes with Grants or I'm missing
something as the grants I had setup previously weren't working when I
rebased it recently.  I added some new ones but haven't been able to get
the front end to let me add subscriptions/contributions and saying there
aren't any valid ERC20 tokens even though the DB says I have plenty of
tokens set up (I verified that DAI and ETH were set up on Rinkeby).

2) Something seems to have changed with avatars too.  It now doesn't like
loading avatars that I set up for some of the profiles.  I've experimented
some with adjusting the data in the fixture but not been able to resolve
this one.  I'll have to dig into that again too.

Otherwise, would love to know if this has the breadth and types of data you
wanted for this.  I actually cherrypicked the data from this one to help me
test  PR #5108 so I guess that's something.  :-)

**Comment by acolytec3** [comment]
@androolloyd @danlipert  I've got the grants situation worked out but still can't figure out why my avatar fixtures won't load. Below is the error message I'm getting:

```django.db.utils.IntegrityError: Problem installing fixture '/code/app/app/fixtures/avatar.json': Could not load avatar.CustomAvatar(pk=1): null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (58, 2019-09-13 17:05:13.380233+00, updated_avatar, {"url": null}, f, null, null, null, null, 2019-09-13 17:05:13.379811+00, 2019-09-13 17:05:13.37993+00, null, null).
```
The avatar fixture I'm loading is all based on avatars that I created in the app and the avatar.json fixture is just the result of a dumpdata avatar > avatar.json command.  As best I can tell, it's trying create a new dashboard.activity record when it's loading the fixture and then throwing an error related to the "profile_id" field.  Is that the "id" field from the profile metadata field?

**Comment by androolloyd** [comment]
yes its the id of the profile table

**Comment by acolytec3** [comment]
> yes its the id of the profile table

So any idea what's causing that error message then?  The base avatar records in my fixture (in avatar.json) have the profile field though the custom avatars don't.  I created these avatars in the app and then just did "dumpdata" to generate the fixture and I haven't touched the fixture at all otherwise so these should be legitimately created records.  I tried adding a profile field with the corresponding profile ID in the custom avatar records in the fixture with the same error resulting.  I didn't see these errors when I originally put this together so I'm guessing something's changed in the way avatars are constructed since then.  Is it possible the app itself isn't constructing one of the records correctly?

**Comment by androolloyd** [comment]
AFAIK the profiles are created when the users are synced with Github, so if there is no sync happening these profiles might have to be created by hand.

**Comment by acolytec3** [comment]
Okay, I'll try creating an avatar with a user who's authenticated through
Github and see if that carries over when loading the avatar fixture.  I
created all my user profiles based on a github authenticated user so I
thought all the fields should be present and valid in the fixture.

**Comment by acolytec3** [comment]
@androolloyd  Same result when I use a user created completely from the front-end using the github login.  I'm stumped.  Everything else loads and works fine.

**Comment by androolloyd** [comment]
@acolytec3 i think the issue is that custom avatars are also baseavatars in the model definition, so they inherit all the columns defined on that model as well, including profile_id, the lack of any defined id's is actually causing the error as its being parsed as null.

**Comment by acolytec3** [comment]
And the 'profile_id' that's pulled into the baseavatar model corresponds to
the pk field of the dashboard.profile model, right?  My avatar fixture has
a profile field with a value that corresponds to primary keys that exist
for profiles in the profiles fixture and my script loads the profile
fixture before the avatar fixture so not sure why it's thinking that the
profile id doesn't exist.

**Comment by acolytec3** [comment]
@androolloyd I've found what's causing the failure though not sure why it's not working.  Basically, the error is being caused by the psave_avatar method in app/avatar/models.py that gets called when ever a new avatar record is saved to the DB.  I'm guessing the loaddata command doesn't pass all the necessary variables to this method when it's adding the avatar records to the DB which is what's causing the failure.  From [here](https://stackoverflow.com/questions/3499791/how-do-i-prevent-fixtures-from-conflicting-with-django-post-save-signal-code), it looks like there are a couple of ways of getting around it that mainly involve adding a filter to the psave_avatar method so it just returns a blank and doesn't try to create the new activity record when I'm loading data from fixtures.  Will report back once I've had a chance to test.

**Comment by acolytec3** [comment]
@androolloyd  Okay, confirmed that the small code change I made to the avatar/models.py psave method resolves the problem.  Basically, it looks for a "raw" parameter in the kwargs for the psave function that is called when an avatar record is created.  That "raw" parameter means that the record is being created by the loaddata management command so it skips the save activity since the activity record already exists in the dashboard.activity table since I created the avatars using the app.

This PR is ready for review again.

**Comment by androolloyd** [comment]
Hey @acolytec3 that change worked for me, as apart of the test data, we'll want to transfer the test repos used with the fixture data over to Gitcoin.

**Comment by acolytec3** [comment]
@androolloyd  For sure.  I'd completely forgot I even set those up.  Who should I transfer them to, you for now?

**Comment by androolloyd** [comment]
@acolytec3 talking that over with @danlipert I'll let you know

**Comment by acolytec3** [comment]
@androolloyd What's the word on this one? Any changes needed?

**Comment by androolloyd** [comment]
@acolytec3 can you transfer the repos to `gitcoinco` and we'll get this merged.

**Comment by acolytec3** [comment]
@androolloyd Github doesn't allow you to transfer to an organization that you don't have access to create repos for.  I can transfer it to you or @danlipert and then I think you should be able to transfer to gitcoinco.  Does that work?

**Comment by acolytec3** [comment]
Done.  Anything else needed to finalize this PR?

**Comment by acolytec3** [comment]
@androolloyd I hate to even ask at this point but should I just go ahead and close this? No point leaving it open if it's never going to get merged. I'd also like my repos back if this bounty is being cancelled.

**Comment by Sirlupinwatson1** [comment]
Nice, i like the new desing, Very attractive to the eyes. good job @owocki @androolloyd :)

**Comment by androolloyd** [comment]
@acolytec3 Hi, I'll follow up and see whats stopping this from being merged. It's been approved

**Comment by danlipert** [comment]
@thelostone-mc does this look good to you? minus the docker conflicts

**Comment by acolytec3** [comment]
@danlipert @thelostone-mc I can't get at my dev  box till tonight or tomorrow but the conflict is easily resolved.  The `loaddata` statements in my my PR overwrite the one that's in the conflict in the master branch.  All the user accounts from the `initial.json` in the master branch are included in my `users.json` fixture so you can just remove the `loaddata initial` statement.

**Comment by acolytec3** [comment]
@danlipert Merge conflict resolved.

**Pull request merged**
