### PR TITLE
WOC: Added new avatar asset for clothing

### PR DESCRIPTION
**Pull request by vikaskyadav**
Added girls one piece svg as per https://github.com/gitcoinco/web/issues/1550 

##### Checklist

- [ x] linter status: 100% pass
- [x ] changes don't break existing behavior
- [ x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

avatar assets

### CODE REVIEW

**Comment by vikaskyadav** [comment]
Image looks like this: 
girls-one-piece-FD4B2D

**Comment by mbeacom** [comment]
@vikaskyadav Thanks! Do you happen to have a screen of this asset displayed in the avatar builder and a final asset?

**Comment by thelostone-mc** [comment]
Also could you compress the svg via `svgio` & squash them into 1 neat commit ? :D

**Comment by owocki** [comment]
hmmm i dont see this actually in the avatar builder [screenshot](http://bits.owocki.com/3X2i0P0B0r3L/Screen%20Shot%202018-08-20%20at%202.43.11%20PM.png)

@mbeacom are we sure that adding to the filesystem is all the user need sto do to submit their avatar items?

**Comment by ajayns** [comment]
I don't think this follows the avatar specs from the sample image posted, probably won't blend well in the avatar builder. What's required is a 899x1415 something svg, taking the positioning of the face into consideration.

**Comment by ajayns** [comment]
Also, do read the guide, the .txt file is supposed to have variable color.

**Comment by thelostone-mc** [comment]
@vikaskyadav would be able to address the comments left by  @ajayns this week ?

**Comment by thelostone-mc** [comment]
Closing this out as we didn't get a response on this!

**Pull request closed without merging**
