### PR TITLE
Add Projects v2

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
image
image
https://www.loom.com/share/c7f78645ca2a4219b36aa3475564278d

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7340

### CODE REVIEW

**Comment by octavioamu** [comment]
waiting conflict fixes

**Comment by PixelantDesign** [comment]
@zoek1 could you post a video for projects v2?

**Review by PixelantDesign — COMMENTED** [review]
Looking good! Just need a video!

Could we remove the favorite at the top and also remove just the comment button, but keep the comment at the top where it is?

Also is it possible to make the convert to grant bright blue button?

The right column doesn't seem aligned - please check original design in figma.

**Comment by thelostone-mc** [comment]
@zoek1 Does this address @octavioamu comments left in the previous PR ?

**Comment by PixelantDesign** [comment]
Hi guys what was the blocker on this one?

**Comment by zoek1** [comment]
@PixelantDesign some errors on the conver2grant branch block this, i think are only conflicts with migrations due to the integration of new changes into master branch.

**Comment by zoek1** [comment]
hey @sanchaymittal try to don't force push changes. That could break any dependent code like this, I'll start fresh this PR just to avoid introduce noise. :smile:

**Comment by sanchaymittal** [comment]
> hey @sanchaymittal try to don't force push changes. That could break any dependent code like this, I'll start fresh this PR just to avoid introduce noise. 😄

Ohh I didn't know you were working off this pr. There were issues with migration file that needed a fix, didn't know you were from this pr otherwise could have taken a long way.

**Pull request closed without merging**
