### PR TITLE
Restore hackathon indicator on presentation cards

### PR DESCRIPTION
**Pull request by zoek1**
## Fix townsqaure display
image
## Fix hackathon townsquare
image
## Fix profile cards
image

### CODE REVIEW

**Comment by zoek1** [comment]
Yes sir! 👍

**Comment by octavioamu** [comment]
@PixelantDesign @zoek1 what do you guys think about moving "looking for a project" to the next line, seems the size of the font and all the like don't fit visually.

**Comment by danlipert** [comment]
@octavioamu I agree it does look quite funky

**Comment by thelostone-mc** [comment]
@zoek could you resolve these conflicts and we can get this in

**Comment by Solexplorer** [comment]
bump

**Comment by frankchen07** [comment]
LGTM, with the caveat that because there's been alot of feedback about communications confusion, this might be a consideration we retire.

**Pull request merged**
