### PR TITLE
Modify static handling to use Whitenoise

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description

The goal of this PR is to implement `whitenoise` for serving static assets.  This will automatically hash static assets when they are changed and serve the appropriate version of the file without the need to invalidate Cloudfront.  This will also generate `brotli` compression assets and serve with the appropriate compression (gzip, brotli) based on browser compatibility.

Additionally, this PR changes hardcoded URLs to django template url reverse lookups, so if an endpoint changes, it'll automatically be reflected in all templates.

##### Additional documentation

Please check out: http://whitenoise.evans.io/en/stable/#isn-t-serving-static-files-from-python-horribly-inefficient for a list of common questions and answers about serving static assets with Whitenoise versus S3 or nginx.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- ui/templates

### CODE REVIEW

**Comment by owocki** [comment]
> this will automatically hash static assets when they are changed and serve the appropriate version of the file without the need to invalidate Cloudfront.

I'm not seeing this when i test on my local. http://bits.owocki.com/2S1l0B0p3C2t/Screen%20Shot%202018-01-31%20at%2011.48.48%20AM.png

is the hash supposed to be in the filename / path? or elsewhere?

**Comment by owocki** [comment]
> Additionally, this PR changes hardcoded URLs to django template url reverse lookups, so if an endpoint changes, it'll automatically be reflected in all templates.

lets try to merge this quickly to reduce the merge conflicts for this

**Comment by mbeacom** [comment]
@owocki Hashed static asset serving isn't enabled when `DEBUG=True` - Ref: https://github.com/evansd/whitenoise/issues/81

### Checklist

#### Pre-deployment

- [ ] Update staging and production nginx configurations to no longer handle `/static/` differently than any other location

#### Post-deployment

- [ ] Disable Cloudfront invalidation requests on deployment following successful validation of hashed assets.

**Comment by mbeacom** [comment]
@owocki Merge conflicts resolved.

**Pull request merged**
