### PR TITLE
WIP - chore(javascript): convert all non-vendor javascript to es6 and make sure it passes linting

### PR DESCRIPTION
**Pull request by ethikz**
This is a work in progress to convert all js to es6.  This will need to be thoroughly tested to ensure no javascript is broken.

This is a portion of #65 

Part of this or a subsequent task should be to create unit tests.

@thelostone-mc here is what I have so far.

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Ah that's heavy re-write. will have to review this carefully.
Quick questions / points : 
- The commit with id `3fe8a91`, is this supposed to be a part of this PR ? Me and @tra38 had got into the code base.
- we should ensure browser compatibility not being an issue , might have to set up babel so that nothing breaks on browsers which don't have `es6` support
- @owocki this totally slipped my mind, we'd have to ask the current contributors if they are okay with the linting style ? 
_example :_
`const foo = ( bar ) =>  {
  return "foobar";
}`
_to ( what folks usually use )_
`const foo = (bar) =>  {
  return "foobar";
}`

PS:  👍  on removing line ending in library files.

**Comment by ethikz** [comment]
@thelostone-mc 

- No `3fe8a91` shouldn't be part of it, thanks for letting me know.  My branches must be messed up, I'll fix it.
- This does have babel and renders everything for ES2015 **babel-env** which was added to replace **babel-es2015**
- I agree, I didn't mention the linting style but didn't mention the committing style.  I'll post in Slack and get a consensus.

Thanks for pointing it out!

**Comment by owocki** [comment]
looks like theres some conflicts already :/  we should try to get this merged soon so there aren't a bunch of ongoing  conflcits.

meanwhile, i need to find a linter for sublime text

**Comment by owocki** [comment]
testing new tip GH PR comment above ^^ @thelostone-mc you're next !

**Comment by ethikz** [comment]
If we are going to merge this then I would start with a partial merge since this one includes all js.

I can create a new branch for the basic implementation and 1 file that can be merged instead if you'd prefer @owocki 

or I can change all the js back except 1 file and push that up

**Comment by thelostone-mc** [comment]
New branch would probably be neater 👍

**Comment by ethikz** [comment]
Was just thinking same thing

**Comment by owocki** [comment]
works4me

**Comment by ethikz** [comment]
Now being tracked here #111

**Comment by thelostone-mc** [comment]
@ethikz I'm actually okay with either ^_^ we haven't enforced it on our guidelines yet

**Pull request closed without merging**
