### PR TITLE
model setup for donation tracking

### PR DESCRIPTION
**Pull request by danlipert**
##### Description

This PR adds the model to track the optional donations made through new and legacy grants.

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/4724

##### Testing

Just the model setup, so no testing (other than the syntax is clean and the server boots)

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@danlipert still a WIP ?

**Comment by danlipert** [comment]
Some notes for the follow on PRs:

**New Grants**

For new grants, the donations are made in two different ways: first, for a one-time contribution to a grant, the one-time donation is made in the frontend via the splitter contract. For this use case, we'll just need to POST the donation data when the one-time contribution is made.

For recurring subscriptions, donations are made with each individual contribution. For this use case, we'll need to add code to the subminer that records the donation data each time a subscription is mined.

**Legacy Grants**

For legacy grants, the donations made through recurring subscriptions and one-time contributions are treated the same - both are made via single transactions and will be recorded via POSTing the donation data when the one-time contribution is made.

**Comment by danlipert** [comment]
> @danlipert still a WIP ?

Dang you're fast! Should be good to review now, but will hold off on adding the migration until we get closer to merging.

**Comment by danlipert** [comment]
> > @danlipert still a WIP ?
> 
> Dang you're fast! Should be good to review now, but will hold off on adding the migration until we get closer to merging.

nevermind on holding off the migration, I see that it missing causes the tests to fail

**Pull request merged**
