### PR TITLE
Fixes grants 8

### PR DESCRIPTION
**Pull request by zoek1**
##### Description

- Fix checkIsCurator, now is space and '@' aware
- Fix removeCollection due to some browser doesn't construct the object properly
- Make optional the '@' in twitter handles
- Extract the username from twitter urls
- Validate twitter accounts using twitter urls and handles, also manage the '@' scenario
https://www.loom.com/share/2f6cabf8424b4a2b8e4fae3e841a4804

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7947

### CODE REVIEW

**Review by chibie — CHANGES_REQUESTED** [review]
@zoek1 i see you validate against twitter url (https?://www?.twitter.com)

we intend for users to only input twitter username (`@johndoe` or johndoe), if '@' is missing, then backend includes it.

i'm handling this here #7961 , initial was #7890 

can you take out twitter validation changes from this PR?

**Comment by zoek1** [comment]
Thanks @chibie for your quick review, here some comments: 
1. Check the vídeo, if the user pastes the Twitter URL, the username is extracted and replaced with the URL. 
2. The validator supports now Twitter URLs and usernames, so it's more strong. It just adds support for grants that already have twitter URLs.
3. I think is a bad idea to store the usernames with the @ character, because that requires being aware and manipulate the username to build just the Twitter URL. The @ doesn't help on anything, just introduces more validations and transformations in the code IMHO.

what do you think @thelostone-mc @octavioamu

**Comment by chibie** [comment]
@zoek1 really good points. i'll prefer your solution then

i guess i'll update backend validations strictly for twitter URL.

cc: @octavioamu @thelostone-mc

**Comment by thelostone-mc** [comment]
synced up with @chibie offline ! makes sense

**Comment by apbendi** [comment]
Hey @zoek1, was just regression testing the Grants Round 8 branch, and Twitter validation fails with the error message "Request must include a Twitter handle", which seems to be related to the "Match Twitter URL" check you added. It's unclear to me why this is failing or what it was trying to achieve. Can you please test on your end and see if you can reproduce?

**Comment by zoek1** [comment]
I see the problem @apbendi, let me make the patch for this

**Pull request merged**
