### PR TITLE
injects web3 0.20.6 if no web3 is present so that opera will work

### PR DESCRIPTION
**Pull request by owocki**
##### Description

injects web3 0.20.6 if no web3 is present so that opera will work

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/4209

##### Testing

still need to test this thuroughly on chrome and opera still

### CODE REVIEW

**Comment by owocki** [comment]
hey all, opening this because yorke from microsoft is big on opera, and wants to be able to use gitcoin across it.

i think that as the world moves from just using metamask to using many web3 browsers... we will have to maintain support for each of them.

am i on the right track?  if so, will continue testing + push this through to non-draft status

**Comment by octavioamu** [comment]
Take a look at #3983 maybe there is something useful there.

**Comment by owocki** [comment]
just commented there

**Comment by thelostone-mc** [comment]
closing this out as we this is now fixed and gitcoin works on opera

**Pull request closed without merging**
