### PR TITLE
warns user if they try to bounty something but dont have enough tokens

### PR DESCRIPTION
**Pull request by owocki**
screencast: http://bits.owocki.com/81f4e7e8febb/Screen%20Recording%202018-08-23%20at%2003.10%20PM.gif

ref: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1535056555000100

### CODE REVIEW

**Comment by owocki** [comment]
note this warns asyncronously (behind the metamask modal)... we could also just defer hitting metamask with the 'post bounty' if needed

**Comment by thelostone-mc** [comment]
@owocki does this also have search history built into it cause I see commits from those here too?

**Comment by owocki** [comment]
thanks for the heads up @thelostone-mc -- i forced pushed and its fixed now!

**Comment by thelostone-mc** [comment]
@owocki does this not kick in for ETH tokens ?
screen shot 2018-08-25 at 12 25 07 am

**Comment by owocki** [comment]
hope only ERC20 (for now)... since metamask will warn you about ETH balance issues

**Pull request merged**
