### PR TITLE
improvement(dark mode): more tag, input and alert styles

### PR DESCRIPTION
**Pull request by vbstreetz**
Some additional dark mode fixes
Time logged: 2 hrs

##### Description

- [x] Tags
- [x] Some townsquare Inputs
- [x] Alerts

##### Refers/Fixes

Closes https://github.com/gitcoinco/web/issues/6631

##### Testing

N/A

### CODE REVIEW

**Comment by vbstreetz** [comment]
Screenshot 2020-05-16 at 15 15 27

**Comment by vbstreetz** [comment]
Alert state styles might need further improvements:

Screenshot 2020-05-16 at 15 04 48
Screenshot 2020-05-16 at 15 04 36
Screenshot 2020-05-16 at 15 03 43
Screenshot 2020-05-16 at 15 03 13

**Comment by willsputra** [comment]
looks good to me!

**Comment by owocki** [comment]
these screenshots look really good!

**Comment by thelostone-mc** [comment]
@vbstreetz looks like CI is failing! Could you make sure -> CI passes in the upcoming PRs ?

**Comment by vbstreetz** [comment]
@thelostone-mc sure! hopefully prettier gets integrated soon as well..

**Pull request merged**
