### PR TITLE
Ui element fixes

### LINKED ISSUE #5718: Unify Inconsistent UI elements - Tabs
**Describe the bug**

Unify Inconsistent UI elements

**To Reproduce**
View tabs on Profile, Quests, Grants

**Expected behavior**

Look and behave the same. 
Make Profile and Quests match Grants.

**Screenshots**

**Grants**
Screen Shot 2020-01-07 at 3 49 56 AM
**Quests**
Screen Shot 2020-01-07 at 3 29 11 AM
**Profiles**
Screen Shot 2020-01-07 at 4 04 36 AM

**Desktop (please complete the following information):**

- OS:MAC
- Browser: Chrome
- Browser Version:

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description
Fix UI inconsistency on tabs.

##### Refers/Fixes
Fixes #5718 

##### Testing
Checkout profile page tabs and quests tabs to view it.

### CODE REVIEW

**Comment by iamonuwa** [comment]
> Left a few comments

Issues has been resolved

**Comment by danlipert** [comment]
@iamonuwa video of the changes please 👍

**Comment by iamonuwa** [comment]
cc @danlipert  https://www.dropbox.com/s/8nkhz9sytktks3i/screen-capture%20%283%29.webm?dl=0

**Comment by iamonuwa** [comment]
Any more issues here guys?

**Pull request merged**
