### PR TITLE
Adds some new eye styles. Male & female versions!

### LINKED ISSUE #1663: New avatar assets
### User Story

As a user, I want to new avatar assets to show off and express myself digitally.

### Description

*Type*:  New implementation

### Definition of Done

- [ ] Create an .svg asset and place it in `app/assets/v2/images/avatar/<category>`
- [ ] Add the SVG asset as a `.txt` Django template in `app/avatar/templates/<category>/<item|index>.txt` with variable fill.
- [ ] Add your asset to [utils.py](https://github.com/gitcoinco/web/blob/master/app/avatar/utils.py#L43-L97)
- [ ] Provide a screenshot of the new asset from the avatar builder AND the profile details page on this Github issue.

### Additional Information

Feel free to submit any assets you would like to see on Gitcoin.  If the asset is accepted, your asset will become a part of the live avatar builder!  All other assets will be escalated to the core team for review and potential modification.

See the [avatar item request shortlist](https://github.com/gitcoinco/web/issues/1550)

**COMMUNITY MEMBERS**
Feel free to add reactions/upvote your favorite new avatar items/assets!

### PR DESCRIPTION
**Pull request by saricden**
##### Description

Adds a male & female version of eyes that have a concerned expression. More to come if these ones go over okay :)

6 svg
5 svg

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
#1663

### CODE REVIEW

**Comment by ajayns** [comment]
We're supposed to run the project locally and showcase how the assets look in the avatar builder as well. Also compression with `svgio` (if you know what that is)

**Comment by thelostone-mc** [comment]
@saricden Ah could you compress them following these [steps](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#contributing-static-assets)

Also like @ajayns stated -> could you integrate it and throw in a screenshot oh how it looks in the avatar builder ?

- Setup repo via [this](https://github.com/gitcoinco/web/blob/master/docs/RUNNING_LOCALLY_DOCKER.md)
- Make sure you've the env variables to use github login as shown [here](https://github.com/gitcoinco/web/blob/master/docs/THIRD_PARTY_SETUP.md)

make the needed changes and updated the PR ^_^

**Comment by owocki** [comment]
@mbeacom @thelostone-mc   i still cannot get the avatar builder to register new assets in any of these PRs. https://github.com/gitcoinco/web/issues/new?template=bug_report.md

**Comment by thelostone-mc** [comment]
@owocki you have to update https://github.com/gitcoinco/web/blob/master/app/avatar/utils.py#L71 for it to appear

x

**Pull request merged**
