### PR TITLE
shared.js: Escape single quotes with &#39;

### PR DESCRIPTION
**Pull request by adtac**
Fixes https://github.com/gitcoinco/web/issues/150

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/contributing/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by mkosowsk** [comment]
Hello @adtac! Do you know why the Travis CI build failed here?

Looks like

_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'ethereum' could not be loaded: (cytoolz 0.8.2 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('cytoolz<1.0.0,>=0.9.0'), set(['eth-tester']))!

is the root cause

**Comment by adtac** [comment]
@mkosowsk not really sure, but I think my change doesn't touch it. Maybe it's something else. I'll take a look later tonight :+1:

**Comment by mkosowsk** [comment]
Yeah I don't understand why I change like this would have an effect like that 🤔🤔🤔

**Comment by owocki** [comment]
did not test, but LGTM.

**Comment by mkosowsk** [comment]
@owocki do you know why the Travis CI build is failing here?

**Comment by owocki** [comment]
i can't recall the root cause, but im fairly certain that this was resolved upstream (maybe on  https://github.com/gitcoinco/web/commit/2e41776627100209b3e3ea5322a7e88a6f936808 ? )

**Comment by mkosowsk** [comment]
Cool, in that case I also did not test but it also LGTM 👍

**Comment by adtac** [comment]
FWIW, I tested and this works :)

**Pull request merged**
