### PR TITLE
Fix: New Hacker activity overlaps top navbar

### LINKED ISSUE #7027: New Hacker activity post tile in Townsquare feed overlaps top navbar
**Describe the bug**
Every **New Hacker** activity post tile in the Townsquare feed seems to overlap the top navbar when scrolling downwards.

**To Reproduce**
Visit Townsquare. Scroll past **New Hacker** activity tiles.

**Expected behavior**
No activity tiles in the townsquare feed should overlap the top navbar

**Screenshots**

Screenshot 2020-07-01 at 11 36 46 AM

### PR DESCRIPTION
**Pull request by sebastiantf**
##### Description
Fixes every New Hacker activity post tile in the Townsquare feed overlapping the top navbar when scrolling past them.

##### Refers/Fixes
Fixes #7027

### CODE REVIEW

**Comment by sebastiantf** [comment]
@PixelantDesign Will an image of the issue be enough?

**Comment by sebastiantf** [comment]
Issue Video: 

https://www.loom.com/share/a1d4f2158df5405b8c30172a341448a3

**Comment by sebastiantf** [comment]
@PixelantDesign Issue Fixed video:

https://www.loom.com/share/7b27796b6f5e4534bc9f16409bef6470

**Comment by thelostone-mc** [comment]
Ah @sebastiantf looks like we need that  background there !
It's been fixed by @zoek over at https://github.com/gitcoinco/web/pull/7023

**Comment by sebastiantf** [comment]
@thelostone-mc What background did you mean? I didn't fully get you. Would you mind explaining?

**Comment by thelostone-mc** [comment]
So if you remove the z-index this bg gets removed 
image

I tried the exact same thing on live :P

**Comment by sebastiantf** [comment]
Oh you're right @thelostone-mc. Didn't notice that. Sorry. My bad 😅 Shall I close this PR and the issue then?

**Comment by thelostone-mc** [comment]
@sebastiantf yup ^_^
Thanks for the throwing in the fix though ! Looking forward to  other PR you get going here :D

**Pull request closed without merging**
