### PR TITLE
feat(theming): dark mode 🌚

### PR DESCRIPTION
**Pull request by vbstreetz**
Screenshot 2020-03-20 at 04 49 36
Screenshot 2020-03-20 at 04 49 31

[Also see demo video](https://siasky.net/AAASCXZ85EzLKQ8TodDHS2T5rKbVsZaSg4vNTCIwxrFueA)

##### Todos

- [x] Auto system dark/light mode detection
- [ ] Enable explicitly setting mode via switcher; persisted to localstorage/cookie

##### Refers/Fixes

[Gitcoin bounty](https://github.com/gitcoinco/web/issues/6223)

##### Testing

Work in progress...

### CODE REVIEW

**Comment by walidmujahid** [comment]
https://github.com/gitcoinco/web/pull/6245

**Comment by vbstreetz** [comment]
|Light|Dark|
|---|---|
|Screenshot 2020-03-21 at 04 26 45|Screenshot 2020-03-21 at 04 26 42|

**Comment by octavioamu** [comment]
@willsputra @PixelantDesign for the feature review

**Comment by vbstreetz** [comment]
Looks like a lot of heat at https://github.com/gitcoinco/web/pull/6245. I guess we can close this :).

**Comment by danlipert** [comment]
@vbstreetz really nice work on this - do you have any interest in building upon this work and extending dark mode across the site? Let me know CC: @owocki

**Comment by vbstreetz** [comment]
@danlipert Sure! When can I resume? 😎

**Comment by owocki** [comment]
@vbstreetz i just created this github issue for you. https://github.com/gitcoinco/web/issues/6530

would love to throw a couple ETH in that.  how big/complex do you think itll be?

**Comment by octavioamu** [comment]
@vbstreetz there where some missing components styles so I decided to fix it since was a blocker for deploy and also to fit the design proposed. Please take a look on the PR https://github.com/gitcoinco/web/pull/6531

**Comment by vbstreetz** [comment]
Hey! I see @octavioamu made some big progress 😎... i'll check it out more soon.

@owocki Cool! Though hard to tell an exact estimate but am def available for 2 weeks from 18th (work vacation) if its not too far? (sorry, i should have hinted this earlier).

**Comment by owocki** [comment]
checkout what @octavioamu did. if we do more bounties, would love to have the PRs submitted with the same style/level of quality that it was after both you/octavio had a pass at it.

**Pull request merged**
