### PR TITLE
removes the subminer, which is no longer used

### PR DESCRIPTION
**Pull request by owocki**
##### Description

removes the subminer, which is no longer used

##### Refers/Fixes

chore

##### Testing

tested locally

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]
<3

**Comment by thelostone-mc** [comment]
@owocki 
> ModuleNotFoundError: No module named 'grants.management.commands.subminer'

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
CI has compile failures

**Comment by owocki** [comment]
97d02c1bead41ed0f9625dd83e1889c9481bdb7b

**Review by thelostone-mc — APPROVED** [review]

**Pull request merged**
