### PR TITLE
makes relationship tab on profile a thing

### PR DESCRIPTION
**Pull request by owocki**
Screen Shot 2019-08-29 at 1 45 57 AM

### CODE REVIEW

**Comment by owocki** [comment]
hey @iamonuwa i havent done any styling no this yet; want to stylize / layout this tab for me?

see design below:
Screen Shot 2019-08-29 at 1 47 24 AM

pls make sure its responsive.  let me know how much ETH ya want

**Comment by iamonuwa** [comment]
Sure, I'll work on this now.

**Comment by owocki** [comment]
cool; do you want some help on the design?  the above is obvoiusly just a rough mock; it should look more pro than this.  i can get one of our designers to post something more aesthetically pleasing if u want.

**Comment by iamonuwa** [comment]
> cool; do you want some help on the design? the above is obvoiusly just a rough mock; it should look more pro than this. i can get one of our designers to post something more aesthetically pleasing if u want.

Thinking of using same tabs used in settings for this. Wdyt?

**Comment by owocki** [comment]
The PR above already has the tabs built in (pull it down and check it out)... you just need to do [this](http://bits.owocki.com/48af5193b9c5/Image%202019-08-29%20at%203.31.46%20PM.png) part.

**Comment by iamonuwa** [comment]
I've pulled thr PR, thr links are broken on my end.

**Comment by owocki** [comment]
what links? the tabs?  

for which profile?

hmm that weird, they are working on my machine

**Comment by iamonuwa** [comment]
The tabs I mean

**Comment by iamonuwa** [comment]
Its working for me now.

**Comment by owocki** [comment]
> Its working for me now.

awesome!  cc @willsputra who has been coming up with some designs for this project; in case you want a design to shoot for for this tab

**Comment by owocki** [comment]
@willsputra @iamonuwa i am working off of https://github.com/gitcoinco/web/pull/5093 as the primary feature branch for this initiative.

tabs that need CSS/design love:
- whos viewed my profile
- portfolio
- ratings
- resume tab

**Pull request merged**
