### PR TITLE
Add missing moment that prevents register ens subdoamin

### LINKED ISSUE #6053: Faied to get my own ens : oussema.gitcoin.eth
Why I can't get my own ens ? I followed this blog https://gitcoin.co/blog/personalize-your-own-gitcoin-ens-name/ I sign with my metamsk wallet but it doesn't work. Any one face the same problem ?

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
Missing moment.js error on ENS page

image

##### Refers/Fixes
#6053

### CODE REVIEW

**Comment by zoek1** [comment]
Also, if requires someone to help on migrating ENS subdomains, I'll be happy to help :smile:

**Comment by developerfred** [comment]
Awesome, thanks @zoek1.

**Comment by owocki** [comment]
> Also, if requires someone to help on migrating ENS subdomains, I'll be happy to help 😄

oh man i had no idea about this.. what do we need to do? is there a ticket?

**Comment by zoek1** [comment]
The instructions to migrate the domain as the owner are here @owocki: https://medium.com/the-ethereum-name-service/step-by-step-guide-to-migrating-your-eth-name-to-the-new-ens-registrar-5314431e22f2

At this moment, this is what display when one user query for gitcoin.eth
image

Here's the motivation behind the migration: https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a

Also, seems that to continue using ENS, the major change on gitcoin codebase requires changing the address of the new contract. After that the following steps could be:
1. Migrate all subdomains in bulk with one script
2. Implement at the ENS gitcoin page the option to upgrade the subdomain to the new contract.

**Pull request merged**
