### PR TITLE
Revert bulk stable

### PR DESCRIPTION
**Pull request by corydickson**
Revert #7880

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Was this tested @corydickson ?
image

i don't seem to be getting any mails

**Comment by thelostone-mc** [comment]
image

fixed it up

**Comment by owocki** [comment]
i'm not exactly sure what im testing + what the success conditions are, but this is what i get in my inbox when i checkout on this branch https://bits.owocki.com/BluQNAw7 - looks similar to aditya

**Comment by corydickson** [comment]
sorry @thelostone-mc cherry picked the wrong commits and takes a while for things to build on my end, should be fixed now:

Screen Shot 2020-12-02 at 3 25 59 PM
Screen Shot 2020-12-02 at 3 25 53 PM
Screen Shot 2020-12-02 at 3 24 18 PM


Again with my sendgrid assets get blocked

**Pull request merged**
