### PR TITLE
WIP Raven initialization fixed

### PR DESCRIPTION
**Pull request by gutsal-arsen**
* app/app/templates/shared/sentry.html:

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [x] Completed: Code review by core team and any requested changes

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [x] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by gutsal-arsen** [comment]
According to: [Raven docs](https://docs.sentry.io/clients/javascript/) `Raven.context` function should be used in some environments.

**Comment by owocki** [comment]
@danlipert thoughts?

**Comment by danlipert** [comment]
@owocki thanks for bringing this to my attention!
@gutsal-arsen whats the impact of this change with our sentry reporting? Have you tested this with a sentry instance? Its hard for me to tell from the docs exactly what additional information this would provide.

**Comment by gutsal-arsen** [comment]
@danlipert I don't believe that my [commit](https://github.com/gitcoinco/web/pull/4012/commits/3b4c21ef3dbb64fee8b303803f26dc4f5ee42a9c) might break anything. It's pretty straightforward. Could it be `yarn.lock` which I [committed](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control)?

**Comment by gutsal-arsen** [comment]
Might be that travis just got confused with my `yarn.lock` commit rollback. Will drop that PR and create new one.

**Pull request closed without merging**
