### PR TITLE
Fix pToken dashboard permissions

### PR DESCRIPTION
**Pull request by corydickson**
##### Description

This updates the Vue context with the correct variable to toggle the create pToken modal as well as fixes the permissions check as the string used was incorrect.

##### Testing

Give a user staff role to view the pToken tab, then run the management command: `docker-compose exec web python3 app/manage.py setup_ptoken_launch`

Navigate to the users menu in the Django admin and add the user to the newly create pToken group along with the `add_pToken_auth` permission. 

Screen Shot 2021-02-22 at 1 48 59 PM
Screen Shot 2021-02-22 at 3 11 56 PM

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by thelostone-mc** [comment]
Would this need `setup_ptoken_launch` to be run again on prod @corydickson  ?

**Review by gdixon — APPROVED** [review]
Everything looks good here! Thank you @corydickson!

**Comment by thelostone-mc** [comment]
@corydickson 
https://github.com/gitcoinco/web/pull/8429#issuecomment-783943653

**Review by octavioamu — APPROVED** [review]

**Comment by corydickson** [comment]
> @corydickson
> [#8429 (comment)](https://github.com/gitcoinco/web/pull/8429#issuecomment-783943653)

You shouldn't have to as the value itself hasn't changed.

**Pull request merged**
