### PR TITLE
Refs:#3195 Alien mask added

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
image
image

**Comment by thelostone-mc** [comment]
Umm the image doesn't entirely cover the face ! Should we increase the size ? 
Also could you run `svgo` to compress the svg

**Comment by mehul0698** [comment]
@thelostone-mc if I increase the size of the alien it will go out of the artboard and I have used the broadest face for the test image. If you want I can increse its size and compress it also tomorrow.

**Comment by thelostone-mc** [comment]
Ah @mehul0698 mind throwing one with a smaller face. I could do with that 🙌 
Ideally would prefer it if could cover the large face but this works too

**Comment by mehul0698** [comment]
@thelostone-mc I'll upload the picture tomorrow once I'm albe to access my system.

**Comment by mehul0698** [comment]
@thelostone-mc I have compressed the image.

**Comment by mehul0698** [comment]
@thelostone-mc picture with smaller face.
image
image

**Comment by owocki** [comment]
😍 

i didnt even know i needed this until now

**Pull request merged**
