### PR TITLE
Avatar assets

### PR DESCRIPTION
**Pull request by ajayns**
##### Description

References #2333 

Adds the following avatar assets to the avatar-builder:
- Guy Fawkes mask
- Mohawk hairstyle
- Suit clothing asset
- Cowboy hat

##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by ajayns** [comment]
@thelostone-mc Can you help me out on the linting and screenshotting a local demo? I'm so sorry I'm still stuck on the fix for the docker bug and I'm quite caught up right now.

**Comment by thelostone-mc** [comment]
@ajayns could you resolve the linting errors yourself ( aka break them into new lines )? 
I can throw in the screenshot when I review it after you address the linting issues  :)

**Comment by ajayns** [comment]
@thelostone-mc I'm sorry, I assumed you had some linter setup and the errors were complex. Will make the changes hold up

**Comment by thelostone-mc** [comment]
@ajayns we've got precommit hooks in place which kick before you make a commit locally ^_^
Go ahead and install them and you'll be notified of the lint issues locally ^_^

**Comment by owocki** [comment]
[suit up!](http://bits.owocki.com/1cafc5b9b870/Screen%20Shot%202018-10-13%20at%205.42.55%20PM.png) this is awesome

**Comment by owocki** [comment]
@ajayns whered ya get the guy fawkes svg ? so cool

**Comment by ajayns** [comment]
Haha, I was watching Mr.Robot and somehow it clicked when I came up with the suit asset. It's a mixture of some inspiration when I looked around online plus a couple of sketches of how the mask would look like in 2D, making it a bit cartoonish to fit in with the other avatar assets. You can see that I've removed the nose and cheeks, just focused on the features that are notable on as a flat surface.

**Comment by ajayns** [comment]
> suit up! this is awesome

Yay! But I just noticed the collar on the suit is missing! Please give me sometime, let me see if everything is in place and I'll let you know

**Comment by ajayns** [comment]
Do we still have linting issues? I hope all of them fixed.

**Comment by mbeacom** [comment]
Thanks @ajayns ! They look great!

**Pull request merged**
