### PR TITLE
Update styling on bounty flow

### PR DESCRIPTION
**Pull request by coderberry**
This PR fixes some styling issues that existed in the bounty wizard (4 steps).

Fixes: #429

### CODE REVIEW

**Comment by thelostone-mc** [comment]
refactoring + reindenting == ❤️

**Comment by coderberry** [comment]
@thelostone-mc Agreed. 4 spaces for HTML is not ideal :(

Can you help me understand how to get the tests passing? I'm new to this codebase

**Comment by thelostone-mc** [comment]
@coderberry Ah sorry I missed this. Not sure on how to change the test rules. Let me dig up on that

Also could we change  [this](https://github.com/gitcoinco/web/blob/master/.editorconfig#L15) ?

Source : https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/

**Comment by PixelantDesign** [comment]
related to #429

**Comment by mbeacom** [comment]
@coderberry @PixelantDesign Is this something that you still want merged?  If so, would you mind resolving the conflicts or I can set aside some time to resolve them later this afternoon.

**Comment by PixelantDesign** [comment]
I would say no at this time since @olaf has already started implementing the new redesign. Thanks Eric!

**Pull request closed without merging**
