### PR TITLE
WIP: #4599 PRs in Bounty Explorer

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
See #4599

##### Refers/Fixes
Fixes: #4599 

##### Testing
[in progress]

### CODE REVIEW

**Comment by kuhnchris** [comment]
@PixelantDesign please decide for going forward:

- Currently we **CANNOT** create an click event as the whole line is sending you to the details page - this would break the basic flow of the table.
- Which style do you prefer - in the footer or separate?
https://files.slack.com/files-pri/T54PGM7NZ-FK82PKB2M/image.png
https://files.slack.com/files-pri/T54PGM7NZ-FKECZG59T/image.png
https://files.slack.com/files-pri/T54PGM7NZ-FKEEBJ196/image.png

**Comment by kuhnchris** [comment]
I managed to... solve this issue somewhat - we just cannot make this box static/stay on screen AND we cannot add any kind of ```<a href>``` - this totally screws up everything within the jsview, so we cannot make links. :-(

**Comment by kuhnchris** [comment]
Well, @PixelantDesign was questioning if we may stomp it alltogether as it is not clickable. It's a nice indicator - but I leave it up to her. If she wants it, I will make a proper new PR / squash it. If not i'll throw it away, probabbly.

**Comment by PixelantDesign** [comment]
The rest of those indicators aren't clickable so I wonder if that would be weird to have that one have an associated action. The other thing is if there are multiple PRs submitted...it could get long and wonky. Let's hold off on this one for now @kuhnchris. Thanks!

**Comment by kuhnchris** [comment]
OK I'll close the PR then

**Pull request closed without merging**
