### PR TITLE
Remove all-caps (text-uppercase) classes

### PR DESCRIPTION
**Pull request by bumi**
aka "do not scream at me"...

This is a quick untested PR to suggest to remove the text-uppercase classes and not write all the content in all-caps. 
I personally think that non-all-caps text is easier to read and generally more polite (uppercase looks like screaming?) :) I don't know what's the reason behind it, I am not a designer at all and generally have no idea, but still wanted to raise this topic.  ;)  

(feel free to close the PR if you disagree/don't care - I know there are more important topics todo :) ❤️ ❤️  :high5:

### CODE REVIEW

**Comment by owocki** [comment]
screencapture-localhost-8080-funding-new-1513307515292
screencapture-localhost-8080-explorer-1513307497807
screencapture-localhost-8080-funding-details-1513307505244

**Comment by mbeacom** [comment]
@bumi You should be able to rebase this with `upstream/master` and it'll pass Travis.  Thanks for the contribution!

**Comment by owocki** [comment]
From the design channel on slack:

> I think there are additional typographic issues at play that make readability an issue currently. I would suggest adding better font weight, sizing and kerning in addition to the removal of oblique font-style.  All-Caps do serve a purpose in certain context but should be restricted to shorter texts. For example titles of content areas etc

**Comment by owocki** [comment]
@bumi are you on the slack channel?

**Comment by bumi** [comment]
ok, awesome. thanks for the feedback. 
I will review the HTML and CSS again and will rebase the master. 

There are some specific styles like (https://github.com/gitcoinco/web/blob/cb88c44aca78b0ea03c357b8f1ee1e48cc214b0f/app/assets/v2/css/gitcoin.css#L16) for headlines etc. this PR does not touch those; it ONLY affects the general text.

**Comment by owocki** [comment]
looking forward to getting this merge-able.  !!

@ me back when its ready

**Comment by owocki** [comment]
will leave a small tip for ya :)

**Comment by owocki** [comment]
there is some convo in channel about the typeface too http://bits.owocki.com/2d2E1M0J1904/Screen%20Shot%202017-12-18%20at%2012.22.46%20PM.png

**Comment by bumi** [comment]
It should be now mergeable. 

And I did not find anything missing. Headlines (h1-h6) and all elements that explicitly have a `text-transform: uppercase` style will still be uppercase. Which I think can be discussed separately.

**Comment by owocki** [comment]
just asked in slack for a final pair of 👀

**Comment by owocki** [comment]
https://gitcoin.co/tip

for consistency.. might be worth doing the same thing for the tips flow...

**Comment by owocki** [comment]
http://bits.owocki.com/3N2V1400343O/Screen%20Shot%202017-12-20%20at%203.49.00%20AM.png

one other small cleanup thing:  we should probably have consistent capitalization on the bounty detail page

**Pull request merged**
