### PR TITLE
fontawesome: upgrade to v5

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description
- Update font-awesome library to 5!
- Removed the old library and replaced it with the new one
- Followed the upgrade instructions as mentioned in the [docs](https://fontawesome.com/how-to-use/upgrading-from-4)
- Updated the icons + css across the site

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/593

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@mkosowsk mind helping me with the review?

**Comment by mkosowsk** [comment]
@thelostone-mc sure will take a peak

**Comment by mkosowsk** [comment]
Code LGTM but did not test :D This PR has earned the 💪🏻🤠👍🏻Mitch Kosowski Seal of Approval™

For other reviewers, @thelostone-mc linked the docs but here is the relevant section on why there are a lot of icon name changes in this update upgrade:

screen shot 2018-03-17 at 7 39 47 am

**Comment by thelostone-mc** [comment]
@mbeacom looks good from our end  !!

**Comment by thelostone-mc** [comment]
@mbeacom rebased ^_^

**Pull request merged**
