### PR TITLE
doc: changed port to 8000 in github integration steps

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

doc: changed port to 8000 in github integration ( same port as what the server is running )
##### Checklist

- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- doc

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@mbeacom merge merge \m/

**Comment by mbeacom** [comment]
@thelostone-mc Thanks for the contribution!

Would you be open to modifying https://github.com/gitcoinco/web/blob/master/app/app/local_settings.py.dist#L30 in this PR as well?

**Comment by thelostone-mc** [comment]
@mbeacom on the `master` branch too ?

**Comment by mbeacom** [comment]
@thelostone-mc A PR to `master` might be the way to go, so it's fixed everywhere.

**Pull request merged**
