### PR TITLE
Accessory - santa moustache and beard

### PR DESCRIPTION
**Pull request by nasehim7**
**Description**
Added Santa Moustache and beard accessory to avatar creator.

**Checklist**
 - [x] linter status: 100% pass
 - [x] changes don't break existing behavior
 - [x] commit message follows commit guidelines

**Affected core subsystem(s)**
avatar

**Testing**
Tested locally, screenshots attached:
- [x] Santa Moustache and Beard
image
image

**Refers/Fixes**
Refs: #2684

### CODE REVIEW

**Comment by nasehim7** [comment]
Gitcoin is set to rock this Christmas :D @owocki

**Comment by nasehim7** [comment]
@mbeacom Your welcome :)

**Comment by owocki** [comment]
this is pure gold

**Comment by nasehim7** [comment]
Thanks Kevin @owocki I have done these two #3005 #2985 as well yesterday. Kindly let me know the take.

**Comment by owocki** [comment]
@nasehim7 awesome!  how much do i owe ya?

**Comment by nasehim7** [comment]
@owocki Thanks! that means a lot to me :D

**Pull request merged**
