### PR TITLE
Add support for Fortmatic

### PR DESCRIPTION
**Pull request by fvictorio**
### Description

Add option for connecting with Fortmatic instead of MetaMask.

image

This isn't 100% complete: it has been tested mainly with the "Fund issue" scenario. The PR is mainly to validate that the implementation approach is OK, and to check if this is a feature you are willing to add.

Some things that are pending:

- As mentioned, this works for the "Fund issue" scenario. In other scenarios, there is a message asking only to connect to MetaMask.
- If this is merged, there are several palces where "MetaMask" should be replaced with the more generic "Wallet".

### CODE REVIEW

**Comment by octavioamu** [comment]
This is great @fvictorio

**Comment by danlipert** [comment]
@fvictorio This is fantastic! We'd definitely be interested in merging this once it gets to a usable point. In terms of acceptance criteria, if the full bounty flow works with creating a bounty, applying to work, payout (and advanced payout, etc.) Then we'd be down to merge it in. We can do the kudos, tips, grants, etc. later

**Comment by fvictorio** [comment]
Closing in favor of #5287.

**Comment by thelostone-mc** [comment]
Closing this out as we have web3modal integrated which supports fortmatic

**Pull request closed without merging**
