### PR TITLE
Simple Nav 

### PR DESCRIPTION
**Pull request by owocki**
continuation of https://github.com/gitcoinco/web/pull/1421

implmenets pixelant nav:

screen_shot_2018-06-13_at_11 46 38_am

### CODE REVIEW

**Comment by mbeacom** [comment]
Deployed to stage.  I'm going to monitor the sendgrid stats and will take corrective action if the outbound thrashing continues.

**Comment by PixelantDesign** [comment]
screen shot 2018-06-13 at 9 19 54 am

screen shot 2018-06-13 at 9 18 07 am

**Comment by PixelantDesign** [comment]
For Reference
screen shot 2018-06-13 at 11 46 38 am

**Comment by owocki** [comment]
we ready to 🚢 it?

**Comment by mbeacom** [comment]
Can we add some space between these two buttons?

screenshot 2018-06-13 15 05 37

**Comment by owocki** [comment]
+1 to marks suggestion

**Comment by thelostone-mc** [comment]
derp derp ! forgot to fix that as per the original design 

x1

**Comment by mbeacom** [comment]
Latest on staging.

**Pull request merged**
