### PR TITLE
FRONT END Inviting Specific Gitcoiners To Work (WIP PR)

### LINKED ISSUE #2200: [Code] Inviting Specific Gitcoiners To Work
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Funder, I'd like the ability to invite specific Gitcoiners to work on my issue after it is funded so that I can foster continuing working relationships with people who I know and trust. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: After the 'Fund Issue' page, while the tx is posting to the blockchain, an option should be provided to send the Gitcoin Issue either a) around the Gitcoin community to top profiles which match the bounty description or b) around the interwebs (on Twitter, Slack, elsewhere) to create a viral loop bringing more dev's into Gitcoin. 

Here's a mock-up from #2038. 

image

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

### Current Behavior
[comment]: # (Describe what actually happened.)
There is no in-app prompting for funders to share / invite people to work on their bounty. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
In-app ways for funders to share with a) Gitcoiner's they've worked with in the past, b) Gitcoiner's who they haven't worked with in the past, but have a good reputation / good fit for the issue and c) social sharing outside of Gitcoin to the funder's community. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Update the bottom portion of the 'Transaction Processing' page into the image provided above (for .sketch files, see #2038). 
- [ ] Re-use existing type down from Tips to search users.
- [ ] This type down should also display wether you've worked with the contributor prior and on how many bounties.
- [ ] The user should be able to clear selected user out of the input field.
- [ ] Please implement and consider failure cases and messaging.
- [ ] Please ensure that the page is responsive.
- [ ] The bounty, once submitted, still should show up in the Issue Explorer as 'Open' status (even though some people have been invited).
- [ ] The invited attendees should receive an e-mail notification / Github notification (if possible) letting them know that they've been invited to work on the task. 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
- Please confirm your technical approach with @mbeacom or @thelostone-mc on technical feasibility/ available data prior to beginning.
- Please expect 3 rounds of reviews with @PixelantDesign @thelostone-mc and @vs77bb .
- Will tip 20% extra for turnaround in 14 days (by 9/25).

### PR DESCRIPTION
**Pull request by mul1sh**
##### Description

This is a WIP PR

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

web

##### Testing

I've tested this PR and i'm sure it will not break anything 😄 

##### Refers/Fixes

Fixes #2200

### CODE REVIEW

**Comment by mbeacom** [comment]
:star: PR built and available in a preview environment **gitcoinco-web-pr-2310** [here](http://web.jx-gitcoinco-web-pr-2310.ci.gitcoin.co)

**Comment by thelostone-mc** [comment]
@mul1sh can you throw in a video / gif ?

**Comment by mul1sh** [comment]
@thelostone-mc sure, its coming up shortly just need to do 2 more commits to clear the issue and then  do the video 🙂

**Comment by thelostone-mc** [comment]
@mul1sh heads up : make sure the design is responsive too ^_^

**Comment by mul1sh** [comment]
@thelostone-mc it is 😃 , just doing my final rebase and then i push

**Comment by usmanmuhd** [comment]
@thelostone-mc Is the PR good to go or are we waiting for something else?

**Comment by SaptakS** [comment]
@mul1sh I can see only a single html file linked to nothing. Are you still working on this? What is the progress?

**Comment by mul1sh** [comment]
I'm on it will wrap it up by mid this week

**Comment by thelostone-mc** [comment]
Closing it out and no progress has been made on this PR. 
Feel free to open up a new one / reopen if this picks up

**Pull request closed without merging**
