### PR TITLE
Add jobs page

### LINKED ISSUE #3931: DESIGN - As a job hunter, I want to have a Gitcoin /jobs page, so I can see what kind of jobs Gitcoin's network has to offer
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
DESIGN - As a job hunter, I want to have a Gitcoin /jobs page, so I can see what kind of jobs Gitcoin's network has to offer.

### Why Is this Needed

Right now our jobs page is fug.

Also, people come to us with an expectation that if they simply apply, that we're going to find time for them to have a half hour call. with them, etc.

Instead, we need to explain to people that we hire mostly through our community and product.  The best way to stand out to us, is to stand out on the platform.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
http://localhost:8000/about#jobs

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Remove existing Jobs section from about page.
- Add a link to `/jobs` on footer.
- A landing page that explains:

* We are built by & for coders.  
* Gitcoin is built with Gitcoin (we dogfood). 
* We believe in try-before you buy hiring (click to see our values => /mission )
* We believe in remote work. (click to see our values => /mission )
* We believe in open source. (click to see our values => /mission )
* Here is a link to our issue explorer.  
* Already done a few bounties?  The best way to apply is below:
* A list of our open Jobs (title, desc)
 *  click on any job and the job desc / application link full details appears.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- 2 -3 revisions
- must follow our brand guidelines (gitcoin.co/presskit)
- must look good on responsivedesign too.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Please include a link to your portfolio in your application.

### PR DESCRIPTION
**Pull request by emiwatanabe422**
Adds the jobs page, with new icons and django view. Adds jobs to footer under Business heading.

##### Description

See #3931

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

ui

##### Refers/Fixes

#3931 

##### Testing and Sign-off

image
image
image
image

###### Contributor

- [ x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x ] Tested all changes **locally**
- [x ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by owocki** [comment]
Design LGTM @PixelantDesign, if it looks good to you i can edit the copy so that it's no longer lorem ipsum.  we'll probably also link it in the footer

**Comment by emiwatanabe422** [comment]
Noticed this button one the products page mentions jobs so it's now linked to the new jobs page.

image

**Comment by emiwatanabe422** [comment]
Hey @owocki, could I get paid out for this? Thanks!!

**Comment by owocki** [comment]
sorry doing so now!

**Comment by owocki** [comment]
@emiwatanabe422 how much do i owe you? i dont see a gitcoin bounty for this and can't remember what we agreed upon :)

**Comment by emiwatanabe422** [comment]
@owocki Maybe 2ETH? I don't think we discussed it before.

**Pull request merged**
