### PR TITLE
css: prettified start work dialog box to match style +  stop work button

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

screen shot 2018-05-02 at 6 23 22 pm

screen shot 2018-05-02 at 8 46 23 pm

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- css

@PixelantDesign @SaptakS thoughts ?

### CODE REVIEW

**Comment by owocki** [comment]
didnt test, but LGTM

**Comment by thelostone-mc** [comment]
> Please move stop work to the row of buttons with the actions associated with the bounty. Let me know if you have questions!

@PixelantDesign I'll change that in a follow up PR  to avoid risk of conflicts ^_^ 

PS : In terms of usage -> isn't it more convenient if the stop work button was next to the bounty hunter
I know it breaks design -> but just putting it out there ^_^

**Comment by thelostone-mc** [comment]
@mbeacom resolved conflicts ^_^

**Comment by mbeacom** [comment]
You pump me up @thelostone-mc ! Thanks! 🍾

**Pull request merged**
