### PR TITLE
Gitcoin chat bot for creating channels

### PR DESCRIPTION
**Pull request by Solexplorer**
##### Description

This PR makes it possible to create channels automatically when the user clicks `Start Work` on a hackathon related bounty. What I have done is the following: 

- Added a function in the `notifications.py` that builds the message as per the example below and then creates a channel:

```
 @solexplorer Work Plan:
I will update the sponsors on my progress as I go.

Use this channel to communicate with teammates and sponsors.
https://gitcoin.co/issue/hashingsystems/hash.js/13/3756
```

- Added docs regarding environment variables

- Created a class that manages the actions of the bot for the gitcoin chat

##### Refers/Fixes

It's more related to #5281 but for MatterMost

##### Testing

I didn't add tests because the setup of the gitcoin chat has not been completed yet. Here is a short of video of [how it works](https://streamable.com/awxwy)

### CODE REVIEW

**Comment by Solexplorer** [comment]
@thelostone-mc @octavioamu @danlipert Can I have a review on this ?
CC: @androolloyd

**Comment by frankchen07** [comment]
I think we'll leave Discord name in until we deprecate, and then we can remove it and make sure we have the correct hooks in to relate gitcoin usernames to mattermost chat (which should be easy).

**Comment by danlipert** [comment]
@androolloyd we can close this right? its already incorporated?

**Comment by Solexplorer** [comment]
Yeah, this is not needed anymore

**Pull request closed without merging**
