### PR TITLE
Job status tab bugs

### PR DESCRIPTION
**Pull request by Adamits**
##### Description

This fixes a minor bug in the `settings/job` page wherein a user needs to re-upload a new resume every time they want to save an update.

##### Refers/Fixes
Fix Bug 2 of https://github.com/gitcoinco/web/issues/4867

##### Testing

Tested locally in browser

### CODE REVIEW

**Comment by Adamits** [comment]
@thelostone-mc Thanks! This is my first PR, what would a working demo look like?

**Comment by octavioamu** [comment]
Great @Adamits thanks for this. What @thelostone-mc is asking is for a video showing how is working with this changes, you can use this [tool](https://chrome.google.com/webstore/detail/screen-and-webcam-recorde/jiihcciniecimeajcniapbngjjbonjan) or any other. 
Thanks!

**Comment by Adamits** [comment]
Great - will do when i'm home from work tonight.

**Comment by octavioamu** [comment]
> Great - will do when i'm home from work tonight.

Thanks @Adamits

**Comment by Adamits** [comment]
Hi, Upon fixing my mistake, I noticed that there is a comment showing the intended way for this to function originally was to simply catch the status code 400 or the no file upload error, and the bug is simply that they catch for a string, rather than int in the condition. Closing this PR and ill submit a new one with that simple fix...

The original issue has also been updated with steps to reproduce BUG 1, so I will address that as well in the new PR.

**Pull request closed without merging**
