### PR TITLE
Add warning for users visiting Grants page

### PR DESCRIPTION
**Pull request by sebastiantf**
##### Description

Adds a warning for users about using Brave Wallet and MetaMask while visiting `https://gitcoin.co/grants`

grantswarning

##### Refers/Fixes

Fixes: https://github.com/gitcoinco/web/issues/5865

##### Testing

No issues on eslint and stylelint.

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@sebastiantf 

This would probably be most effective on the /fund page when users are about to contribute to grant and the grant creation page (/grants/new)

What do you think on restricting the alert to just those pages?
Also If we can figure out if user is using brave and only show it then -> it's super effective 

a quick google led me to this 
https://stackoverflow.com/questions/36523448/how-do-i-tell-if-a-user-is-using-brave-as-their-browser

**Comment by sebastiantf** [comment]
@thelostone-mc Showing the warning on `/grants/new` seems like a good idea. That can be done.

But as I mentioned on the [issue](https://github.com/gitcoinco/web/issues/5865) page, Brave browser doesn't seem to provide a Brave-specific `User Agent` which makes detecting Brave browser difficult. See [#1052](https://github.com/brave/brave-browser/issues/1052)

Since Brave Wallet is a fork of MetaMask, the `web3.currentProvider.isMetamask` returns `true`.

So it seems displaying the warning only for Brave users by detecting **Brave Browser** or **Brave Wallet** to be hard.

**Comment by thelostone-mc** [comment]
@sebastiantf let's do it that way !
If I see a way to detect it -> i'll throw that in later

Danke :D

**Comment by molecula451** [comment]
Good job. This was the best suggestion as per Brave removed UA a while ago

**Comment by sebastiantf** [comment]
@thelostone Shall I change the warning from /grants to the other two pages mentioned?

**Comment by sebastiantf** [comment]
@thelostone-mc Please check my new commits and review this PR. I have changed the warning from `/grants` to `/fund` and `/grants/new`

**Comment by thelostone-mc** [comment]
@sebastiantf Looks good ^_^

**Pull request merged**
