### PR TITLE
Add about section

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
https://www.loom.com/share/23ddaddc911546b0a75ade2cd442df77

## Admin view
Funding The Future! _ Gitcoin

#User view
Funding The Future! _ Gitcoin (1)

##### Refers/Fixes
Close https://github.com/gitcoinco/web/issues/6445

### CODE REVIEW

**Comment by PixelantDesign** [comment]
Looks great! Would it be possible to see a video of the interactions @zoek1 ?

**Comment by thelostone-mc** [comment]
@zoek1 could you map it to the right issues and say if it closes the issue mark it as 
closes <issue-link>

that way the issue is closed when it is merged in

**Comment by zoek1** [comment]
done @thelostone-mc. @PixelantDesign i attached a demo

**Comment by PixelantDesign** [comment]
@thelostone-mc mentioned some issues with this...please hold off deploying.

**Comment by zoek1** [comment]
@thelostone-mc could you mention here the issues so i can address them :pray:

**Pull request merged**
