### PR TITLE
WIP: Fix record_bounty_activity..

### LINKED ISSUE #1659: Wrong profile in activities / messed up activity log
**Describe the bug**
Wrong profile on work_done, work_submitted activities.
Should be the 'fulfiller'.

For reference:
- https://gitcoin.co/issue/gitcoinco/web/1472/637
- https://gitcoin.co/issue/zeppelinos/zos-cli/122/622

I think the problem is in record_bounty_activity.

user_profile = Profile.objects.filter(handle__iexact=new_bounty.bounty_owner_github_username).first()
// if we have a fulfillment; we should use the handle from that fulfillment. right?

See work_done, work_submitted
https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/zeppelinos/zos-cli/issues/122&network=mainnet&standard_bounties_id=622&not_current=1

### PR DESCRIPTION
**Pull request by pinkiebell**
..so that work_done and work_submitted activities[n].{profile} = {fulfiller_profile}
and not bounty_owner_profile.

Note: we need to purge all activities from all already recorded bounties

Fixes #1659

### CODE REVIEW

**Comment by mbeacom** [comment]
@pinkiebell Thanks for the contribution!

I'm testing this locally and will merge if no issues are present!

Thanks again

**Comment by owocki** [comment]
@mbeacom how are your local tests going?  

this may work on a go forward basis... but on a go-backward basis, we'll need another patch.  im coding that now

**Comment by pinkiebell** [comment]
@owocki yep. For backwards resolution you can drop all activities from all bounties
-or-
in create_activity_records.py
//comment out and clear instead
if not bounty.activities.count():

**Comment by pinkiebell** [comment]
@owocki @mbeacom 
Please try again with the new changes.

**Pull request merged**
