### PR TITLE
WIP: Feature/faucet

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
This is a PR to finish faucet designs

##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
UI

##### Refers/Fixes
#407 

##### Examples
screencapture-localhost-8000-faucet-1520360079974
screencapture-localhost-8000-faucet-1520360066513

### CODE REVIEW

**Comment by owocki** [comment]
thanks for the rebase...  PR looks much cleaner now :)

looks like this pr still has some python2 functionaliy in it (i have a pr that migrates things to python3 => https://github.com/gitcoinco/web/pull/407 ) and the old designs (to my knowledge the ones that we want to get merged in are https://github.com/gitcoinco/web/issues/173#issuecomment-354392850 )

let me know if you think this is scope creep and we should take another look at the bounty amount.  happy to revisit that conversation given how much hands this whole thing has been trhough :)

**Comment by KennethAshley** [comment]
@owocki So yea the designs i coded up are the comment you posted. I've updated the description to include the comments. I think the original bounty amount should still apply to this. This was just left hanging due to not knowing how to handle certain states.

**Comment by owocki** [comment]
sorry, too much coffee and im having a hard time understanding what you mean.  

are you saying the new designs are already coded?  or that the bounty should be expanded to cover the new scope of the new designs?

here is what i see when i pull up `/faucet` on this branch. am i just looking at the wrong route?

screencapture-localhost-8080-faucet-1520360846258

**Comment by owocki** [comment]
i think whats throwing me off is that the desktop / tablet sized views don't match [the designs at all](https://github.com/gitcoinco/web/issues/173#issuecomment-354392850).. though after re-reading the PR comment thread, it is clear to me that the mobile sized ones *do* match the designs

**Comment by owocki** [comment]
i believe that if we just make the desktop/tablet sized frontend match the mobile one (and lose the left sidebar) we should be in good shape on this aspect

**Comment by owocki** [comment]
hey @PixelantDesign -- @KennethAshley and i chatted on slack and i think the root of the confusion is that we have mobile designs but no desktop/tablet designs.. 

should we 
1. just scale up (and leave some whitespace) the mobile designs for the desktop design
2. spend a few cycles coming up with another design

?

**Comment by PixelantDesign** [comment]
I think it would be fine to center the designs in a web screen. Let me know if you need a larger top graphic. 

@owocki @kennethashley

**Comment by KennethAshley** [comment]
@PixelantDesign yea a larger top graphic would be perfect!

**Comment by thelostone-mc** [comment]
@KennethAshley care to replace the subscribe to [newsletter](https://github.com/gitcoinco/web/pull/541/files#diff-3cf94c118800a323d8319a6a2ec721a0R39) `Be the first to know about...`  with this 
https://github.com/gitcoinco/web/blob/master/app/dashboard/templates/bounty_details.html#L131 ?
It pushes it to the bottom and it makes it a tad bit neater

@PixelantDesign thoughts ?

**Comment by KennethAshley** [comment]
@thelostone-mc How does this look?

screencapture-localhost-8000-faucet-1520436270631

**Comment by owocki** [comment]
itshappening.gif!  so excited! 😍 i love it

**Comment by owocki** [comment]
my only comment on the above is that it's probably okay to `display:none` the sidebar..

@KennethAshley should @mbeacom and i do a round of testing / code review on this?

**Comment by KennethAshley** [comment]
@owocki I can get rid of the sidebar on this page. and yea id like @mbeacom to do some testing on this. Its went through so many hands i'd feel a bit uneasy without testing.

**Comment by thelostone-mc** [comment]
@KennethAshley It's awesome :D

**Comment by owocki** [comment]
testing now!

**Comment by owocki** [comment]
this is close enough to deploy.... added some more commits over at https://github.com/gitcoinco/web/pull/581 and am merging now!

**Comment by owocki** [comment]
https://gitcoin.co/faucet !!

**Comment by owocki** [comment]
just paid out! https://etherscan.io/tx/0x6884e4168f6867c2103de5d1d7c880d2483abab6cd3560c761cc62da977cab52

**Pull request merged**
