### PR TITLE
3370 - Add V3 Infura API call(s)

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
See #3370 

##### Checklist
- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

crypto

##### Refers/Fixes

Fixes: #3370 

##### Testing and Sign-off

Check it

###### Contributor

- [X] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by kuhnchris** [comment]
Work in Progress - do not merge yet, thanks.

**Comment by owocki** [comment]
do we need to make changes to the js code on the frontend to accomodate using our API keys there?

**Comment by kuhnchris** [comment]
No, we should never expose that key to the public, else everyone could simply go and do stuff with the api. If we have directly a frontend call we need to funnel it through an API

**Comment by kuhnchris** [comment]
@owocki is this issue still open? I did see a "USE_INFURA_V3" config setting in master.

**Comment by owocki** [comment]
donno, i've been focusing on strategic stuff moreso than engineering.  i'd tag one of the engineers.

**Comment by thelostone-mc** [comment]
@kuhnchris this is taken care of ! thanks man ^_^
closing this out

**Pull request closed without merging**
