### PR TITLE
Add new design for grants

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
Implemente this design: https://www.figma.com/file/OAwjMgNRZe16or6QLxIhWx/Grants-CLR-Matching-4?node-id=0%3A1

### CLR Period
Gitcoin Grants Explorer _ Gitcoin (5)

### No CLR Period
Gitcoin Grants Explorer _ Gitcoin (4)

##### Refers/Fixes

redesign grants modules #6224

### CODE REVIEW

**Comment by zoek1** [comment]
@owocki i left you a message on figma. Also, do you prefer i implement a file uploader for the banner or just an input filed (link) is ok for the moment?

**Comment by owocki** [comment]
@PixelantDesign @willsputra what were you thinking for the banner?  do we want to enable user uploads here?

**Comment by owocki** [comment]
talked to will and alisa, i think for simplicity's sake lets just use existing headers for now

grants_index

**Comment by owocki** [comment]
@zoek1

**Comment by zoek1** [comment]
Ok, no problem.

**Comment by owocki** [comment]
lmk when rdy

**Comment by zoek1** [comment]
ready @owocki

**Pull request closed without merging**
