### PR TITLE
temp: using font-awesome CDN

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Not sure what is being missed here, so shifting to FA CDN until resolved

screen shot 2018-06-02 at 11 35 45 pm

screen shot 2018-06-02 at 11 35 51 pm

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by arun1595** [comment]
@thelostone-mc I see the request being sent to https://gitcoin.co/v2/css/fontawesome-all.min.css

I am not sure how static files are handled in Django, shouldn't it instead be https://gitcoin.co/static/v2/css/fontawesome-all.min.css :thinking: ?

I tried hitting https://gitcoin.co/static/v2/css/fontawesome-all.min.css but didn't work.

**Comment by arun1595** [comment]
@thelostone-mc Also, I noticed the following error in Google Chrome browser console.

```
Refused to apply style from 'https://gitcoin.co/v2/css/fontawesome-all.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by thelostone-mc** [comment]
@arun1595 Ah I know 😓 
waiting on the team to help out, if everyone is out -> I'll revert the other PR and restore it to the older state in a bit

**Comment by thelostone-mc** [comment]
@arun1595 Yeah I saw that in the docs!
https://docs.djangoproject.com/en/1.11/howto/static-files/

**Pull request merged**
