### PR TITLE
added branding style to terms page

### LINKED ISSUE #435: Use Gitcoin Brand Template on Terms Page
As a user I want to know that the terms and conditions is real so that I can trust the Gitcoin site.

# Description
Update this page with Gitcoin brand template.
https://gitcoin.co/legal/terms

# Definition of Done
- [ ] Use Muli font
- [ ] Follow front-end design guidelines for styling the page
- [ ] Keep this very simple and legible
- [ ] This page must be responsive
- [ ] There should be no language changes or typos on this page

# Reviewers

@pixelantdesign @thelostone-mc @SaptakS

### PR DESCRIPTION
**Pull request by evgeniuz**
##### Description

Uses Gitcoin brand for terms page.

##### Checklist

- [X] linter status: 100% pass
- [X] changes don't break existing behavior
- [X] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

Added template with brand style (header/footer), similar to other pages, included existing terms into this template (only change to existing terms was removal of `html`, `head` and `body` tags), added context for `terms` view that defines page title.

##### Affected core subsystem(s)

Does not affect core subsystems.

##### Refers/Fixes

Fixes #435

### CODE REVIEW

**Comment by evgeniuz** [comment]
@thelostone-mc Cannot find `boldify` class in code, should I just make `h2` bold?

Will apply changes after other comments answered (about leaving terms.txt/wrapping it in trans).

**Comment by thelostone-mc** [comment]
@evgeniuz derp derp I think we removed that 😅  Yeah just use `font-weight: bold`

**Comment by mbeacom** [comment]
Wrapping in trans or blocktrans would be a solid idea.  The translations might be a huge pain, though.
As for the `.txt`... we should either remove it or treat it as a proper .html template since html resides in the file.

**Comment by thelostone-mc** [comment]
I vote to remove it @evgeniuz ^_^

**Comment by evgeniuz** [comment]
Removed .txt, wrapped in `blocktrans`, added suggested classes to `h2` tags.

**Comment by thelostone-mc** [comment]
rebased + added a few changes to it ^_^

**Comment by PixelantDesign** [comment]
@thelostone-mc good to payout?

**Comment by thelostone-mc** [comment]
@PixelantDesign yup we good for payout ^_^

**Pull request merged**
