### PR TITLE
[WIP] Integrate Portis as a web3 provider

### PR DESCRIPTION
**Pull request by bakaoh**
##### Description
Integrate Portis as a web3.js provider

##### Checklist

- [x] defined Portis as an additional web3.currentProvider
- [x] offering the user to "click here" to use Portis instead

##### Affected core subsystem(s)
No

##### Testing
No

##### Refers/Fixes
Fixes: #969

### CODE REVIEW

**Comment by owocki** [comment]
quick work here.. thanks @bakaoh ! 

doesnt seem like we can merge before the upstream https://github.com/gitcoinco/web/issues/969#issuecomment-384582478 is handled

**Comment by owocki** [comment]
i think we'll have to hit all of the 'no metamask' warning pages. not just the sidebar.  [this one included](http://bits.owocki.com/2o442L2g2v0G/Screen%20Shot%202018-04-26%20at%204.54.22%20PM.png)

**Comment by bakaoh** [comment]
@owocki -- i've updated portis library and added it to all 'no metamask' pages

**Comment by mbeacom** [comment]
@bakaoh Would you mind resolving the conflicts here?

**Comment by owocki** [comment]
just tested this out.  unfortunately it generates a lot of js errrors on localhost:8000/new.  otherwise its pretty cool!

**Comment by bakaoh** [comment]
@owocki --- i'm on vacation. i will look into it when i come back, but it may takes some time since i forgot what i's doing here >_<

**Comment by mbeacom** [comment]
@bakaoh Are you still interested in updating this with the latest Portis library?

**Comment by bakaoh** [comment]
@mbeacom --- really sorry, i'm afraid i don't have time to do updating it now

**Comment by mbeacom** [comment]
Closing this due to major changes in the Portis client that needs to be addressed in a fresh PR.  Please feel free to revisit this @bakaoh

**Pull request closed without merging**
