### PR TITLE
adds 10 more kudos to the site

### PR DESCRIPTION
**Pull request by owocki**
adds 10 more kudos to the site

### CODE REVIEW

**Comment by jasonrhaas** [comment]
For the new kudos, need to make sure we:
- Compress SVG files using `svgo --disable=removeViewBox`
- Update kudos.yaml in the kudos-badges repo (need to be moved over from private to public)
- Mint kudos on chain
- Kudos should sync automatically via the cron

**Comment by owocki** [comment]
wrestling with some dependancies to install svgo now...

**Comment by mbeacom** [comment]
I ran `svgo` against the `images/kudos` directory @owocki

**Comment by owocki** [comment]
thanks! brew wasnt playing nice on this

**Pull request merged**
