### PR TITLE
Refs:#3195 Shades added

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
image
image

**Comment by mehul0698** [comment]
In the second image the black background and boxes are due to clothing.
image

**Comment by mehul0698** [comment]
@thelostone-mc I don't have access to my laptop. I'll do it tomorrow.

**Comment by mehul0698** [comment]
@thelostone-mc I don't have access to my laptop. I'll do it tomorrow.

**Comment by mehul0698** [comment]
@thelostone-mc I have compressed the file.

**Comment by mehul0698** [comment]
@thelostone-mc should I make some more changes for you to merge this branch?

**Comment by mehul0698** [comment]
@thelostone-mc should I make some more changes for you to merge this branch?

**Comment by mehul0698** [comment]
@thelostone-mc I don't know what a merge commit is, so should I make more changes before you merge this branch?

**Comment by thelostone-mc** [comment]
@mehul0698 ah I'm just doing a merge commit with master to ensure all the commits in master are present in your PR before we merge it in!
It ensure your PR is always ahead of master. Tests kick in and ensure nothing has broken

**Comment by mehul0698** [comment]
@thelostone-mc thanks for the info. I have uploaded the pictures for the alien mask also.

**Pull request merged**
