### PR TITLE
Add girl-ey avatar clothing options

### PR DESCRIPTION
**Pull request by emiwatanabe422**
##### Description

Add blouse, coat, crochet top and polka dot blouse to avatar clothing options
For issue:
https://github.com/gitcoinco/web/issues/3713

##### Checklist

- [x ] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x ] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x ] Changes don't break existing behavior
- [x ] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Testing and Sign-off

I have tested the changes
polka
polka2
coat
coat2
crochettop
crochettop2
blouse
blouse2

###### Contributor

- [x ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x ] Tested all changes **locally**
- [x ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by emiwatanabe422** [comment]
I added some formatting changes to the `app/avatar/utils.py`, that should make rebasing slightly less painful.  Does gitcoin have a developer style guide?

**Comment by emiwatanabe422** [comment]
CI is failing because of conflicting migrations. Seems unrelated to my changes.

"django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0012_merge_20190221_2246, 0014_matchpledge in grants).
           To fix them run 'python manage.py makemigrations --merge'"

**Comment by thelostone-mc** [comment]
@emiwatanabe422 yup yup that's not cause of your changes ! fixing that up ^_^

**Comment by owocki** [comment]
master is fixed if you want to merge in those changes.  

i love the new avatar items!

**Comment by thelostone-mc** [comment]
@emiwatanabe422 looks like we do have isort check failing over at app/avatar/utils.py
Could you resolve those ?

**Comment by owocki** [comment]
thanks @emiwatanabe422 how much do i owe you

**Comment by emiwatanabe422** [comment]
@owocki, 100DAI. Thank you!

**Comment by owocki** [comment]
just sent you a tip !  accidently attached to https://github.com/gitcoinco/web/issues/383#issuecomment-469041169 tho

**Pull request merged**
