### PR TITLE
funder_dashboard: core setup

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Ports over the code as is from https://github.com/gitcoinco/web/pull/1351
as commit history was messed up.

The css + js + html file have been restructured! 
Other than that no improvements have been made.

Could we have this up on staging once and then enable that this is URI is available for admin access until we throw in the UI changes ?

Need some help testing it cc @SaptakS @mbeacom

### CODE REVIEW

**Comment by mbeacom** [comment]
Endpoint updated for staff only and on staging.

**Comment by mbeacom** [comment]
screenshot 2018-09-18 09 57 35

**Comment by mbeacom** [comment]
Resolved bad template path/ref and redeployed.

**Comment by mbeacom** [comment]
Committed the requested stickler fixes.

**Comment by PixelantDesign** [comment]
Hi @NedelescuVlad 

Here are the outstanding things we would like you to address to get it across the finish line:

- [ ] The links for active/completed/expired bounties all point to /explorer. Please add the params to filter by the appropriate category.
- [ ] Reclaim Funds CTA currently links to the Expired List on the Issue Explorer. It should show me my expired issues filtered.
- [ ] Bounties in the all bounties should link to the appropriate issue details page.
- [ ] Outgoing funds link should link to the bounty detail page
- [ ] Sorting for recent/oldest don't seem to do anything. 
- [ ] When selecting something with 0 elements...Please display default copy like: No pending bounties.
- [ ] Pagination:  When there are no other pages, do not display the prev/next/page number buttons.
- [ ] Hide prev button if they are on page 1
- [ ] Hide the Next if they are on the last page.
- [ ] Please check the Inconsistent bounty results in the generated CSV from what is displayed/available on the dashboard.
- [ ] - Tidy up Front End some boxes are larger than others…please reference design and check different browsers.
- [ ] - We should hide Budget box/Input for now It does not work in it's current state.
- [ ] - Shrink up the height of Bounties Created, Total Contributors, Total Paid Out
- [ ] - Payout history filters are not working (just monthly)
- [ ] - View Etherscan should open in a new window
- [ ] - Eth and USD labels styles and sizes are not consistent with issue explorer
- [ ]  Ensure this page is responsive.

Let us know if you have any questions!

Anything else here @mbeacom @thelostone-mc

**Comment by NedelescuVlad** [comment]
@PixelantDesign nice, will get on it. Glad you decided to keep the pagination in the end :). 

For the budget box, it seemed to work fine for me when I was testing. I'll look into it and get rid of it if I can't get it to work; though I would like to keep it if it does work. The UI for it is very ugly atm, but I think if I put the bulk of total budget input it in a modal it would be good UX. 

I will follow up with you for ```Ensure this page is responsive``` when I get to it. 

For this - ```Bounties in the all bounties should link to the appropriate issue details page.``` -> so point to the gitcoin.co website's issue details and not github, correct?

**Comment by PixelantDesign** [comment]
Hey @NedelescuVlad we'd to get the remaining work tidy'd up in a week or so, do you think this is possible?

**Comment by NedelescuVlad** [comment]
PR coming out today.

@PixelantDesign I'm a bit unclear about these 2 bullet points:

- Bounties in the all bounties should link to the appropriate issue details page. - The only link this links to is the github link. Is the link of the issue it's linking to, on github, not correct? Can you give an example of what it is right now vs what it should be? 
- Outgoing funds link should link to the bounty detail page. - Is this the 'view etherscan' link on a row basis in the table? It's currently linking to github, should it be the gitcoin website instead?

**Comment by NedelescuVlad** [comment]
Haven't opened the PR yet, wasn't happy with the state of things. I've made a list of what is done and what is left to do on my branch. Here's the list.  The only must do that I don't have a question about is making it responsive, which I'll be working on tomorrow. If I get answers to my other questions under 'Must do' I'm sure I'll be able to finish this up tomorrow. 

You'll also find that there's 2 nice to do's that I've added and which I think would be rather useful - so i'll be doing these as well unless there's any objections.

Must do:
- Bounties in the all bounties should link to the appropriate issue details page. - The only link this links to is the github link. Is the link of the issue it's linking to not correct?
- Outgoing funds link should link to the bounty detail page. - Is this the 'view etherscan' link on a row basis in the table? It's currently linking to github, should it be the gitcoin website instead?
- Payout history filters are not working (just monthly) - This seems to be a data issue. The 'weekly' chart won't show anything when there is no data for the current month. The yearly one shows one point for my test data, for 2018, at the origin of the chart. For the first issue I've added another bullet point to display default text when no data can be shown. For the last one I'm not sure if to handle it specially at all.
- Ensure this page is responsive.


Would be nice to do:
- Ask for the total budget data in a modal instead. Pop up the modal through a button on the total budget module.
- Display default copy when no data is in the chart.


Done:
- We should hide Budget box/Input for now It does not work in it's current state. - I fixed it instead. Might want to put the input stuff in a modal in the front-end.
-The links for active/completed/expired bounties all point to /explorer. Please add the params to filter by the appropriate category. - This was already done in JS. Have a look at activateLinksToIssueExplorer function in funder.js (lmk if we want to change it to be in the html, though I don't really much benefit it doing it).
-Reclaim Funds CTA currently links to the expired List on the Issue Explorer. It should show me my expired issues filtered. - DONE, it wasn't filtering by 'MINE' bounties only. This was due to having used an old query string that controlled that (bounty_owner_github_username instead of bounty_filter=createdByMe).
-Pagination: When there are no other pages, do not display the prev/next/page number buttons. - DONE
-Hide prev button if they are on page 1 - DONE
-Hide the Next if they are on the last page. - DONE
-Sorting for recent/oldest don't seem to do anything. - DONE. I'm using bounty.created_on instead of web3_created.
-Shrink up the height of Bounties Created, Total Contributors, Total Paid Out - DONE
-View Etherscan should open in a new window - DONE
-When selecting something with 0 elements...Please display default copy like: No pending bounties. - DONE. The copy is: 'No outgoing funds were found matching your filters.' and
'No bounties were found matching your filters.'
- Tidy up Front End some boxes are larger than others… please reference design and check different browsers. - DONE
- Please check the Inconsistent bounty results in the generated CSV from what is displayed/available on the dashboard. - DONE

- Eth and USD labels styles and sizes are not consistent with issue explorer - DONE. The previous implementation was respecting the original design in terms of sizing; text color for the token one was a bit off though. Please note I have also updated the outgoing funds to use the same classes for consistency (the original design didn't use background color for outgoing funds).

**Comment by NedelescuVlad** [comment]
Thanks for the tip @owocki !

**Comment by NedelescuVlad** [comment]
Have finished the 'nice to do' bits and 50% through with page responsiveness. Only need to tidy up some more responsive design before I hand this over for re-QA from you guys. Please have a look at the questions I asked in my earlier comment regarding the links issues that were pointed out (it's in the 'Have to do' section)

Will add some screenshots tomorrow for different screen sizes and browsers

**Comment by NedelescuVlad** [comment]
Here's some screenshots - pretty much done I think. Will open a PR. https://imgur.com/a/jhQffHV

Suggestions for how the page should look on mobile / tablet devices are still welcome :)

**Comment by owocki** [comment]
these screenshots look good!

can we resolve merge conflicts

**Comment by NedelescuVlad** [comment]
Yup, I'll solve them on the new PR branch

**Comment by NedelescuVlad** [comment]
Yup, no worries @PixelantDesign - not sure if I'll be able to do these tomorrow but will try :)

**Comment by NedelescuVlad** [comment]
Will wrap this up by the end of tomorrow, deadlines at uni kicked in a bit

**Comment by NedelescuVlad** [comment]
Have dealt with the bullet points. I've also made both 'View Etherscan' (outgoing funds) and 'View Github'(all bounties) point to the Gitcoin Bounty page for the respective bounty. Lmk if this was the intended implementation

@PixelantDesign

I might need some help fixing lint errors... I work on a windows machine and it replaces all file endings that I commit with CRLF instead of LF... any ideas on how to fix that would be great :)

**Comment by NedelescuVlad** [comment]
@thelostone-mc please have a look at merging https://github.com/thelostone-mc/web/pull/2 into this branch. Do expect lint errors though... I've merged master so the conflicts in `helpers.py` should also be resolved after merging that branch.

**Comment by thelostone-mc** [comment]
@NedelescuVlad would it make more sense for you to raise a PR directly to gitcoin/master ? 
Would it make it a lot easier to review as my branch is stale. 
If you think this is easier -> I'd be happy to rebase with master but I'm hoping that doesn't give you conflicts in your PR 😅

**Comment by NedelescuVlad** [comment]
@thelostone-mc yeah that makes sense, I'll make the PR straight to master.

**Comment by owocki** [comment]
pls ignore the aboev.. its just me testing kudos gitcoinbot notifications

**Pull request closed without merging**
