### PR TITLE
fix repeated contributor email.

### LINKED ISSUE #4691: If a grant gets a contribution, you get two mails
**Describe the bug**
When someone contributes to your grant you get 2 mails

**To Reproduce**
Get contributed at

**Expected behavior**
One mail

**Screenshots**
grafik

### PR DESCRIPTION
**Pull request by Skyge**
##### Description

When someone contributes to your grant you will get only 1 mail.

##### Refers/Fixes

Fix #4691 

##### Testing

Try to contribute a project.

### CODE REVIEW

**Comment by Skyge** [comment]
Besides fix this bug, I find at line 265: 
``` javascript
const linkURL = get_etherscan_url(transactionHash);
```
and line 396:
``` javascript
const linkURL = get_etherscan_url(transactionHash);
``` 
we use the function `get_etherscan_url()`, we, however, just provide one parameter, but it also can receive one parameter `network` more, so is there a necessary to provide that?

**Comment by Skyge** [comment]
Because the `web3.eth.sendTransaction()` will return `PromiEvent` that means promise combined event emitter, and fired from confirmation 0 on, which is the block where its minded. so sometimes, it will give two mined block, so the code will run twice in the 
```js
web3.eth.sendTransaction().on('confirmation')
```
then, that will trigger to send email twice.

**Comment by Skyge** [comment]
Ohhh, it crossed my mind that is there a necessary to wait for more confirmation number? such as some exchanges will have at least 12 blocks to confirm a transaction?

**Comment by danlipert** [comment]
The reason a subscription gets saved multiple times is that we save the subscription when the person submits the contribution form, and then again when we get the web3 callback from metamask. To fix this I think we actually need to check when the email gets sent out from the backend rather than changing the frontend logic.

**Comment by Skyge** [comment]
Yeah, but when I look through the code, I find only at the frontend logic will trigger the backend to send email.

**Comment by danlipert** [comment]
@Skyge Yes - what I'm saying is that when that backend logic is triggered, a check should be added to see if the subscription is in the correct state to send the email

**Comment by Skyge** [comment]
@danlipert  I think it is [here](https://github.com/gitcoinco/web/blob/master/app/grants/views.py#L514):
```ts
if 'signature' in request.POST:
    ……
    new_supporter(grant, subscription)
```
So, only when the request.POST contains the key word `signature`, it will send email, maybe I should find more details about it.

**Comment by Skyge** [comment]
@danlipert So how to judge the subscription is in the correct state?

**Comment by Skyge** [comment]
@danlipert Any advice?

**Comment by Skyge** [comment]
If backend logic is triggered, it should send an email, so for correct state, I think it should be contained in the backend logic.

**Comment by danlipert** [comment]
@skyge I think the correct state is where the signature and such is in place - if you watch the database as a grant is created, it first gets created with many fields missing, and then once the signature is done it gets updated - once its in its final updated state, then we should fire the email

**Comment by thelostone-mc** [comment]
Seems like this has been fixed during triage ! 
Closing this out !

Thanks @Skyge  ❤️

**Pull request closed without merging**
