### PR TITLE
Sped up static collect, minor changes to RUNNING_LOCALLY.md in docs

### PR DESCRIPTION
**Pull request by the-rileyj**
## Main Change:

Adding the variable which indicates the number of threads desired for collectfast to use in ```~/web/app/app/settings.py```
* ```COLLECTFAST_THREADS = 20```

Results on a Dual Core laptop

### Synopsis:

I don't have very powerful hardware, allocating 20 threads when I truly only have 4 isn't prudent, however I would imagine that the machine collect static is typically ran on has many more threads; so this is a decent starting place

## Other Changes:

Rationale for the Following Changes:
    Jumping in with no background, there were a few gotchas when it came to gathering all of the dependencies locally (I understand that docker is used in production); I would imagine that this would prove to be a barrier to entry for any future contributors. Which is why I made a few additions to make the local installation more robust.
    Note: I was doing all of this on Ubuntu, so if there are any discrepancies in the additions I made to some of the shell commands in the ```~/web/docs/RUNNING_LOCALLY.md``` file that may be a reason why (using apt instead of brew as a package manager, etc.)

Changed brew install packages
* changed ```python``` to ```python3``` for the sake of clarity
* added ```libvips libvips-dev libvips-tools``` which are needed for the python pyvips python library to function

Added line to ```~/web/docs/RUNNING_LOCALLY.md``` to assure as many packages as possible are installed for running locally in the case an error occurred with the requirements file

```shell

awk '!/^(-r)/' requirements/base.txt requirements/test.txt | xargs -n 1 pip3 install

```

Made minor changes to the portions in ```~/web/docs/RUNNING_LOCALLY.md``` which concerned python but were not explicit in the version
* ex. ```pip``` -> ```pip3```, ```virtualenv ...``` -> ```python3 -m virtualenv```

Made minor changes to ```~/web/docs/RUNNING_LOCALLY.md``` to indicate the context for which commands are executed

From

```shell

python3 -m virtualenv ...

```

To

```shell

~/web$ python3 -m virtualenv ...

```

##### Checklist

- [ x ] changes don't break existing behavior
- [ x ] commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)

##### Affected core subsystem(s)

Changes to ~/web/doc/RUNNING_LOCALLY.md
1 line addition to ~/web/app/app/settings.py

##### Testing

No changes to core code base.

##### Refers/Fixes

https://gitcoin.co/issue/gitcoinco/web/2869/1781

### CODE REVIEW

**Comment by mbeacom** [comment]
@the-rileyj Thanks for the contribution and welcome to the community!

I'd love to enable multithreading for `collectstatic`/`collectfast` and I intended on doing so when I first implemented `collectfast`.  The problem is, we are using the `HashedFilesMixin` to enable us to cache static files for extremely long periods of time and simply upload new assets if they've changed while updating the salt.

There is some incompatibility with collectfast multithreading and the hashing mixin:  https://github.com/antonagestam/collectfast/issues/107

Once this is resolved, I'd be more than happy to add `COLLECTFAST_THREADS = env.int('COLLECTFAST_THREADS', 20)` to start with.

**Comment by the-rileyj** [comment]
Understood, I'll try to do more.

**Comment by mbeacom** [comment]
@the-rileyj Feel free to PR the documentation updates

**Comment by the-rileyj** [comment]
Will do! Expect to see a new PR soon

**Comment by owocki** [comment]
> The problem is, we are using the HashedFilesMixin to enable us to cache static files for extremely long periods of time and simply upload new assets if they've changed while updating the salt.

i wonder why collectstatic takes 3 minutes to run if it's only uploading new assets that have changed  ( see profile on  https://github.com/gitcoinco/web/issues/2869 )

**Pull request closed without merging**
