### PR TITLE
dos2unix line endings for yge and html cleanup

### PR DESCRIPTION
**Pull request by bumi**
Seems like only yge was using non unix line endings. This PR does a dos2unix on the yge files. (please review).
Additionally I also did some indentation cleanup in the HTML files.
And fix an html error I introduced in #195

### CODE REVIEW

**Comment by owocki** [comment]
thanks.. yeah the tests need to be cleaned up.

i should maybe run `dos2unix` on the whole codebase myself.  its very hard to review this PR and make sure there's no vulnerability injected.. since theres so much code taht's changed.  unless thers an easier way to do a diff?  not that i don't trust ya @bumi , but.... its crypto... so the downside is high.

@mbeacom what do you think

**Comment by bumi** [comment]
yeah, not sure how to diff it best or how to make it easier to review.
Such huge PRs suck. I've made two commits, one for the html that also includes some indentation fixes and one for the assets. 
(btw. regarding the HTML: I mostly use 2 spaces indentation for HTML - is it in python projects 4 spaces, like in python files? )

If the reason is "crypto" then I think we should not even "trust" your computer and as a project not even "trust" your account :)  actually guess it is less about trust but more about reviewing changes in general.

**Comment by owocki** [comment]
@bumi appreciate you doing this..  i think in leiu of accepting this Pr, could you just let us know what command you used to migrate everything over?

**Comment by bumi** [comment]
[dos2unix](https://waterlan.home.xs4all.nl/dos2unix.html) is the friend :) 
let me know if I can help something

**Comment by mbeacom** [comment]
Thanks @bumi! We're working to move everything over to a standard format and we'll likely validate syntax/styling via a pre-commit hook.

**Comment by bumi** [comment]
great! standards sound good :) 
I think for the dos file endings it is more a local git setting isn't it?

**Pull request closed without merging**
