### PR TITLE
zksync version update

### PR DESCRIPTION
**Pull request by mds1**
We bump the zksync version to a version which requires us to provide API keys for node providers. Without API keys, ethers falls back to shared API keys which can be throttled. For Infura, `document.contxt.INFURA_V3_PROJECT_ID`. Do we have API keys that we can use for Etherscan, Alcehmy, or Pocket?

### CODE REVIEW

**Comment by mds1** [comment]
@octavioamu @thelostone-mc This is now ready for review/merge, pending any additional API keys we want to include

**Review by thelostone-mc — APPROVED** [review]

**Comment by thelostone-mc** [comment]
let's roll with INFURA for now !

**Review by danlipert — APPROVED** [review]
We have a paid infura account so we should be good in terms of throttling

**Review by aamustapha — APPROVED** [review]

**Comment by thelostone-mc** [comment]
@mds1 could you resolve the conflict and we can get this in todayn

**Comment by mds1** [comment]
@octavioamu Looks like the conflict is because you changed the CDN for the zkSync package. Do you have any context for why this change was made? I don't think it should matter which CDN we use but want to confirm first before resolving the conflict

**Comment by thelostone-mc** [comment]
@mds1 had issues with unpkg and it wasn't loading in a few situations so @octavioamu switched it over to jsdeliver which fixed that issue. 
Here is the slack link https://gitcoincore.slack.com/archives/CAXFMVDGD/p1608218741052000

**Comment by mds1** [comment]
Ok, just updated the URL 👍

**Pull request merged**
