### PR TITLE
html: replaced slack image with font-awesome icon

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

replaced img with font-awesome -> page loads a tad bit faster
If this is alright, will do it in batches so as to use icons rather than images + refactor along the way

- replaced slack image with slack font-awesome
- re-indented nav
- noticed that nav bars have different size on different pages, so evened it out

##### Checklist

- [ ] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- html

### CODE REVIEW

**Comment by owocki** [comment]
as youre submitting these frontend PRs it might be nice to see screenshots of your work without having to pull the branch :)

**Comment by thelostone-mc** [comment]
@owocki Yeah I was getting to that 😅

**Comment by thelostone-mc** [comment]
Most pages in gitcoin have a navbar of this size: 

screen shot 2018-01-30 at 5 08 43 pm

But pages like the landing, help have a larger nav bar

screen shot 2018-01-30 at 5 08 57 pm

After fix: 

screen shot 2018-01-30 at 5 09 11 pm

**Comment by thelostone-mc** [comment]
@owocki review + merge ?

**Comment by owocki** [comment]
thanks!

**Pull request merged**
