### PR TITLE
GITC-580: implements matching pool filter

### PR DESCRIPTION
**Pull request by gdixon**
##### Description

This PR implements the matching pool filter:

```
GIVEN a grants round is active
WHEN I am on the Grants Explorer Page
THEN I see a grant round filter, tags, region, blockchain, and "more" filter.

GIVEN a grants round is not active
WHEN I am on the Grants Explorer Page
THEN I do not see a categories filter, only a tags, region, blockchain filter, and a "more" filter.

GIVEN a grants round is active, I'm on the Grants Explorer Page, and see the grant round filter
WHEN I click on the grant round filter
THEN the pill box reads "Grant Round",
AND the arrow carat switches to point up,
AND the primary and secondary menus show:
main (primary) -> all (secondary)
cause (primary) -> (advocacy, longevity, climate change) (secondary)
ecosystem (primary) -> (algorand, uniswap, etc) (secondary) in alphabetical order.

GIVEN I am looking to filter by a primary matching category
WHEN I click on my primary-level selection
THEN the primary item is highlighted
AND the page returns all grants eligible in rounds under the primary matching category selection
AND the pillbox reads "Grant Round: [primary]".

GIVEN I am looking to filter by a secondary matching category
When I click on my secondary-level selection
THEN the secondary item is highlighted with the parent primary item
AND the page returns all grants eligible in rounds under the secondary matching category selection
AND the pillbox reads "Grant Round: [primary] - [secondary]".

GIVEN I have selected options on the grant round filter
WHEN I scroll down on the grant explorer page
THEN the filter bar with the grant round pill will be stickied at the top.

GIVEN I have filtered options using the grant round filter
WHEN I click off the menu
THEN the menu minimizes AND keeps the pillbox selection.

GIVEN I have filtered options using the grant round filter and have clicked away
WHEN I click back into the grant round filter
THEN the menu highlighting and pillbox reflects my previous selection.

GIVEN the design updates on the web platform for the grants explorer matching pool filters
WHEN I view the grant explorer on my mobile
THEN the responsive views will take effect.
```

##### Refers/Fixes

Closes: GITC-580

##### Testing

Screenshot 2021-11-24 at 04 54 59

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by frankchen07** [comment]
On staging, it seems like selecting primary or secondary menu items doesn't filter the grants down. I anticipate it showing "0 grants" for most menu selections, but for most of them, it still says 24 grants.

**Comment by gdixon** [comment]
> On staging, it seems like selecting primary or secondary menu items doesn't filter the grants down. I anticipate it showing "0 grants" for most menu selections, but for most of them, it still says 24 grants.
> 
> Gitcoin Building Gitcoin shows up under "Main" in the filter, but the Main Rounds (All) doesn't show up there.

This is because of an error in the CLR configuration:

e.g for Polygon, we need to change:

`{"tags": "11", "grant_type": ["1", "2", "6", "7", "8", "10"]}
`
->

`{"tags": "11", "grant_type__in": ["1", "2", "6", "7", "8", "10"]}`

**Comment by frankchen07** [comment]
@gdixon - got it. So I updated the `__in`, but the primary level filter still doesn't work. You can test it by doing ecosystem rounds?

Uniswap filters on uniswap. The other ecosystem specific ones have 0. If I just do all ecosystem as the only primary level, the logic should dictate that it shows the Uniswap ones, right? Right now, nothing happens from all grants.

**Comment by frankchen07** [comment]
- [ ] Also, it looks like ecosystem rounds aren't showing up on the homepage.

- [ ] And Gitcoin Building Gitcoin is showing up twice.

Screen Shot 2021-11-29 at 3 35 28 PM

**Comment by gdixon** [comment]
> @gdixon - got it. So I updated the `__in`, but the primary level filter still doesn't work. You can test it by doing ecosystem rounds?
> 
> * [x]  Uniswap filters on uniswap. The other ecosystem specific ones have 0. If I just do all ecosystem as the only primary level, the logic should dictate that it shows the Uniswap ones, right? Right now, nothing happens from all grants.

Good catch @frankchen07 - I missed that! I've addressed it here: https://github.com/gitcoinco/web/pull/9767

----

The mini banners were adjusted in the following PRs: https://github.com/gitcoinco/web/pull/9641 && https://github.com/gitcoinco/web/pull/9766

**Comment by gdixon** [comment]
> * [x]  Gitcoin Building Gitcoin shows up under "Main" in the filter, but the Main Rounds (All) doesn't show up there.

The round wasn't set to active, its showing up now 👍

**Comment by frankchen07** [comment]
- [ ] Gitcoin Building Gitcoin round shows in filtering menu (shouldn’t be there at all), is it possible to remove it?

**Comment by gdixon** [comment]
> * [x]  Gitcoin Building Gitcoin round shows in filtering menu (shouldn’t be there at all), is it possible to remove it?

Someone had set the Gitcoin Building Gitcoin round from GR11 to active - fixed now 👍

**Comment by gdixon** [comment]
> * [x]  And Gitcoin Building Gitcoin is showing up twice.

I've raised a PR to correct this: https://github.com/gitcoinco/web/pull/9768

**Comment by gdixon** [comment]
> * [x]  Also, it looks like ecosystem rounds aren't showing up on the homepage.

I've raised a PR to correct this: https://github.com/gitcoinco/web/pull/9769

**Pull request merged**
