### PR TITLE
Daily Email PR

### PR DESCRIPTION
**Pull request by owocki**
copy of https://github.com/gitcoinco/web/pull/6471 , so that travis will re-run the tests

### CODE REVIEW

**Comment by danlipert** [comment]
@owocki I tried fixing this today but didn't get too far - basically it seems that the tests for the daily email are failing because the daily emails now reference a CSS file that cannot be found due to collectstatic not being run on travis. Typically, we don't have tests that require rendering a template so this hasn't been an issue before? I tried adding collectstatic to the travis.yml but couldn't get it to work.

**Comment by owocki** [comment]
sorry, closed wrong PR!

**Comment by sebastiantf** [comment]
@danlipert Can you please share specifically how you tried adding collectstatic to travis.yml, if you don't mind?

**Comment by sebastiantf** [comment]
I tried to add collectstatic to travis build step but getting this error repeatedly at collectstatic:
```
Ignored error in Collectfast:
relation "collectfast" does not exist
LINE 1: SELECT "cache_key", "value", "expires" FROM "collectfast" WH...
                                                    ^
--> Continuing using default collectstatic.
```

**Pull request closed without merging**
