### PR TITLE
Add Travis and Codecov integrations

### PR DESCRIPTION
**Pull request by mbeacom**
The goal of this PR is to implement automated testing and coverage to the repository. 

Reference: #89 

Repository owner should:

- Visit https://codecov.io/gh/gitcoinco/web/ and add the github webhook  
- Visit https://github.com/apps/codecov and configure codecov integration for `gitcoinco/web`
- Visit https://travis-ci.org/ and add the `gitcoinco/web` repository to Travis.

### CODE REVIEW

**Comment by owocki** [comment]
ok, added to travis / code cov.  @mbeacom thanks for doing this.  let me know if you need edit access to gitcoinco/web on either service

**Comment by owocki** [comment]
hmm readme still shows 'unknown' http://bits.owocki.com/3o2A2i031103/Screen%20Shot%202017-12-11%20at%201.16.50%20PM.png

**Comment by mbeacom** [comment]
It'll show unknown until a new build is initiated and merged that has ran against travis.

**Comment by owocki** [comment]
build is passing now!  but dat codecov icon! http://bits.owocki.com/1d2Y320N3M2h/Screen%20Shot%202017-12-11%20at%202.54.34%20PM.png

**Comment by mbeacom** [comment]
I know ☹️ We'll get it up!

**Pull request merged**
