### PR TITLE
Add chat page

### LINKED ISSUE #5578: CODE - As a Gitcoin user, there's a new chat? Where, why, and how can I get access?
### User Story

As a Gitcoin user, there's a new chat? Where, why, and how can I get access? This is the design of the chat landing page.

### Why Is this Needed

With the upcoming release of Mattermost Gitcoin chat, we'll be migrating our hackathon Discord chats and also slowly closing out our Slack community chat in favor of our own hosted Gitcoin chat. 

As we make the transition, there needs to be a page explaining the new chat system, a web-window for people to chat in that don't have the web/mobile app yet, as well as easy-access to the web & mobile download links. Transparency and marketing for this new chat will be groundbreaking so we want to make sure we have a nice landing page so everyone can get onboarded.

### Description

gitcoin.co/slack is the current "chat" page, we want to make gitcoin.co/chat the landing page
gitcoin.co/chat/web will be the in-browser chat window
if they have not joined gitcoin yet, then gitcoin.co/chat should lead to gitcoin.co/chat/login?

on the landing page we should have:

1. copy as to how the gitcoin community how has chat and why we're moving over (advanced functionality, in-app, future integrations with gitcoin products)

2. shows how many people are online now!

3.  links to download the desktop & mobile standalone versions
from my perspective it should just talk briefly about how the gitcoin community has chat (and maybe X ppl are online now) and have links to web/desktop/mobile experiences

gitcoin.co/chat redirects to a landing page gitcoin.co/chat/login

### Current Behavior

no design for chat landing page

### Expected Behavior

design for chat landing page

### Definition of Done
- [ ] chat landing page design with requirements above

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Refers/Fixes
Fixes #5578 

##### Testing
Navigate to `/chat` to view

### CODE REVIEW

**Comment by owocki** [comment]
ready for a review? can u send screenshots in mobile/tablet/desktop view?

**Comment by owocki** [comment]
@androolloyd

**Comment by iamonuwa** [comment]
Sure, will send it this morning

**Comment by owocki** [comment]
any udpate on screenshots @iamonuwa

**Comment by iamonuwa** [comment]
I did a rebase that needs me to re-run the docker-compose thing. Once I have it up, I'll send in a screenshot

**Comment by owocki** [comment]
..

**Comment by owocki** [comment]
if you dont post a bug letting us know whats blocking you we cant help you on this onuwa

**Comment by iamonuwa** [comment]
It's not a bug, I need to update the dependencies

**Comment by iamonuwa** [comment]
This is the error I've been running into.

Screenshot from 2019-12-12 18-29-26

**Comment by iamonuwa** [comment]
@owocki desktop view

Screenshot from 2019-12-25 00-48-56
Screenshot from 2019-12-25 00-49-02
Screenshot from 2019-12-25 00-49-05

**Comment by iamonuwa** [comment]
Mobile view

Screenshot_20191225-005147_Chrome
Screenshot_20191225-005200_Chrome
Screenshot_20191225-005133_Chrome

**Comment by Sirlupinwatson1** [comment]
What a nice upgrade @iamonuwa  !!!!  Great work … Merry Christmas to you my friend !!!! 

Keep the good work going on ! Ill be watching ya !  🥇

**Comment by owocki** [comment]
looking good to me @iamonuwa  (except the travis CI build is failing)..

cc @androolloyd who is pushing towards the 1/6 launch of chat

**Comment by iamonuwa** [comment]
> looking good to me @iamonuwa (except the travis CI build is failing)..
> 
> cc @androolloyd who is pushing towards the 1/6 launch of chat

I'll look at why ci is failing

**Comment by androolloyd** [comment]
I think I already merged this into my branch @iamonuwa

**Comment by owocki** [comment]
great; paying out now. thanks again @iamonuwa

**Comment by thelostone-mc** [comment]
Closing this out cause it's already in #5569

**Pull request closed without merging**
