### PR TITLE
bump github api usage

### LINKED ISSUE #8751: Update pyGithub version and code
**Describe the bug**

we must update https://github.com/PyGithub/PyGithub to the latest.

image

- Update lib
- Update access_token as query param to auth header (js and django)
- Update client_id client_secret to be a header 

check deprecations here and follow the changes https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

### PR DESCRIPTION
**Pull request by chibie**
##### Description

update API usage according to deprecation notice here https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/ and https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/

- [x] update headers
- [x] update oauth application endpoints i.e send `access_token` in body
- [x] update test cases
- [x] bump pyGithub

##### Refers/Fixes

closes #8751 

##### Testing

- [x] Send tips kudos and every place using the (search github user)
- [x] Create bounty / hackathon bounty
- [x] Update bounty details
- [x] login/logout
- [x] Sync profile command
- [x] User directory

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]
codewise lgtm

**Comment by octavioamu** [comment]
hey guys this should have the pygithub bump? Is the main one causing the reports from github.

**Comment by chibie** [comment]
@octavioamu i've added a new checklist item... i'm looking at the latest version of pygithub to be sure it makes requests the right way before bumping that.

**Comment by chibie** [comment]
@octavioamu from https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py

L315-L317...L580-L582

```
        elif login_or_token is not None:
            token = login_or_token
            self.__authorizationHeader = f"token {token}"
        ...
     def __authenticate(self, url, requestHeaders, parameters):
        if self.__authorizationHeader is not None:
            requestHeaders["Authorization"] = self.__authorizationHeader
 ```

 this commit removed it https://github.com/PyGithub/PyGithub/commit/901af8c862666370010513259f206e251ac3b4b4#diff-03c77d4fafa64b1562eb82c0999ce1be6b7a2609b01f2eba4d2279a163e60a0c

**Comment by octavioamu** [comment]
@chibie I think you are confused, we don't use pygithub to oauth2, we use it to fetch data in many places from github api

**Comment by chibie** [comment]
@octavioamu let's get on a call asap

**Review by octavioamu — APPROVED** [review]

**Comment by octavioamu** [comment]
Good work @chibie , I will say this pr kind of scare me a little not because the code, but more because touch so many places.

**Pull request merged**
