### PR TITLE
Fix space, typo and rename

### PR DESCRIPTION
**Pull request by gamwe6**

### CODE REVIEW

**Comment by owocki** [comment]
is `LISCENSE` the standard, instead of `LISCENSE.txt`?

**Comment by gamwe6** [comment]
You can use both https://www.apache.org/dev/apply-license.html#license-file-name.
Just to be consistent with README.md, I've uppercased it. If you want, we can let it lowercased.
Which leads to another question? What do you think of a CONTRIBUTING.md file (for coding style, naming conventions, etc.)?

**Comment by gamwe6** [comment]
Do you need these extra spaces?

**Comment by owocki** [comment]
> What do you think of a CONTRIBUTING.md file (for coding style, naming conventions, etc.)?

All for it.  Want to PR up a quick draft and I'll contribute in with anything I want to specify?

>Do you need these extra spaces?
No, thanks.

**Pull request merged**
