### PR TITLE
add kudos section to modal

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

image

##### Checklist

- [ ] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [ ] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by PixelantDesign** [comment]
awesome!

**Comment by octavioamu** [comment]
Tested in local but the entry is only created if is shared by looking for a user, not when you share the link in social networks or direct, in this case is givin an error.  I think the entry need to have some reference to the one who invited and create the entry when someone gets in using it.

**Comment by SaptakS** [comment]
@octavioamu When you are sharing a link, you have to share the link in this text: 
```
Check out this bounty that pays out 0.001 ETH http://localhost:8000/issue/U2FwdGFrU1g5NmdSQVZ2d3g1MnVTNnc0UVlDVUhSZlIzT2FvQjE=  #Smarty
```

If you share the normal URL, obviously it can't be tracked.

@PixelantDesign currently it's shown like this:

Screen Shot 2019-03-14 at 9 41 37 AM

Let me know if there needs to be a UI/UX update to show the shareable link more prominently rather than in the text.

cc: @willsputra

**Comment by SaptakS** [comment]
@PixelantDesign @octavioamu @willsputra Updated the message and the link in the social shares to include the same hashed URL link so we can track the invite.

**Pull request merged**
