### PR TITLE
Details edit - PR to view changes and migrate to grantz

### PR DESCRIPTION
**Pull request by captnseagraves**
DO NOT MERGE - Details edit - PR to view changes and migrate to grantz

### CODE REVIEW

**Comment by mbeacom** [comment]
@captnseagraves HEADS UP - You can use `dont merge` label versus all caps in the title xD

**Comment by mbeacom** [comment]
Also, the base branch here is still `grants` vs `grantz`

**Comment by captnseagraves** [comment]
OK good to know. I'm just using this PR as a way to cherry pick out the changes so I can put them on a branch of `grantz`. This PR is based off of `grants` still.

**Comment by mbeacom** [comment]
You can grab a patch diff `git diff branch_or_sha branch_or_sha > changes.patch` then `git checkout grantz; git apply changes.patch`, so you can do this in the future without raising a PR.  Going to close this for now since it's not intended to be merged.

**Pull request closed without merging**
