### PR TITLE
Fixes: https://github.com/gitcoinco/web/issues/792

### PR DESCRIPTION
**Pull request by willsputra**
##### Description

Separated profile and username to 2 lines. 
##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes

Fixes: https://github.com/gitcoinco/web/issues/792

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@willsputra Conflicts :P

**Comment by thelostone-mc** [comment]
@mbeacom you just copied what I said :P

**Comment by mbeacom** [comment]
@thelostone-mc 🤷‍♂️ Just going down the list! 😅

**Comment by willsputra** [comment]
oops thanks @mbeacom @thelostone-mc lemme try it out in a bit!

**Comment by thelostone-mc** [comment]
@willsputra squash  + screenshot !!

**Comment by willsputra** [comment]
screenshot here:

screenshot 2018-04-09 22 58 04

**Comment by mkosowsk** [comment]
@willsputra looking good! I haven't looked at the latest changes so you may have already done this but make sure to do `npm run stylelint:fix` and fix the `css` errors... @thelostone-mc and @mbeacom please make sure to let people know to do this, it's very important! 👍

**Comment by mbeacom** [comment]
@mkosowsk Per the contributor guidelines, you should install `pre-commit` - This will alert you before committing that your branch won't pass Travis CI.

**Comment by willsputra** [comment]
apologies for the hiccup guys 🙏

**Comment by mbeacom** [comment]
@willsputra All good! Thank you for your contribution!

**Comment by mkosowsk** [comment]
@willsputra no worries and congrats on the contribution! 

I was just trying to be a smartass and give @mbeacom a hard time for repeating what @thelostone-mc said 😂 but then he went and provided some good insight 🤔

**Pull request merged**
