### PR TITLE
Update quest style to support portrait view

### PR DESCRIPTION
**Pull request by zoek1**
##### Description

Add portrait view support for android and iphone devices and fix overlapping options and submit button.
##### Refers/Fixes

https://github.com/gitcoinco/web/issues/5418

##### Testing
*Android samsung galaxy s5*:
Play the _MetaCartel Lore_ Gitcoin Quest and win a _Meta Cartel_ Kudos _ Gitcoin (1)
Play the _MetaCartel Lore_ Gitcoin Quest and win a _Meta Cartel_ Kudos _ Gitcoin

*Iphone 5*:
Play the _MetaCartel Lore_ Gitcoin Quest and win a _Meta Cartel_ Kudos _ Gitcoin (2) se
Play the _MetaCartel Lore_ Gitcoin Quest and win a _Meta Cartel_ Kudos _ Gitcoin (2)

### CODE REVIEW

**Comment by zoek1** [comment]
@owocki could you give me feedback of how looks the changes?

**Comment by thelostone-mc** [comment]
This is def a improv ❤️

**Comment by zoek1** [comment]
@thelostone-mc i've been waiting for feedback of the proposed adaptation, but if it's ok that's awesome. 
I couldn't click the start work button, someone is assigned to the work :sweat_smile:.

**Comment by zoek1** [comment]
I think i can fix other little glitches at the quests, maybe this weekend i'll submit a PR :thinking:

**Comment by zoek1** [comment]
> This is def a improv 
> 
> @zoek1 go ahead and click on start work on the bounty so that you can get paid out on merge


@owocki @thelostone-mc  still could i be rewarded by this PR. Because the bounty is traditional and only one user is assigned i couldn't click the start work button, i see that other MR was merged  so i don't know if that could have a conflict.

**Pull request merged**
