### PR TITLE
Gitcoin Updates modal

### LINKED ISSUE #4896: UX & BUILD - As a Gitcoin funder I'd like to be tastefully routed to the dashboard after a login event via a "new dashboard" dynamic modal.
# User Story
UX - As a Gitcoin funder I'd like to be tastefully routed to the dashboard after a login event via a "new dashboard" dynamic modal.

# Why
Funder Feedback Example:
" I'd be happy for that to be my landing page after I log in.
That's what I need most."

# Assumptions
Human - Funders want to go to the dashboard when they come to Gitcoin
Business - We assume that redirecting them at every login enhances their exprience.
Tech - Only going to apply this to people set as a funder. 

# Description

1. dynamic modal admin section (keep it simple)
2. one entry when we need it, with a scroll
3. marked if a user will see it or not

# Definition of Done
- [ ] Route all funders to the dashboard post log-in
- [ ] Come up with rules on scenario where funder returns, already logged in.

Estimate: **small**

# Data (requirements)
Url tracking , google analytics
Where do people go after dashboard - behavioral flows
Whats the most common action?
Need tracking on modules.

Metrics
Unique page views
Most commonly executed flow
Increased retention!

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

All the content is from a Gist file, so can be updated in any moment.
I created some rules to not affect performance or be annoying with the users:
- just prompt for logged users
- Don't fetch and open the modal if user had seen the modal in the last 7 days.
- If the user had seen the modal more than 7 days ago, check if the content of the modal had changed, if is diff than the last time then open the modal.
- Also I can bypass all the rules with a parameter if we want to link the modal in anywhere 

image

##### Refers/Fixes

Fix #4896
##### Testing

https://embed.vidyard.com/share/DfE1gP7mvRvSh6e79DLNDF

### CODE REVIEW

**Comment by octavioamu** [comment]
@danlipert yes agree, there is not shared management of gists. Should we create it in our database instead? There is other external tool we can use for that? I was checking maybe gh wikis ?

**Comment by danlipert** [comment]
Yeah the Github Wiki could work

-Dan Lipert

**Comment by thelostone-mc** [comment]
Looks solid ! adding a don't merge label until we have content figured out to throw into the wiki ❤️

**Comment by octavioamu** [comment]
looks like wiki are not available by gh API https://github.community/t5/How-to-use-Git-and-GitHub/API-for-repository-s-wiki/td-p/6706

**Comment by octavioamu** [comment]
ok found a better way, now is an issue https://github.com/gitcoinco/web/issues/5057

**Comment by danlipert** [comment]
This good to merge today? What do y'all think? @octavioamu @thelostone-mc

**Pull request merged**
