### PR TITLE
feedback system WIP

### PR DESCRIPTION
**Pull request by owocki**
##### Description

feedback system

[screenshot of process issue](http://bits.owocki.com/0I43373V430W/Screen%20Shot%202018-06-16%20at%202.19.56%20PM.png)
[screenshot of submit work](http://bits.owocki.com/1j1f2Y1y2f0h/Screen%20Shot%202018-06-16%20at%202.20.44%20PM.png)

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

submit / accept fulfillment

##### Testing

no tested yet

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/1464

### CODE REVIEW

**Comment by kuhnchris** [comment]
Hey there everyone. @PixelantDesign assigned me to finish up the good man's work you started here.
Some intermediate changes already done: 
- Stars are now gitcoin-green and on hover transparent and on click filled (still broken for payout for some reason, investigating)
image
- Checked the data flow, comments will be stored with the ipfs call
image

Next steps:
- when receiving the data back from web3/ipfs we need to store the comment object (dashboard/helpers.py:715ff)
image
- create comment (database) object and store data
- administration view (dashboard/admin) to show comment objects

Next steps II:
- display comments on the profile page
- display rating on the apply/profile page (example KuhnChris 4 stars (10) -> <name> <med./avg. rating> (<amount of ratings>) )

If you have any more points regarding this topic @owocki  @PixelantDesign @mbeacom let me know.

**Comment by mbeacom** [comment]
@kuhnchris I have a stash with the vast majority of this completed.  I was under the impression we were putting this on the back burner for the time being until we could come to a consensus on integration with the bounties network platform, though 🤔 
@PixelantDesign This has changed?

**Comment by kuhnchris** [comment]
oooh! dammit! I'll stop working on it right away! Sorry @mbeacom . @PixelantDesign want me to switch priorities?

**Comment by PixelantDesign** [comment]
ohh right...There wasn't anything updated on this ticket since September. And yes, we did say we are going to work on thet in Q1, slipped my mind. Sorry @kuhnchris!

**Comment by kuhnchris** [comment]
I think @mbeacom has it already schedule somewhere so may aswell not disturb him on that. The fast-forward of the state of the branch that was submitted was without any issues, so there may just be a couple of adaptions to his code, especially if he's nearly finished.
Up to him, but usually it doesn't make sense to switch dev mid-implementation

**Comment by owocki** [comment]
i'd prefer if @mbeacom shared his stash of code changes so that @kuhnchris can move forward on this.  @mbeacom is (understandably) busy for this month, so if we want to get this moving forward again, we should move the implementation over to @kuhnchris

**Comment by owocki** [comment]
@kuhnchris i dont think the core team is going to get to this anytime soon.. if you have cycles, lets figure out how to get it back in flight

**Comment by kuhnchris** [comment]
@owocki @mbeacom talked to me about this - the basic idea is already implemented. What needs to be done is that we need to "redo" the avatar builder/configurator to use the new system and URLs. If you want I can go ahead and start working on it. According to Mark we need to improve the available parameters to the new URL so we can use it dynamically, but aside from that not much work is left on the backend side. If you want me to focus on this, let me know!
:-)

Merry X-Mas,
Chris

**Comment by kuhnchris** [comment]
image
:suspect:

**Comment by owocki** [comment]
shit @kuhnchris we probably have to normalize the kudos image size and/or add a max-width property to that element.

@mbeacom can you share your stash?

**Comment by owocki** [comment]
@kuhnchris i talked to @mbeacom on slack today; he is going to share his stash

**Comment by owocki** [comment]
@kuhnchris i've asked mark a few times to post his stash and he hasn't followed through.  i dont know what to say, i'm ready to give up on using mark's code.  can you just move forward without it?

**Comment by kuhnchris** [comment]
Hey there @owocki well @mbeacom has his hand full right now with other topics, I guess. Maybe poke him on the core-team chat once more. Please clarify with @PixelantDesign if we can go ahead without mark's stash if you really want to get this up and running.

Thanks!
cc @PixelantDesign

**Comment by PixelantDesign** [comment]
Hey @kuhnchris I think @owocki means that @mbeacom will share his code so that you can take that and run to help us get it across the finish line. Let me know if you have questions!

**Comment by owocki** [comment]
I understand if @mbeacom has his hands full elsewhere and am fine if he's not responsive if you go forward without it.

**Comment by thelostone-mc** [comment]
Followed up at https://github.com/gitcoinco/web/pull/3709

**Pull request closed without merging**
