### PR TITLE
designs corrected

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
Mistakes:-
image
image
image
image
Corrected:-
!
image
[image](https://user-images.githubusercontent.com/37936499/55348101-0da18580-54d4-11e9-8014-de5a5872dc6b.png)
image
image
image
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have corrected 7 assets out of which the clothing one and the 2 necklaces I had to make from the scratch. Please review this pr.

**Comment by mehul0698** [comment]
@owocki you owe me 70 to 75 dollars as 4 I resized and change the artboard and 3 made from scratch.

**Comment by owocki** [comment]
what are those prices based upon?  i'd really like to treat this as a conversation instead of feelling like those prices are demanded

**Comment by mehul0698** [comment]
5 dollars for each resize and 25 for the clothing as made it from scratch and 10 for the necklace as made that from scratch also. Last time I corrected 6 accessories you paid me the same rates otherwise what ever is fine with you.

**Comment by owocki** [comment]
OK cool -- FYI for go-forward; i closed down the avatar asset bounty for the time being (i want to open another one soon though)

**Pull request merged**
