### PR TITLE
Email design update 

### PR DESCRIPTION
**Pull request by jakerockland**
##### Description

This PR is a current work in progress solution for updating the email templates as described in issue #563.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

n/a?

##### Testing

I have only changed HTML/CSS for email templates (all Django templating has been left unchanged).

##### Refers/Fixes

Fixes: #563 

##### Screenshots of Current Progress
screenshot 2018-03-29 18 49 30
screenshot 2018-03-29 18 49 35
screenshot 2018-03-29 18 49 07
screenshot 2018-03-29 18 49 13

### CODE REVIEW

**Comment by owocki** [comment]
purdy excited about this.. what is still left TODO on this PR?

**Comment by jakerockland** [comment]
@thelostone-mc sure thing, can take care of all of those things. I like to commit early and often so was waiting to squash commits until after the WIP is a bit more finalized. 😄Also I don't believe that this PR updates the Gitcoin weekly email (unless the weekly email uses `template.html`). The design file for the weekly email was included as a reference in #563 but it wasn't mentioned that it was part of the included changes so I wasn't sure if I was to look into addressing that with this PR.

@owocki only outstanding things are those listed above from @thelostone-mc (I wanted to start off with WIP PR to see if there were any other outstanding tweaks changes that anyone had in feedback) and also I still need to verify if `new_tip` and `roundup` pages look like they should. I saw and appreciate your feedback in #563 on verifying that but haven't had the chance to generate tip object in the DB (new to this stack/Django in general) and adjust parameters for roundup testing.

**Comment by thelostone-mc** [comment]
Ah other than that , everything else looks solid :D 
Let's get this PR merged once everything is addressed  \m/

**Comment by owocki** [comment]
screenshots of the tip / roundup emails:

screencapture-localhost-8080-_administration-email-new_tip-2018-04-02-15_40_05
screencapture-localhost-8080-_administration-email-roundup-2018-04-02-15_40_29

**Comment by owocki** [comment]
> @owocki only outstanding things are those listed above from @thelostone-mc (I wanted to start off with WIP PR to see if there were any other outstanding tweaks changes that anyone had in feedback) 

makes sense to me!

> also I still need to verify if new_tip and roundup pages look like they should. I saw and appreciate your feedback in #563 on verifying that but haven't had the chance to generate tip object in the DB (new to this stack/Django in general) and adjust parameters for roundup testing.


i posted some screenshots of this above.  tip email looks okay.  roundup email needs a little work though

thanks... looking forward to getting this to merge!

**Comment by PixelantDesign** [comment]
Looking good @jakerockland!

**Comment by thelostone-mc** [comment]
@owocki The redeem tip button!
Thoughts on putting it above the logo + make it a big fat button to grab the users attention  ?

**Comment by jakerockland** [comment]
So I believe that this PR addresses almost outstanding issues now except for one thing, on the single bounty page, are we sure we want to remove the fire emojis? From what I understand, that email currently will only ever have content for one bounty.

@owocki  I was able to get things working with being able to effectively work on `roundup` and `new_tip`. Work on the `roundup` email is taking more time than I expected but will be able to finish things up tomorrow.

**Comment by jakerockland** [comment]
@thelostone-mc Is it possible to merge this with Githubs [squash & merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) feature? I'm having trouble squashing my commits now that I've pulled the upstream changes to resolve the merge conflicts from adding translation support. 

Also I was able to cleanup the `roundup` email so I think this may be close to being ready to merge?

**Comment by owocki** [comment]
519207dc6af80eeef909679f379fe59b192edbdc <= there were some untested emails.. i just submitted some fixes for them here.. now i'm good with the merge 

shipit! :shipit:

**Comment by jakerockland** [comment]
@thelostone-mc So the problem is that there were previously merge conflicts with the master branch so I pulled the master branch into this branch to resolve those conflicts, but now when I try to rebase using the above method, the commit history includes all of the commits that were on master that I pulled into my branch, not just my commits onto this branch before pulling master in. 😓

**Comment by mbeacom** [comment]
@jakerockland Don't worry about rebasing this branch. I'll squash commits when I merge it.

**Pull request merged**
