### PR TITLE
WIP: Personals Project Page

### PR DESCRIPTION
**Pull request by crisgarner**
Hackathon Personals Project Page

##### Description

As a Gitcoin hacker / as a Gitcoin administrator, it'd be awesome to have Gitcoin project pages for all of my submissions.

- Adds a new Template for user projects.
- Adds a new view that gets all the hackathons of a user
- Adds a new route "handle/projects" to see the projects of a user 

##### Refers/Fixes
- Refs https://github.com/gitcoinco/web/issues/6004

Screenshot from 2020-02-23 16-13-33

### CODE REVIEW

**Comment by octavioamu** [comment]
just pinging to be sure everyone knows https://gitcoin.co/crisgarner/hackathons the personal projects exist, maybe we just need the "single project page" and features related to it

**Comment by crisgarner** [comment]
is what @octavioamu mentions the same feature requested? @vs77bb, I'm sure "hackathons" is not as intuitive as "projects"

**Comment by thelostone-mc** [comment]
Closing this out as we ended up team agreed this wasn't needed in right now

**Comment by crisgarner** [comment]
@thelostone-mc wasn't this actually a bounty? I actually did the requested job

**Comment by owocki** [comment]
@vs77bb posted the bounty => https://gitcoin.co/issue/gitcoinco/web/6004/4027

**Comment by owocki** [comment]
IMHO if it's complete he should pay it out

**Pull request closed without merging**
