### PR TITLE
[WOC] PR@#2802: Clarify error message for MetaMask Integration

### LINKED ISSUE #2802: Metamask connection message is too vage
**Describe the bug**
User does not really feel the need to use the "connect to metamask" to connect MetaMask to Gitcoin.

**To Reproduce**
Be unconnected from gitcoin, try to access gitcoin

**Expected behavior**
User understands he has to press the icon to connect MetaMask

**Additional context**
Mulili [18:01]
ohh wait, its now displaying mainnet bounties and i can see the submit page too :smile:
i simply clicked on the button `click here to connect to metamask` and metamask popped up and ask me to confirm whether gitcoin should connect
and on refreshing everything was back to normal
@owocki this error msg is a bit misleading then, because i was already connected to metamask and on the `mainnet`.
image
Mulili [18:07]
perharps it should say `click on this button to authorize gitcoin to work with metamask` or something along those  lines :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
Fixes #2802 

##### Affected core subsystem(s)
UI

##### Testing
Please test first - currently PyVips broke my setup. :-(

##### Refers/Fixes
Fixes: #2802

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Ah seems like a really long button. Could we trim the text down ? 
`Click to Authorize`  maybe ?

**Comment by mbeacom** [comment]
@kuhnchris Any followup on this following resolution of your kernel issue?

**Comment by kuhnchris** [comment]
Ah, pardon, ill check tomorrow!

**Comment by mbeacom** [comment]
@kuhnchris ping - anything you need from us here?

**Comment by kuhnchris** [comment]
ah my bad, I'll throw @thelostone-mc  's suggestion in and wipe up a screenshot, i'll just finish up the other topic I have on hand first so I don't mix anything up :-)

**Comment by mbeacom** [comment]
Any movement here @kuhnchris ? Anything you need from us?

Thanks

**Comment by kuhnchris** [comment]
Ah my bad, that was still open! I will take a look at it this evening and get back to you on that!

**Comment by kuhnchris** [comment]
Finally! 

image

OK like this?
The shared.js one only happens if you are "deeper" into the tool, cannot trigger that one right now, sorry.

**Comment by kuhnchris** [comment]
Resolved.

**Comment by frankchen07** [comment]
@thelostone-mc - the new warning message is a little bit wordy:

I would say:

```
Please Connect to MetaMask to Continue (larger text)
In order to proceed, you'll need to authorize MetaMask on Gitcoin. (smaller text)
(space between text and button)
Authorize (button)

Note the capitalization on MetaMask and Gitcoin - we want to be accurate and consistent.

**Comment by kuhnchris** [comment]
@frankchen07 changed message. want another screenshot?

**Comment by thelostone-mc** [comment]
@kuhnchris yes please ! that way there is no confusion
every UI change -> needs a screenshot / gif recording :)

**Comment by thelostone-mc** [comment]
Closing this out as we've updated the text+ design

**Pull request closed without merging**
