### PR TITLE
standardbounties: check web3 to see if bounty exists

### PR DESCRIPTION
**Pull request by thelostone-mc**
updated fulfill_bounty, kill_bounty, process_bounty to check web3 if
API call returns result for the bounty github url.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- bounty 
##### Refers/Fixes
https://github.com/gitcoinco/web/issues/263

### CODE REVIEW

**Comment by owocki** [comment]
thjanks for the PR @thelostone-mc :)

https://github.com/gitcoinco/web/issues/263

doesnt this PR check BOTH the api and web3 to see if the bounty exists.. whereas the solution we *want* in #263 would only check web3?

**Comment by thelostone-mc** [comment]
@owocki I let the api check there so as to avoid the web3 call if it's not available within our db!
I sort of assumed that the web3 check would be secondary check if the api returned a null/error response

Is it an overkill ? :P

**Comment by thelostone-mc** [comment]
@jasonrhaas Do we want the extra safety net on checking up the db ?

**Comment by jasonrhaas** [comment]
so I think this one is OBE, given the new way that we are doing bounty syncs on the back-end.  I'll re-post here when I wrote in Slack to @mbeacom:

> The db auto syncs every x seconds with web3 right?  I’m pretty sure the logic of checking both the db and web3 is already accounted for in the python logic.

I know we are still support the "old way" for the legacy bounties, but I'm not sure if we want to update the legacy code at this point.

**Comment by mbeacom** [comment]
For now, we'll be closing this PR.  Thanks for the contribution @thelostone-mc !

**Comment by darkdarkdragon** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/301/454).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Pull request closed without merging**
