### PR TITLE
add animated logos

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

Add animated logos 

**Note**  js inside svg only runs when svg are inlined, for security reasons. So those were included as templates and called inside the navs to keep the code more maintainable.

### CODE REVIEW

**Comment by owocki** [comment]
yesssss

**Comment by thelostone-mc** [comment]
@octavioamu do we wanna remove the commented out code / wanna take it out in a follow up PR ?

**Comment by octavioamu** [comment]
> @octavioamu do we wanna remove the commented out code / wanna take it out in a follow up PR ?

Kevin already cherry picked and deployed but is ok for now I think.

**Comment by danlipert** [comment]
already cherry-picked into stable

**Pull request closed without merging**
