### PR TITLE
Feature/utm hypercharge

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
This feature will be done when the following UTM values are added:

- [X] tweeted 2x/day automatically
`utm_source=hypercharge-auto&utm_medium=twitter&utm_campaign=[bounty-title-name]`

- [X] gitcoinbot will write a pinned post about it
`utm_source=hypercharge-auto-pinned-post&utm_medium=gitcoinbot&utm_campaign=[bounty-title-name]`

- [X] there will be secret offer for the bounty
`utm_source=hypercharge-auto-secret&utm_medium=gitcoinbot&utm_campaign=[bounty-title-name]`

- [ ] there will be daily offer for the bounty -> No daily offers created in hypercharge mode
`utm_source=hypercharge-auto-daily&utm_medium=gitcoinbot&utm_campaign=[bounty-title-name]`

- [X] The bounty will be featured in the daily email.
`utm_source=hypercharge-auto-daily&utm_medium=email&utm_campaign=[bounty-title-name]`

- [X] Notify users who have worked with that org before
`utm_source=hypercharge-auto-notify&utm_medium=email&utm_campaign=[bounty-title-name]`

- [X] Auto feature on hack explorer/normal prize explorer
`utm_source=hypercharge-auto-hack-explorer&utm_medium=gitcoin&utm_campaign=[bounty-title-name]`

- [X] Auto feature on normal prize explorer
`utm_source=hypercharge-auto-prize-explorer&utm_medium=gitcoin&utm_campaign=[bounty-title-name]`

image

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7308

### CODE REVIEW

**Comment by zoek1** [comment]
As we talked @jdorfman yesterday, here is the UTM's for hypercharge mode :)

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
https://github.com/gitcoinco/web/pull/7464#pullrequestreview-492318258

DRY code

**Comment by jdorfman** [comment]
> [#7464 (review)](https://github.com/gitcoinco/web/pull/7464#pullrequestreview-492318258)
> 
> DRY code

@zoek1 are we able to reuse the code on https://gitcoin.co/hackathon-list?

**Comment by thelostone-mc** [comment]
*bump* @zoek1 gimme a ping when you get to this and we can roll it out asap cause i know @jdorfman is waiting on ti

**Comment by zoek1** [comment]
this is also ready @thelostone-mc

**Review by thelostone-mc — APPROVED** [review]

**Comment by jdorfman** [comment]
via #7464 
> @jdorfman closing this out as this code is also present is open in PR https://github.com/gitcoinco/web/pull/7502/commits

@zoek1 @thelostone-mc I'm confused, the [gas history](https://gitcoin.co/gas/history) page still has Disqus installed. ⬇️

image

**Comment by thelostone-mc** [comment]
@jdorfman This hasn't been deployed yet !
Will roll out this week

**Pull request merged**
