### PR TITLE
Rename Chinese locale file to correct format.

### PR DESCRIPTION
**Pull request by ziyangkoo**
##### Description

Changes to fix auto-translation of Gitcoin to Simplified Chinese

##### Checklist

- [x] changes don't break existing behavior
##### Affected core subsystem(s)

ui

##### Testing

Tested with Accept-Language header

##### Refers/Fixes
Fixes: #1843

### CODE REVIEW

**Comment by ziyangkoo** [comment]
chinese_translation 1

Here's a gif preview.

**Comment by ceresstation** [comment]
Thanks @ziyangkoo! @mbeacom alright if I merge this or do you want to give it one more check?

**Comment by ceresstation** [comment]
Hey @ziyangkoo did you have a chance to review the translations?

**Comment by ziyangkoo** [comment]
Hey @ceresstation, sorry I am still working on it, quite a few changes. The auto translations are not really good for Chinese language... I will submit a new pull request in next few days.

**Pull request merged**
