### PR TITLE
greenpill avatars draft pr

### PR DESCRIPTION
**Pull request by owocki**
##### Description

loads these greenpill avatars into the avatar builder, so ppl can use them on their profiles during schelling point + the greenpill launch :)

still waiting on revisions from some of the artists.  do not merge yet

##### Refers/Fixes

https://github.com/gitcoinco/skunkworks/issues/255

##### Testing

tested locally; lots of fun new art!

### CODE REVIEW

**Comment by IamJvck** [comment]
edited sir @owocki
greenpill_avatar
.
this is the link for SVG file:
https://github.com/IamJvck/Green-Pill-avatar-for-builder/blob/main/greenpill_avatar.svg
.
this is the link for Ai file:
https://github.com/IamJvck/Green-Pill-avatar-for-builder/blob/main/greenpill_avatar.ai

**Comment by mibvase** [comment]
gitrob avatar3-gitrobAvatr greenpill
greenpil_avatar

**Comment by mibvase** [comment]
this is the link to my repository to my designed Avatar
https://github.com/mibvase/greenpill_bot

**Comment by owocki** [comment]
subsumed by https://github.com/gitcoinco/web/pull/10071

**Comment by rasaso** [comment]
[PicsArt_01-22-07.17.46.zip](https://github.com/gitcoinco/web/files/7981447/PicsArt_01-22-07.17.46.zip)

**Comment by thelostone-mc** [comment]
Closing this out in favour of https://github.com/gitcoinco/web/pull/10071

**Pull request closed without merging**
