### PR TITLE
Fix Bad HTML on Product Emails

### PR DESCRIPTION
**Pull request by frankchen07**
##### Description

Removed faulty href link.
Added Kyle to the product email/team.

##### Refers/Fixes

Scott identified it.

##### Testing

Just some text changes.

### CODE REVIEW

**Review by aamustapha — APPROVED** [review]
This looks okay, but I'm curious, why aren't the names properly capitalized?

~kyle, frank & alisa~ Kyle, Frank & Alisa

**Comment by frankchen07** [comment]
I'm keeping with the kevin standard of lowercase makes it look a little bit
more personalized and less machine-y.

~

Frank Chen
frank-chen.com

**Review by bubbagunit — COMMENTED** [review]
Yes

**Review by bubbagunit — COMMENTED** [review]
What is this actual holdings in my assets

**Pull request merged**
