### PR TITLE
add "setup database" section to documentation

### PR DESCRIPTION
**Pull request by galaxy233**
##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/contributing/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by owocki** [comment]
mostly looks good to me... might be good to provide some exact commands for creating the postgres role / user

**Comment by galaxy233** [comment]
I've added some more detailed instructions for creating the db and user.

**Comment by owocki** [comment]
thx

**Comment by owocki** [comment]
@galaxy233 DM me your email on slack (or email me at kevin@gitcoin.co) for the tip email address.  i wasnt able to pull one from github for ya

**Pull request merged**
