### PR TITLE
add: url shortner on message box

### LINKED ISSUE #6131: Townsquare - add url shortener on message box
### User Story

Adoraria ter um encurtador de links nativo na message box, toda vez que eu adiciono um link ele encurta automaticamente.

e.g: gitcoin.co/xhshash

### Additional Information
[PyShortners](https://pypi.org/project/pyshorteners/)

### PR DESCRIPTION
**Pull request by developerfred**
##### Refers/Fixes
#6131

### CODE REVIEW

**Comment by octavioamu** [comment]
The problem I see with gitcoin.co/shortlink is the collisions with profiles urls https://gitcoin.co/octavioamu should be nice :
A - having some subdomain 'short.gitcoin.co/shortlink'  or 'gitcoin.co/short/shortlink' or maybe we should look for s short domain url to buy ? 
But I think for now something like gitcoin.co/sh/shortlink maybe can work to avoid conflicts.

**Comment by thelostone-mc** [comment]
@developerfred would you be able address @octavioamu comment ?
We can get in after that

**Comment by developerfred** [comment]
for now let's use the shot subroutine, correct?

**Comment by developerfred** [comment]
Short*

**Comment by danlipert** [comment]
Hey @developerfred - what exactly does this PR do? In the PR submission form, there is a section for the description as well as testing. In the description field please add a description of what your changes do, why they are important, and how they work. In the testing field, please describe how you tested this PR, and include a video of the feature working as expected. Thanks!

**Comment by thelostone-mc** [comment]
Closing this out ! Do reopen this when you get the time to attach a video + address @danlipert comment

**Pull request closed without merging**
