### PR TITLE
Fix card  image display on twitter cards

### PR DESCRIPTION
**Pull request by zoek1**
##### Refers/Fixes
https://github.com/gitcoinco/web/pull/6451

##### Testing
image

### CODE REVIEW

**Comment by zoek1** [comment]
@owocki done!

**Comment by owocki** [comment]
thanks @zoek1 - this looks amazing!

**Comment by owocki** [comment]
@zoek1 heres the rest of the twitter cards - any interst in PRing the rrest? https://www.figma.com/file/TqLkp6GdCyebACbaSbD4pE/Tw_cards?node-id=0%3A1

**Comment by zoek1** [comment]
@owocki could you have a list with the associated page for each additional image? I already have `Chat` and ``Townsquare` image covered.

**Comment by owocki** [comment]
@zoek1 

the 'not a token' one is the only other obvious 1:1 image.

for image 10 that can go on the leaderboard page

for the rest of the URLs i'd love to just love if you could choose a 'blank' image (11, 12, 17, 18, 19) and add some text in it with a one word page title and use that.

does that work?

**Pull request merged**
