### PR TITLE
[WIP] - refactor dropdown shown when a user is trying to tag someone

### PR DESCRIPTION
**Pull request by walidmujahid**
refactor 58826bd62678ba1cd19007c2755b09243c5e2389

**Late initial demo video - 2020-03-19:** https://youtu.be/UwHUZ0ndk30

Uses jQeryUI Autocomplete 

I need to:

- fix styling and add user avatars to the listed items
- fix key events so pressing `ENTER` does not post the status update

closes https://github.com/gitcoinco/web/issues/6191

### CODE REVIEW

**Comment by octavioamu** [comment]
We are trying to remove jqueryui for all the code base.

**Comment by walidmujahid** [comment]
@octavioamu I had a feeling :-D

Do you have a recommended alternative? Perhaps a Vue solution? Or should I work on exteding the dropdown solution from 58826bd62678ba1cd19007c2755b09243c5e2389 which is currently live?

**Comment by octavioamu** [comment]
I believe extending since we are not using vue (yet) there.

**Comment by thelostone-mc** [comment]
Closing this out as we'd want to migrate this to vue and then build it out.
Will reopen if we decide to get this back in

**Pull request closed without merging**
