### PR TITLE
purge: remove grant ownership feature

### PR DESCRIPTION
**Pull request by thelostone-mc**
### Description

removes grant ownership feature in grant.
Once a grant has been created, the grant owner can 

- edit grant info
- cancel grant (if logged in with the address with which the grant is created )

##### Refers/Fixes

closes https://github.com/gitcoinco/web/issues/4839

##### Testing

- Created Grant
- Edited Grant Info
- Cancel Grant 
- Edit Grant via Admin

Demo : https://embed.vidyard.com/share/pkJZKTs3GjcQZcP42aJHf9?

### CODE REVIEW

**Comment by danlipert** [comment]
Looks good @thelostone-mc - we should also remove the little down arrow in the grant owner box since that makes it look like you can change it. Also the audio was on in your video :P

**Comment by thelostone-mc** [comment]
Derp derp ! I forgot to turn out the audio :P

**Comment by thelostone-mc** [comment]
rebased +  retested 
@octavioamu / @danlipert

**Comment by Nustthanapuss6153** [comment]
Github sir you take care on
working on Google or not
We help your support on Microsoft I can not use it. About donate If I need to give
up where I can notice. 
Now working it more difficult
when not ability to use one note please tell. What we can  use replace. 
On Github I never know how
to work.

DEVELOPING LIFE.

There are many kinds of life tried to learn and develop life. For to be alive on tomorrow.
Even though it is difficult or not. Such as many kinds of animals in the zoo.They tried
to learn and follow the orders of people  so that they could be alive and spent their lives with happiness. They can
escape from hunting. 
People are the same among
changing they tried to learn
and develop life to be better
than yesterday. Developing life among changing. Just say to be welcome tomorrow will
come on. Believed everything around people were changed a little bit and a little bit. Until
it can not remember. Isn't sure it will be good or bad. Somehow among changing alway have the good thing and the bad thing. Were be happened.
It will be good more than bad
or bad more than good. 
Maybe we do not ability to know. Really not lying.

What this you think this thought right or wrong?
Who can answer this is 
the truth?
Please Subscribe and Unsubscribe.

**Comment by owocki** [comment]
this caused a regression here @thelostone-mc https://github.com/gitcoinco/web/issues/5026

**Pull request merged**
