### PR TITLE
homepage + pricing fixes

### PR DESCRIPTION
**Pull request by thelostone-mc**
- pricing: fixed banner css
- added fadein animation code + documented
- used fadein animation on homepage

untitled

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@owocki 

how to use this is on the styleguide https://github.com/gitcoinco/web/pull/3814/files#diff-328a2bb516993d3146c61ac971cce9bbR68

**Comment by owocki** [comment]
can my feedback from https://gitcoincore.slack.com/archives/CF9FSDR8V/p1550006002033500?thread_ts=1549932773.028000&cid=CF9FSDR8V be processed?

**Comment by thelostone-mc** [comment]
@owocki Maybe it's just me but I think the funnel bit is just meh. 
I'd have it removed / represented in a diff way all-together. 
( The best I could come up with was zelda aka gitcoin bot holding 3 gems representing the problems we are attempting to solve in OSS )

That said @octavioamu had some cool color transitioning idea for the funnel so I've synced up with the @PixelantDesign  + @octavioamu and he'll be throwin in the code for this.

The `10X numbers` will update it when @PixelantDesign gets an updated copy!
will review with the team before we go live

**Comment by owocki** [comment]
> @owocki Maybe it's just me but I think the funnel bit is just meh.
> I'd have it removed / represented in a diff way all-together.
> ( The best I could come up with was zelda aka gitcoin bot holding 3 gems representing the problems we are attempting to solve in OSS )

what does @PixelantDesign think about this?

maybe we could just use our existing image.... 

oss_cycle with gitcoin 1 1

**Comment by thelostone-mc** [comment]
@willsputra / @PixelantDesign Thoughts on using the above layout but 

- replacing the User images with an avatar
- updated the other images + arrows + font 
- maybe make the color a lil less harsher 


^ I'd just have to update the svg if you guys can help out with this ❤️

**Pull request merged**
