### PR TITLE
Keywords suggestion bleeding edge fix Funding page

### LINKED ISSUE #6644: "Add tags from repo" bleeding over on bounty funding page
**Describe the bug**

**To Reproduce**
Fund this bounty: https://github.com/Azure-Samples/bc-community-samples/issues/76

**Expected behavior**

**Screenshots**
Screen Shot 2020-05-12 at 1 28 19 PM

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

### PR DESCRIPTION
**Pull request by molecula451**
##### Description

wrap1

##### Refers/Fixes

wrap

Fixes #6644

### CODE REVIEW

**Comment by molecula451** [comment]
@thelostone-mc

**Comment by molecula451** [comment]
@thelostone-mc I were approved to work...

**Comment by x5engine** [comment]
you just copied my pr...

**Comment by molecula451** [comment]
> you just copied my pr...

It's a fairly simple task you shouldn't start to work at first. You were not approved to work

**Comment by x5engine** [comment]
yeah but I fixed it in 10mn, and even if it was simple you just copied from my or...

**Comment by molecula451** [comment]
> yeah but I fixed it in 10mn, and even if it was simple you just copied from my or...

I am using CSS standard I don't know why you mean by "copy" you shouldn't star to work at first don't you get it?

**Comment by molecula451** [comment]
I'm wondering if by copy you mean you re-inventing the CSS rule? @x5engine

**Comment by x5engine** [comment]
ok whatever man

**Comment by molecula451** [comment]
> ok whatever man

No. it's not "whatever" other users also applied to work and they were respectful they did not started to work. You should be respectful everyone is contributing for a Mission and By a Mission Open Source and to leverage Gitcoin.

Again if you opened a PR focus on your PR and do not claim someone else it's working onto you

**Comment by x5engine** [comment]
okay, I respect that!

**Pull request merged**
