### PR TITLE
Auto-Translation to Japanese #1863

### LINKED ISSUE #1863: Confirm Auto-Translation of Gitcoin to Japanese
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a user I want to fulfill / fund bounties in my native language.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: For maximal inclusion :)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)

The base translation files have been generated as in https://github.com/gitcoinco/web/pull/971

There are two .po files that will need modified for each language we wish to support. 

`django.po` and `djangojs.po`

You can see how some of them are populated [in 971](https://github.com/gitcoinco/web/pull/971/files).

Please edit the files directly and submit a PR.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

The PR is merged and the auto-translation of the site to Japanese is confirmed :)

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #1863 

##### Description

Enables Auto-translation to Japanese

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@thelostone-mc @owocki Any updates 😅

**Comment by owocki** [comment]
@ceresstation has a friend that speaks japanese that he's pull in to QA This!

**Comment by aashutoshrathi** [comment]
ping @owocki @ceresstation

**Comment by thelostone-mc** [comment]
Hey @aashutoshrathi ! Ah don't hate us for this but @ceresstation is on vacation! 
He'll be back by then! Mind waiting it out ? 
I've pinged him 

Again sorry about the delay 😓

**Comment by aashutoshrathi** [comment]
@thelostone-mc It's Fine 😄

**Pull request merged**
