### PR TITLE
Add VSCode remote debugging handling and documentation

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description

The goal of this PR is to add vscode remote debugging support (optional) and necessary setup documentation.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Testing

Locally

### CODE REVIEW

**Comment by timborden** [comment]
@mbeacom & @SaptakS - just a heads up...looks like `ptvsd` needs to be added to https://github.com/gitcoinco/web/blob/master/requirements/base.txt as well. Not a prod issue, as it only errors when `VSCODE_DEBUGGER_ENABLED` is _"on"_ ....and even then, it appears to fail gracefully in the development environment....but VS Code debugging won't work without it.

**Comment by mbeacom** [comment]
@timborden Please check out the documentation at: https://docs.gitcoin.co/mk_contributors/#vscode-remote-debugger

[This section](https://github.com/gitcoinco/web/pull/2263/files#diff-9b74db5a5a6c7358724d34a227099303R27) in the additions installs `ptvsd` on initial launch of the container if `VSCODE_DEBUGGER_ENABLED=on`.  I'm fine with adding the dep to `base.txt`, but I was trying to avoid changes for users that don't use vscode (or the debugger).

If you execute: `docker-compose down; docker-compose up -d`, it *should* automatically install `ptsvd` on initial spin up IFF `VSCODE_DEBUGGER_ENABLED =on` is already present in the `.env` when you start the compose stack.

**Comment by timborden** [comment]
Ahh....I spotted the `VSCODE_DEBUGGER_ENABLED=on` after running `make fresh` and didn't realise it was used in `docker-command.bash` as well.

I like the approach and agree it's better to keep the package out of the requirements for those that don't use VS Code.

Thanks for clarifying! (...nice work, by the way)

**Comment by timborden** [comment]
I needed to change my `"remoteRoot": "/code/app"` in `launch.json` to `"remoteRoot": "/code"`...not sure if that's specific to my setup.

**Comment by mbeacom** [comment]
@timborden 🤔 That's odd.  Which version of vscode and OS are you running on?

Do you happen to know what the error read?  The provided `launch.json` snippet works on my end, but I want to catch this case before other users start adopting it.

Also, a random note...  I was doing to include a `make` entry to automatically add the provided launch configuration to the project level `launch.json`, but Microsoft uses `//` comments in the automatically generated flavor of the config file that yields errors without stripping them out first.  I didn't want to take the liberty of modifying user config files to that degree.  I'm open to discussion about whether or not this process **should** be abstracted further, though.

**Comment by timborden** [comment]
I'm on OSX 10.13.6 and VS Code 1.27.2...here's the warning:
```
pydev debugger: warning: trying to add breakpoint to file that does not exist: /code/app/app/marketing/views.py (will have no effect)
```

Interesting idea. It's probably enough to note the instructions in the Markdown file. There's a chance that someone could already have a `launch.json` file setup (unlikely, but possible) so the code would need to add/update that file....which (to me) feels like it could be a rabbit hole.

**Comment by mbeacom** [comment]
@timborden It appears this was due to a modification in one of **my** testing configs.  I have updated the documentation accordingly.  Thanks @timborden

**Pull request merged**
