### PR TITLE
Explorer agnostic language in grant contribution email

### PR DESCRIPTION
**Pull request by danlipert**
##### Description

This PR removes references to Etherscan in the successful contribution email that goes out to contributors.

##### Refers/Fixes

n/a
##### Testing

untested

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@danlipert this seems to have other commits as well !

**Comment by danlipert** [comment]
@thelostone-mc woops! should have been against stable

**Review by octavioamu — APPROVED** [review]

**Comment by thelostone-mc** [comment]
Ah it still has conflicts 😓

**Comment by danlipert** [comment]
better fix is already in stable actually woops!

**Pull request closed without merging**
