### PR TITLE
#4515 - GRANTS - Adding sorting

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
add sorting for subscriptions, cancelled_subscriptions and contributors

##### Refers/Fixes
Fixes: #4515

##### Testing
Works

Thanks!

### CODE REVIEW

**Comment by danlipert** [comment]
Hey @kuhnchris - why can't you test this locally? Just create a grant, then use test users to subscribe to it and take other actions to see if they are ordered correctly in the page.

**Comment by kuhnchris** [comment]
> 
> 
> Hey @kuhnchris - why can't you test this locally? Just create a grant, then use test users to subscribe to it and take other actions to see if they are ordered correctly in the page.

because they need to separated by days

**Comment by danlipert** [comment]
> > Hey @kuhnchris - why can't you test this locally? Just create a grant, then use test users to subscribe to it and take other actions to see if they are ordered correctly in the page.
> 
> because they need to separated by days, or do you happen to have a grant ready locally where you could test this? Cause I surely do not, I'm eagerly awaiting the test-data PR to get done...

You can create your own test data locally using the Django admin page and set the dates however you want.

**Comment by kuhnchris** [comment]
> 
> 
> > > Hey @kuhnchris - why can't you test this locally? Just create a grant, then use test users to subscribe to it and take other actions to see if they are ordered correctly in the page.
> > 
> > 
> > because they need to separated by days, or do you happen to have a grant ready locally where you could test this? Cause I surely do not, I'm eagerly awaiting the test-data PR to get done...
> 
> You can create your own test data locally using the Django admin page and set the dates however you want.

well, if you say so, I can surely go and retry it, maybe you guys improved that since a couple of months ago when I first tried and failed... I'll get back at you when I got some info on this.

**Comment by danlipert** [comment]
great, thanks!

-Dan Lipert

**Comment by kuhnchris** [comment]
@danlipert it works, but...
grafik

this is technically correct but the year is missing. shall we add the year to the display?

**Comment by danlipert** [comment]
@kuhnchris nice! looking good! @willsputra what are your thoughts on adding the year?

**Comment by willsputra** [comment]
@kuhnchris @danlipert looking good! yeah having the year would be great :)

**Comment by kuhnchris** [comment]
grafik

@willsputra & @danlipert

**Comment by PixelantDesign** [comment]
Looks great @kuhnchris !

**Comment by willsputra** [comment]
@kuhnchris looks good to me!

**Pull request merged**
