### PR TITLE
Added santa hat accessory

### PR DESCRIPTION
**Pull request by jakerockland**
##### Description

Added santa hat accessory to avatar creator.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

avatar

##### Testing

Tested locally, screenshots attached:

screenshot 2018-11-05 18 23 28

screenshot 2018-11-05 18 23 39

##### Refers/Fixes

Refs: #2684

### CODE REVIEW

**Comment by jakerockland** [comment]
@thelostone-mc Running `svgo` locally now rather than just using the Sketch plugin, so hopefully all looks kosher this time on that front 😅

**Comment by thelostone-mc** [comment]
Awesomee :D thanks @jakerockland !!

**Comment by pereiray-ryan** [comment]
Hey i am a newbie for design, can you help me understand how do i create a asset of any sort, does it needs to be made from scratch or do i have a default aavtar already present.

**Comment by jakerockland** [comment]
@pereiray-ryan So I'm using [Sketch](https://www.sketchapp.com/) to create the image assets I've submitted, but you could use any design software you prefer that allows export to `.svg`. Checking out the [avatar style guide](http://bits.owocki.com/9a25c298e3d9/gitcoin-avatarconstructionguide_082218.pdf) is probably a good place to start 😃

**Pull request merged**
