### PR TITLE
bounty: mobile alignment fix

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Fixed up the actions buttons to ensure it's rendered right on mobile 

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- css

##### Testing
screen shot 2018-04-02 at 1 32 40 am

##### Fixes
-  https://github.com/gitcoinco/web/issues/759

### CODE REVIEW

**Comment by mkosowsk** [comment]
Hot damn, that turnaround time 😳LGTM 👍🏻

**Comment by thelostone-mc** [comment]
@mkosowsk  I was waiting for my subway delivery + netflix kept crashing. Hence :P

**Comment by thelostone-mc** [comment]
@PixelantDesign This PR is just for the mobile fix
What you are looking for is here https://github.com/gitcoinco/web/pull/768  ^_^

**Comment by thelostone-mc** [comment]
@mbeacom resolved conflicts + fixed linting

**Pull request merged**
