### PR TITLE
Glitches fixes and overall better buttons look and feel

### PR DESCRIPTION
**Pull request by algae12**
Fixes: https://github.com/gitcoinco/web/issues/126
### Site-wide changes:

- I removed the `raise` class from all buttons to fix glitches. In all buttons that used to contain that class, interactivity is now indicated by a contrast change.

### Specific changes:

- **Hero buttons:**
Old:
old_hero
New:
new_hero

- **Carousel buttons.**
Old:
old_car
New:
new_car

- **Email submit form.**
Old:
old_submit
New:
new_submit

### CODE REVIEW

**Comment by owocki** [comment]
amazing :) digging in on this now

**Comment by owocki** [comment]
awesome!

**Comment by owocki** [comment]
what do you think of the interior buttons a la  http://localhost:8080/funding/new ?

**Comment by algae12** [comment]
@owocki Thanks for the tip! Glad you like them 😊
In regards to the interior buttons, I’ve got some redesign ideas for the issue pages and browser, this redesign will include some new shiny buttons ⚡️
Going to start working on some mockups after the weekend. I’ll drop them by the slack design channel as soon as they’re ready.

**Comment by owocki** [comment]
great :)

**Comment by owocki** [comment]
unexpected consequence on the accept/reject page. http://bits.owocki.com/3n0w2a173r1f/Screen%20Shot%202017-12-17%20at%2010.39.42%20PM.png

looking forward to the PR for button updates on internal portion of site

**Comment by algae12** [comment]
@owocki Oops, sorry about that. Fixed and waiting for approval.

**Pull request merged**
