### PR TITLE
[Kale] Consistent Usage of ES7 Code

### PR DESCRIPTION
**Pull request by DomAmato**
##### Description

Currently there is inconsistent use of things like Array.includes and indexOf as well as 
the exponentiation operator and Math.pow. This just changes the old methods to use the new ones for consistency.

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [x] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

just a syntax change but it does affect pages and grants

##### Refers/Fixes

no issue just a consistency change

##### Testing and Sign-off

I ran the travis script and it passed, no code was added it just changed syntax

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by DomAmato** [comment]
sure though I think you now have the option to squash the commits as well when accepting the merge
https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by thelostone-mc** [comment]
Yup we've got that bit documented [here](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit) 
I usually encourage the contributor to squash the commits so as there is no confusion when the contributor decides to use the same branch to fix something else -> which results in conflicts + duplicate commits showing up. It's happened a few times when the contributor isn't comfortable with git. Squashing is a lot easier than -> dealing with conflicts + rebase with duplicate commits

Ideally, they would ensure their branch would be in sync with master before starting but when folks forget that -> they get into a fix :P

**Comment by DomAmato** [comment]
makes sense, I know I made my fair share of boneheaded mistakes when I first started using git 🤦‍♂️

**Comment by DomAmato** [comment]
I squashed the commits and fixed the conflicts :)

**Comment by DomAmato** [comment]
Just checking in since the merge is approved but still pending

**Comment by SaptakS** [comment]
@DomAmato I think this is great and ready to be merged. But for making it ready to deploy, we need to some rigorous regression testing since it affects a lot of the services. So was waiting to merging it till we have done that. 
@danlipert @thelostone-mc I think we can merge it and put it into regression for this week's deploy?

**Comment by octavioamu** [comment]
LGTM also, but as @SaptakS said we need to test it with care to see if nothing is affected by the changes.

**Comment by danlipert** [comment]
@octavioamu @SaptakS lets test this on its own before merging as it does affect a lot of the codebase. Can one of you just run quick regression tests and post here again if everything looks good? (create and payout a bounty, send kudos, send tip, create and subscribe to grant)

**Comment by thelostone-mc** [comment]
This PR has gotten stale cause we goofed up on the testing process ! Derp
Sorry about that 
Closing this one out but @DomAmato would be stoked to get it in if you are open to raising a fresh PR with these changes in

**Pull request closed without merging**
