### PR TITLE
show tips on leaderboard / profiles

### PR DESCRIPTION
**Pull request by owocki**
example: 
screencapture-localhost-8080-profile-kamescg-1520303465178

### CODE REVIEW

**Comment by thelostone-mc** [comment]
_note to self -> fix the alignment tip + funded section_

**Comment by owocki** [comment]
does this help? 4b82defe7ac095885e68a3aa21f988268dccd168

screencapture-localhost-8080-profile-kamescg-1520373338767

**Comment by thelostone-mc** [comment]
@owocki Yup better ^_^
The repos section seems to having extra margin/padding (it's probably a 2 line fix )

**Comment by owocki** [comment]
probably worth a convo about a more exhaustive profile overhaul soon.. gonna ship this in the meantime and we can carry that convo into the other ticket about profile design

**Pull request merged**
