### PR TITLE
Clickable bounty hunters #1682

### PR DESCRIPTION
**Pull request by olafghanizadeh**
refs: https://github.com/gitcoinco/web/issues/1682

- [ ] Make bounty hunters clickable
- [x] Test for responsiveness

- [x] Switch assets to SVG and text instead of image
- [x] Recreate HTML with bootstrap

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@owocki That seems confusing in my head! Wouldn't users end up waiting longer to see something happen 🤔

**Comment by owocki** [comment]
ok im not married to the clickability idea if you guys dont think its a good idea

**Comment by olafghanizadeh** [comment]
How should we proceed here?

**Comment by thelostone-mc** [comment]
@olafghanizadeh just leave them as non clickable :P

**Pull request merged**
