### PR TITLE
[WIP] bounty: support multiple contract

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- loaded duplicate bounty contract + abi to mock new contract
- added getBountyABI to return version specific ABI
- updated bounty_address to return verision specific address
- Bounty model has version field
- bounty actions (new, fulfill, process, kill, bulk, increase) updated
  to use retrieve version specific address + ABI
- introduced version as hidden input in all the bounty forms

##### TODO:

- [x] update sync_geth + sync_listener
- [ ] debate if contract_version  should be `Choice` / `String` in model
- [ ] test flow once

##### Post new contract deployment 

- [ ] Wire up the new contract info into `abi.js`
- [ ] Update the contract invocation functions which for new bounties on the new contract
- [ ] Old bounties should work as is without any changes
- [ ] All new bounty creation would be on the new contract 

##### Checklist

- [ ] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [ ] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

### CODE REVIEW

**Comment by danlipert** [comment]
What do you think about having the old bounty contract labelled as `v1` instead of `''` just to avoid confusion in the future or from contributors?

**Comment by owocki** [comment]
that makes sense to me

**Comment by thelostone-mc** [comment]
@danlipert / @owocki  I'm good with that ! 
I wasn't sure if we'd be open to running a command throughout our db to update all our old bounties to add version `v1` to the Bounty model.
Hence defaulted to `''`

**Comment by thelostone-mc** [comment]
Parking this aside for now 

TODOS: 
- sync_geth need to ensure contract_version is also set so that `bounty_change` returns the right value. aka it should NOT be set to `true` just cause `contract_version` is available 

In `dashboard/utils.py`
`def get_bounty(bounty_enum, network, contract_version='1.0')` should pass `contract_version`

In `dashboard/helpers.py`
`process_bounty_details`

**Comment by thelostone-mc** [comment]
Closing this out as it's being built out in #5073

**Pull request closed without merging**
