### PR TITLE
GITC-670: Allow snoozing notifications even if there are no actions by the user …

### PR DESCRIPTION
**Pull request by nutrina**
##### Description

For a user that is interested but for whom we could not detect any actions, we do apply the snoozing, and we count the snoozing days since the day he was accepted.

##### Refers/Fixes

GITC-670

##### Testing

This has been tested locally

GIVEN i have funded an issue
WHEN i snooze notifications FOR X DAYS
THEN no comments should be left for the same X days that it was snoozed for
AND all notification should be snoozed

Snooze bot looking at Start Date:
GIVEN i have funded an issue
WHEN i snooze notifications AND the user has not performed any action
THEN the snooze day count should look at the contributors Start Date to determine when notifications should resume

### CODE REVIEW

**Comment by nutrina** [comment]
@ksolo @thelostone-mc @gdixon 
What is your opinion, should I add test cases for the notification? 
It will make future changes much safer and easier to test ...

**Comment by gdixon** [comment]
Code lgtm here!!

> @ksolo @thelostone-mc @gdixon What is your opinion, should I add test cases for the notification? It will make future changes much safer and easier to test ...

 Yes, that sounds like a solid idea - @GTChase, how urgent is it that we get this out before the break?

**Comment by GTChase** [comment]
> Code lgtm here!!
> 
> > @ksolo @thelostone-mc @gdixon What is your opinion, should I add test cases for the notification? It will make future changes much safer and easier to test ...
> 
> Yes, that sounds like a solid idea - @GTChase, how urgent is it that we get this out before the break?

I think we should def add tests here.. This seems like a feature that would really benefit from some level of testing. The noise has quieted down a bit on this one, so i think we can take our time do said tests.

**Comment by nutrina-fest** [comment]
Ok, I will ad tests

**Comment by nutrina** [comment]
Ok, I will add tests

**Comment by nutrina** [comment]
@GTChase  @gdixon Have added tests, the PR is ready for review.

**Review by gdixon — APPROVED** [review]
LGTM! Awesome work here @nutrina! 🚀

**Review by thelostone-mc — APPROVED** [review]

**Pull request merged**
