### PR TITLE
HOLD: Fixes: https://github.com/gitcoinco/web/issues/1007

### PR DESCRIPTION
**Pull request by bakaoh**
##### Description
one click approval of erc20 token bounties

##### Checklist
- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines]

##### Affected core subsystem(s)
New funding

##### Testing
Custom network

##### Refers/Fixes
Fixes: #1007

### CODE REVIEW

**Comment by mbeacom** [comment]
@bakaoh Ping me when this is ready for review and testing.  Feel free to ping me on slack if you have any questions!

**Comment by owocki** [comment]
@bakaoh when i did web3 batch stuff i was not having any luck.. hopefully you will have more luck than me!

**Comment by bakaoh** [comment]
@mbeacom i've already test it with custom network, it works, but there're some issues i mentioned here https://github.com/gitcoinco/web/issues/1007#issuecomment-386997615 with metamask not with the PR itself, so it's ready to review

**Comment by owocki** [comment]
> but there're some issues i mentioned here #1007 (comment) with metamask not with the PR itself

are the metamask issues crippling to the UX?  for example, if the user confirms the transactions backwards (issueandPostBounty before activateBoujnty), that'd be a pretty large dealbreaker for merging this into master (despite it being an upstream issue)

**Comment by bakaoh** [comment]
@owocki --- yes, i think we shouldn't merge this pr before resolving these issues, but till it need a technical review to prove that this route works

About UX, from my perspective:
- Current flow "surprising" users by asking for another transaction after the first one, that's not a good practice, users should allow to preview all transaction before accept any of them. Moreover, the time gap between 2 transaction (sometime few minutes) may increase unfinished rate.
- The issue with metamask, while waiting for the upstream be fixed, can be temporary bypass by show a modal that only allow process if user read it (in this modal, we may explain that using token bounty, user must approve token first, so there're 2 transaction in this case...), i guess funders will happy to read that (few seconds) than wait for miners (few minutes)
batch

Anyway, that's just view of a technical guy, we need more comments from UI/UX designers.

**Comment by owocki** [comment]
i like the modal you designed... but i still just think the UX isnt very good bc of the upstream issue.

would you be willing to try the smart contract route?  since we've burned a bunch of time on the batch direction, i'm happy to re-up the bounty for you

**Comment by owocki** [comment]
I'm fairly certain that you can pass the authorization of the original signed function down to the other smart contract.   @mbeylin do you know if im right/wrong here?

**Comment by owocki** [comment]
asking in consensys slack here too

**Comment by owocki** [comment]
according to consensys slack, it should work.  not familiar with the implementation you tried, but [heres the chat](http://bits.owocki.com/1x1i3L1g3I3O/Screen%20Shot%202018-05-09%20at%2011.38.09%20AM.png)

beucase Standadrdbounties uses `msg.sender` [here](https://github.com/Bounties-Network/StandardBounties/blob/master/contracts/StandardBounties.sol#L197-L233) we should be okay

**Comment by vs77bb** [comment]
@bakaoh this is unrelated to this PR (sorry all) but are you on [Gitcoin Slack](gitcoin.co/slack)? Couldn't find you but would love to chat if you want to DM me!

**Comment by bakaoh** [comment]
@owocki --- from solidity document `delegateCall`

> ... Storage, current address and balance still refer to the calling contract, only the code is taken from the called address. This makes it possible to implement the “library” feature in Solidity...

`delegateCall` modify the storage of the caller not the callee, so `issueAndActivateBounty` and `approve` will only affect the proxy smart contract storage, leave the `StandardBounties` and `Erc20Token` unchanged. You may test this https://github.com/nirmalgupta/delegatecall

This is my attempt to tackle the problem https://gist.github.com/bakaoh/f3cb7088ebc698612f23932ea92cf5ed

**Comment by mbeacom** [comment]
@bakaoh Mind resolving the conflicts here?

**Comment by owocki** [comment]
> delegateCall modify the storage of the caller not the callee, so issueAndActivateBounty and approve will only affect the proxy smart contract storage,

@bakaoh

i'm fairly certain that delegate call should preserve the execution context that it is called with, so that StandardBounties and the ERC20 contract should be executing within the context that is proper for this use case.  

i'm trying to test this now.

**Comment by owocki** [comment]
heres an alternative approach i just coded up https://github.com/gitcoinco/web/pull/1190 -- this would mean we only have to do an `approval()` once per coin instead of once per bounty

still trying to get the contract you gave me above to compile in truffle...

**Comment by owocki** [comment]
> This is my attempt to tackle the problem https://gist.github.com/bakaoh/f3cb7088ebc698612f23932ea92cf5ed

@bakaoh i'm able to get your contract to compile (or... at least.. [one thats similar to it](https://gist.github.com/owocki/64171130d7b1bb36353a0457b4234500) ) and deploy to my testnet.  in my test setup, though i have setup an example token and a standardbounties contract, i'm unable to post any bounties.  i just got a `revert()` back

the variables im using to test
```
var standard_bounties_address ='0x440bb30febabaedadb7324df7620672b6f927b66';
var _tokenContract = '0xad38354f48b7cd71bdd9d50c1ca5c3f762065ab4';
var tb_address = '0xbb04604294aa1d52967de548e6c6692aa8bd3d64';

// standard tokenbounty
var _issuer = web3.eth.coinbase;
var _deadline = 999999999999;
var _data = '';
var _fulfillmentAmount = 111;
var _arbiter = 0x0;
var _paysTokens = true;
var _value = 111;
var _bountyContract = standard_bounties_address;
var tb = TokenBounty.at(tb_address);
tb.issueAndActivateTokenBounty(_issuer,_deadline,_data,_fulfillmentAmount,_arbiter,_paysTokens,_tokenContract,_value,_bountyContract,)
```

response from truffle:

```
truffle(development)> tb.issueAndActivateTokenBounty(_issuer,_deadline,_data,_fulfillmentAmount,_arbiter,_paysTokens,_tokenContract,_value,_bountyContract,)
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:224765:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
truffle(development)>
```

@bakaoh are you actually able to get a standardbounty to post via this method?

**Comment by owocki** [comment]
ok, so upon further testing ([my latest contract here](https://gist.github.com/owocki/ceef204ca8c84374b1c03b54b5cf5f3b), i am able to get the proxy contract to *read* from the subcontract... but not able to write to it.

interestingly enough, this fails in both `call()` and in `.delegatecall()`.

so i think i see what you were staying here @bakaoh 

> delegateCall modify the storage of the caller not the callee, so issueAndActivateBounty and approve will only affect the proxy smart contract storage, leave the StandardBounties and Erc20Token unchanged. You may test this https://github.com/nirmalgupta/delegatecall

while the execution context says the same (good), we need to update the context and storage of the standardbountides contract (bad, we can't do that)

**Comment by bakaoh** [comment]
@owocki --- yes, i stuck here in almost one week before giving up. I'd should made it clearer to save you some time building/trying it.

**Comment by owocki** [comment]
i learned a thing or two from playing with it!  it was time well spent

**Comment by mbeacom** [comment]
@bakaoh Is this good to close due to the technical limitations?

**Comment by bakaoh** [comment]
@mbeacom --- it's not really a technical limitation since batch request (as in this pr) allow one click approval, but @owocki and i think atomic contract will give a better UX so it's good to close

**Comment by owocki** [comment]
@bakaoh i just paid you out because you were so instrumental in our thinking here.  thank you!

**Pull request closed without merging**
