### PR TITLE
Prompt the user to log in before starting work

### LINKED ISSUE #1107: As a user, I want to be prompted to authenticate before seeing a start work modal
Currently,  if a user is not logged into Gitcoin and they click on `Start Work`, they are still prompted with the start work modal.  Once they submit the modal, they receive the notification that they must authenticate with Github.

We need to alert them to authenticate and redirect them to the FTUX if necessary.

start_work

### Estimated Hours / Rate
1 Hour
$20 USD / hr

### Reviewers
@PixelantDesign @vs77bb @owocki @mbeacom @thelostone-mc

### PR DESCRIPTION
**Pull request by arun1595**
##### Description

- Implement a check to prompt the user to log in before starting work.

- Replaced native browser alerts in `bounty_details.js` with custom alerts.

- 'You must agree not to keep the fulfiller updated ...' ->  'You must agree to keep the funder updated ...'

##### Screenshot

image

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- ui

##### Testing

I tested it manually to make sure it works as expected.

##### Refers/Fixes

Fixes #1107

P.S. I am a Django noob. If I didn't follow Django's conventions or if there's a way to improve my solution, do let me know.

### CODE REVIEW

**Comment by arun1595** [comment]
@thelostone-mc @mbeacom This is ready for review.

**Comment by thelostone-mc** [comment]
@arun1595 could you resolve the conflicts? 😅 

Also could we update the text to `<logo> | Login with Github` ?
screen shot 2018-05-10 at 2 41 07 am

you'll find the code for that in `onboard.css`

**Comment by arun1595** [comment]
@thelostone-mc On it!

**Comment by arun1595** [comment]
@thelostone-mc Done.

Screenshot

image

**Comment by thelostone-mc** [comment]
Thanks for contribution and super quick response @arun1595 ^_^

(Yes @mbeacom I stole your line :P )

**Pull request merged**
