### PR TITLE
Add script to swap ERC-20 token balances in Gitcoin Fee address to ETH using Uniswap 

### LINKED ISSUE #4150: As a Gitcoin administrator, I would like any ERC20 tokens in my FEE_ADDRESS converted to ETH so I don't have to manage a complex tax situation
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin administrator, I would like any ERC20 tokens in my FEE_ADDRESS converted to ETH so I don't have to manage a complex tax situation

### Why Is this Needed
because john chard advised us taxes can be a pain in the arse.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no management of ERC20 tokens in FEE_ADDRESS

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
a new django management command that is scheduled to run every hour.
two new entries into `.env` and `settings.py` which manage the following vars
- FEE_ADDRESS -- the web3 address where fees exist
- FEE_ADDRESS_PRIVATE_KEY -- the private key to the above address.

the management command will, when run, check for any ERC20 tokens and use uniswap to transfer them into ETH.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above ^^

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

### PR DESCRIPTION
**Pull request by acolytec3**
##### Description

Pulls ERC-20 token balances associated with fee address and converts to ETH using Uniswap.
Notes:
 * Do-over of #4229 
 * On Rinkeby testnet, Uniswap trading request only currently works for BAT Uniswap exchange but not OMG or MKR exchanges (using my on test account)

##### Checklist

- [ ] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [ ] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

N/A

##### Refers/Fixes

Fixes #4150 

###### Contributor

- [x ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x ] Tested all changes **locally**
- [x ] Verified existing functionality
- [x] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by acolytec3** [comment]
@thelostone-mc @danlipert @owocki 

Do-over of #4229 with commit history cleaned up.

**Comment by acolytec3** [comment]
Just an FYI, I revisited this and moved the feeswapper.py command to the right directory (app/feeswapper/managemnet), incorporated a check for the debug flag from settings.py, and fixed another bug in the unit test I missed before.  Should be ready for final review though otherwise.

**Comment by owocki** [comment]
hey @acolytec3 taking a look now.  code looks sane (but big :) )

1. how did you test locally?  did you just run this on rinkeby? can you post the sample output on the PR?
2. 97 commits is a lot!  can you squash them into one commit?
3. it doesnt look like the CurrencyConversion model is used at all.  is this intended?

**Comment by owocki** [comment]
@gitcoinco/engineers look ok?

**Comment by acolytec3** [comment]
@owocki 
1.  Ran on Rinkeby. Sample output is in this [file](https://github.com/acolytec3/web/raw/feeSwapper/app/feeswapper/management/commands/sampleOutput.txt) (it's big so didn't want to post it all here).  If you want a copy of the two transaction failure emails, I can forward those as well.  Here's the [etherscan history](https://rinkeby.etherscan.io/address/0xe643cd48a9a902f6ce947324abe245b3fe4106dc) on the test qallet I was using.  You can see the failed transactions for the OMG, DAI, and MKR uniswap transactions but will see the BAT moving in and out the wallet on the ERC-20 tab.
 You'll see the failed transactions for OMG, DAI, amd MKR if you look at the 0xE643cD48A9A902F6cE947324abE245b3Fe4106dc
2. I'll create another local copy of the fork and try again.  The last time I did that it just completed confused the commit history up (though this is probably just my inexperience with Git showing as this is my first big PR)
3.  The entries in the CurrencyConversion model are created starting on line [138](https://github.com/acolytec3/web/blob/fe821a597289ad251a2562bb2abdd466af6e0c98/app/feeswapper/management/commands/feeSwapper.py#L136) of the feeSwapper.py file.  If the transaction succeeds, it posts a record of the fee conversion or posts a failure record (line 141) if not and it didn't previously find a failed transaction in the table.

**Comment by danlipert** [comment]
@acolytec3 Can you squash the migrations as well? Thanks!

**Comment by acolytec3** [comment]
I think I finally figured out what happened with the commit history that's made this such a mess for purposes of squashing but the upshot is that there is no easy way to get just my commits and squash them (due to an unfortunate rebase gone awry early in the history of this branch) so I'm having to start a new branch with all the final set of code commits.  I'll redo yet again in a new PR that links from the new branch I've made that clones all the code changes from this one but has them in a single commit.  I'll get the new PR opened momentarily and it should be good to go at that point.  I've revalidated the functionality/tests on the new branch and all appears to be in order.

**Pull request closed without merging**
