### PR TITLE
Proposed fix for Kudos marketplace search bar

### PR DESCRIPTION
**Pull request by ososco**
##### Description

When you add whitespace in search bar value, for example: "Limited edition", the query parameters will be "Limited+edition", so when results come back in the view, the search bar get its value from query parameters (queryParam.q), so it will also show up in the search bar as Limited+edition. The simplest solution is to replace the plus signs with whitespace:\

$('#kudos-search').val(queryParam.q.replace(/\+/g, " "));

I think it does look better.

##### Testing

simplescreenrecorder-2019-10-28_10 27 32

### CODE REVIEW

**Comment by danlipert** [comment]
@ososco nice! Thanks for the PR! In the PR description, theres a section to add how you tested your changes - here a screenshot or video would be good, or just a brief description on how you verified the changes are working. Thanks again!

**Comment by ososco** [comment]
@danlipert 

simplescreenrecorder-2019-10-28_10 27 32

**Comment by ososco** [comment]
Actually there is a better way to fix this with decodeURIComponent, i will commit the new fix after testing it.

**Comment by octavioamu** [comment]
@ososco I changed the base branch to be 'master'

**Pull request merged**
