### PR TITLE
fix: duplicate registration on hackathon onboarding

### PR DESCRIPTION
**Pull request by walidmujahid**
To prevent duplicate hackathon registrations under an event:

- return error on POST to /register_hackathon/ if user already registerd
- if no poll on hackathon onboard page, disable 'Join Now' button on click
- if poll on hackathon onboard page, disable poll submit button on click

fixes https://github.com/gitcoinco/web/issues/7070

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by octavioamu** [comment]
@walidmujahid notice you are just adding a disable class not actually disabling the button + if the request fails should "reenable" the button.

**Comment by walidmujahid** [comment]
> notice you are just adding a disable class not actually disabling the button

Are requests still sent after the disabled class added? I thought I checked for that. The idea was to prevent any new requests from being sent via the frontend button after the user first clicks to join an event by adding `disabled` to prevent further clicks. I will look at this later today.

> if the request fails should "reenable" the button.

I see. I completely missed this. I will be sure to fix it.

**Comment by walidmujahid** [comment]
> notice you are just adding a disable class not actually disabling the button

@octavioamu Are requests still sent after the disabled class added? I thought I checked for that. The idea was to prevent any new requests from being sent via the frontend button after the user first clicks to join an event by adding `disabled` to prevent further clicks. I will look at this later today.

> if the request fails should "reenable" the button.

I see. I completely missed this. I will be sure to fix it.

**Comment by walidmujahid** [comment]
Thinking back on how I did this, the click event is still running. I should have probably just set a conditional and exited -and added the class for possibly UX. Sorry for the trouble @octavioamu, I should have noticed the error before it was merged. I will try to get a fix out later today.

**Comment by octavioamu** [comment]
No problem just add attr disabled I stead of class and remove it on error

**Pull request merged**
