### PR TITLE
lander video switcharooooooooooooO

### PR DESCRIPTION
**Pull request by owocki**
##### Description

puts the 'what is it' video on about, and adds the funder video the existing lander

screenshot => http://bits.owocki.com/0A2x1y3Z2W2b/Screen%20Shot%202018-08-02%20at%201.56.38%20PM.png

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

ui

##### Testing

tested

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/1836

### CODE REVIEW

**Comment by owocki** [comment]
@PixelantDesign any feedback?

**Comment by owocki** [comment]
@thelostone-mc whats the idea behind putting the 'mission' and 'not a token' buttons next to each other?

the 'mission' button is meant to go with the h3 'A Mission to Grow Open Source.'
same with the 'not a token' one. its meant to go below the h3 'No ICO. No Token. No Funny Business.'

**Comment by thelostone-mc** [comment]
Would you like it be place like that ?
I know this seems a lil unorthodox but it seemed clear to me
Mission (you see the button below it)
The button next to it would be defaulted to the content below it 

We can switch it back if you found it misleading

**Comment by PixelantDesign** [comment]
@thelostone-mc treatment of the buttons look nice visually but from a flow/ content and connection perspective, it would read better/make more sense per @owocki recommendation.

**Comment by thelostone-mc** [comment]
Okie me switching it back

**Pull request merged**
