### PR TITLE
purge: bounties universe

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- updated migration to remove bounties-universe from toolup
- removed from settings.py
- removed app external_bounties + js + css files
- updated doc + APIs to remove ref to external bounties

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [x] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@mbeacom test on staging ? locally stuff seems to be fine 👍

**Comment by thelostone-mc** [comment]
@owocki already taken care ^_^ 👍

**Comment by owocki** [comment]
> @owocki already taken care ^_^ 👍

hmm maybe we should create a 'retired' section of tools and put bounties universe / iphone on that..  just to celebrate our projects that didnt work :P

**Comment by thelostone-mc** [comment]
@mbeacom lemme know when you want to get this in and I'll rebase

**Pull request merged**
