### PR TITLE
Batch email per checkout

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
image

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7131

### CODE REVIEW

**Comment by octavioamu** [comment]
@PixelantDesign to confirm the email looks good

**Review by thelostone-mc — APPROVED** [review]
lgtm but pending stakeholder (@PixelantDesign ) sign off

**Comment by danlipert** [comment]
Is this still good to go? @PixelantDesign for final signoff I think

**Review by danlipert — APPROVED** [review]

**Comment by corydickson** [comment]
@zoek1 Looks like there was some communication issues and I duplicated some work: see #7880 

Your PR has the styling changes necessary that I'm missing, would you want to add some changes I made to the celery tasks? Essentially I create a `chord` which waits until all of the grant processing tasks are completed before taking the successful grant ids and composing the email. Let me know what you think!

**Comment by apbendi** [comment]
Looks like we got our wires crossed a bit here. I think since @corydickson has built and tested his update against the most recent branch, it's probably best for him to cherry-pick in the style changes from @zoek1's PR here, and then we merge this one. Does that work for you @thelostone-mc?

**Comment by thelostone-mc** [comment]
@apbendi so close this PR -> cherry pick styles from here onto @corydickson branch and use that ?
Works for me

**Comment by apbendi** [comment]
> so close this PR -> cherry pick styles from here onto @corydickson branch and use that ?

Hey @thelostone-mc, my explanation was not very clear, but you figured it out! That is indeed what I meant. Let's go with that, then.

**Comment by thelostone-mc** [comment]
Closing this out and porting over needed commits onto https://github.com/gitcoinco/web/pull/7880 as discussed above

**Pull request closed without merging**
