### PR TITLE
nav: redesigned the dropdown

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- refactored nav_auth.html
- replaced images with font-awesome
- redesigned css

help

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- css 
- html

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@PixelantDesign

**Comment by thelostone-mc** [comment]
@PixelantDesign Updated the icon as requested

**Comment by PixelantDesign** [comment]
looks good!

**Comment by thelostone-mc** [comment]
@mbeacom merge ready ?

**Comment by mbeacom** [comment]
@thelostone-mc I ended up reverting this and sent you a DM. Let's sync up when you have a few minutes.

**Pull request merged**
