### PR TITLE
explorer: added sort feature

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Added the sort feature in the search tab on the explorer page

help

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- css

##### Refers

- https://github.com/gitcoinco/web/issues/570

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@mbeacom  would like this to be considered for merge post https://github.com/gitcoinco/web/pull/573 if possible

**Comment by mbeacom** [comment]
@thelostone-mc I'll be running through and testing both this and #573 shortly.  Thanks for the contribution!

**Comment by owocki** [comment]
just tested.. seems to work fine..

one thing thats missing that was in the old explorer... is the ability to sort by `web3_created_on` date.. i think that was a valuable way of sorting the data.. in fact i'd advocate for adding that in in such a way that it replaces either the 'difficulty' or 'length' sort options!

**Comment by thelostone-mc** [comment]
@mbeacom @owocki  Done 👍 

help

**Comment by owocki** [comment]
LGTM; @mbeacom ?

**Pull request merged**
