### PR TITLE
feat: sybil data input endpoint for round

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Endpoint: `/grants/v1/api/clr-data/<round-id>`

Response: 

```
{
    "metadata": {
        "count": 12,
        "current_page": 1,
        "total_pages": 2,
        "has_next": true
    },
    "contributions": [
        {
            "created_on": "2020-09-28T20:57:02.800Z",
            "profile_for_clr__handle": "lorem",
            "profile_for_clr_id": 94849,
            "match": true,
            "normalized_data": {...}
        }
    ]
```    

- create BSCI_SYBIL_TOKEN in static json store + set value

##### Refers/Fixes

https://gitcoin.atlassian.net/browse/GITC-303

##### Testing

Untitled

### CODE REVIEW

**Review by gdixon — APPROVED** [review]

**Review by zacheryschiller — APPROVED** [review]
👍

**Comment by gdixon** [comment]
One thought - do we need to account for `defer_clr_to_id` in this feed?

**Comment by octavioamu** [comment]
can we consider change `get-clr-data` to not include the verb? maybe just `clr-data`?

**Comment by octavioamu** [comment]
should we consider moving the error if not valid token to be a json error instead of render a html error page?

**Pull request merged**
