### PR TITLE
[WOC] Funder dashboard final

### PR DESCRIPTION
**Pull request by NedelescuVlad**
Moving https://github.com/gitcoinco/web/pull/2239 to this PR.

In addition to the code there, the issues outlined in bullet points by @PixelantDesign have been resolved. As far as I could test this is ready to merge (even total budget module works, make sure to run a `docker-compose --build` though as the schema has been changed)

Will need help testing @thelostone-mc @PixelantDesign

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@NedelescuVlad could you throw in a video recording of the page and all it's functionalities  ( with responsive design and stuff )
so that @PixelantDesign can review it in parallel ?

**Comment by NedelescuVlad** [comment]
@thelostone-mc sure thing. Also, lmk if you want to know how to test certain parts of the app (like csv export, outgoing funds etc.).

**Comment by PixelantDesign** [comment]
That would be great @vlad! 

cc @frankchen07 @willsputra

**Comment by NedelescuVlad** [comment]
Just recorded the demo yesterday, uploading to YT today and linking soon; found a few small tweaks i can make when recording it so will do these as well

**Comment by NedelescuVlad** [comment]
Demo here: https://www.youtube.com/watch?v=3KU4wfqlJvA

**Comment by NedelescuVlad** [comment]
Small tweaks done, if you folks can test this on staging and see if everything works as expected I'd be very happy =)

**Comment by thelostone-mc** [comment]
@NedelescuVlad we'll have this on staging this week and test it out :)

**Comment by NedelescuVlad** [comment]
Nice, lmk how it goes!

**Comment by mbeacom** [comment]
screenshot 2018-11-19 13 53 08

`pluralize` is being used (with `bountie` vs `bount`) and isn't specifying the defaults for singular and plural cases.

Committing change to adjust these `pluralize` cases to use:  `bount` coupled with: `pluralize:"y,ies"`

**Comment by owocki** [comment]
some QA

1. [the issue number is strange](http://bits.owocki.com/4679a27aef52/Screen%20Shot%202018-11-26%20at%207.46.29%20PM.png) maybe we should just remove it?
2. [why are all my payments status pending?](http://bits.owocki.com/4679a27aef52/Screen%20Shot%202018-11-26%20at%207.46.29%20PM.png) -- these bounties arent' actually pending.. they're done.
3. [it'd be nice if all these 'view' links](http://bits.owocki.com/fc94f8b542e9/Screen%20Shot%202018-11-26%20at%207.47.59%20PM.png) actually pointed to specific search queries instead of just `/explorer/
4. [add budget doesnt work](http://bits.owocki.com/333bd2caaad0/Screen%20Recording%202018-11-26%20at%2007.48%20PM.gif)
5. this page takes about 5s to load with a cold cache (but only 40 ms with a warmed cache!)
6. small nitpick - [can we fix the plurality here?])http://bits.owocki.com/c3398a3bb66a/Screen%20Shot%202018-11-26%20at%207.50.12%20PM.png)
7. in the CSV, can we add a 'created_time' column?  also the 'github link' in there points to gitcoin not github
8. for a v2, we should fold tips/kudos into the funder dashboard. right now it's pretty bounty specific.
9. what are the units on this graph? [screenshot](http://bits.owocki.com/199c34a287ee/Screen%20Shot%202018-11-26%20at%207.52.15%20PM.png)

**Comment by NedelescuVlad** [comment]
Ah just noticed that this is WOC again. Will have a look these days

**Comment by thelostone-mc** [comment]
@NedelescuVlad all good / anything we can help with ?

**Comment by NedelescuVlad** [comment]
Hey Aditya, was a bit short on time due to coursework this week. My last
one is due tomorrow so looking forward to get this done in the weekend.
Everything seemed straight forward enough. The only points I want to
discuss are these:

1. "the issue number is strange
<http://bits.owocki.com/4679a27aef52/Screen%20Shot%202018-11-26%20at%207.46.29%20PM.png>
 maybe we should just remove it?" --- I could replace the issue ID with
Bounty ID if there is such a unique bounty id. Currently the issue id is
the issue # in the github repo the issue belongs to. Replacing it with a
unique Bounty ID that is unique across the Gitcoin website (and also
replace "Issue ID" with "Bounty ID") would be a viable approach. I'm also
fine with removing it, but would only like to do this as a last resort.

2. "why are all my payments status pending?
<http://bits.owocki.com/4679a27aef52/Screen%20Shot%202018-11-26%20at%207.46.29%20PM.png>
--
these bounties aren't actually pending.. they're done." --- I agree. I
coded it to say "pending" based on the fulfillments object, intention being
to say "pending" when the bounty fulfiller hasn't accepted the payment yet;
thus amounting to an outgoing fund that is pending receival. I can see how
this can be confusing... can we please confirm when an outgoing fund should
be flagged as pending?

**Comment by thelostone-mc** [comment]
@NedelescuVlad 

1. We do have a bounty id but not sure if it would make sense to show it as we don't show it across the site at the moment. I think we do away with for now and add it in later if we feel it adds value

2. Well as of across the site we leave the status as submitted if it's pending payment 
That might make more sense. cc @owocki

**Comment by NedelescuVlad** [comment]
@thelostone-mc @owocki @PixelantDesign 
Just finished (I think) fixing the QA issues pointed out by @owocki . Here is what I did on each one:

1. `the issue number is strange maybe we should just remove it?` - Have just removed it, personally also like it with no issue number
2. `why are all my payments status pending? -- these bounties arent' actually pending.. they're done.` - I've reworded "Pending" to "Submitted". I've kept the styling the same italicized eth-colored purple.
3. `it'd be nice if all these 'view' links actually pointed to specific search queries instead of just "/explorer/"` - 
* I can't view the screenshot anymore, but most of the links do apply query strings to the explorer url (i.e the active/done/expired bounty links in the right column). 
* The query strings are appended in JS and not hardcoded in the link, which is why they don't show up if you just hover over.
*If filtering isn't appropriate once you've clicked on the link please get back. Sorry if I misunderstood this one.
4. `add budget doesnt work` - It does work for me, but I needed to do a `docker-compose down -v`, delete the docker image and then build from scratch with `docker-compose up -d --build` in order to get the db to migrate properly. I then did the `sync_geth` command. Once I had that it worked... I'm not sure if deleting the image was necessary (my docker understanding isn't the best) but can you please make sure the migrations work properly when you test? 
5.` this page takes about 5s to load with a cold cache (but only 40 ms with a warmed cache!)` - Haven't done anything. There's a lot of room for improvement here by not fetching everything on the GET imo and/or caching more granularly i.e not per page, but per i.e done bounties across the site and then looking for the user in those. 
6. `small nitpick` - can we fix the plurality here? - good spot, done
7. `in the CSV, can we add a 'created_time' column? also the 'github link' in there points to gitcoin not github` - added
8. `for a v2, we should fold tips/kudos into the funder dashboard. right now it's pretty bounty specific.
what are the units on this graph? screenshot` - done, added the `$` sign in front =)

LGTM?

**Comment by thelostone-mc** [comment]
Closing this out as this is being rebuilt again !

**Pull request closed without merging**
