### PR TITLE
bounty: review feedback added

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- vertical aligned activity section
- Changed Kill Bounty -> Cancelled Bounty
- Changed Order of Cancel Bounty  & Add contribution

x

screen shot 2018-03-27 at 2 48 21 am

screenshot-2018-3-27 funded issue details gitcoin

##### Refers/Fixes
- https://github.com/gitcoinco/web/pull/691

### CODE REVIEW

**Comment by PixelantDesign** [comment]
@thelostone-mc you are fast! 

- Add contribution should be a secondary button (White button)
- When there are no tags assigned, we should hide the background of the tags
- What does the tooltip say on hover over **Add contribution**?
- Need more space between these elements, try adding 10px in between *months* and *open*, *ago* and *experience*, and so on
screen shot 2018-03-26 at 10 32 57 pm
- Can we match inside padding bottom with the top? See below:
screen shot 2018-03-26 at 10 39 01 pm 

Thank you!

**Comment by thelostone-mc** [comment]
@mbeacom all changes added 👍

**Comment by PixelantDesign** [comment]
@thelostone-mc 

Is there no comment count because there arent any comments on this github issue example?

can we increase padding on the USD label? match ETH.

@mbeacom I’d like to look at this one more time on staging before merge. 

Thank you.

**Comment by thelostone-mc** [comment]
> Is there no comment count because there arent any comments on this github issue example? 

Yup

> can we increase padding on the USD label? match ETH.

Done

screen shot 2018-03-27 at 7 23 28 pm

**Comment by mbeacom** [comment]
The latest changes are deployed to staging. @PixelantDesign

**Comment by PixelantDesign** [comment]
looks great! thank you @thelostone-mc

**Comment by thelostone-mc** [comment]
@mbeacom merge merge :D

**Comment by mbeacom** [comment]
@PixelantDesign Is this good to go?

**Comment by owocki** [comment]
you are all ⭐️ s

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/711/542).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/711/543).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Pull request merged**
