### PR TITLE
Clothing

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
image
image
image
image
image
image
image
image
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc please review these designs once

**Comment by thelostone-mc** [comment]
I LOVE :D
Oh could we extend the sleeves on the round neck and collar shirt ? It looks like they have no arms 😂

**Comment by mehul0698** [comment]
extending the sleeves will spoil the design

**Comment by mehul0698** [comment]
@thelostone-mc will this not work without extending the sleeves?

**Comment by thelostone-mc** [comment]
It would work but the issue the image is a square! 
So when folks download it -> they avatar would not have arms

**Comment by mehul0698** [comment]
image

**Comment by mehul0698** [comment]
image
image
image

**Comment by mehul0698** [comment]
@thelostone-mc I have updated the 2 designs. Please review it once.

**Comment by mehul0698** [comment]
@owocki please review this once.

**Comment by owocki** [comment]
screenshots LGTM ... defer to @thelostone-mc from here

**Comment by mehul0698** [comment]
@owocki from the doctor design should I put the stethoscope as a separate accessory?

**Comment by owocki** [comment]
i think its fine the way it is

**Comment by mehul0698** [comment]
@owocki the pr has been merged. I consider 3 of these to be exotic. Owe me 140 dollars.

**Comment by mehul0698** [comment]
@owocki will you accept anymore clothing designs?

**Comment by owocki** [comment]
@mehul0698 let me know what you had in mind and we can take it case by case from there!

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have made a space suit should I put a pr?

**Comment by owocki** [comment]
i like all of them!

**Comment by owocki** [comment]
can the american football jersey come with a helmet ? :)

**Comment by mehul0698** [comment]
@owocki Yes the helmet is possible. You want it as a separate accessory or along with the clothing?

**Comment by owocki** [comment]
along w. clothing sounds good to me

**Comment by mehul0698** [comment]
@owocki the helmet wont be in front as the avatars are composed of layers, the clothing layer is the bottom most layer so the head is always going to be above the clothing layer so the helmet will become hidden. Under the current restriction the helmet is only possible as a separate accessory as the accessories are the topmost layer.

**Comment by owocki** [comment]
oh sorry when you said "along with the clothing" i thought we were talking about in the same PR.

totally makes sense to have it as an accessory layer item to me!

**Pull request merged**
