### PR TITLE
chore: participants Experiment fixes 

### LINKED ISSUE #7084: Participants Experiment fixes
- [ ] Put in a default message in the input field for users that don't enter a message during registration. 
"I'm a new hacker! Great meet you all!"
- [ ] Remove #intro  button from prizes view
- [ ] Remove background image on the participant card - makes it difficult to read. Leave top bar design.
- [ ] Profile picture should be centered in the circle
Screen Shot 2020-07-10 at 10 00 55 AM

follow up  to #6443

### PR DESCRIPTION
**Pull request by developerfred**
##### Refers/Fixes
close #7084
> * [x]  Put in a default message in the input field for users that don't enter a message during registration.
>   "I'm a new hacker! Great meet  you all!"
> * [x]  Remove #intro  button from prizes view
> * [x]  Remove background image on the participant card - makes it difficult to read. Leave top bar design.
> * [x]  Profile picture should be centered in the circle

##### Testing

Screen Shot 2020-07-10 at 17 20 29

#### Video screen
https://share.getcloudapp.com/X6uoPPnr

### CODE REVIEW

**Comment by developerfred** [comment]
@PixelantDesign yes, I will do now!

**Comment by developerfred** [comment]
@PixelantDesign updating in dev environment I'm having error 500 when I do the hackathon registration process. I'm investigating as soon as it works I can make the video.

**Comment by developerfred** [comment]
- [x] tag post on hackathon page
Screen Shot 2020-07-20 at 11 23 00

**Comment by developerfred** [comment]
@PixelantDesign  https://share.getcloudapp.com/X6uoPPnr

**Comment by frankchen07** [comment]
I think we should consider stopping intros for now, and leaving the townsquare as the announcement board. There hasn't been conclusive evidence that the intros are being used to form teams. Many intros are also left blank.

We can surface the intros data elsewhere once we've figured out the best medium, maximum impact way to do this.

**Comment by joramowuor** [comment]
}, reload
#249

**Comment by PixelantDesign** [comment]
agree with that   @frankchen07,  it's not working how we intended.

**Comment by danlipert** [comment]
closing for now as we rethink the intro functionality

**Pull request closed without merging**
