### PR TITLE
gitcoin.co/profile/owocki => gitcoin.co/owocki

### PR DESCRIPTION
**Pull request by owocki**
makes gitcoin profiles a first class path on gitcoin.co; thereby giving users more sense of ownership of their gitcoin profile being a premium thing.  and increasing the chances they pass it around like they do other social networks (twitter.com/owocki github.com/owocki facebook.com/owocki all have first class URL routes)

##### Refers/Fixes

self

##### Testing

tested locally; the only hard part is handling url collisions.. which i think `dashboard.models.profile.url` does quite elegantly

### CODE REVIEW

**Comment by owocki** [comment]
@gitcoinco/engineers feedback?

**Comment by owocki** [comment]
@gitcoinco/engineers feedback?

**Comment by danlipert** [comment]
@thelostone-mc @owocki good point! I think its okay if we add a canonical url tag

**Comment by owocki** [comment]
> I'm not too keen on having multiple URL to access the same page but defer to the others on this

except for the one time migration; where will we have multiple URLs pointing to the same place?  to my knowledge this is only linked via `profile.url`

**Comment by owocki** [comment]
@thelostone-mc @danlipert f36a2edba91a6ba3ce828d1f6e3acda409df338c adds a canonical tag

**Comment by octavioamu** [comment]
My only concern is about collisions. What happens if this guy want to use gitcoin? https://github.com/profile

**Comment by owocki** [comment]
@octavioamu that is handled here : https://github.com/gitcoinco/web/pull/5278/files#diff-0d2d86c824ef942c5a3a01c83ddfe758R3141-R3145

basically if a collision is detected it uses the old format ( `/profile` )

**Comment by octavioamu** [comment]
I think could be amazing if we can create username.gitcoin.co but again not sure about collisions ex https://github.com/hackathons

**Comment by owocki** [comment]
> I think could be amazing if we can create username.gitcoin.co but again not sure about collisions ex https://github.com/hackathons

yea this is something that the whiteblock team requested at https://github.com/gitcoinco/web/issues/4832 too

**Comment by owocki** [comment]
yayyy

**Comment by thelostone-mc** [comment]
I'm gonna have to revert this cause 

Screenshot 2019-10-23 at 5 57 02 AM


- /grants takes me to a profile which doesn't exist 
- it does confuse the user -> if we were to search for `/explorer` and mistyped it -> it would take him to a profile

**Pull request merged**
