### PR TITLE
Add flag to display showcase

### PR DESCRIPTION
**Pull request by zoek1**
##### Description

- [X] Add ability to turn on showcase tab in admin.
- [X] If showcase is toggled on in admin, hide all tabs except Projects and Showcase.
- [X] Editor should be able to remove a spotlight (add a link to remove)

image
image

### Add showcase to hackathon list
image

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7083

##### Testing

https://www.loom.com/share/4d89bf4775d9415d98d66360840785e4

### CODE REVIEW

**Comment by octavioamu** [comment]
Nice, just one point, turning off all the others tabs will be a problem, mostly for sponsors trying to find their prizes cc @PixelantDesign

**Comment by octavioamu** [comment]
@zoek1  The code looks good but I really feel the only tab need to turn off is the guide, the rest should be there, so I can keep chatting with people on townsquare or chat, see the participants tabs, I want to see the others participants not only the winners and for sure keep the activity on townsquare.

**Comment by octavioamu** [comment]
+ this is the card of a finished hackathon, prizes are still important but maybe we can add the showcase link there 
image

**Comment by PixelantDesign** [comment]
yes agree @octavioamu

**Comment by octavioamu** [comment]
@zoek1 can you do that changes?

**Comment by octavioamu** [comment]
Thanks @zoek1

**Comment by PixelantDesign** [comment]
how are we looking on this ticket? could we get into Monday  deploy? @octavioamu @danlipert @thelostone-mc ?

**Comment by androolloyd** [comment]
@zoek1 travis seems to be complaining about the import order, and needs the base branch merged in

**Comment by PixelantDesign** [comment]
@danlipert @octavioamu @thelostone-mc could we  have  a review please?  thanks!

**Comment by PixelantDesign** [comment]
could we get this in Monday's deploy? @danlipert @octavioamu @thelostone-mc

**Pull request merged**
