### PR TITLE
Issue 794 campaign email

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description
PR for sending campaign emails to new users for the first 3 days

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [x] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

UI
##### Refers/Fixes
Fixes #1010 

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [x] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@iamonuwa can PR 1010 be closed out once this is gets in ?

**Comment by iamonuwa** [comment]
#794 will be closed once this gets in

**Comment by iamonuwa** [comment]
> @iamonuwa can PR 1010 be closed out once this is gets in ?
> Also could we get in tests so as to avoid obvious bugs
> 
> cc @danlipert

Yes

**Comment by iamonuwa** [comment]
> @iamonuwa can PR 1010 be closed out once this is gets in ?
> Also could we get in tests so as to avoid obvious bugs
> 
> cc @danlipert

Yes

**Comment by iamonuwa** [comment]
@danlipert @octavioamu @thelostone-mc @PixelantDesign

**Comment by danlipert** [comment]
@iamonuwa can you please add tests? thanks!

**Comment by thelostone-mc** [comment]
@iamonuwa I've resolved the conficts cause I had made a few minor changes along with this PR. 
Could you please ensure the tests are added in as suggested by @danlipert ?

**Comment by iamonuwa** [comment]
> @iamonuwa I've resolved the conficts cause I had made a few minor changes along with this PR.
> Could you please ensure the tests are added in as suggested by @danlipert ?

Yes, will add the needed tests

**Comment by iamonuwa** [comment]
@thelostone-mc tests has  been added. Let me know if you need more :joy:

**Comment by thelostone-mc** [comment]
@iamonuwa travis CI failures :P

**Comment by iamonuwa** [comment]
Wierd, tested locally and everything was green

> @iamonuwa looks like the tests you added seems to be failing over at travis CI :P

**Comment by thelostone-mc** [comment]
@danlipert ^ Any idea on this ?

**Comment by iamonuwa** [comment]
@thelostone-mc @danlipert @vs77bb ready for review

**Comment by thelostone-mc** [comment]
Can't merge it until CI passes. :/  Else every CI would end up failing 
@danlipert / @SaptakS any idea what's going on here ?

**Comment by iamonuwa** [comment]
> Can't merge it until CI passes. :/ Else every CI would end up failing
> @danlipert / @SaptakS any idea what's going on here ?

Noted.

**Comment by thelostone-mc** [comment]
@iamonuwa dudeeee @octavioamu fixed it up ^_^ It was a missing CSS file (not cause of your PR )

**Pull request merged**
