### PR TITLE
Add shirtsweater avatar asset

### LINKED ISSUE #1663: New avatar assets
### User Story

As a user, I want to new avatar assets to show off and express myself digitally.

### Description

*Type*:  New implementation

### Definition of Done

- [ ] Create an .svg asset and place it in `app/assets/v2/images/avatar/<category>`
- [ ] Add the SVG asset as a `.txt` Django template in `app/avatar/templates/<category>/<item|index>.txt` with variable fill.
- [ ] Add your asset to [utils.py](https://github.com/gitcoinco/web/blob/master/app/avatar/utils.py#L43-L97)
- [ ] Provide a screenshot of the new asset from the avatar builder AND the profile details page on this Github issue.

### Additional Information

Feel free to submit any assets you would like to see on Gitcoin.  If the asset is accepted, your asset will become a part of the live avatar builder!  All other assets will be escalated to the core team for review and potential modification.

See the [avatar item request shortlist](https://github.com/gitcoinco/web/issues/1550)

**COMMUNITY MEMBERS**
Feel free to add reactions/upvote your favorite new avatar items/assets!

### PR DESCRIPTION
**Pull request by ajayns**
##### Description
Adds shirtsweater clothing asset to avatar builder. Currently I've only worked on one color, but if the design looks good, I'll add the other colors and we could move forward.

screenshot from 2018-08-21 13-57-05

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)A

##### Refers/Fixes
#1663

### CODE REVIEW

**Comment by owocki** [comment]
looks like a collared shirt to me!

**Comment by ajayns** [comment]
My idea initially was a shirt with a sweater over it, but with the specs limitations it turned out like this. Maybe I could rename it to whatever it looks more like

**Comment by owocki** [comment]
got it makes sense

**Comment by thelostone-mc** [comment]
Yo @ajayns 
Could you 
- wire it up to the avatar builder and attach a screenshot [like this](https://d3vv6lp55qjaqc.cloudfront.net/items/3w2s053y1S262E3f3Z46/Screen%20Shot%202018-08-20%20at%202.43.11%20PM.png) here so that we know how it looks
- run `svgio` on the `svg` to compress it

**Comment by ajayns** [comment]
@thelostone-mc Hey, yes! As I mentioned, I wanted to make sure the design looks go to you guys, so that I could add the rest of the colors, optimize svg. About the screenshot, I wasn't able to run it locally due to some docker issues, which I'm still trying to figure out, I'm trying it again on broadband today and will open an issue regarding the same.

cc @owocki

**Comment by thelostone-mc** [comment]
@ajayns looks like you've got a 👍 from our UX lead :D
So go ahead with the integration ^_^

**Comment by ajayns** [comment]
I couldn't find what you meant by `svgio` though? Could you provide me a link or something of that sort I can use?

**Comment by thelostone-mc** [comment]
@ajayns Ah sorry about that it's `svgo` 😅 
Here you go : just follow [this](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#contributing-static-assets)

**Comment by ajayns** [comment]
All the requested changes have been made @thelostone-mc

**Comment by owocki** [comment]
assets look okay at this point, but id ont seem to be able to see them in the site , logged the issue here https://github.com/gitcoinco/web/issues/2102

**Comment by thelostone-mc** [comment]
@ajayns what's left to do : 

- Update [this](https://github.com/gitcoinco/web/blob/master/app/avatar/utils.py#L71) to include `shirtsweater`
- Throw in a screenshot with the changes


@owocki ^ Did you try that out ?

**Comment by thelostone-mc** [comment]
x

**Pull request merged**
