### PR TITLE
Added menorah hat accessory

### PR DESCRIPTION
**Pull request by jakerockland**
##### Description

Added menorah hat accessory to avatar creator 🕎.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

avatar

##### Testing

Tested locally, screenshots attached:
screenshot 2018-11-05 20 43 46
screenshot 2018-11-05 20 43 58

##### Refers/Fixes

Refs: #2684

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Could you resolve the conflicts ? :P

**Comment by jakerockland** [comment]
@owocki is it possible to get payout on this guy and on #2702 sometime soon? I wanna turn my DAI -> ETH and buy more Gods Unchained cards while the market is down hehe...

**Comment by owocki** [comment]
yes as soon as https://github.com/MetaMask/metamask-extension/issues/5764 is solved

**Comment by jakerockland** [comment]
Rad thank you @owocki 

Also, thoughts on this? https://github.com/gitcoinco/web/pull/2852

**Comment by owocki** [comment]
LGTM!

**Comment by jakerockland** [comment]
Thank you @owocki <3

**Pull request merged**
