### PR TITLE
add bulk add for collections

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

- when using the search if "enter" is pressed execute the query.
- If Im seeing a collection I can add all the collection to my cart with one click 

image

##### Refers/Fixes
Based on discord users feedback 
unblock #9460

https://gitcoin.atlassian.net/browse/GITC-402

### CODE REVIEW

**Comment by zacheryschiller** [comment]
Didn't we intentionally remove the bulk add collection to cart recently? @PixelantDesign @frankchen07

**Comment by chibie** [comment]
@octavioamu is there a limit to how many grants can be in a collection?

**Review by thelostone-mc — APPROVED** [review]
code wise LGTM.
Still not sure on the bulk add as a feature but defer to product here

**Comment by octavioamu** [comment]
> @octavioamu is there a limit to how many grants can be in a collection?

I don't think so

**Review by gdixon — APPROVED** [review]
Nice @octavioamu!! 🚀

**Pull request merged**
