### PR TITLE
Check-In Tool (ambassador) API extension

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description

This PR adds a new view-set that quickly provides data for the check-in tool

##### Refers/Fixes
No public issues available.

##### Testing
checked against the mockserver.py - data is 100% compatible and usable the moment we switch it in.
image

### CODE REVIEW

**Comment by danlipert** [comment]
Hey @kuhnchris - is this good to merge in? I saw some discussion about it among y'all so I wanted to double check - let me know, thanks!

**Comment by kuhnchris** [comment]
> 
> 
> Hey @kuhnchris - is this good to merge in? I saw some discussion about it among y'all so I wanted to double check - let me know, thanks!

we only asked around for people to help merge, it's good from my side. :-)

**Comment by danlipert** [comment]
@kuhnchris can you fix the isort error?

**Comment by kuhnchris** [comment]
> 
> 
> @kuhnchris can you fix the isort error?

ah sure, my bad. I'll fix it in a bit!

**Comment by ryan-shea** [comment]
@kuhnchris anything you need from our side to get ready to merge?

**Comment by kuhnchris** [comment]
Yes, from my aside a.o.k. Thanks for the merge @danlipert

**Pull request merged**
