### PR TITLE
Remove button class disabled and css for disabled button

### LINKED ISSUE #4315: bug - 'fund issue' button on gitcoin.co/new is always greyed out
**Describe the bug**

bug - 'fund issue' button on gitcoin.co/new is always greyed out on submit

**To Reproduce**

1. go to gitcoin.co/new
2. fill out the form
3. the 'fund issue' button stays greyed out.

**Expected behavior**

3. the fund issue button should not be greyed out as soon as validation passes

**Screenshots**

http://bits.owocki.com/cac7582eba71/Image%202019-04-29%20at%205.33.45%20PM.png

**Desktop (please complete the following information):**
Chrome, Mac OS X

### PR DESCRIPTION
**Pull request by shad-k**
##### Description
Removed the addClass('disabled') for button and css for button:disabled selector.

##### Refers/Fixes

Fixes #4315

### CODE REVIEW

**Comment by owocki** [comment]
the button should only be disabled if the validation fails.  this just removes the disabled button in all cases..

**Comment by shad-k** [comment]
> the button should only be disabled if the validation fails. this just removes the disabled button in all cases..

I have only removed the `button:disabled` selector, the `button.disabled` more specific selector is still there. So the disabled button still exists and the button is disabled when the validations are not met.

**Comment by owocki** [comment]
thanks; how did you test? i noticed you left out the 'Testing' section of the template...

**Comment by shad-k** [comment]
> thanks; how did you test? i noticed you left out the 'Testing' section of the template...

I ran the tests already written but haven't written any new tests for this. Rest was mostly manual.

**Comment by owocki** [comment]
ok so you tested the validation working + not working states on gitcoin.co/new on your local @shad-k ?

@danlipert @thelostone-mc code LGTM; let me know what u think

**Comment by shad-k** [comment]
@owocki yes

**Comment by thelostone-mc** [comment]
LGTM 🙌

**Pull request merged**
