### PR TITLE
new missions page v1

### PR DESCRIPTION
**Pull request by walidmujahid**
##### Description

New missionsn page, v1 and v1_mobile.
Demo Video: https://youtu.be/ym2WfDp70A4

##### Refers/Fixes

closes https://github.com/gitcoinco/web/issues/7242

### CODE REVIEW

**Comment by owocki** [comment]
@walidmujahid seems really strong to me!

can you remove these buttons from the v1 https://bits.owocki.com/RBuObQvP https://bits.owocki.com/WnuJ5jGq

you may also want to run the linter; seems as tho the tests are failing

@thelostone-mc passing this into code review

**Comment by walidmujahid** [comment]
> can you remove these buttons from the v1 https://bits.owocki.com/RBuObQvP https://bits.owocki.com/WnuJ5jGq

I commented it out in the markup @owocki. I am unable to do any furtehr testing at the moment as I am facing some errors: https://github.com/gitcoinco/web/issues/7347

> you may also want to run the linter; seems as tho the tests are failing

I am ucnertain as to what is causing this at the moment. According to travis, it is the 'Muli' font that I have in the css file. I tried @import-ing it, however, it did not seem to resolve it. I had assumed that the font was being loaded, however, I will need to do further testing once my local build is running smoothly again.

**Comment by owocki** [comment]
this looks SOOOOO good 🚢 :shipit: 🚢 :shipit: 🚢 :shipit: !

**Comment by owocki** [comment]
this looks GREAT to me @walidmujahid ; @thelostone-mc can i get this in the next deploy

**Comment by walidmujahid** [comment]
> this looks GREAT to me @walidmujahid 

Good to hear @owocki . If anything is needed before it is deployed, or an issue is found after, I will work on a fix as soon as possible. For now, I will just submit as is as Finished Work to the bounty.

**Comment by walidmujahid** [comment]
> this looks GREAT to me @walidmujahid 

Good to hear @owocki . If anything is needed before it is deployed, or an issue is found after, I will work on a fix as soon as possible. For now, I will just submit this work as is now to the bounty.

**Comment by walidmujahid** [comment]
> this looks GREAT to me @walidmujahid 

Good to hear @owocki . If anything is needed before it is deployed, or an issue is found after, I will work on a fix as soon as possible. For now, I will just submit this work to the bounty. I was just waiting for to be merged, but I hope that will be soon.

**Comment by owocki** [comment]
cherry-picked

**Comment by thelostone-mc** [comment]
Closing this out as this in live !
https://gitcoin.co/mission

thanks @walidmujahid :)

**Pull request closed without merging**
