### PR TITLE
Future Salaries system

### PR DESCRIPTION
**Pull request by vporton**
##### Description

_This is a work-in-progress for the following project:_

I modified "prediction markets" from gambling to get "money transfer from the future": accordingly, my mathematical model the amount of money withdrawn from the contract is equal (relatively to market sizes) to the amount of money put in the future. For money transfer from the future to work well, traders need to know the future well enough and follow simple rules for profit maximization.

I use it to pay salaries to common good producers (such as scientists and free software authors, even carbon accounters - in conjunction with my other project) using money transfer from the future accordingly to traders predictions of future oracles, e.g. citation counts after 100 years. We can collect money (donations, taxes, even a fee from miners - if we won't break Ethereum by a fork in the way) during 100 years in the future to pay to us huge salaries soon.

Common good = future, so in a sense, it is the fairest way to pay salaries we can think of. Let the market decide, not centralized authorities.

Which oracles to use can be decided by global voting (in the future).

To do this I create a market that provides a monetary stimulus for traders to calculate common good producers' salaries.

Because we have 100 years to gather donations, it is reasonable to bequest in addition to donating, so we grab users' wallets who bequests them to us. (Won't users, who don't want to donate, bequest?) It is possible to donate/bequest DeFi tokens with all their future profits.

This PR is a very work-in-progress, I am currently rewriting contracts in https://github.com/vporton/future-contracts dependency to incorporate new ideas. Please comment on contracts. However, the detailed information about the contract logic is not yet published.

I submitted the article about the logic of the contract to a peer-reviewed journal. How do you think, is it is good idea to withdraw my article from there and add it to this pull request instead?

Please comment on my idea, contract details, and philosophy.

I need about $3000 to pay for smart contract audit. [Donate.](https://gitcoin.co/grants/1591/science-of-the-future-the-100-years-forward-plan)

P.S. This PR provides a fairer, because less random and more future-oriented alternative to GitCoin grants.

P.P.S I will write much more on this topic. Now, it is not described well enough, just subscribe to this PR comments!

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/8183

### CODE REVIEW

**Comment by vporton** [comment]
@owocki I've pushed a new version of this pull request. It is almost an MVP, except only:

- audit of smart contracts in https://github.com/vporton/future-contracts
- storing user IDs into the GitCoin DB when a user registers (and showing the registered user info instead of Register button if he or she is already registered)

Please show it to the community. I am most interested in community review of the [smart contracts](https://github.com/vporton/future-contracts).

**Comment by vporton** [comment]
@owocki MVP of Future Salaries!! (except for contract audit)

@owocki Please create a branch.

**Comment by vporton** [comment]
I've added accepting donations in ETH.

**Comment by vporton** [comment]
I've added the whitepaper of the system:
- https://github.com/vporton/gitcoin-web/blob/future/app/assets/docs/science-salaries.odt
- https://github.com/vporton/gitcoin-web/blob/future/app/assets/docs/science-salaries.pdf

Now you can know what I did :-)

**Comment by vporton** [comment]
The UI was much improved:
Screenshot from 2021-01-24 13-42-31

**Comment by vporton** [comment]
The (not audited) MVP for Rinkeby is fully ready! (A thing missing is requesting. There are also some minor errors.)

Please merge this PR to gain the attention of the community with the purpose to acquire people's opinions / ideas / error checking, before we submit it to paid audit and then deploy to mainnet!

GitCoin rocks, **now** GitCoin rocks.

**Comment by vporton** [comment]
@owocki @Kweiss Rinkeby MVP!! Please review the pull request and make design changes, then merge (see above).

**Comment by vporton** [comment]
@owocki @Kweiss 
I've updated
- https://github.com/vporton/gitcoin-web/blob/future/app/assets/docs/science-salaries.odt
- https://github.com/vporton/gitcoin-web/blob/future/app/assets/docs/science-salaries.pdf
The updated version contains the use case and motivation for funding open-access publishers.

P.S. My contracts are to be audited soon. I have already initiated a money transfer to the auditor.

**Comment by owocki** [comment]
Hey Victor, we appreciate you taking the interest in building to extend the gitcoinco/web codebase.

This PR spurred some conversation on our internal team slack, and after reviewing the proposal, we regret to inform you that we have no plans to pursue this functionality anytime soon.  

I dont know if you're building this for us, or for your own needs.  But either way we felt that we should let you remove this ambiguity sooner rather than later, in case this affects how much time you spend on it.  

Thanks
Kevin

**Comment by thelostone-mc** [comment]
Closing this out for now based on above conversation

**Pull request closed without merging**
