### PR TITLE
Reduce logging noise

### LINKED ISSUE #9992: [Sentry] Resolve "could not get issues..."
**Background**
We have some persistent issues being flagged by Sentry that are creating a ton of noise and causing us to max out our issues per month. We want to systematically start resolving these issues to get more value out of Sentry. 

**Link to Sentry error**
"[Could not get issues...](https://sentry.io/organizations/gitcoin/issues/2515419359/?project=1398424)"

### PR DESCRIPTION
**Pull request by nutrina**
##### Description

Reduce severity of log messages in order to reduce noise in sentry.

##### Refers/Fixes

#9992

##### Testing

Has been tested locally

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by thelostone-mc** [comment]
Does this ensure it doesn't pop up on sentry ?

**Comment by thelostone-mc** [comment]
Could we add it to the PR review board as well @nutrina

**Comment by nutrina** [comment]
> Does this ensure it doesn't pop up on sentry ?

Yes, it should not pop up. As far as I know only error logs pop up on sentry.

**Review by gdixon — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
