### PR TITLE
[WIP] Notifications app

### PR DESCRIPTION
**Pull request by octavioamu**
##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)

##### Refers/Fixes

Refs: #2404

### CODE REVIEW

**Comment by octavioamu** [comment]
@Anish-Agnihotri here is the PR to work with I will be updating it so we can work together. Ping me if anything.

**Comment by octavioamu** [comment]
Hey @Anish-Agnihotri any update on this?

**Comment by owocki** [comment]
performance concerns:

* do we do DB queries on every page
* will the DB queries be super slow when inbox table grows (activity feed table size, this is slow)?  do we have approprirate indexes?
* can we turn off longpolling?
* do longpolling/websockets take down gunicorn?  can we move these requests to their own server?

**Comment by octavioamu** [comment]
Moved to #3221 without longpulling and vue.js as discussed

**Pull request closed without merging**
