### PR TITLE
Runs clr calcs more frequently (every 15 mins)

### PR DESCRIPTION
**Pull request by gdixon**
##### Description

This PR updates the crontabs to run the clr calc more frequently (every 15 minutes)

##### Testing

Tested locally

### CODE REVIEW

**Review by zacheryschiller — APPROVED** [review]
LGTM
When we deploy this, let's make sure to watch it for a few hours to make sure it's not taking longer than we expect after many runs.

**Comment by owocki** [comment]
note that i dont think the deploy script automatically installs crontab2 - crontab4 .  youll need to install these manually on the celery boxes once merged in.

**Review by chibie — COMMENTED** [review]
@gdixon just for clarity, shouldn't the slim clr calc be more frequent than full clr calc?

**Review by chibie — APPROVED** [review]

**Review by octavioamu — APPROVED** [review]

**Comment by gdixon** [comment]
> note that i dont think the deploy script automatically installs crontab2 - crontab4 . youll need to install these manually on the celery boxes once merged in.

I've got these installed 👍 

> @gdixon just for clarity, shouldn't the slim clr calc be more frequent than full clr calc?

Yes it should -- I think we can likely deprecate the slim calc now though because its only around 30secs faster than the full calc (when we run it against the end state of one of the gr10 clrs)

**Pull request merged**
