### PR TITLE
add: markdown on statusbox 

### LINKED ISSUE #6307: Support markdown formatting in Gitcoin Grants posts in the Activity tab
It would be great if markdown formatting were supported in Gitcoin Grants posts in the Activity tab. Right now, it ends up looking odd if you try to use multiple newlines and hyperlinks in a post.

Screenshot 2020-03-26 12 03 04

### PR DESCRIPTION
**Pull request by developerfred**
* Lib https://github.com/markdown-it/markdown-it
* import markdown [default python]

##### Refers/Fixes
#6307

### CODE REVIEW

**Comment by developerfred** [comment]
> @developerfred could you add a screenshot/video ?

https://share.getcloudapp.com/jkuKBXNl

**Comment by danlipert** [comment]
Does this render the markdown in the individual status posts as well, or just the preview?

**Comment by developerfred** [comment]
Ok, I change to js and add function parse markdown

**Comment by thelostone-mc** [comment]
@developerfred give us a headsup when those changes are in

**Comment by developerfred** [comment]
@thelostone-mc I already added the script to parse, the next step is to preview it in javascript / jquery

**Comment by danlipert** [comment]
@developerfred I'm not sure what all this PR actually does - from the video you shared it shows a preview of the markdown, but then when you click post nothing happens. Please add a description that describes the expected functionality. Also you should add a note that the code originally comes from https://gist.github.com/hakib/73fccc340e855bb65f42197e298c0c7d

**Comment by thelostone-mc** [comment]
Closing this out for now ! Do reopen when comments are addressed + conflicts are resolved and we can review it again

**Pull request closed without merging**
