### PR TITLE
feat: email design

### LINKED ISSUE #6208: Update weekly email build
@iamonuwa @PixelantDesign 

OLD:
weeklyemail-old

NEW:
weeklyemail-new

### PR DESCRIPTION
**Pull request by developerfred**
*template: email default
* add params: kudos_friday

##### Refers/Fixes
#6208 #6011

### CODE REVIEW

**Comment by owocki** [comment]
got a screenshot? what email clients did u test in?

**Comment by owocki** [comment]
thanks @developerfred - got any screenshots of the emails? 

@danlipert @gitcoinco/engineers i added this to the review board

**Comment by thelostone-mc** [comment]
@developerfred could you throw in the screenshots if this is ready. ?C

**Comment by thelostone-mc** [comment]
Closing this out ! 
@developerfred do reopen this if this PR is still valid and attach screenshots so that it's easier to validate

**Pull request closed without merging**
