### PR TITLE
explorer: updated view

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- updated the #stats secition
- trimmed down the bounty summary text

m

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/601

### CODE REVIEW

**Comment by mbeacom** [comment]
@thelostone-mc I've updated the api to take `bounty_owner_github_username` for bounties and made some adjustments that seem to have resolved the filtering functionality.

**Comment by thelostone-mc** [comment]
Gimme an hour and I'll push in the new changes too!

**Comment by mbeacom** [comment]
@thelostone-mc Thanks!  Just remember to rebase with `master` to pull in the changed to the API, so you can filter by owner handle.

**Comment by thelostone-mc** [comment]
@mbeacom So I've updated the sidebar, to include the new filters
I've added a `console.log()` // To show the `API` URI being generated.

m

**Comment by mbeacom** [comment]
@thelostone-mc If you rebase with `master`, this PR should be g2g 👍 - filter has been added for `fullfiller_github_username`

**Comment by thelostone-mc** [comment]
Removed colon and changed the color to grey as discussed offline with @PixelantDesign 

screen shot 2018-03-15 at 1 25 22 am

**Comment by thelostone-mc** [comment]
@mbeacom Done with this! Tested it out, seems to be working
All design changes done!

Could you pull this in and try it out once ? 
Select one of the filters under  **MyProjects**

**Comment by mbeacom** [comment]
@thelostone-mc Deploying to staging. https://stage.gitcoin.co

**Comment by mbeacom** [comment]
@thelostone-mc I've added `interested_github_username` as a valid param you can pass to the bounties api.

**Comment by thelostone-mc** [comment]
@mbeacom waiting on what all to put there under that filter, then will update it in
PS: could you share the commit where you did that ?

**Comment by mbeacom** [comment]
@thelostone-mc https://github.com/gitcoinco/web/commit/368009587225e46031e2d895b7303b7613665c94

**Comment by thelostone-mc** [comment]
@mbeacom Done all the changes! What do you think ? 
Rebased code and added the changes. MyGitcoin now has radio buttons ^_^

x

**Comment by mbeacom** [comment]
@thelostone-mc Looks like this is failing the eslint check.  Can you `npm run eslint:fix` ?

**Comment by mbeacom** [comment]
@owocki @thelostone-mc One thing I'm noticing here is that we're passing the `coinbase` param with the user's active wallet address.  We might want to update these to no longer pass `coinbase` since we're filtering by `username` for all three of these already.  Currently, if a user creates a few bounties under a secondary wallet, they won't see them until they switch active wallets in metamask.

**Pull request merged**
