### PR TITLE
dashboard: base setup

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Reason for this PR
Rather than working on explorer page and submitting a PR with tons of changes.
I'd wanna break it into batches (small deliverables ) => easier to review and merge

This PR has two commits
- added support for `Muli` font family
- reindent `/explorer` page and added missing closing tag

This would be the first of the series.
Me and  @eswarasai will start on the explorer page soon. Figured I'd get some cleaning up done beforehand to make our work easier

##### Checklist
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
- https://github.com/gitcoinco/web/pull/487

cc: @owocki

### CODE REVIEW

**Comment by owocki** [comment]
i wish there was an easy way to say via github diffs that this is just formatting changes without having to do it line by line :/

this lgtm; @mbeacom ?

**Comment by thelostone-mc** [comment]
@owocki I also added another commit here! 
Just added `Muli` fonts to our code base

**Comment by eswarasai** [comment]
@thelostone-mc -- I've added [`.editorconfig`](https://github.com/gitcoinco/web/blob/master/.editorconfig) to ensure that the spacing issues won't occur in the future and also to follow standard indentation throughout the project. Can you please try to configure your IDE to use the local `.editorconfig` and fix the spacing issues?

cc: @owocki @mbeacom

**Comment by thelostone-mc** [comment]
@eswarasai thoughts on shifting to 2 spaces = 1 tab for html pages ? 
https://github.com/gitcoinco/web/pull/487#issuecomment-368093806

**Comment by eswarasai** [comment]
@thelostone-mc -- Sure. If that's what ideal and preferable, then we can definitely remove `html` from `4-space` indentation.

@owocki @mbeacom -- Any objections here?

**Comment by owocki** [comment]
defer to @mbeacom on this one..  ill do whatever the group does

**Comment by mkosowsk** [comment]
@mbeacom 

Is it in the roadmap to use something like Prettier to codify code formatting?

**Comment by mkosowsk** [comment]
@mbeacom Using Prettier seems relatively straightforward:

1. Install dependencies
2. Configure prettier.rc with JSON of agreed upon styles (bracketSpacing, tabWidth, etc.)
3. I'm using TypeScript so here I use a TSLint but Gitcoin would use an ESLint. Seems that there are some issues with using Prettier and a lint but looks like they're straightforward to resolve: 

https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint

4. Configure .lintstagedrc 
5. Add appropriate scripts to package.json that people can run before submitting PR's
6. Contributors now can write and commit pretty code by just running a script after
 doing their work 😍

Might be interesting to open up to the community what type of standards they think are good to enforce 👍🏻

Think this is a very important topic to tackle so that contributors can focus their energy on more crucial things, like whether or not to use emoji in the codebase. I personally give that idea two 👍 way up!

**Pull request merged**
