### PR TITLE
Rename user-facing instances of 'personal token' to 'time token'

### PR DESCRIPTION
**Pull request by mds1**
Rename "Personal Tokens" to "Time Tokens". To simplify the renaming process, variables, classes, and contracts continue to use the old name, but user-facing text uses the new name. Personal tokens and Time tokens are the same thing, so you will likely see those two phrases used interchangably throughout the codebase.

@thelostone-mc One of the changes is to a migration file `0150_auto_20200904_1505.py`—should this file be changed, or should it be left alone?

### CODE REVIEW

**Review by aamustapha — APPROVED** [review]

**Review by chibie — COMMENTED** [review]
why not replace occurrences of ```ptoken / ptokens``` with ```ttoken / ttokens```  ?  👀

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
@mds1 I'd say let's not update the 0150_auto_20200904_1505! 
Instead create a new migration file 
It makes it cleaner and less messier on stable as 0150 has already been executed in live

**Comment by mds1** [comment]
> why not replace occurrences of ptoken / ptokens with ttoken / ttokens ? 👀

@chibie Just because it's a lot simpler not to! If we rename the variables we have to re-test all the functionality to make sure there's nothing we missed. Additionally, the contracts would have to be redeployed if we also wanted to rename them to be consistent, but at current gas prices that costs over $250 so doesn't seem worth it

>  I'd say let's not update the 0150_auto_20200904_1505!
> Instead create a new migration file
> It makes it cleaner and less messier on stable as 0150 has already been executed in live

@thelostone-mc Just force-pushed with a new commit that doesn't update the migration file. Do we need a new migration though? We only updated user-facing text, not variable names/DB fields, so I don't think we need one!

**Comment by thelostone-mc** [comment]
@mds1 nah it should be fine!

**Pull request merged**
