### PR TITLE
fix for tx's running out of gas

### PR DESCRIPTION
**Pull request by owocki**
gas limit fix.  this is a fix for 

https://github.com/gitcoinco/web/issues/2586

it needs to be tested before deployment.  i can't do that currently bc i have bad internet..

### CODE REVIEW

**Comment by mbeacom** [comment]
Seeing an [out of gas error](https://rinkeby.etherscan.io/tx/0x29f590258542caefdb70a4930d001ba8860c9ca6e25c3f4bf4b2a5d7d1ddfb23) when using this on rinkeby

**Comment by jasonrhaas** [comment]
> Seeing an [out of gas error](https://rinkeby.etherscan.io/tx/0x29f590258542caefdb70a4930d001ba8860c9ca6e25c3f4bf4b2a5d7d1ddfb23) when using this on rinkeby

@mbeacom this was a Kudos Indirect Send right?

**Comment by owocki** [comment]
@mbeacom https://github.com/gitcoinco/web/pull/2656/commits/f93b8345f4daa4fb768716b8c6f8273c0074afce should fix that

**Comment by jasonrhaas** [comment]
Doesn't this line https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/pages/kudos_send.js#L508

already account for the Kudos gasLimit?  It seems like we are sending the gas money twice.  I suppose it's better to have extra gas in there anyway.  We just need to make sure that we return the extra gas money leftover.

**Pull request merged**
