### PR TITLE
WIP grants/index: search functionality

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

WIP

##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

### CODE REVIEW

**Comment by captnseagraves** [comment]
@thelostone-mc Is there anything I can do to help keep this moving?

**Comment by thelostone-mc** [comment]
@captnseagraves I'm a lil confused on how to proceed with this!
If you pull this in you'll notice that the search works but the page refreshes each time the user click on search as opposed to using the the [api](https://github.com/gitcoinco/web/pull/2522/files#diff-3dc4970f50a896f3b3911da07a463c47R66)

I belive @mbeacom had some concerns using the API route , so I'm not too sure on what the right thing to do here is.
Would you have the bandwidth to get that checked out ? 😓

**Comment by captnseagraves** [comment]
@thelostone-mc Sure thing! I'll take a look!

**Comment by mbeacom** [comment]
@captnseagraves This was a WIP? 🤔

**Pull request merged**
