### PR TITLE
Gitcoin Pajamas 

### PR DESCRIPTION
**Pull request by Dgilliams**
##### Description
Organic hand stitched pajamas with the gitcoin logo

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)

##### Affected core subsystem(s)
Avatar builder

##### Testing
tested on chrome using docker and windows 10 pro. 

pjs_1
pjs2
pjs3
pjs4
pjs5
pjs6

### CODE REVIEW

**Comment by owocki** [comment]
@Dgilliams - the hero we need.  the hero we deserve

**Comment by owocki** [comment]
hmmm i dont see this on the avatar builder even after deploying https://gitcoin.co/onboard/profile/?steps=avatar#section-title

**Comment by mbeacom** [comment]
Looks like it's there 🤔 

screenshot 2018-11-21 12 58 58

**Comment by owocki** [comment]
oh thx, i must have missed it..

**Pull request merged**
