### PR TITLE
Grants 15 updates to homepage

### PR DESCRIPTION
**Pull request by giliomeejg**
##### Description

Change homepage banner to make it more focusses on GR15.  Note the scalable background required a hack in order to make things more responsive.

https://youtu.be/9nGxjAOSmJQ

### CODE REVIEW

**Review by schultztimothy — APPROVED** [review]
LGTM

**Review by kevinrolsen — APPROVED** [review]
lgtm

**Comment by thelostone-mc** [comment]
Hmm @nfrgosselin  this PR looks alright but the slider piece was something which had been built out for GR15.
Are we sure we are good removing the feature / changing the structure ? 

@giliomeejg

**Comment by giliomeejg** [comment]
> Hmm @nfrgosselin this PR looks alright but the slider piece was something which had been built out for GR15. Are we sure we are good removing the feature / changing the structure ?
> 
> @giliomeejg

I was unaware of the slider piece that was worked on before and am not aware of any specific content that would warrant a 2nd slide.

**Review by thelostone-mc — APPROVED** [review]

**Pull request merged**
