### PR TITLE
Tasteful animation for Bounties Logo on Hovering

### LINKED ISSUE #5824: add a hover animation to the hackathon/bounties logos
the scope of this issue is to add a hover animation to the hackathon/bounties logos (like exists for the kudos, quests, and grants logos in the nav)

please make it tasteful!  post a screenshot to submit the bounty

### PR DESCRIPTION
**Pull request by molecula451**
##### Description

Some cool animation for the logo when hovering on the Bounties. May have some more fun as soon as feedbacks

logobounties

logo

https://codepen.io/molecula451/pen/NWPOwGg

##### Refers/Fixes

#5824 

##### Testing

Brave Browser

### CODE REVIEW

**Comment by molecula451** [comment]
no clean branch because contains some files that has not yet been merged

**Comment by owocki** [comment]
the gfx look interesting.  branch history needs cleanup tho!

**Comment by molecula451** [comment]
@owocki I will make sure repo is clean and provide some more animation. Assign the task to me when possible

**Comment by molecula451** [comment]
Just remove unnecesary files for this branch. I had to due this way since uploads images are disabled on main repo to be able to propose file change.

**Comment by molecula451** [comment]
bounties_desktop

heartbeating colorful robot animation for the bounties

**Comment by danlipert** [comment]
@molecula451 The codepen you posted looks different than the animated gifs I'm seeing here - is that just an old version or something like that? Appreciate all the documentation

**Comment by molecula451** [comment]
@danlipert No, the document it's me just having fun with the .svg while the animation requires more than just coding the svg and then convert it to gif...

**Comment by danlipert** [comment]
@molecula451 I see, thats cool. I'm not sure what you are talking about regarding the request to fix the branch history, also why are some files getting removed as part of this PR from the docs folder? Since this PR doesn't seem to actually change anything, I think you should close this out and just post the gifs in our community slack, and ping our designers @PixelantDesign and @willsputra

**Comment by molecula451** [comment]
@danlipert It's because my repo contains files from a Open PR it was expected to be reviewed but only approved by lostone #5607 and the animations are for the bounty #5824 and to submit the files. If the PR it's not necessary I can proceed with what you asking for

**Comment by molecula451** [comment]
I will appreciate your feedback guys so I can close this out

**Comment by owocki** [comment]
i think a clean branch history is a must to close out the PR.  i'd also like to see a screencap of what it looks like actually on the site

derp i just did it myself.  yolo https://bits.owocki.com/Z4uw4wZK

62aeafda747ddebd9192e5a1487910e64c2bd570 commits it to the codebase.. @molecula451 pls DM me on gitcoin.co/chat when u have some hackathon logo hover animations i can play with.  once we get those in i will pay u out

**Pull request closed without merging**
