### PR TITLE
Alert user if insufficient tokens for tip

### LINKED ISSUE #2250: bug (er... UX thing) -- tips flow should warn you when u dont ahve enough ERC20 tokens to send tip
bug (er... UX thing) -- tips flow should warn you when u dont ahve enough ERC20 tokens to send tip

https://github.com/embark-framework/embark/issues/761#issuecomment-423005979

a fixer could perhaps copy how this works in the bounty flow https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/pages/new_bounty.js#L436-L446

### PR DESCRIPTION
**Pull request by dylanjw**
##### Description

See https://github.com/gitcoinco/web/issues/2250

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)

##### Affected core subsystem(s)

ui

##### Testing

I tested locally with docker.  I both test the validation message on sending a tip, and on submitting a bounty.

##### Refers/Fixes

Fixes #2250

### CODE REVIEW

**Comment by dylanjw** [comment]
@thelostone-mc The CI is throwing the following error:

```
django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0012_merge_20190221_2246, 0014_matchpledge in grants).
E           To fix them run 'python manage.py makemigrations --merge'
```

I dont think this is related to the changes in the PR.

**Comment by thelostone-mc** [comment]
@dylanjw My bad ! I'll fix up travis ^_^
Could you throw in a recording of the PR ?

**Comment by owocki** [comment]
migration issues have been resolved upstream

**Comment by dylanjw** [comment]
After testing this again recently it looks like there has been a regression with Eth based tips.  When I first worked on this, I think insufficient Eth had a warning already, and I just needed to implement the alternative token warning. Now Im only getting the warning for the alternative token.  I will include a fix for the insufficient Eth in this PR.

**Comment by dylanjw** [comment]
The regression when sending an ETH tip looks a little deeper than I anticipated.  I opened this issue: https://github.com/gitcoinco/web/issues/3877.

Im surprised by that issue, because there looks like a lot of areas where that issue could be breaking things.

**Comment by dylanjw** [comment]
While it is decided if #3877 is a bug or not, I have updated this PR to normalize 0x0 to the full length address.

Here are screenshots of the tip error message displaying with Eth and with an alternate token:

screenshot from 2019-03-05 14-42-15
screenshot from 2019-03-05 14-42-57

**Comment by thelostone-mc** [comment]
@dylanjw will test this out but could you fix the CI errors ?

**Comment by dylanjw** [comment]
@thelostone-mc Im getting a CI from the code coverage calculation.  The file with the change is coverage looks unrelated to my changes.

**Comment by dylanjw** [comment]
@thelostone-mc Ready to merge

**Pull request merged**
