### PR TITLE
Make transaction link in waiting state page obvious

### PR DESCRIPTION
**Pull request by arku**
##### Description

The transaction link in the waiting state isn't obvious as there's no visual cue that it's a link. This PR improves the UX by adding an underline style to the link.

##### Before

image

##### After

image

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

/cc @PixelantDesign

### CODE REVIEW

**Comment by PixelantDesign** [comment]
Hey @arun1595  why does that first line need an underline?

**Comment by arun1595** [comment]
@PixelantDesign To provide a visual cue to the user that it's a link and not just plain text.

**Comment by PixelantDesign** [comment]
I think we are mixing informational text with an action. If we should show a link to the etherscan in progress, let's break it out and put it above the GitHub url.

cc: @arun1595 @thelostone-mc

**Comment by mbeacom** [comment]
:star: PR built and available in a preview environment **gitcoinco-web-pr-2134** [here](http://web.jx-gitcoinco-web-pr-2134.ci.gitcoin.co)

**Pull request merged**
