### PR TITLE
Fixes: https://github.com/gitcoinco/web/issues/1048

### PR DESCRIPTION
**Pull request by bakaoh**
##### Description
 Add 'info' tooltip to make it clear which information is public or not

##### Checklist
- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
No

##### Testing
Local test

##### Refers/Fixes
Fixes: #1048

### CODE REVIEW

**Comment by owocki** [comment]
@bakaoh  @PixelantDesign did you mean to close this without review?

i see a work submission on gitcoin from @bakaoh so just trying to figure out what to do with it

**Comment by PixelantDesign** [comment]
Hmm... I must have closed on accident. I don't have anything waiting for my review.

**Comment by thelostone-mc** [comment]
@PixelantDesign no worries  :)

@bakaoh could you throw in a screenshot to make review easier  ? 
Also we've got a few conflicts -> could you resolve them ^_^

**Comment by bakaoh** [comment]
@thelostone-mc -- here is screenshot
screenshot from 2018-05-11 10-47-11

Look like the conflicts is because someone add the checkbox in place i add the tooltip. Don't know what you want to keep

**Comment by thelostone-mc** [comment]
> Edit: it comes from #1097 so i think @owocki decided to use checkbox. It's seem this pr is not necessary anymore

@owocki safe to close ?

**Comment by owocki** [comment]
checking this out now

**Comment by owocki** [comment]
yes i think so!  @bakaoh ill send you a tip for your efforts now

**Pull request closed without merging**
