### PR TITLE
Add psql persistence and remove redundant services

### PR DESCRIPTION
**Pull request by mbeacom**
The goal of this PR is to remove redundant service containers to reduce the local stack footprint and provide data persistence for the PostgreSQL instance via a data volume.

### CODE REVIEW

**Comment by owocki** [comment]
nice!  will test tomorrow

**Comment by owocki** [comment]
got caught up today with all the things. planing on testing tomorrow

**Comment by owocki** [comment]
Thanks again.  Clearly i dont know docker as tight as I should

**Comment by mbeacom** [comment]
Haha.  No problem!

**Pull request merged**
