### PR TITLE
Ratings Sections

### LINKED ISSUE #5619: Ratings Section [Work submmited] issue
**Describe the bug**

There is an issue I am seeing on the <code>gitcoin.co/username/ratings</code> section where I have applied to work/contribute on some bounties and I have actually submmited any work. And it does look like if I have actually worked and submmited one.

The two bounties that are in yellow are not expected to be there. The bounty that is in green it's was actually submmited so that's good.

**To Reproduce**

Apply for a work, don't work on the bounty and don't submit any work. It should still there like if you have submmited a work

**Expected behavior**

On the ratings sections [Work Submmited] make only appear bounties that you have actually worked and submmited work and work was done.

**Screenshots**

issue

**Desktop (please complete the following information):**

- OS: Win32
- Browser: Brave Browser
- Browser Version: Chromium

### PR DESCRIPTION
**Pull request by molecula451**
##### Description

Instead expecting the bounty to be "done" and the user getting a feedback Request in [Work Submmited]. When the bounty turns [Work Submmited] It will ask the user for ratings in the [Work Submmited] Sections

##### Refers/Fixes

#5619 

##### Testing

Tested and it's working locally

submitted

submit

### CODE REVIEW

**Comment by molecula451** [comment]
the great @octavioamu :)

**Comment by octavioamu** [comment]
@molecula451 is this ready or something is missing?

**Comment by octavioamu** [comment]
> @molecula451 is this ready or something is missing?

@molecula451 yes or no?

**Comment by molecula451** [comment]
> @molecula451 is this ready or something is missing?

I think this is a good solution to the problem. It will mostly ask for feedback on **[Work Submmited]** works instead of asking anytime for feedback even if you don't submit any work, just because you "applied"

**Comment by octavioamu** [comment]
@molecula451 be aware if you left prs in draft or [WIP] then yes we are not going to review it, Think we are 3 devs reviewing all the PRs so we can't get on each of your PRs to guess if they are ready or not. 
If you want a more agile review then make your part.

**Comment by molecula451** [comment]
> @molecula451 be aware if you left prs in draft or [WIP] then yes we are not going to review it, Think we are 3 devs reviewing all the PRs so we can't get on each of your PRs to guess if they are ready or not.
> If you want a more agile review then make your part.

Absolutely agree on your positiveness octavio thanks for clarifying everything honest. This will only make myself work in a sort better way for the whole repo and with you guys

**Pull request merged**
