### PR TITLE
adds tabs to the profile to reduce information overload & complexity; also introduces scalable way (tabs) to build profiles out further

### PR DESCRIPTION
**Pull request by owocki**
##### Description

adds tabs to the profile to reduce information overload & complexity

##### Refers/Fixes

self

##### Testing

# my profile

Screen Recording 2019-07-17 at 10 23 AM

# org profile

Screen Shot 2019-07-17 at 10 23 08 AM

# not found profile

Screen Shot 2019-07-17 at 10 22 58 AM

### CODE REVIEW

**Comment by owocki** [comment]
current bounties, past bounties, who you've worked with.. could all be interesting tabs.

**Comment by vs77bb** [comment]
> current bounties, past bounties, who you've worked with.. could all be interesting tabs.

@owocki Agree with all these. Testimonials, in the future, maybe? 

Re Org view, breaking it down into 'Current Bounties' / 'Past Bounties and clearing out a lot of the noise on all of the user actions (applications / start work / submit work) would make a big difference and would solve a funder need per this note from Arweave

image

**Comment by danlipert** [comment]
@owocki whats up with the wonky commit history? Was this branched from master or stable? Looks like it maybe has the wrong base

**Comment by owocki** [comment]
ive got some work to do withi product on definining the direction on profiles.. will re-open this if/when that needs to be done

**Comment by thelostone-mc** [comment]
Closing this out cause our profile is evolved into something way cooler :D

**Pull request closed without merging**
