### PR TITLE
Update to Add styles and  Hackathon project page

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
Original work Hackathon Project Page #6297

Minor error fixes and fix styles on the mobile view.

image

image

To move this fast I fixed some error on indexing and also fix some styles on mobile view, thanks to @walidmujahid for his awesome work on this feature.

### CODE REVIEW

**Comment by walidmujahid** [comment]
Make a PR against my branch and I will merge it. I have yet to update with master yet, but will do so later today.

**Comment by walidmujahid** [comment]
I have cherrypicked 6ce47947b6d34d06848f859a9be7428e759fe664 into my PR. 

As for commit 75281b65affda7f3c7670cdb4da9a83252658ad4 I am not quite sure what is happening. If teh SVG is being deleted, which I understand since it is unused, the linked asset should not changed from PNG in the template.

**Comment by walidmujahid** [comment]
cherrypicked 75281b65affda7f3c7670cdb4da9a83252658ad4 and  df3baf3f4beb195b0a68c339f8c54c252751e2ed into b24217b3fec6e5ae69a430a07d8bff71b737bd55

**Comment by thelostone-mc** [comment]
@zoek1 + @walidmujahid can this be closed out ?
since 6297 has all the commits ?

**Comment by walidmujahid** [comment]
@thelostone-mc Yes, 6297 has all the commits.

**Comment by PixelantDesign** [comment]
Thanks @zoek1!

**Comment by androolloyd** [comment]
@zoek1 can we sort out travis?

**Comment by walidmujahid** [comment]
> @zoek1 can we sort out travis?

Everything is sorted on the original PR @androolloyd https://github.com/gitcoinco/web/pull/6297

**Comment by zoek1** [comment]
Sure, give a moment

**Comment by zoek1** [comment]
Perfect @walidmujahid integrated my changes :raised_hands:  Lets with #6297!

**Pull request closed without merging**
