### PR TITLE
WIP - Add documentation for dynamic widgets

### LINKED ISSUE #354: as a website mantainer, i want a javascript widget that can show off my bounties, so i can lead more of my community to gitcoin
what : a javascript widget (or image) that let me show off the bounties on my repos

please reuse the design from https://github.com/gitcoinco/web/pull/644/ , but implement it in javascript to be responsive instead of as an embedded image

37573585-266c9b1a-2adf-11e8-8484-50aced6a8bae

### PR DESCRIPTION
**Pull request by matthewlilley**
##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
#354

### CODE REVIEW

**Comment by matthewlilley** [comment]
@mbeacom Great.

Now just to wait and see what @owocki wants to do with including it. I suggested a separate gitcoin-js-sdk repo to allow including the sdk directly into your application, as mentioned in the docs.

**Comment by owocki** [comment]
https://gitcoin.co/sdk.js seems to 404 when I try to access  it?  should that sdk js be PR'd as part of this?

**Comment by owocki** [comment]
RE: sdk.js im assuming its something that was developed as part of the bounty?  but i dont know where the code for it is

**Comment by owocki** [comment]
per https://github.com/gitcoinco/web/issues/354 i assume this is sdk.js? https://stackblitz.com/edit/js-nkwz7t?file=sdk.js

**Comment by matthewlilley** [comment]
@owocki Yes.

**Comment by mbeacom** [comment]
@matthewlilley Would you mind adding the sdk.js to this PR?

**Comment by matthewlilley** [comment]
@mbeacom Yes. Sorry I thought I was waiting for an answer on something here. Shall I just peel it back to the same standard as you are using for assets/v2 and pop it in there? 

One point. For some of the documentation I wrote to be correct, it should be requirable as a desperate package via npm.

**Comment by owocki** [comment]
> Shall I just peel it back to the same standard as you are using for assets/v2 and pop it in there?

yes pls!

> For some of the documentation I wrote to be correct, it should be requirable as a desperate package via npm.

i dont have any experience with the npm packaging system.  is it easy to do?  happy to throw in a tip to make it worth your while

**Comment by matthewlilley** [comment]
@owocki I've updated the documentation to include a CDN source via unpkg. Package is published on npm as "gitcoin-sdk", and github repo is here, https://github.com/matthewlilley/gitcoin-js-sdk. We'll need to transfer it over to the gitcoin org and update the package json with repo name.

**Comment by mbeacom** [comment]
@matthewlilley Would you mind PRing this back in a subdirectory? Maybe: `js-sdk/` in the root dir?

**Comment by matthewlilley** [comment]
@mbeacom You should be able to add it to the package.json now, and require it that way. Once your build system is wired up completely, you can include it in the build and serve from this repo itself.

**Comment by mbeacom** [comment]
@matthewlilley Yeah, I gotcha on that. Thanks. I was planning on setting that up a build/publish step in our pipeline once the source is in place.

**Pull request closed without merging**
