### PR TITLE
adds wiki

### PR DESCRIPTION
**Pull request by IntoThe1337ness**
##### Description

this adds django wiki so it Is Easy to create documents as community.

##### Refers/Fixes

https://gitcoin.co/townsquare?tab=activity:133048

##### Testing

I tested.  Here is what looks like

screencapture-localhost-8000-docs-2020-02-19-20_36_59

### CODE REVIEW

**Comment by owocki** [comment]
thanks for reading the thread & taking this up.  im pretty excited to allow the community to write their own guides about gitcoin (and finally deprecate http://gitcoin.co/help )

some content we could build on top of a wiki:

i just got here, now what
how do i maximize my gitcoin grants impact?
how do i use gitcoin to X (for X = find coders, find work, earn $$, etc)
what are all the things gitcoin does?
how the @#^@ does CLR work :joy:
there’s so many things to do, where do I start - building this out in emails - take a new action that leads them down a new flow (weekly?)
start / stop / submit work

**Comment by owocki** [comment]
can we move the path from `/docs` to `/wiki` to avoid confusion with docs.gitcoin.co?

**Comment by IntoThe1337ness** [comment]
@owocki OK DONE

**Comment by owocki** [comment]
thanks @IntoThe1337ness !

**Pull request merged**
