### PR TITLE
[WIP] fix: new bounty invite user search 

### PR DESCRIPTION
**Pull request by developerfred**
#6013

## Result
Captura de Tela 2020-02-28 às 10 59 44

## Movie
https://youtu.be/DIqp_6FE8eI

### CODE REVIEW

**Comment by octavioamu** [comment]
this one is ready for review?

**Comment by developerfred** [comment]
> this one is ready for review?

No, i'm having some problems when i try to get the keywords of an issue from github.

**Comment by thelostone-mc** [comment]
@developerfred let us know when this is good for review

**Comment by developerfred** [comment]
Yes, @thelostone-mc

**Comment by thelostone-mc** [comment]
@developerfred marked this as draft ! Once @octavioamu comments are addressed 
mark it as ready for review

**Comment by thelostone-mc** [comment]
Closing this out for now ! @developerfred do raise a PR whenever you get around to addressing the comments

**Pull request closed without merging**
