### PR TITLE
Enhancement: Apply new design to townsquare

### LINKED ISSUE #5838: Apply New Design to Town Square
Townsquare

Scope of this task: Apply New Design to the homepage on gitcoin.co

Requirements
- GOOD PR by EOD Monday (2 days)
* Works in responsive contexts (mobile, tablet, desktop)

### PR DESCRIPTION
**Pull request by mul53**
##### Description
Adds new user interface design to townsquare.

##### Refers/Fixes
Fixes #5838

### CODE REVIEW

**Comment by mul53** [comment]
@owocki, currently there is the post message button which initiates a dialog. Should that be replaced?

**Comment by danlipert** [comment]
@mul53 can you post some screenshots, or even better, a video walkthrough of the new design? Thanks!

**Comment by owocki** [comment]
a few things i noticed from pulling it down
1. sidebar on left should highlight which tab ur currently on
2. responsiveness works good!
3. daily/weekly actions not clickable. search button not working
4. feed doesnt load on first pageview... i seem to ahve to refresh a few times

**Comment by mul53** [comment]
@owocki i will work on that, @danlipert let me make the changes described then i will post a video walkthrough.

**Comment by octavioamu** [comment]
@mul53 How is going? we have some eta on this? Asking to start doing some related work.

**Comment by mul53** [comment]
@octavioamu currently working on fixing the search then 4 on @owocki list, then i'm done with the changes i need to make.

**Comment by octavioamu** [comment]
Cool, can you fix the conflict so I can base my pr from yours?

**Comment by mul53** [comment]
@octavioamu i have fixed the merge conflict

**Comment by mul53** [comment]
Screenshot from 2020-01-30 11-25-58
Screenshot from 2020-01-30 11-26-49
Screenshot from 2020-01-30 11-26-55
Screenshot from 2020-01-30 11-27-00

**Comment by owocki** [comment]
@mul1sh looks like theres more merge conflicts..

for the search bar... just use the same logic thats on the existing search bar https://bits.owocki.com/nOumjnj1

@octavioamu how close is this to mergeable?  trying to get my design off the town square in prod as imminentlaly as possible..

**Comment by mul1sh** [comment]
@owocki  I think you mean't @mul53 not me 😄

**Comment by octavioamu** [comment]
I see there still work todo on the search comments part. I think is kind of diff compared to the general search.

Also as we added a lot of features to townsquare there are a lot of conflicts + stuff without design.

**Comment by owocki** [comment]
bummed this didnt make it into deploy today..

@mul53 can u take another pass at this today pls?:

**Comment by mul53** [comment]
I definitely will, gimme a few hours

**Comment by mul53** [comment]
@owocki i have added the new search logic and fixed the conflict

**Comment by owocki** [comment]
the town square looks great.. but 

1. seems like this broke the feed on the user profile https://bits.owocki.com/NQuvyojN
2. on grants page  https://bits.owocki.com/Z4uwWKmQ
3. on the /activity page https://bits.owocki.com/E0uEwAX0

i'd recommend leaving the old styles in place for these 3 files, then making the new css apply on the town square page

also the logo in the top left seems misaligned (too close to bottom) https://bits.owocki.com/p9u50A4p

other than that this LGTM!

**Comment by owocki** [comment]
https://bits.owocki.com/YEud7Dgq

on the right side in the design theres diff icons by action type.. would be good to get this to match the design.

**Comment by mul53** [comment]
Working on this right now

**Comment by owocki** [comment]
@thelostone-mc @octavioamu worth sharing you8r PR to prevent du8plicate work?? https://github.com/gitcoinco/web/tree/improv/townsquare-ui

**Comment by octavioamu** [comment]
@mul53 and @owocki as we are integrating to the current core work I considerate this PR done, I recommend not doing here any other changes because we are already detached from here. We are going to merge the branch we are preparing with this and others changes in a few days.
Thanks @mul53 for the work!!!

**Comment by owocki** [comment]
kewl can we get a WIP PR for that branch?  

shortly thereafter that branch is merged im gonna want to get https://github.com/gitcoinco/web/pull/5898 and https://github.com/gitcoinco/web/pull/5884 in

**Comment by octavioamu** [comment]
cool I will do a PR so everyone can check. Probably we will need some work for those branchs too.

**Comment by thelostone-mc** [comment]
@mul1sh + @owocki + @octavioamu  -> the PR is open over at https://github.com/gitcoinco/web/pull/5968

Closing this out !
Nice job on the PR @mul1sh

**Comment by mul53** [comment]
@thelostone-mc name mix up, its @mul53

**Comment by thelostone-mc** [comment]
LOL DERP DERP :P My bad 😂

**Pull request closed without merging**
