### PR TITLE
Support multiple Web3 wallets

### LINKED ISSUE #5909: BOUNTY - Integrate Fortmatic into Gitcoin
The scope of this bounty is to integrate formatic into Gitcoin

The winning submission for this bounty will have integrated Formatic into Gitcoin and will have tested locally
1. Send Tip
1. Receive Tip
1. Create Bounty 
1. Payout Bounty
1. Submit Bounty
1. Create Grant
1. Fund Grant
1. Send Kudos
1. Receive Kudos

on Google Chrome without Metamask.  Additionally we would like to have the following browsers tested (albeit with a lighter test footprint)
1. Brave
2. Safari
3. Edge

The winning submission will have updated all references to Metamask to 'Your Web3 Wallet'

The winning submission must be complete within 2 weeks of worker acceptance.

### LINKED ISSUE #5954: Add Authereum Support
Integrating [Authereum](http://authereum.com/) will allow users to use Gitcoin with free transactions. New users can sign up in seconds and won't be required to download anything. Also, users can purchase DAI instantly with a debit card and can contribute to grants without needing ETH in their wallet.

More information on integration can be found here: http://docs.authereum.com/
If you're considering supporting multiple non-injected wallet providers, I'd recommend looking into one of the following solutions:
https://www.blocknative.com/onboard
https://github.com/NoahZinsmeister/web3-react (best for custom UIs)
https://github.com/web3connect/web3connect

The scope of this bounty is to integrate Authereum into Gitcoin

The winning submission for this bounty will have integrated Authereum into Gitcoin and will have tested locally
1. Send Tip
1. Receive Tip
1. Create Bounty 
1. Payout Bounty
1. Submit Bounty
1. Create Grant
1. Fund Grant
1. Send Kudos
1. Receive Kudos

on Google Chrome without Metamask.  Additionally we would like to have the following browsers tested (albeit with a lighter test footprint)
1. Brave
2. Safari
3. Edge

The winning submission will have updated all references to Metamask to 'Your Web3 Wallet'

The winning submission must be complete within 2 weeks of worker acceptance.

### PR DESCRIPTION
**Pull request by KiChjang**
* Vendor Web3Connect, Fortmatic and Authereum into frontend code
  * Ensure Send Tip user flow works
    - Refactor web3.eth.coinbase and web3.eth.accounts to use their
      corresponding async API counterparts

##### Description

Allow user to choose the web3 wallet to connect to Gitcoin with.

##### Refers/Fixes

Fixes #5954, fixes #5909.

##### Testing

Manual smoke testing has been done on the following flows:

1.    Send Tip
2.    Receive Tip
3.    Create Bounty
4.    Payout Bounty
5.    Submit Bounty
6.    Create Grant
7.    Fund Grant
8.    Send Kudos
9.    Receive Kudos

### CODE REVIEW

**Comment by KiChjang** [comment]
I've added the ability to select your wallets via the network button:

image

**Comment by danlipert** [comment]
@KiChjang excited for this! Let us know when its ready for review

**Comment by faridrached** [comment]
@KiChjang btw, in the past we made a Gitcoin themed modal; we can deploy that if you send me the test and live api keys which you can find in the Fortmatic dashboard. Feel free to dm me on Telegram @faridrached or email me on farid@fortmatic.com. Thanks!

**Comment by KiChjang** [comment]
@danlipert Sorry I wasn't clear; this is ready for review.

@faridrached I am currently using my own personal test and live API keys on Fortmatic, and I'm suspecting that I should use the one for gitcoin instead? If so, then gitcoin would have to provide one.

**Comment by faridrached** [comment]
> @faridrached I am currently using my own personal test and live API keys on Fortmatic, and I'm suspecting that I should use the one for gitcoin instead? If so, then gitcoin would have to provide one.

Yes, its wiser if someone from Gitcoin creates an account and shares the key indeed.

**Comment by owocki** [comment]
@KiChjang ill create my own key for the gitcoin production deployment. just make it configurable in the .env file (thats where we store secretse on the gitcoin app)

> Manual smoke testing has been done on the following flows:

its such great to see that you've done this testing.. yay!  did u test in chrome/metamask?  brave? safari?

**Comment by KiChjang** [comment]
@owocki I actually did my testing on Firefox, because that's the only browser that didn't have any issues with the Authereum integration. The specific issued I encountered while testing Authereum on Chrome is that `window.crypto.subtle` is disabled on non-HTTPS pages except on `localhost`, and since I use WSL for local development, the docker container I connect to isn't `localhost` but a randomly assigned internal IP. Firefox is the only browser that still allowed `window.crypto.subtle` to be accessed even when I'm not connecting to `localhost`.

I'll push a commit up soon to make it configurable via `.env`.

**Comment by faridrached** [comment]
>  I actually did my testing on Firefox

Hi @KiChjang curious if you also tested Fortmatic on the mentioned browsers?

**Comment by octavioamu** [comment]
Tested on my local but didn't worked. 
I just tried to send a tip on townsquare and metamask never prompted
When reloading the home page is asking to connect a wallet even if I'm not logged, we want to support multiple chains so people need to be able to navigate the site even without wallet, and asked when just trying to interact with blockchain.
web3 browser support also is not working also.

**Comment by KiChjang** [comment]
@octavioamu Ah, sending tips through townsquare is a flow that I didn't test, but I tried to dig into it and find the root cause, and it looks like to me that the API call to `/tip/send/3` is returning 500. Did you also encounter this error?

**Comment by KiChjang** [comment]
@octavioamu I did a rebase to master on this PR and the Send Tip flow should work as intended. Please re-review.

**Comment by KiChjang** [comment]
@faridrached I've tested Fortmatic on Firefox only, and everything worked fine.

**Comment by faridrached** [comment]
Good to hear that @KiChjang. Any blockers left?

**Comment by owocki** [comment]
is this ready to get into the PR review queue?

**Comment by owocki** [comment]
fyi its still marked as 'waiting on contributor' there..

**Comment by KiChjang** [comment]
I've asked for a re-review and had been waiting on it.

**Comment by owocki** [comment]
ill move it to the core team test column

**Comment by owocki** [comment]
@danlipert heads up this has been moved to your testing column on the pr review board

**Comment by danlipert** [comment]
hey @KiChjang would you mind resolving the conflicts and rebasing on latest master? thanks!

**Comment by KiChjang** [comment]
@danlipert it's rebased

**Comment by owocki** [comment]
@KiChjang @faridrached  looks like this has been merged. we should get it testeed to make sure no regressions + looks good then maybe start doing some marketing :)

**Comment by faridrached** [comment]
Great job. As soon as its ready to go in production, then lets definitely market it!

**Pull request merged**
