### PR TITLE
[WIP] #4394 - Add meta data

### PR DESCRIPTION
**Pull request by kuhnchris**
WIP #4394

### CODE REVIEW

**Comment by danlipert** [comment]
@kuhnchris is this ready to be merged? If so, please remove the WIP label and add a description to the PR - thanks!

**Comment by kuhnchris** [comment]
Ah, I just saw, for some reason my 2nd PR didn't get in here? That's weird.
I have to add the 2nd batch of changes after your PR guy did a revision, I'll add it when I return

**Comment by Ricardo386** [comment]
Koe Fred, cada o aplicativo? Cadê o nosso dinheiro? Como tu some e não responde as pessoas que acreditaram em vc. Qual foi do bagulho? Tu fez tudo isso pra roubar a gente mesmo?

Koe Fred, each application? Where's our money? How you disappear and don't answer the people who believed in you. What was the stuff? You did all this to steal from us

**Comment by owocki** [comment]
@Ricardo386 i think you've got the wrong PR.

**Comment by kuhnchris** [comment]
Yap, no idea what you are talking about @Ricardo386

**Comment by PixelantDesign** [comment]
@kuhnchris any updates on this one?

**Comment by kuhnchris** [comment]
Ahhh! That one was open, my bad!

**Comment by thelostone-mc** [comment]
@kuhnchris still in WIP. worth opening a draft PR instead ?

**Comment by kuhnchris** [comment]
the problem is, there has been a couple of changes already, more precise: the inclusion of H1 and some more changes on explorer. I need to reevaluate the current branch to see where we are at with this.

**Comment by thelostone-mc** [comment]
@kuhnchris wanna try and getting this in / should we close this out ?

**Comment by kuhnchris** [comment]
I think at this point we can kill it.

**Pull request closed without merging**
