### PR TITLE
#4745: Surface re-marketed issues to the top of the issue explorer

### PR DESCRIPTION
**Pull request by vince0656**
##### Description

Changes meet the requirements detailed in issue #4745. The new code adds the ability to re-market issues that have been abandoned or had all workers rejected. When issues are re-marketed, the new code surfaces the issue to the top of the issue explorer under a new default sorting option ‘Last Marketed’. In addition, the new code will:
-Not allow a funder to market an issue more than twice
-Send a slack notification to #notif
-Re-order buttons on the bounty details page into a more convenient drop down

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/4745

##### Testing

Appropriate unit tests have been included

##### Video demonstration

https://drive.google.com/open?id=1J_eGGdcepsupj6yx3KYV1WqHUmcFR2Lv

Please bear in mind that my laptop slowed down during recording which is why the first re-market took a while to kick in :)

### CODE REVIEW

**Comment by vince0656** [comment]
Reason for travis failure: 

E           django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0043_auto_20190724_1507, 0042_auto_20190718_1749 in dashboard).
E           To fix them run 'python manage.py makemigrations --merge'

**Comment by vince0656** [comment]
Whilst trying to record a video of my feature working in action, I found a bug which prevented me from loading the bounty details page. Bug was introduced in #4775 on line 135 and 152 of app/assets/v2/js/pages/bounty_details.js - I have fixed this in the latest push

**Comment by vince0656** [comment]
@thelostone-mc I have addressed all points in your comment and have attached a link to a video demonstrating the new feature. 

Any further questions, please don't hesitate to ask

**Comment by PixelantDesign** [comment]
Looking great @vince0656! 

My only change request is on the confirmation banner. Please update to:

Your issue has been remarketed. The issue will appear at top of the issue explorer. You will be able to remarket this bounty one more time if a contributor does not pick this up.

Thanks! Please let me know once this copy is in!

**Comment by vince0656** [comment]
@PixelantDesign the copy changes you requested have been pushed in the latest commit. 

Thanks,
Vincent

**Comment by vince0656** [comment]
@PixelantDesign build issues have now been rectified

**Comment by PixelantDesign** [comment]
Great! @thelostone-mc will you take a look please? Thanks!

**Comment by vince0656** [comment]
@thelostone-mc I am just in the process of resolving the conflicts that will block merging

**Pull request merged**
