### PR TITLE
Issue 5578 chat page

### LINKED ISSUE #5578: CODE - As a Gitcoin user, there's a new chat? Where, why, and how can I get access?
### User Story

As a Gitcoin user, there's a new chat? Where, why, and how can I get access? This is the design of the chat landing page.

### Why Is this Needed

With the upcoming release of Mattermost Gitcoin chat, we'll be migrating our hackathon Discord chats and also slowly closing out our Slack community chat in favor of our own hosted Gitcoin chat. 

As we make the transition, there needs to be a page explaining the new chat system, a web-window for people to chat in that don't have the web/mobile app yet, as well as easy-access to the web & mobile download links. Transparency and marketing for this new chat will be groundbreaking so we want to make sure we have a nice landing page so everyone can get onboarded.

### Description

gitcoin.co/slack is the current "chat" page, we want to make gitcoin.co/chat the landing page
gitcoin.co/chat/web will be the in-browser chat window
if they have not joined gitcoin yet, then gitcoin.co/chat should lead to gitcoin.co/chat/login?

on the landing page we should have:

1. copy as to how the gitcoin community how has chat and why we're moving over (advanced functionality, in-app, future integrations with gitcoin products)

2. shows how many people are online now!

3.  links to download the desktop & mobile standalone versions
from my perspective it should just talk briefly about how the gitcoin community has chat (and maybe X ppl are online now) and have links to web/desktop/mobile experiences

gitcoin.co/chat redirects to a landing page gitcoin.co/chat/login

### Current Behavior

no design for chat landing page

### Expected Behavior

design for chat landing page

### Definition of Done
- [ ] chat landing page design with requirements above

### PR DESCRIPTION
**Pull request by androolloyd**
##### Description

Chat landing page from @iamonuwa 

##### Refers/Fixes
#5578

### CODE REVIEW

**Comment by danlipert** [comment]
@androolloyd Is this ready to be deployed? I see theres still a bunch of lorem ipsum

**Comment by thelostone-mc** [comment]
@iamonuwa could you throw in screenshots ?

**Comment by owocki** [comment]
i can update the lorem ipsum..   sholuld i do it here or on @iamonuwa s branch

**Comment by iamonuwa** [comment]
@thelostone-mc, I rebased and everytime I attempt to run it, it crashed. Am trying to fix the problem at my free time.

**Comment by androolloyd** [comment]
The target of this is just to my 1.2 branch to see changes sorry. Wanted to get a glimpse of what was coming into my branch before merging.

**Comment by androolloyd** [comment]
@iamonuwa we recently moved the docker container to build from ubuntu, what issues are you having?

**Comment by owocki** [comment]
i pulled this down and i cant actually find the page

http://localhost:8000/chat/ just yields an empty page ( https://bits.owocki.com/GGuANrOm )

**Comment by owocki** [comment]
8828501d625d684008bb18d3198dfece7b7fd5fc fixes the copy issues .. here are screenshots

note @androolloyd the last thing to do is link the apps, and make the 'num online' number dynamic.

screencapture-localhost-8000-chat-2019-12-13-08_29_39
screencapture-localhost-8000-chat-2019-12-13-08_29_51

**Pull request merged**
