### PR TITLE
toolbox: avoid $.get when url is undefined

### PR DESCRIPTION
**Pull request by thelostone-mc**
###### Issue 
x1

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- js

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Fixes the failed get calls but still do we need to invoke it in a setInterval ? 

```
  $('.cards .img img').each(function(index, element) {
    document.preloads.push($(element).data('hover'));

  });
```

@owocki  Can't we just directly do `$.get` here instead ? 
Haven't changed this cause I wanna check why this was written this way (so that I don't break anything unknowingly )

**Comment by mbeacom** [comment]
@kziemianek completed the original bounty for this.  Any thoughts?

**Comment by SaptakS** [comment]
@thelostone-mc @mbeacom I am removing the `$.get` code for the time. Hope you both are okay with it?

**Comment by mbeacom** [comment]
Sounds good!

**Comment by mbeacom** [comment]
screenshot 2018-05-31 16 39 31
Beautiful.

**Pull request merged**
