### PR TITLE
added pony for avatar builder

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

Changes added in https://github.com/gitcoinco/web/pull/2368. I messed up while updating the PR and ended up closing it by mistake during a force push 😓 

Ported over your commits in this PR and added the refactoring on top of it @Dgilliams 

screen shot 2018-10-07 at 8 33 04 pm

### CODE REVIEW

**Comment by owocki** [comment]
@Dgilliams what tool do yall use to edit SVGS in avatar builder? when i import them into sketch and re-export them, i can’t seem to find a way to make it so that they stay the same size http://bits.owocki.com/b16d9bf81671/Screen%20Shot%202018-10-07%20at%207.50.14%20PM.png

**Comment by Dgilliams** [comment]
Hey yall! Sorry for my silence I was camping. :)

@owocki I use Adobe illustrator. Your art seems to be bounded by the art shape and not the artboard. Unless your beard takes up the entire artboard. Try making your artboard (or workspace/entire image size) the same size as the other assets. Make sure you select "size to art board" when you're exporting the svg. I used a screenshot of the asset generator to place the hair directly on the character with the artboard the exact size. Then hid everything besides the hair to export. That way the svg just fits on the character in the exact spot you made it.  The final asset won't be zoomed in on the beard. Hope that helps. I can always help doctor the file up too if you send it over. 

@thelostone-mc thanks for your help! I'm going to review your commits to see what I need to do differently for the next one.

**Comment by owocki** [comment]
@Dgilliams you are my hero!

**Comment by Dgilliams** [comment]
got it working?!

**Comment by owocki** [comment]
@Dgilliams f yeah i did !

https://github.com/gitcoinco/web/pull/2399
https://github.com/gitcoinco/web/pull/2400

**Pull request merged**
