### PR TITLE
dashboard: enable deep link of search 

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

This PR does the following  - 
- Enables applied filters to be reflected on the URL
- Refactor code ( rename  + remove dead code)
- remove the extra `Any` filters 

How it works: 

- /explorer defaults to mainnet + localStorage applied filters
- adding filters updates the URL with filters
- visting URL with filters attached -> resets localStorage 
  and stores updates the filters from the URL onto the localStorage

Note: @mbeacom I haven't removed the network filter cause hotjar did show a few folks using it on live
we could wait for a month and see -> and then remove it if needed 

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- js

##### Testing

x

##### Refers/Fixes
- https://github.com/gitcoinco/web/issues/1791

### CODE REVIEW

**Comment by mbeacom** [comment]
Seems good on staging!

**Comment by owocki** [comment]
just tested.. seems to work really well!

**Comment by thelostone-mc** [comment]
@mbeacom  / @owock can we SHIPL ?

**Comment by owocki** [comment]
seems good to me.  both coding and testing (though i only tested in chrome)

**Pull request merged**
