### PR TITLE
[WIP] 4343 - fixing wrong network bounties

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
Fixes the issue of selecting wrong network bounties

##### Refers/Fixes
Fixes: #4343

##### Testing
Currently in progress...

### CODE REVIEW

**Comment by kuhnchris** [comment]
@owocki do we have any "easy" way to find out which network we are on? Right now I use the KUDOS_NETWORK variable since that one should be close enough, and SHOULD always be the same to the "mainnet being used".
Else we need some variable like "PROFILE_NETWORK" to fix running issues from this problem. On live we do have rinkeby and normal bounties. That screws up our totals.
Please advise.

Also, maybe we should start providing some data via dumpdata and loaddata in django?
https://docs.djangoproject.com/en/2.2/howto/initial-data/

I know there's an open ticket, but I don't think there's any progress on it yet?

Thanks

**Comment by kuhnchris** [comment]
Did you manage to test it @thelostone-mc ? I cannot test it for the life of myself, I cannot get that rating stuff working on my local instance...

**Comment by SaptakS** [comment]
@kuhnchris you can use the settings.DEBUG to check if it is a production environment. If it is a prod environment then the network is mainnet, else it is rinkeby.

**Comment by kuhnchris** [comment]
settings.DEBUG also isn't set when there's some trouble on prod and you guys are debugging it @SaptakS ?
If we can ensure it's always displaying properly on prod then I'm all for it 👍

**Comment by kuhnchris** [comment]
Since I assume the answer to that question is "no" I'll simply go for
```
settings.DEBUG == True => Rinkeby 
Else => Mainnet
```

Update coming soon

**Comment by kuhnchris** [comment]
so we can throw this one away @thelostone-mc ?

**Pull request closed without merging**
