### PR TITLE
Adds cors headers, and conditionally allow all for GET requests of bounties.

### PR DESCRIPTION
**Pull request by matthewlilley**
##### Description
Adds cors headers, and conditionally allow all for GET requests of bounties.

##### Checklist
- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines]

##### Refers/Fixes
https://github.com/gitcoinco/web/pull/1076

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Code looks alright 👍 

@matthewlilley @mbeacom haven't worked with a large scale project like this before up close & personal , any security implications of enabling CORS for`GET`calls ?

**Comment by matthewlilley** [comment]
@thelostone-mc It wouldn't hurt to get a second opinion here, though I believe the cors headers should only be sent for that single endpoint "/api/v0/bounties". I was unsure if POST methods are used on this endpoint, as it seems to be a resource, so to be cautious I limited the method to GET only.

**Comment by owocki** [comment]
>  It wouldn't hurt to get a second opinion here, though I believe the cors headers should only be sent for that single endpoint "/api/v0/bounties".

yes tahts right

**Comment by owocki** [comment]
i didnt test.. but code looks sane. very happy if this enables https://github.com/gitcoinco/web/pull/1076 !
@mbeacom what do you think of this?

**Pull request merged**
