### PR TITLE
designs added

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
image
image
image
image
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have added 3 more accessories. Please review this pr.

**Comment by mehul0698** [comment]
@owocki @thelostone-mc Please review this pr.

**Comment by mehul0698** [comment]
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have added 4 accessories. Please review this pr.

**Comment by mehul0698** [comment]
image
image
image
image
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc Please review this pr. I have added 7 accessories.

**Comment by mehul0698** [comment]
@owocki my pr has been merged you owe me 130 to 135 dollars.

**Comment by mehul0698** [comment]
@owocki Thanks. Next time if you open any svg or design related issue let me know I would love to contribute. 
There are still some avatar assets that are not correct in the avatar builder, if you want I can look into that. Looking forward to working more with you.

**Comment by owocki** [comment]
> There are still some avatar assets that are not correct in the avatar builder, if you want I can look into that. Looking forward to working more with you.

yes pls!

**Comment by mehul0698** [comment]
@owocki Hey Kevin, when will you reopen the avatar assets issue?

**Pull request merged**
