### PR TITLE
Pop Over Across the site

### LINKED ISSUE #6610: Take the townsquare user modal, and make it live across the site.
The object ive this ticket is to take the below modal, which currently shows when you hover a username on gitcoin.co/townsquare, across the site.
 
slack-imgs

To do so, you need to add `data-usercard="{{ row.profile.handle }}"` to any DOM element that needs to have the card, and add `user_card.js` to the page ( this is probably easiet to do with footer_scripts.html and footer_scripts_lite.html )

List of pages to add it
- bounty details
- users serach
- hackathon pages
- tribe pages
- profile pages
- results page
- and anywhere else a profile shows up on gitcoin.

### PR DESCRIPTION
**Pull request by molecula451**
##### Description

record-03045607052020

handlergrant

popover activity feed

popoverover

##### Refers/Fixes

Fixes #6610

##### Testing

**Hacking Completed......**

### CODE REVIEW

**Comment by molecula451** [comment]
Hacked your implementation and spread it across the site my friend @octavioamu :P (slightly easy tho)

**Comment by molecula451** [comment]
Hacked your implementation and spread it across the site my friend @octavioamu :P

**Comment by octavioamu** [comment]
Putting a fix about this PR since was duplicating the user_card.js addition in many places. 
Seems this wasn't ready since 
- hackathon pages have other places like participants and projects 
- On tribes just the townsquare is with cards http://localhost:8000/gitcoinco
- profile pages just the activity was added
- results page not added
- and anywhere else a profile shows up on gitcoin 

Please submit a new PR with the missing parts (the duplication of user_card is something Im fixing on stable right now)

**Comment by molecula451** [comment]
> Putting a fix about this PR since was duplicating the user_card.js addition in many places.
> Seems this wasn't ready since
> 
> * hackathon pages have other places like participants and projects
> * On tribes just the townsquare is with cards http://localhost:8000/gitcoinco
> * profile pages just the activity was added
> * results page not added
> * and anywhere else a profile shows up on gitcoin
> 
> Please submit a new PR with the missing parts (the duplication of user_card is something Im fixing on stable right now)

Just saw the fixing commit. Submitting a PR asap

**Pull request merged**
