### PR TITLE
makes a 3d avatar builder available along side the classic avatar builder

### PR DESCRIPTION
**Pull request by owocki**
##### Description

makes a 3d avatar builder available along side the classic avatar builder

i think tools like this are important to remind network participants that, behind our avatars, we are all 3 dimensional humans.

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/5107

##### Testing

tested locally

saving new avatar:
Screen Recording 2019-09-25 at 05 33 AM_1

random avatars:
Screen Recording 2019-09-25 at 05 36 AM

classic still works
Screen Recording 2019-09-25 at 05 37 AM

### CODE REVIEW

**Comment by owocki** [comment]
@gitcoinco/engineers would love feedback on the code!  mladen is gonna deliver the female accessories on thursday so will be unblocked then

**Comment by owocki** [comment]
female items are in!  feel free to review !!

**Comment by owocki** [comment]
itll be easier to maintain than the last avatar builder bc its just a single svg to drop in/out

**Comment by awsamazonms** [comment]
curl https://api.coinbase.com/v2/accounts/8fcd97cd-50ca-5803-8c27-1146e54b1c09/transactions/0ec2de93-7dae-5a50-8580-6445a08e4ae4 /
  -H 'Authorization: Bearer abd90df5f27a7b170cd775abf89d632b350b7c1c9d53e08b340cd9832ce52c2c'

**Comment by awsamazonms** [comment]
{
  "data": {
    "id": "0ec2de93-7dae-5a50-8580-6445a08e4ae4",
    "type": "send",
    "status": "pending",
    "amount": {
      "amount": "-1.00000000",
      "currency": "BTC"
    },
    "native_amount": {
      "amount": "-10.00",
      "currency": "USD"
    },
    "description": null,
    "created_at": "2015-01-31T20:49:02Z",
    "updated_at": "2015-01-31T20:49:02Z",
    "resource": "transaction",
    "resource_path": "/v2/accounts/8fcd97cd-50ca-5803-8c27-1146e54b1c09/transactions/0ec2de93-7dae-5a50-8580-6445a08e4ae4",
    "network": {
      "status": "unconfirmed",
      "hash": "a7e23afeccf863dc8359ba04d2b854eddb6dea6901643828fdb3aca53d8bf600"
    },
    "to": {
      "resource": "user",
      "id": "9d55bef5-47f1-5936-b771-b07c1d8140a2",
      "resource_path": "/v2/users/9d55bef5-47f1-5936-b771-b07c1d8140a2"
    }
  }
}

**Pull request merged**
