### PR TITLE
Hackathon Explorer Tabbed View: Participant Tab

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
Implement the participants design.

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/6364

##### Testing
image

image

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Closing this out as it was built in vue and is live 
https://gitcoin.co/hackathon/stop-covid/participants/?tab=hackathon:19

**Comment by zoek1** [comment]
@thelostone-mc the current implementation doesn't meet the Figma proposed design. So this could be reopened and integrate into the new design but this time with Vue.

**Comment by thelostone-mc** [comment]
Oh that helps ! Set some context

**Comment by zoek1** [comment]
I'll migrate this and ping you when it is ready. Thanks!

**Comment by zoek1** [comment]
@thelostone-mc I fixed the conflicts and integrate the changes with the Vue component, this PR is ready for review.

**Comment by androolloyd** [comment]
I'm getting an error in the console, that openChat is not defined.

https://share.getcloudapp.com/kpuLmeNA

**Comment by zoek1** [comment]
Sorry @androolloyd, I fixed this.

**Comment by thelostone-mc** [comment]
@zoek1 we've got a few conflicts here too

**Comment by zoek1** [comment]
solved @thelostone-mc

**Pull request closed without merging**
