### PR TITLE
A sample Adobe Illustrator file to help artists get started

### PR DESCRIPTION
**Pull request by Dgilliams**
##### Description
A starting point for beginner artists with prenamed layers and artboard dimensions set.
layers

The overlays from the design guide are included as hidden layers with partial opacity. Toggle the visibility of these with the eyeball next to their layer name.  
grid_sections

##### Checklist

- [ ] linter status: 100% pass
- [ ] changes don't break existing behavior
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
none 

##### Testing
none

##### Refers/Fixes
open to suggestion!

### CODE REVIEW

**Comment by Dgilliams** [comment]
@mbeacom you got it! I'm not seeing that other repo, is it private?

**Comment by mbeacom** [comment]
@Dgilliams I updated the original URL after I posted it.  https://github.com/gitcoinco/creative should be public and available.  I think @PixelantDesign has some recommendations as well, so you could probably wait for her followup before PRing there, though.

**Comment by Dgilliams** [comment]
color_palette

**Comment by Dgilliams** [comment]
@mbeacom is the new directory ok? 
I also added several new hair assets.
This is my first experience with Docker and I haven't quite got it running yet. Any chance you could help me out? I want to make sure these work before knocking out more assets.

**Comment by willsputra** [comment]
@Dgilliams This looks great! Would definitely be helpful for designers like me to work on avatar bounties without starting from scratch.

Also love how you put the default color schemes, grid, strokes from the styleguide. The attention to detail is much appreciated. 😊

Few comments from me:
1. Could we make the no-hair, no-accessories base as the default? Would make it easier for me if I want to create new hairstyles/accessories/clothes
2. Also notice the left ear looks kinda odd

screenshot 2018-10-18 23 50 53
3. I might be nitpicking here but I think the jaw should be sliiiightly wider (follow the blue line) and the taper starts sliiiightly lower (below the dashed line)

screenshot 2018-10-18 23 53 55

Let me know if you need any help? Can't wait to push this through the finish line 🤩
Thanks a lot!

cc @PixelantDesign

**Comment by Dgilliams** [comment]
@willsputra You're very welcome. I hope it gives you and others the courage to jump in and start creating. I appreciate the nitpicky-ness :) I'll fix those real quick. Keep the notes coming! There are other things I'd like to make better as I make other assets for the generator, but I wanted to get it out there quickly for others to use. This file can still be much better. 

The art on top was left as default as an example so others can see how the shapes and outlines should be before exporting. It's pretty quick to delete what's there and save your own template file. This did just make me wonder... should there be two files? one as a blank template and the other is an example?

Remember to select "size to artboard" when exporting any svg assets :D

**Comment by Dgilliams** [comment]
@willsputra file is updated. I left the art in there, lol I actually added more for a little variety. I realized as I was deleting it all down to the base that it's nice to have something to start with. ex: If I only want to design eyes, I don't want to need to import hair to see how it looks among other assets.

**Comment by willsputra** [comment]
@Dgilliams wow that was fast! :) this looks good to me. @PixelantDesign any comments?

**Comment by Dgilliams** [comment]
@all, finally got my docker instance working right. I swear I did the same steps the other day and it wouldn't launch. Don't pull this in yet. I found a few things that need adjustments.

**Comment by Dgilliams** [comment]
avatar_ex_1
avatar_ex_2
avatar_ex_3_inverted_mohawk
avatar_ex_4_mohawk
avatar_ex_5

Is there something special I should be doing with the beard and mustache files? 
no_beard_err

**Comment by Dgilliams** [comment]
@all, @PixelantDesign, @willsputra 
I removed the beard since it only fit my face shape. Everything else is ready to go. 4ish new hair styles. This should be ready for a merge.

**Comment by PixelantDesign** [comment]
Thanks @Dgilliams!

**Comment by willsputra** [comment]
Awesome @Dgilliams!

**Comment by Dgilliams** [comment]
No problem 🤘🤓 @pixelantdesign @willsputra

**Pull request merged**
