### PR TITLE
'Play a Quest' in dropdown menu

### PR DESCRIPTION
**Pull request by molecula451**

### CODE REVIEW

**Comment by molecula451** [comment]
> @molecula451 Is this mapped to a github ticket ?

Not at all. I'm feeling the Open Source freedom and added the changes

**Comment by thelostone-mc** [comment]
@PixelantDesign  + @octavioamu defer decision to you guys on this !

**Comment by molecula451** [comment]
> @PixelantDesign + @octavioamu defer decision to you guys on this !
> 
> @molecula451 could you throw in a screenshot so that everyone knows where this appears on the nav dropdown

quests

We would have it just below the grants + i think it will make a lot of interactivity (more than what already is) for the quests

**Comment by molecula451** [comment]
I mean quests is a important part of the whole Gitcoin. I'm visioning quest bigger than what it is right now, long term

**Comment by octavioamu** [comment]
Im ok with it.
@PixelantDesign need to give the final word

**Comment by thelostone-mc** [comment]
Closing this out @molecula451 as we've got a PR coming up which revisits the entire dropdown + navbar
I've pointed folks working on this onto the PR as well ^_^

**Pull request closed without merging**
