### PR TITLE
Can't trust the delete button activity on Dashboard

### LINKED ISSUE #5837: Scary delete button activity add confirmation
**Describe the bug**
Cannot intentionally trust the delete button on activity it might further remove valuable activity unintentionally

**To Reproduce**
Click the button you will see

**Expected behavior**
Add confirmation

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win32/Linux
- Browser: Brave
- Browser Version: Lastest Compilation

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

### PR DESCRIPTION
**Pull request by molecula451**
Need testing

##### Description

delete

Delete button on activity instantly remove the activity what about if I somehow unintentionally clicked and remove some valuable stuff

##### Refers/Fixes

#5837 
##### Testing
Need further testing

### CODE REVIEW

**Comment by danlipert** [comment]
@molecula451 thanks for the PR - if you are opening an untested PR, please make sure to set it as a draft PR so that it doesn't ping the core team for a review. It makes our lives a bit easier, thanks!

**Comment by molecula451** [comment]
> Was this tested ?
> Could you add a video recording of the fix for both scenarios
> Looks like python syntax has been used in js for `else`
> 
> Also could we update the code to do this
> 
> ```
>     if (!document.contxt.github_handle) {
>         _alert('Please login first.', 'error');
>         return;
>     }
> 
>     if (!confirm('Are you sure you want to delete this?')) {
>         return
>     }
> ```

You are right great lostone

**Comment by danlipert** [comment]
@molecula451 Can you post some screenshots or a video - thanks!

**Comment by thelostone-mc** [comment]
@molecula451 would you be able to get this in ?

**Comment by molecula451** [comment]
Yes guys. I am finishing testing this

**Comment by molecula451** [comment]
Working @thelostone-mc  @danlipert 

working

**Comment by molecula451** [comment]
working

**Pull request merged**
