### PR TITLE
WIP partial route change

### PR DESCRIPTION
**Pull request by usulix**
##### Description
Changes the format of the bounty URL
https://github.com/gitcoinco/web/issues/201

NOTE - WIP because I did not yet get to the change to the url when a bounty is created - I had a little trouble tracing through that process.

##### Checklist
- [X] linter status: 100% pass
- [X] changes don't break existing behavior
- [X] commit message follows [commit guidelines]
   - add new urls to urls file
   - maintain old format while adding new format to bounty/view

##### Affected core subsystem(s)
bounty creation

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/201

### CODE REVIEW

**Comment by owocki** [comment]
> NOTE - WIP because I did not yet get to the change to the url when a bounty is created - I had a little trouble tracing through that process.

Search for `/funding/details`  in the codebase and youll see where you need to change

let me know when this isnt WIP anymore and ill review it

**Comment by step21** [comment]
Should mixpanel use new or old urls or support both?

**Comment by owocki** [comment]
@step21 @usulix any interest in picking up on this?

**Comment by step21** [comment]
I started working on it, but not done yet. (but almost)
With the changes to bounty_details that  you mentioned on slack, should we hold off on this?

**Comment by owocki** [comment]
id still love to see it... what changes to bounty_details are you referring to?

**Comment by step21** [comment]
Oh, I think I mixed it up with sth else. I think I have most things in place based on the work by usulix and posting my branch in the PR. Just have to test it properly as I probably missed something and that is a bit tricky at the moment. Tried testing on Rinkeby but somehow not enough ether as Metamask quoted me costs of up to 12 ETH. So gonna try with ganache again.

**Pull request closed without merging**
