### PR TITLE
Carnival

### PR DESCRIPTION
**Pull request by j0ker1234**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by j0ker1234** [comment]
image
image

**Comment by thelostone-mc** [comment]
@j0ker1234 that looks pretty dope ! can you resolve the conflicts though ?

**Comment by thelostone-mc** [comment]
@j0ker1234 wanna get this in this week ?

**Comment by j0ker1234** [comment]
@thelostone-mc I am working on some more designs, will submit a pr by Friday.

**Comment by j0ker1234** [comment]
@thelostone-mc I have resolved the conflicts for this branch. For the other designs will create a new pr.

**Comment by thelostone-mc** [comment]
@j0ker1234 Ah merging your other PR introduced conflicts here again 😅 Mind resolving them again?

**Comment by j0ker1234** [comment]
@thelostone-mc Done.

**Pull request merged**
