### PR TITLE
Environment variable setting handling

### LINKED ISSUE #144: Environment variable based settings
##### Description
It might be helpful for us to switch to environment variable based settings for the Django app.

##### Possible Implementation
Implement `django-environ` and switch from `local_settings.py` to using `environ`, default envvars, and a base env var file.

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description
The goal of this PR is to introduce a little 12factor methodology by using environment variables (and .env files) to pass settings to the Django application.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/contributing/CONTRIBUTING.md#step-4-commit)

##### Refers/Fixes
Fix #144 - Setup the project to use `django-environ`.

### CODE REVIEW

**Comment by owocki** [comment]
code mostly LGTM... is there a sibling PR to the servers repo too?

**Comment by owocki** [comment]
also: how are you testing changes like this?

**Comment by mbeacom** [comment]
@owocki Going to resolve the conflicts in this branch -> merge it -> merge `gitcoin_server` setting/env file additions and changes -> deploy to staging -> deploy to master -> 🕺

**Comment by owocki** [comment]
sounds good to me

**Comment by mbeacom** [comment]
@owocki This is live on `stage`

**Comment by mbeacom** [comment]
This is live.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/646

**Pull request merged**
