### PR TITLE
WIP: Duplicate users in https://gitcoin.co/users view

### LINKED ISSUE #4409: Duplicate users in https://gitcoin.co/users view
**Describe the bug**
Users are sometimes duplicated in the users view.

**To Reproduce**
Scroll down the page.

**Expected behavior**
No duplicate entries.

**Screenshots**
duplicate
duplicate2

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Chrome 
- Browser Version:

Google Chrome | 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux
JavaScript | V8 7.3.492.27

@iamonuwa FYI.

### PR DESCRIPTION
**Pull request by nadirlaskar**
`user_list` is duplicated after `prefetch_related` joins  `'fulfilled', 'leaderboard_ranks', 'feedbacks_got'`

##### Description

To fix the issue, I have used `distinct('id')` after `order_by` to return only distinct users from prefetch joins 

##### Refers/Fixes

#4409 Fixes Duplicate users

### CODE REVIEW

**Comment by acolytec3** [comment]
@nadarliskar Are you sure that using .distinct('id') solves the problem?  I experimented with this a few days ago and was still seeing duplicate users if I clicked on various filters and then using browser back button.  Note, this was based on me adding 5-6 additional profiles to the database in my dev environment.

I did see some Vue warning messages about duplicate keys in the browser console logs so wondering if the issue doesn't lie there per what @gutsal-arsen commented on the other thread.

**Comment by octavioamu** [comment]
Yep distinct is not going to solve the problem alone, already tried that. @acolytec3 yes vue is complaining since v-for key can't be a duplicate, so when every that error shoes in the console means the users are duplicated.

**Comment by nadirlaskar** [comment]
> Yep distinct is not going to solve the problem alone, already tried that. @acolytec3 yes vue is complaining since v-for key can't be a duplicate, so when every that error shoes in the console means the users are duplicated.
@octavioamu Due to some docker [issue](https://github.com/gitcoinco/web/issues/4412), I am unable to test changes locally.

**Comment by nadirlaskar** [comment]
I was unable to do further development due to docker issues,
[#4409](https://github.com/gitcoinco/web/issues/4409) issue seems to be fixed and closed.
So, closing the pull request.

**Pull request closed without merging**
