### PR TITLE
#3143 hardcoded kudos.json path replaced by osPath

### LINKED ISSUE #3143: app/manage.py - sync_kudos has /kudos/kudos.json hardcoded
**Describe the bug**
Executing app/manage.py sync_kudos via docker-compose exec fails due to a hardcoded path expecting you to be in the app directory to do this command.

**To Reproduce**
docker-compose exec app/manage.py sync_kudos rinkeby opensea --catchup

**Expected behavior**
Synchronization of Kudos

**Screenshots**
image

### PR DESCRIPTION
**Pull request by kuhnchris**
##### Description
See #3143

##### Affected core subsystem(s)
management

##### Refers/Fixes
Fixes #3143

### CODE REVIEW

**Comment by kuhnchris** [comment]
maybe @willsputra or @thelostone-mc want to check? :-)

**Comment by kuhnchris** [comment]
@thelostone-mc @owocki want me to throw this away?

**Comment by danlipert** [comment]
Sync kudos works fine now (right?) so I think this is no longer needed @thelostone-mc

**Comment by thelostone-mc** [comment]
Closing this out cause it's not needed anymore
Thanks @kuhnchris  ^_^

**Pull request closed without merging**
