### PR TITLE
Add turtle neck design

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description
As requested by a twitter user https://twitter.com/abbey_titcomb/status/1167446204332040198

### CODE REVIEW

**Comment by owocki** [comment]
screenshot??

**Comment by iamonuwa** [comment]
I can't get to load into the app after running `make collect-static`

**Comment by iamonuwa** [comment]
IMG-20190902-WA0007
This is how it looks

**Comment by owocki** [comment]
LGTM... @gitcoinco/engineers ?

**Comment by owocki** [comment]
actually u need to add it to avatar/utils @iamonuwa .. did you test this? screenshot of it working?

**Comment by iamonuwa** [comment]
Let me do this immediately

**Comment by iamonuwa** [comment]
The design is now loading and works
image

**Comment by thelostone-mc** [comment]
@owocki  @gitcoinco/engineers give it a  👍

**Pull request merged**
