### PR TITLE
Feature/backup 3box

### PR DESCRIPTION
**Pull request by zoek1**
##### Description

# Implement Integration of Gitcoin + 3box

Give Gitcoin users the option to backup their complete Gitcoin profile and contribution history to 3Box. This feature will give Gitcoin users greater control of their data and allow them to take this information to other platforms. Once this feature is live, users won't have to build up separate contribution histories and reputation on different future of work platforms, but they can instead reuse their existing history.

## Core principles and guidance
1. Being transparent
2. Give users control about his data
3. Start to enable applications around users data 

1. Being transparent
Since we are in an ecosystem where trust and transparency are the principal enablers following such a way is natural to continue with it but also from a personal perspective is a must to continue creating, contributing and progressing. We present the user the resources and its fields as its privacy level, to know what of his data is exposed to the world behind the consent access process.

2. Give users control about his data
These days is required to give the user the tools to maintain its privacy, in this case, structure in a proper way to preserve data confidentiality and enhance user privacy. Allow the user giving to apps only they needed to function, due to this each resource corresponds to one space, so if the user doesn't want to access a particular resource only need to denied the access.

3. Start to enable applications around users data
Start to developing apps with information on other platforms could lead to tight coupling, and reduce the potential space and compatibility between the apps. To avoid this from the start, I propose a draft spec to start iterating from this until getting a "spec that fits".

[Contribution Profile Specification](https://github.com/gitcoinco/web/blob/02473245a6c6c27542dd5d0ccad72dc582a85a84/app/dashboard/context/backup/schema.py)

## Implementation
1. Definition of the specification: The spec is composed of the following elements:
  - Profile Data: Mainly backup data that could be used to populate user profile to other platforms, the art, and the avatar builder are great let's share the produced resources with the world.
  - Bounties: Data related to bounties where the user has participated, this is to share contributions and this is the main component to share.
  - Tips: Help to others or get acknowledge from others by tips is also a way to contribute.
  - Activity: Related to events related to the user, this could be great to unify and get the general view of what we doing.
  - Preferences: This backup preferences that could be helpful to have a better one unified user "preferences". Do you like Black mode? Let the other app to access to preferences space and the app should set black mode for you.
  - Kudos: 3Box already displays kudos but this will focus on the full send, created and received kudos.
  - Stats: This could be for data lovers to build its own dashboard and gamify between platforms
  Why is not included jobs, interests, grants: This is not included to focus only on a subset due to time restriction but definitely will be included in the next iterations.
2. Serve specification + data
  Every resource will be in the companion of its respective spec to get a clear understanding of the propose, type, and desc of each;
  I added backup preferences functionality to help with the accessibility and in a future iteration takes these preferences and backup the user data automatically. The functionality is already implemented only is required to add the button and bind the `backup` function. I decided not to follow this way to at least for a period allow the users to know what data and with which service is provided the backup process.
3. User flow at the client-side:  Allow the user to select what data will be back up into 3box, this will be described in test section.
4. Preserve preferences: There two ways to preserve backup preferences, one is select data to backup and performs te backup. When the backup start the backup preferences are sent to the backend to be persistent.

Notes: https://hackmd.io/@cwaFdb2fRaOvRzDcU-7aXA/ByHBhWfAB
Demo: https://www.dropbox.com/s/ejnux5vzh0gsuxo/2019-12-18%2018-02-04.flv?dl=0

##### Refers/Fixes
https://github.com/3box/3box/issues/839

##### Testing

All testing was manual, I hope work on this further to provide certainty with tests.

The process to test is the following:
1. Run migrations: In case to use de docker test environment run the following lines:
```
$ docker-compose up -d
$ make migrate
```
2. Go to personal profile and click at the sync option:
@zoek1 _ Gitcoin
3. This redirects to the backup view, selects the resources to back up and after that click at the backup button. In this step I recommend creating a new account at metamask:
backup_data_desc
4. Accept the requests to sign a message, this allows the app to create the spaces to backup data to 3box
DeepinScreenshot_20191218125009
5. Wait patiently  and until the waiting screens despair:
backup_views
5. Now the preferences are saved to gitcoin backend and resource saved to 3box, also you can update the preferences at the management setting on the backup tab `/settings/backup`:
backup_settings

### CODE REVIEW

**Comment by danlipert** [comment]
Hi @zoek1 - is this ready for review? If so can you please fill out the testing section and describe how your changes work, why you made the decisions you did, how it was tested, etc.? Also can you post some video or screenshots of your changes? Thanks!

**Comment by zoek1** [comment]
@danlipert  this PR is ready!

**Comment by zoek1** [comment]
@danlipert could you help me adding the tag `Gitcoin Global Communities Hackathon' to this PR, I haven't permissions to add it. Is a requirement for the https://gitcoin.co/issue/3box/3box/839/3793 :sweat_smile:

**Comment by danlipert** [comment]
@zoek1 I added the label - I'm guessing you were supposed to fork the repo and then do a PR to your fork's master so you can add the label yourself :) anyway - this looks like a pretty substantial PR so we'll take a closer look at it after the new year

**Comment by zoek1** [comment]
@danlipert i'll pending on any request of change to integrate this fast as possible! 😀

**Comment by thelostone-mc** [comment]
@zoek1 Yo thanks for the PR ! 
We ended up getting the 3Box integration in and this is live 
Closing this out now ^_^

**Pull request closed without merging**
