### PR TITLE
Add hackathons events

### PR DESCRIPTION
**Pull request by zoek1**
##### Description
image

### CODE REVIEW

**Comment by jdorfman** [comment]
Looking good @zoek1! Is there a way to add UTM's to the "Join" buttons?

**Comment by jdorfman** [comment]
@PixelantDesign @octavioamu this will replace the Disqus widget that has 2+ years of stale content on the [gas history page](https://gitcoin.co/gas/history). This page gets a lot of organic search traffic (see GAnalytics) and advertising our current hackathons seems like a better use of space.

**Comment by thelostone-mc** [comment]
@zoek1 could we make the code reusable ! I believe we have the exact same format on the hackathon list page 
So ideally make that into it's own file and import it in both places

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
DRY code needed

**Comment by jdorfman** [comment]
@thelostone-mc will this allow @zoek1 to add custom UTM's so we know where the sign-ups are coming from?

**Comment by thelostone-mc** [comment]
@jdorfman So this would be mapped to the buttons right ?  yeah that's possible even with DRY code

**Comment by thelostone-mc** [comment]
@jdorfman closing this out as this code is also present is open in PR https://github.com/gitcoinco/web/pull/7502/commits

**Comment by jdorfman** [comment]
Thanks @thelostone-mc !

**Pull request closed without merging**
