### PR TITLE
Disables editing of the issue title and description

### PR DESCRIPTION
**Pull request by SaptakS**
##### Description
Since issue title and issue description are fetched from github, we are disabling editing of the title and description to maintain consistency.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
Funder form

##### Refers/Fixes

#1588

### CODE REVIEW

**Comment by owocki** [comment]
was this tested? it seems to become un-disabled when the GH API response returns

movie of this in prod today: http://bits.owocki.com/3I3g1K3v2u30/Screen%20Recording%202018-07-18%20at%2011.48%20AM.gif

**Comment by SaptakS** [comment]
I tested it. Was working fine in local and stage.

**Comment by owocki** [comment]
@SaptakS is the disabled desc / title stuff still live?  im not seeing it on gitcoin.co/new

**Comment by SaptakS** [comment]
@owocki it's not disabled. It's readonly. Meaning you can't edit it. I just checked in [gitcoin.co/new](https://gitcoin.co/funding/new) and it seems to work fine.

**Comment by owocki** [comment]
oh you are right!

would it make sense to grey out the textbox so the user knows those fields are inediatable and/or create a little info popup that explains how / where to edit title desc.?

**Comment by SaptakS** [comment]
I think a popup does make sense. I can grey out if it makes sense visually.

**Comment by owocki** [comment]
makes sense to me. @PixelantDesign ?

**Pull request merged**
