### PR TITLE
tooltip: updated as per review comments

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description
Updated tooltip as per review comments from @PixelantDesign  as given in https://github.com/gitcoinco/web/pull/585#issuecomment-372419795

screen shot 2018-03-13 at 2 14 59 am

##### Checklist

- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
- ui 

##### Refers/Fixes
Refs: #585

### CODE REVIEW

**Comment by PixelantDesign** [comment]
@thelostone-mc could use the inside padding on the left side of the tooltip and apply it so that it's even to all sides? Will you also decrease the shadow darkness by 30%?

Thanks!

**Comment by thelostone-mc** [comment]
@PixelantDesign You mean you want the right and left to be evenly padded right ?

**Comment by PixelantDesign** [comment]
Right, Left, Top & Bottom. Thank you!

**Comment by thelostone-mc** [comment]
@PixelantDesign @mbeacom Done!!

screen shot 2018-03-14 at 11 05 45 am

**Comment by thelostone-mc** [comment]
@PixelantDesign reduced the padding further. Further reducing it makes it looks cramped up 

screen shot 2018-03-15 at 12 15 29 pm

cc @mbeacom

**Pull request merged**
