### PR TITLE
Added pilgrim hat accessory

### PR DESCRIPTION
**Pull request by jakerockland**
##### Description

Added pilgrim hat accessory to avatar creator 🦃.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

avatar

##### Testing

Tested locally, screenshots attached:
screenshot 2018-11-05 21 21 42
screenshot 2018-11-05 21 21 49

##### Refers/Fixes

Refs: #2684

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@jakerockland you'll have to rebase. Looks like your earlier PR caused it :P

**Comment by jakerockland** [comment]
@thelostone-mc Fixed! May have to do this again on #2704 after this one is merged 😅

**Comment by jakerockland** [comment]
Rad, this should be g2g now @thelostone-mc 😄 apologies for the merge conflicts, tricky getting the linter happy while also leaving changes that don't confuse `git` when trying to compartmentalize the accessories in their own PRs.

**Comment by jakerockland** [comment]
@thelostone-mc odd, something changed on master and things needed to be resolved again—just did so now though and it LGTM so hopefully all looks good on your end for merge 👍

**Comment by owocki** [comment]
native american headress next ??

**Comment by jakerockland** [comment]
@owocki You want one? Can do that! 👍 😄 Did you see the hannukah and santa hats? 

screenshot 2018-11-08 15 50 57

**Comment by jakerockland** [comment]
Through my avatar, I have become my true self...

**Comment by owocki** [comment]
i love it

**Comment by jakerockland** [comment]
Shall I make 'le headdress? Not sure exactly at what point I've tapped out on making avatar accessories haha.

**Comment by owocki** [comment]
you've never tapped out :)

i'd like to see the headdress sure

**Pull request merged**
