### PR TITLE
Adding girly hairstyles

### LINKED ISSUE #3195: New Avatar Assets -- Winter 2019
### User Story

As a user, I want to new avatar assets to show off and express myself digitally.

### Description

*Type*:  New implementation

### Definition of Done

- [ ] Create an .svg asset and place it in `app/assets/v2/images/avatar/<category>`
- [ ] Add the SVG asset as a `.txt` Django template in `app/avatar/templates/<category>/<item|index>.txt` with variable fill.
- [ ] Add your asset to [utils.py](https://github.com/gitcoinco/web/blob/master/app/avatar/utils.py#L43-L97)
- [ ] Provide a screenshot of the new asset from the avatar builder AND the profile details page on this Github issue.
- [ ] Asset should follow the [avatar style guide](http://bits.owocki.com/9a25c298e3d9/gitcoin-avatarconstructionguide_082218.pdf)

See this example PR for how to do an accessory:
https://github.com/gitcoinco/web/pull/2356

and this one for adding a peice of clothing
* https://github.com/gitcoinco/web/pull/2401

### Additional Information

Feel free to submit any assets you would like to see on Gitcoin.  If the asset is accepted, your asset will become a part of the live avatar builder!  All other assets will be escalated to the core team for review and potential modification.

See the [avatar item request shortlist](https://github.com/gitcoinco/web/issues/1550)

We *especially* want to see 

* more GIRL-ey hairstyles, girly type choices, and clothing
* items that celebrate the holidays here in the US (Channukah / Christmas themed items)
* items that show off super powers and frame our community as super heroes / super villians.

**COMMUNITY MEMBERS**
Feel free to add reactions/upvote your favorite new avatar items/assets!

# Bounty Rules

i will pay 

* 25 DAI per item of regular clothing
* 20 DAI per hairstyle
* 15 DAI per accessory
* 10 DAI per nose, eyes, head

+ 5 DAI per item, if the item is exotic looking in some way

but only if the asset is QAed and merged, up to 100 DAI per person and 500 DAI total.  please allow 1-3 iterations on your design from first submission

### PR DESCRIPTION
**Pull request by nanspro**
##### Description

Adding girly hairstyles 

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [x] Added relevant tests
- [x] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [x] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [x] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

Front End and Images section

##### Refers/Fixes

Fixes #3195 

##### Testing and Sign-off
locally

### CODE REVIEW

**Comment by nanspro** [comment]
screenshot 2018-12-31 at 6 22 00 pm
screenshot 2018-12-31 at 6 22 20 pm
screenshot 2018-12-31 at 6 22 37 pm

**Comment by nanspro** [comment]
screenshot 2018-12-31 at 6 23 21 pm

**Comment by thelostone-mc** [comment]
@nanspro could you run `svgo` and compress the images

**Comment by nanspro** [comment]
@thelostone-mc check now?

**Comment by thelostone-mc** [comment]
@nanspro could you check your images once again ?
It looks too short upon saving the avatar

screen shot 2019-01-03 at 12 39 49 am

cc @owocki you've seen this before right ?

**Comment by nanspro** [comment]
@thelostone-mc could it be because of running svgo because I didn't test it afterwards ( I used a MacBook for running Adobe illustrator which I don't have access right now).

**Comment by nanspro** [comment]
I will test it tomorrow 👍

**Comment by owocki** [comment]
looks like a scaling issue!

**Comment by nanspro** [comment]
@owocki  @thelostone-mc  i made those images in black color using illustrator then i just changed the color using gravit designer but the new color is not rendering properly.
I have never created svg's before could you help me with this issue?

**Comment by nanspro** [comment]
screenshot from 2019-01-05 19-03-56
screenshot from 2019-01-05 19-04-23
screenshot from 2019-01-05 19-04-43
screenshot from 2019-01-05 19-04-47

**Comment by owocki** [comment]
unfortunately i dont have the cycles to dive in here.  i'd try asking on the community help slack, or combing through past PRs that have added hair styles

**Comment by thelostone-mc** [comment]
@nanspro mind poking around the hairstyle PRs / reaching out to the community ?

**Comment by nanspro** [comment]
@owocki  @thelostone-mc  i believe the issue is due to using different tools for color change (initially i used  illustrator but for changing color i used gravit). 
Do you guys know any other open-source tool which i can use for changing color only? (I can't use adobe now)

**Comment by owocki** [comment]
you could probably just edit in a text editor... if you know the from/to hex values

**Comment by thelostone-mc** [comment]
sketch / adobe is what folks who've contributed before have used! But yeah simply changing the hex 
Example: [Hairstyle](https://raw.githubusercontent.com/gitcoinco/web/master/app/assets/v2/images/avatar/HairStyle/womanhair-0ECF7C.svg)

**Comment by nanspro** [comment]
@owocki @thelostone-mc   i have fixed this PR with https://github.com/gitcoinco/web/pull/3720, could you review?

**Pull request merged**
