### PR TITLE
default gitcoin contrib 0 and hide

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- add d-none to hide UI
- defaults the number to 0

Screenshot 2020-12-10 at 8 54 13 PM
Screenshot 2020-12-10 at 8 54 57 PM

### CODE REVIEW

**Review by aamustapha — APPROVED** [review]
lgtm

**Review by danlipert — APPROVED** [review]

**Comment by owocki** [comment]
just tested; seems to be good to me.

**Review by aamustapha — APPROVED** [review]
LGTM

**Comment by owocki** [comment]
closing this due to convo with scott on slack

**Pull request closed without merging**
