### PR TITLE
WIP: Multiple submissions

### PR DESCRIPTION
**Pull request by zoek1**
##### Refers/Fixes
BUILD - Submit n Number of Projects Per Person per Prize #7772

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Closing this out for now cause it looks like it's being worked upon now! @zoek1 do reopen when this is ready to be review

**Comment by zoek1** [comment]
Ok @thelostone-mc, i'll reopening friday with new changes.

**Comment by thelostone-mc** [comment]
Any progress on this ?

**Comment by thelostone-mc** [comment]
Closing this out now !

**Pull request closed without merging**
