### PR TITLE
Inline validations

### LINKED ISSUE #554: inline validations
design: http://bits.owocki.com/1n350K0E3w1G/Screen%20Shot%202018-03-06%20at%207.19.14%20PM.png (referenced from https://user-images.githubusercontent.com/238235/36852925-0e56140e-1d3b-11e8-9cb3-31eafafa5538.png ) 

implement jquery.validator (or similar)... in order to do inline validation of the following forms:

* new tip
* new funded issue
* submit work
* accept work
* kill bounty

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
There are a few form validations but validations aren't consistent. So we included jQuery validate

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
UI

##### Testing
1. Pull down
2. Play with forms

##### Refers/Fixes
#554 

##### Examples

Errors
image

Success
image

### CODE REVIEW

**Comment by owocki** [comment]
@KennethAshley is this ready for reveiw?

**Comment by KennethAshley** [comment]
@owocki i talked to pixelant. There are a few things that need to be one. Doing them now.

**Comment by PixelantDesign** [comment]
We had a quick check-in today, looking good so far!

**Comment by mbeacom** [comment]
sorry
for the merge conflicts 😅

**Comment by mbeacom** [comment]
@KennethAshley Per our slack conversation, I'll have this tested on staging and merged once the conflicts are resolved... again. 😅

**Comment by mbeacom** [comment]
@KennethAshley 
```
/home/travis/build/gitcoinco/web/app/assets/v2/js/pages/new_bounty.js
  327:64  error  Parsing error: Unexpected token *
```

**Comment by mbeacom** [comment]
@KennethAshley Would you mind resolving the conflicts from #553 ?

**Comment by KennethAshley** [comment]
@mbeacom phew so this was a bit of a crazy rebase. I tested everything and it seems to be working well but i'd like more eyes on this just to confirm.

**Comment by mbeacom** [comment]
@KennethAshley This is deployed to https://stage.gitcoin.co right now.

Currently seeing this on submitting work to a bounty:

screenshot 2018-03-19 23 58 14
You can submit a fulfillment to a bounty without accepting the TOS.

**Comment by KennethAshley** [comment]
@mbeacom ok. looks like we missed the `required` tag on the TOS on that page. Should be fixed now.

**Pull request merged**
