### PR TITLE
Add new products page. Refs: #3278

### PR DESCRIPTION
**Pull request by mukulverm4**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [x] Ran `make test` and everything passed!

###### Reviewer

- [x] Affirm contributor guidelines have been followed and requested changes made
- [x] CI tests and linting pass
- [x] No conflicts (migrations, files, etc)
- [x] Regression tested against staging

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by owocki** [comment]
wow @mukulverm4 you made quick work of this!!!

can you add in the bottom module from the designs, and web-optimize the images for size?  other than that.. this is looking really good.

@thelostone-mc any comments?

**Comment by mukulverm4** [comment]
@owocki  I have made the images responsive. Can you please elaborate what do you mean by:
> web-optimize the images for size

**Comment by kuhnchris** [comment]
There's a command for that, it compresses svg and png in the project folder. Check the Makefile.

**Comment by owocki** [comment]
> web-optimize the images for size


the header image is 150 kb.  can it be slimmed down?

**Comment by mukulverm4** [comment]
Hey @owocki , I have made the necessary changes. Please check.

**Pull request merged**
