### PR TITLE
chore: removing unnecessary css on template Email

### LINKED ISSUE #7183: Daily Digest Email is Clipping
**Describe the bug**

When Gitcoin sends out a Daily Digest Email, the message is over 102 KB which means Gmail (and other clients) clip the message.

**To Reproduce**

Subscribe the Daily Digest and or check out:

* https://gist.github.com/jdorfman/9135252a45775c7bef24940046043802 (HTML = `108 KB` - `6 KB` over)

**Expected behavior**

Show the whole message, **NOT** say `[Message Clipped] View entire message`

**Screenshots**

image
image
image

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Browser Version: Version 84.0.4147.89 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

n/a

**Additional context**

This can be fixed by 

* The inline CSS is `15 KB` can be combined with `<link rel=3D"stylesheet" href=3D"https://s.gitcoin.co/static/v2/css/lib/typ=
ography.f6be2cb9c323.css">`
* Find and remove unused CSS classes and ID selectors.
  * https://purifycss.online/
image

### PR DESCRIPTION
**Pull request by developerfred**
##### Description
Removing css that is not being used and files that are not being used
Screen Shot 2020-08-19 at 16 39 44

##### Refers/Fixes
 #7183 #7201

##### Testing
[All screenshots ](https://drive.google.com/drive/folders/1UpHO8C7i0GSjQjHAAii6Qb6w2NnBfrD7?usp=sharing)
[movie 1](https://share.getcloudapp.com/DOuxqx4w)
[movie 2](https://share.getcloudapp.com/v1u2Y27d)

### CODE REVIEW

**Comment by jdorfman** [comment]
Thanks @developerfred! 

@octavioamu @danlipert how can we test to see if this fixes the Gmail "clipping" issue?

**Comment by thelostone-mc** [comment]
has all the email templates been tested via /_Admin view @developerfred  ?
Could you post screenshots of them

**Comment by developerfred** [comment]
> has all the email templates been tested via /_Admin view @developerfred ?
> Could you post screenshots of them

I only have 1 minute in the cloud app, I have these two videos I will make one more complete and put it on youtube
movie screen [1]-> https://share.getcloudapp.com/DOuxqx4w
movie screen [2]-> https://share.getcloudapp.com/v1u2Y27d

**Comment by jdorfman** [comment]
@developerfred what about `_administration/email/new_bounty_daily`? Not seeing it in the videos.

image

**Comment by developerfred** [comment]
> _administration/email/new_bounty_daily

@jdorfman sorry i will add this screen

**Comment by jdorfman** [comment]
Ok great thanks @developerfred

**Comment by jdorfman** [comment]
@developerfred do you need any help?

**Comment by jdorfman** [comment]
@developerfred if you have any questions please ask @danlipert @thelostone-mc

**Comment by jdorfman** [comment]
@thelostone-mc how are we looking?

**Comment by jdorfman** [comment]
@developerfred I would like to close this out and pay you. Where are you stuck?

**Comment by developerfred** [comment]
@jdorfman  I was unable to do a quest in my development instance.

**Comment by thelostone-mc** [comment]
@developerfred could you just hardcode those values and then populate the email for the sake of testing ?

**Comment by developerfred** [comment]
@thelostone-mc yes, I will do that.

**Review by octavioamu — CHANGES_REQUESTED** [review]
your are removing here a lot of code not related to the email templates, that will break a lot of things like darkmode on towsquare and everything showing the activity (activity_stream.css)

**Comment by danlipert** [comment]
@developerfred marking as draft until you have a chance to address @octavioamu 's comments

**Comment by developerfred** [comment]
@octavioamu  and @danlipert, I am put the files back in PR.  
I minified all email related files at email_style_min.css

**Comment by developerfred** [comment]
I put all these files in one: **(`./assets/css/email_style_min.css`)**
```
./assets/css/activity_stream.css
./assets/css/town_square.css
./assets/css/activity_stream.css
```

**Comment by thelostone-mc** [comment]
Closing this out as we did a major overhaul on emails and weeded out un-used styles along with it
PR: https://github.com/gitcoinco/web/pull/8413

**Pull request closed without merging**
