### PR TITLE
TLDR section on landing page

### PR DESCRIPTION
**Pull request by owocki**
# Feedback wanted on this:

# (Look at the TLDR section, fourth on landing page 👇 )

screencapture-localhost-8080-1513894996954

### CODE REVIEW

**Comment by thelostone-mc** [comment]
This looks sweet :D
@owocki Do you draw up these images yourself?

**Comment by owocki** [comment]
@thelostone-mc no! im an adobe illustrator n00b.    i found an illustrator on upwork that i like though

**Comment by owocki** [comment]
2a

21aaa
ss
untitled-2

some other stuff he's working on ^^

**Comment by thelostone-mc** [comment]
Woah :D do let him know, he's got a fan \m/

**Pull request merged**
