### PR TITLE
css: shrunk vertical navbar +  refactoring

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- shrunk vertical nav from col-3 to col-2
- refactored base.css

##### Checklist

- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/contributing/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

- ui
##### Refers/Fixes

Refs: https://github.com/gitcoinco/web/issues/133

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@owocki not big a change, just shrunk down the vertical navbar + refactored css
if it's better as it currently is, close the PR ^_^

**Comment by thelostone-mc** [comment]
@owocki yay or nay ? Don't wanna refactor that huge file again to resolve conflicts if it's worth it

**Comment by owocki** [comment]
sry been on vacay.  looking now

**Comment by owocki** [comment]
@thelostone-mc just tested it out.. and it looks quite good. 

hard to code review with all of the linting changes... we should all standardize on one linter preferences :)

go ahead nad resolve merge conflicts and i will merge.. pls ping me on slack when ready so that i can merge quickly and not leave the changes outstanding for too logn

**Comment by thelostone-mc** [comment]
@owocki Yeah I know 😓 I followed the what's set [here](https://github.com/gitcoinco/web/blob/master/.editorconfig#L15)

Resolved and ready for merge

**Comment by owocki** [comment]
> happiness will be the moment when the linter says -> 100% pass :')

amen to that

**Pull request merged**
