### PR TITLE
set description and image for SEO

### PR DESCRIPTION
**Pull request by x5engine**
Set description and image for SEO (twitter and facebook...)

PR fix for https://github.com/gitcoinco/web/issues/6645

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@x5engine would you be able to throw in a screenshot please?

**Comment by x5engine** [comment]
@thelostone-mc for this one I can't since I didn't get the docker image running on windows :'( help and I'll knock any bugs like flies, mosquitos and so on.

**Comment by danlipert** [comment]
@x5engine not sure why you are having issues on windows - maybe try setting up a ubuntu VM? Since you didn't get this running, I'm assuming this is untested?

**Comment by x5engine** [comment]
Untested but 90% working

**Comment by thelostone-mc** [comment]
locally seemed to work !

**Comment by x5engine** [comment]
It works! Would fix this

**Pull request merged**
