### PR TITLE
Add default ordering users in user directory

### LINKED ISSUE #4398: User Directory - Sort "Default view" by Contributor number
### User Story
As a funder I'd like to see the only relevant contributors to fulfill my bounty

### Definition of Done
- Display recently worked on your bounties first.
- Update default view (prior to entering a search) sorting to show contributors by leaderboard number
- Review with core team
- Post screenshot of implementation

- BE sort queries based on above
- add conditions when filtering

### Why
- We'd like to help funders easily find the best contributors to work with

### PR DESCRIPTION
**Pull request by rafalkowalski**
Please kindly review 
@octavioamu  @thelostone-mc 

##### Description
Shows your coworkers at the begining in user directory

image

##### Refers/Fixes
Fixes #4398

### CODE REVIEW

**Comment by octavioamu** [comment]
@rafalkowalski thanks for this I think this code is outdated in master since some fixes got into stable, tomorrow we will consolidate master and stable but maybe this code will need some changes to work with that.

**Comment by rafalkowalski** [comment]
@octavioamu Should i rebase it with master?

**Comment by thelostone-mc** [comment]
@rafalkowalski we made a hot patch fix on stable ! could you wait 12 hours before rebasing 
we need to get those commits into master

**Comment by rafalkowalski** [comment]
@octavioamu I've rebased it with master

**Comment by octavioamu** [comment]
Now can be rebased @rafalkowalski

**Comment by rafalkowalski** [comment]
@octavioamu done

**Comment by danlipert** [comment]
@rafalkowalski Can you update the description to include the required fields? Thanks!

**Comment by rafalkowalski** [comment]
@danlipert I've updated the description

**Comment by danlipert** [comment]
@rafalkowalski How was this tested? Can you include some screenshots or a video showing how the changes affect the current behavior? Thanks!

**Comment by rafalkowalski** [comment]
Screenshot at 2019-06-22 21-23-17


Screenshot at 2019-06-22 22-48-24

**Comment by rafalkowalski** [comment]
@danlipert thanks ;)

**Comment by PixelantDesign** [comment]
hooray!

**Pull request merged**
