### PR TITLE
Integrate 3Box and Gitcoin: Backup Gitcoin Profiles to 3Box [Gitcoin Global Communities Hackathon]

### PR DESCRIPTION
**Pull request by think-in-universe**
### Description

According to the requirements in [the GitCoin issue](https://gitcoin.co/issue/3box/3box/839/3793), we implemented 3Box integration for GitCoin:

- [x] Integrate 3Box.js into Gitcoin's frontend
- [x] UI for backing up my Gitcoin data to 3Box, inside of a "Gitcoin" space. This likely happens on a button from the "My Profile" page
- [x] When clicked, the user should be prompted to approve the messages inside their wallet (openBox() and openSpace() methods via 3Box.js). This logs them in to 3Box.
- [x] You will need to decide which data should be saved publicly, which should be saved privately (encrypted), and the keys to use for the key-value store.
- [x] Logic for updating a user's backup with new information. User can choose to update manually or automatically. 

##### Design Principles

1. Simplistic and seamless user experience for data synchronization.
1. Privacy and security: keep sensitive data safe at both client and 3Box cloud
1. Data interoperability: open / public data should be provided with context for external applications to utilize the datasets easily

##### Design Details

1. **User Experience**: Here we provide one-button click to get all the backup process done, and save the most meaningful data to user's 3Box Hub spaces. We may provide user more control over their data at different granularity, such as which fields to be exported, public or private, etc. 
1. **Data Model**: Here we used a pre-defined data models for the user profiles and contribution histories from the users, including the account info, statistics, feedbacks, grants, portfolio, active work, bounties, and activities, which are the major datasets that an external application could refer to make the best use of the value of the data. 
1. **Data Storage**: All the profiles data will be saved in a single "GitCoin" space, with public and private key-value for different fields. 
1. **Data Privacy**: When exporting data from the data source (or ETL process), we need to take care of both private fields and private items when mapping them into the GitCoin spaces key-value data structure. For a typical list of items, one solution is to divide them into 3 sets {public items with public fields, public items with private fields, private items) and saved separately with different keys. For example, private "feedback" items will be placed in a key-value pair called "feedbacks.private_items", while private "tip" fields will be saved in a key-value pair called "tips.private_fields"
1. **Automation**: Automatic update of profile data should be enabled or disabled based on the user scenario. We plan to also support the data synchronization at server side, in the case when the user would like to view data daily or at a fixed frequency. The client-driven data backup is not sufficient for certain use cases. 

##### Data Models

Now we export most of the necessary user profiles and contribution history, which can be extended to support more fields when needed.

**Profiles**

- Account Info
- Statistics
- Feedback
- Grants
- Portfolio
- Active Work
- Bounties
- Tips
- Activities

In the GitCoin space, we tackle the public and private data in below 
- Dictionary type data, such as, Account info and statistics are stored directly as key-value, with public or private keys
- For the keys of list type values, such as Grants, Bounties, Tips, etc., they're stored with below patterns:
    - **the public fields in public items** are stored with the key name such as "grants"
    - **the private fields in public items** are stored with a key of "private_fields" suffix, such as "tips.private_fields" (i.e. private_comments filed)
    - **private items** are stored with a key of "private_items" suffix, such as "feedbacks.private_items" (i.e. private feedbacks)

In the data export module, we use underscore (_) prefix for manually defining private keys, such as "_email" or "_feedbacks.private_items".

### Preview

Per the requirements, the user will find a 3box button for start synchronizing the data to 3box. 

1. 3Box button in the profile page

- user could single click the button to launch the backup process,
- or the user could long press the button (on web or mobile) to enable/disable automatic backup when he/she opens the profile page next time in the client (we may also support server-side backup later)

image

2. Profile backup started

After clicking the button, the user will be notified in MetaMask to consent the actions, and then resume the the backup process. You might need to wait for 10~30 seconds before the backup process is completed (depends on your network). 

image

image

3. Profile backup done

Once completed or failed, the user will be notified the backup result. He/she can checkout the result in his/her 3Box Hub page if the data is backed up successfully. 

image

Screen Shot 2019-12-20 at 12 29 05 AM

Screen Shot 2019-12-20 at 12 29 32 AM

4. Enable/disable automatic backup

By long press the 3Box button, user can enable/disable the automatic backup feature. 

image

If user has enabled automatic backup, the backup process will be started every time he/she opens the profile page. We may also support server side automatic backup later.

image

After the update, the outdated fields will be cleaned up automatically, and the new fields or values will be added automatically. 

##### Refers/Fixes

Fixes: https://github.com/3box/3box/issues/839

##### Testing

No tests have been added yet. We can add more tests for app/dashboard and JavaScript.

### CODE REVIEW

**Comment by think-in-universe** [comment]
Could anyone please share how to fix the **pytest** errors in CI?

I tried to reproduce the pytest failure locally, but met the below errors when execute test with `make pytest`. Am I missing any configuration before running the test? I deployed the local GitCoin app with Docker: https://docs.gitcoin.co/mk_setup/

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytest_django/plugin.py", line 162, in _handle_import_error
    yield
  File "/usr/local/lib/python3.6/dist-packages/pytest_django/plugin.py", line 326, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/dist-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 675, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 845, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 809, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/dist-packages/pytest_django/plugin.py", line 326, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/pytest_django/plugin.py", line 166, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'app'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
make: *** [pytest] Error 1

```

**Comment by danlipert** [comment]
@think-in-universe thanks for reporting the issue - fixed here: https://github.com/gitcoinco/web/pull/5642 if you rebase your branch on `master` you should be good to go

**Comment by think-in-universe** [comment]
@danlipert Hi Dan, it seems there're still errors after I updated the code to the latest, could you please help confirm what should I fix to pass the tests?

**Comment by think-in-universe** [comment]
@danlipert there should be a migrations conflict and should be fixed now. Do I need to fix the `
codecov/patch — 30% of diff hit (target 30.08%)` error?

**Comment by think-in-universe** [comment]
@danlipert the CI failure should be removed now 😄 thanks!

**Comment by owocki** [comment]
id like to get this merged soon...

**Comment by thelostone-mc** [comment]
resolving the conflicts and moving this over to https://github.com/gitcoinco/web/pull/5947

**Comment by octavioamu** [comment]
@think-in-universe we deployed this but is not working here you can check the sentry error in my profile https://sentry.io/share/issue/b1ee001d8e7948aa9f7b9a2df949ad8a/

**Comment by think-in-universe** [comment]
@octavioamu  It worked when we tested with 3Box team few weeks ago. I'll take a look and fix that ASAP.

**Comment by octavioamu** [comment]
You can test on your profile

**Comment by think-in-universe** [comment]
@octavioamu I have tested and figured out why the issue happens. I have proposed a fix here: https://github.com/gitcoinco/web/pull/5955

It would be nice if anyone could help test locally before merge it into master. It seems I cannot create bounties locally successfully today, probably due to IPFS connection issue.

**Comment by think-in-universe** [comment]
I was always hanging on the processing page after submitting a funded issue in my dev env. 

image

It seems it's waiting for syncing with web3, according to the console:

```
bounty_details.js:584 checking for updates
bounty_details.js:588 waiting for web3 to be available
bounty_details.js:590 waiting for tx to be mined
bounty_details.js:592 tx mined
bounty_details.js:621 syncing gitcoin with web3
```

**Comment by owocki** [comment]
this error is in prod rn https://bits.owocki.com/qGuo1Zrz

**Comment by think-in-universe** [comment]
@owocki thanks Kevin. this should already be fixed in this PR https://github.com/gitcoinco/web/pull/5981 which is submitted 3 days ago...

**Pull request closed without merging**
