### PR TITLE
adds polls to newsfeed

### PR DESCRIPTION
**Pull request by IntoThe1337ness**
##### Description

this PR adds polls to gitcoin newsfeed to allow poll of userbase

##### Refers/Fixes

discussion in newsfeed about poll

##### Testing

Screen Recording 2020-02-19 at 05 48 PM

### CODE REVIEW

**Comment by octavioamu** [comment]
Amazing!!! 
I will probably need your help on a voting system as the mechanics will be similar, maybe next week I will have the ticket ready and the bounty for you if you want it.

**Comment by IntoThe1337ness** [comment]
Looks like BUILD is failing. But I dont know why. Doesnt look Related to My PR logic.

**Comment by danlipert** [comment]
@IntoThe1337ness can you rebase these commits so they are against the master branch? Then it should kick off the appropriate tests

**Comment by IntoThe1337ness** [comment]
new PR https://github.com/gitcoinco/web/pull/6077

**Pull request closed without merging**
