### PR TITLE
[WIP] Hide tribes for user

### LINKED ISSUE #6424: as a suggested tribes user, i want to be able to X out suggested tribes so i dont have to see them again
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a suggested tribes user, i want to be able to X out suggested tribes so i dont have to see them again

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
to allow peoiple to filter through tribes that they dont want to see

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
suggested tribes
screen_shot_2020-04-12_at_1 59 24_pm

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
an X next to each suggested tribe, which when clicked
- removes that tribe from the DOM
- sends a PUT reuqest to the backend which stores an 'IgnoredSuggestedTribe' object in the DB
- refreshes the suggested tribes module with 5 new tribes
- next pageload, the X'd out tribe will not be loaded again

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description

Allows user to hide a suggested tribe.

##### Refers/Fixes
closes #6424

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@iamonuwa could we keep them as draft PRs until they are ready to go ?

**Comment by iamonuwa** [comment]
> @iamonuwa could we keep them as draft PRs until they are ready to go ?

I'll have to close it an open a new draft PR. I can't find the draft option.

**Comment by thelostone-mc** [comment]
@iamonuwa turned it into draft :P chill

**Comment by thelostone-mc** [comment]
Closing this out ! Do reopen when this is ready

**Pull request closed without merging**
