### PR TITLE
fix(hackathon): replace flyout panel with chat window

### PR DESCRIPTION
**Pull request by chibie**
##### Description

Use new window frame instead of flyout panel for chat in hackathon participants tab.

Here's a recording https://drive.google.com/file/d/1kKMIA_ciZUqPZI-CGJM9XDHqLWuY3Y56/view?usp=sharing

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by danlipert** [comment]
do we still want this PR in? looks like it now has conflicts @thelostone-mc @chibie

**Comment by danlipert** [comment]
what do y'all think given chat is being retired now? @thelostone-mc @PixelantDesign @vs77bb @chibie

**Comment by thelostone-mc** [comment]
I'd say we close this out in that case

**Comment by danlipert** [comment]
Sorry @chibie but since we are retiring chat soon I'm going to close this PR out

**Pull request closed without merging**
