### PR TITLE
Testimonials

### PR DESCRIPTION
**Pull request by tra38**
This is submitted on behalf of #63 - creating a testimonial module for Gitcoin. I'm happy to accept improvements for CSS styling. I couldn't get the small icons to line up nicely on mobile devices so no avatar is displayed on phones (however, it does display on tablets).

Carousel itself operates on pure HTML/CSS, though some Javascript is added to allow for auto-advancing and arrow key interaction. To add a testimonial to the carousel, you simply need to write a Python tuple containing the name, the path to the avatar image, and the testimonial.

### CODE REVIEW

**Comment by owocki** [comment]
This is awesome!  Thank you @tra38 .

where do i control the frequency of it auto-scrolling to the next testimonial?

A few things I noticed from my QA (all QA in chrome):
1. doesn't scale to mobile size very well.
2. at very wide resolutions there is a y scroll on the right hand side of the module.
3. at very wide resolution, the alignment is kind of messed up http://bits.owocki.com/0E1j2Y1b180K/Image%202017-12-02%20at%209.18.50%20PM.png

otherwise, i think this looks really good.  i need to circle back with the folks who are actually going to be on the testimonials page and get their real quotes / avatars

**Comment by tra38** [comment]
Hey @owocki. I'm not that great at CSS to begin with...and I'm stuck in trying to fix those issues, so I cannot go any further. So someone else should probably fix them. I really do like this job site, and I would definitely take more projects...but this specific project was difficult because it wasn't really a good language for me to work in. I tried though. :)

I'm pretty good at languages that are not CSS, so let me push up a change to make it very easy for you to change the duration of the carousel. Hopefully that works out. Thanks.

**Comment by owocki** [comment]
thanks for your work so far @tra38 -- its been good working with you!  ill put the css cleanup on my TODO list, and if not, someone else can pick it up for a small tip

btw, are you in the gitcoin.co/slack slack channel?  have a question to ask you, but GH comments is not the place.

**Comment by tra38** [comment]
Thanks, @owocki! It was pleasure working with you too.

I just registered an account on the Gitcoin Slack under the name "Tariq Ali", so ask me there then.

**Comment by owocki** [comment]
thank you again for your PR here.  ill give you a good portion of the bounty :)

closing this PR in favor of https://github.com/gitcoinco/web/pull/80#issuecomment-349195075 now

**Pull request closed without merging**
