### PR TITLE
Pin the slackclient and websocks version to solve conflicts.

### LINKED ISSUE #4367: ModuleNotFoundError: No module named 'slackclient'
**Describe the bug**
`ModuleNotFoundError: No module named 'slackclient'`

**To Reproduce**
pull the newest code, and run 
```
docker-compose up --build
```
 to run the code, it throws out an error:
```
ModuleNotFoundError: No module named 'slackclient'
```

**Expected behavior**
it should not throw out this error.

### PR DESCRIPTION
**Pull request by Skyge**
Fix #4367

### CODE REVIEW

**Comment by Skyge** [comment]
Thanks for @usmanmuhd help, at now, I use the version of `1.1.1`, It works, but I am not sure whether it is the best version. @owocki any idea? 
BTW, maybe we should pin all modules version.

**Comment by danlipert** [comment]
> Thanks for @usmanmuhd help, at now, I use the version of `1.1.1`, It works, but I am not sure whether it is the best version. @owocki any idea?
> BTW, maybe we should pin all modules version.

I thinking pinning all modules isn't a bad idea, gives us some more control over these types of issues at the expense of having to be more vigilant about dependency security updates. @Skyge have you tested the Kudos functionality after pinning the websockets version?

**Comment by Skyge** [comment]
@danlipert Not yet, when I try to solve the incompatible version problem of `slackclient`, I find there is a tip for websockets version, so I make a change at the same time.

**Comment by Skyge** [comment]
> gives us some more control over these types of issues at the expense of having to be more vigilant about dependency security updates.

Yeah, that is a truth, we really need to update to use the new version to prevent potential risks, and we also should test to prevent incompatible problem caused by new version. so how to know we should update our dependency modules in time? write a shell to monitor? or others ways?

**Comment by Skyge** [comment]
@danlipert As a matter of fact, after I solve the imcompatible version problem, I meet another problem : #932, I can not connect to ipfs, I am not sure wether it has impact on testing Kudos functionality.

**Comment by danlipert** [comment]
@Skyge do you have that problem if you switch to the master branch? I wonder if it is related to the websocket change somehow

**Comment by Skyge** [comment]
@danlipert Yeah, I have already switch to the master branch, and do not specify the websocket version, but it also throw out that error.

**Comment by Skyge** [comment]
Even though I go back to a earlier working well version now, it will not work again.

**Pull request closed without merging**
