### PR TITLE
more designs added

### PR DESCRIPTION
**Pull request by mehul0698**
##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [ ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by mehul0698** [comment]
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have added 7 more accessories. The last one is a sword. It looks very cool, do check that out. Please review the pr.

**Comment by mehul0698** [comment]
Hey did you see the pictures I posted on the other thread with all the misplaced assets?

**Comment by thelostone-mc** [comment]
@mehul0698 mind tagging the link here ?

**Comment by mehul0698** [comment]
@thelostone-mc #3971

**Comment by mehul0698** [comment]
@thelostone-mc don't merge this pr. I'll push the corrected assets on this branch.

**Comment by mehul0698** [comment]
More mistakes
image

**Comment by mehul0698** [comment]
image
image
image
image
image
image

**Comment by mehul0698** [comment]
@thelostone-mc I have corrected 6 assets. Please review the pr.

**Comment by mehul0698** [comment]
Will I get paid for correcting them?

**Comment by owocki** [comment]
hey -- before i answer that question @mehul0698 -- who originally added the assets that were misplaced?  does your fix apply across all assets / how can we prevent this in the future?  how did you fix them and how much time did it take per asset

**Comment by mehul0698** [comment]
I think the assets were added by yash412. I have fixed the ones that I was able to find. To prevent in this future you just ask them to upload 2 pictures for each asset one in avatar builder and one once it is saved as the problem with these assets was not in the avatar builder but once they were saved they appeared out of place. 4 of these I had to resize and make minor changes and change their .txt file but the bird and necklace I made them from scratch as resizing was not working for them. For all the assets that I make upload 2 pictures to give you the assurance that they will work anywhere and that they meet size criteria. The problem with some of these assets was that the artboard size was messed up and once I corrected that the asset got messed up so had to redo a lot in it. I hope this helps.

**Comment by mehul0698** [comment]
@owocki I think there might be more as when I was looking for inspiration I found these.

**Comment by owocki** [comment]
@mehul0698 did you correct the artboard sizes in sketch?  if so, are there guidelines with respect to artboard sizes we should start enforcing?

**Comment by mehul0698** [comment]
Yes and do make sure they upload both pictures as it might look alright in the avatar builder but once saved it appears out of place. In the bounty description you have mentioned the gitcoin style guide in one line. I suggest you put more emphasis on that as some designs dont even follow the colour guidelines. Mainly I saw some developer using a misplaced asset on gitcoin and does not look good for the brand.

**Comment by mehul0698** [comment]
@owocki the mail you sent about avatars to everyone also had misplaced assets. The one I got was also in bad shape.

**Comment by mehul0698** [comment]
image
Look at this one.

**Comment by mehul0698** [comment]
@owocki The black partial background ruins this clothing option. No one is going to use this.

**Comment by mehul0698** [comment]
image
In the avatar builder this looks fine.

**Comment by mehul0698** [comment]
image
This one also.

**Comment by mehul0698** [comment]
@owocki The pr has been merged. I made 7 accessories out of which I consider 4 to be exotic. You owe me around 125 to 130 dollars.
If its fine by you I corrected 6 accessories out of which 2 I had to make from scratch, for that you could pay me 50 to 60 dollars.
If you want I could look into other messed up assets also. TIA

**Comment by mehul0698** [comment]
@owocki do you want me to look into other assets?

**Comment by mehul0698** [comment]
@owocki @thelostone-mc I have made 2 more designs should put a pr?

**Comment by owocki** [comment]
sorry, was away for the weekend.  yes pls PR the last two designs

**Comment by mehul0698** [comment]
@owocki As avengers endgame is about to release so one of them is avengers related. If it contains the avengers logo will it have any proprietary problems?

**Comment by owocki** [comment]
its probably not a great idea to include anything proprietary

**Comment by owocki** [comment]
its probably not a great idea to include anything proprietary.  it can be inspired by avengers, but not lifted from avengers

**Comment by mehul0698** [comment]
Cool. I'll change it.

**Comment by owocki** [comment]
@mehul0698 hey just got back from traveling.  whats our tab up to now?  i see i paid you 1.1 ETH about  6 days ago

**Comment by mehul0698** [comment]
All previous payments are done except this pr. This was merged 5 days ago. 
I made 7 accessories out of which I consider 4 to be exotic. You owe me around 125 to 130 dollars.
If its fine by you I corrected 6 accessories out of which 2 I had to make from scratch, for that you could pay me 50 to 60 dollars.
I have put another pr with 3 designs #4040

**Comment by owocki** [comment]
ok so 175 to 190?

**Comment by mehul0698** [comment]
Yes. Thanks

**Pull request merged**
