### PR TITLE
U Remove the duplication in the CONTRIBUTORS.

### LINKED ISSUE #4389: As a gitcoin user, when I create a grant, I do not want to see duplicate contributors
### User Story

As a gitcoin user, I want to get the correct number of a grant contributors.

### Why Is this Needed

There are some duplications in the grant contributors, so sometimes it misleads me.

*Summary*:

### Description

*Type*:Feature

### Current Behavior

image

As you can above, it will display five contributors, but as a matter of fact, it is just some extra donations, and it is two people.

### Expected Behavior
Remove duplicate contributors.

### PR DESCRIPTION
**Pull request by Skyge**
Fix #4389 
Rebase #4388

### CODE REVIEW

**Comment by Skyge** [comment]
@danlipert Should I do like this?

**Comment by Skyge** [comment]
Emmm, I am not similar with git commands, I always use sourceTree instead, so should I use `git rebase -i xx`?

**Comment by owocki** [comment]
why do this in the template instead of in the `views.py` ?  simple as adding a `.distinct()` to the views.py

**Comment by Skyge** [comment]
Emmm, OK, I will try to do it later.

**Comment by danlipert** [comment]
> Emmm, I am not similar with git commands, I always use sourceTree instead, so should I use `git rebase -i xx`?

Looks like you got it! Theres a couple ways you can go about it, but I do interactive rebase like the command you suggested.

**Comment by Skyge** [comment]
@owocki the test querySet is 
```ts
<QuerySet [<Contribution: id: 5; 0x8a84a3fc... => subs:id: 6; PAST DUE, 5.000000000000000000 
FOO / 30 days for grant 1 created 1 month, 4 weeks ago by moving-forward ( active: True, billed 1 
times, last contrib: 1 month, 4 weeks ago, next contrib: 4 weeks ago ); 1 month, 4 weeks ago>, 
<Contribution: id: 4; 0x3b244351... => subs:id: 5; PAST DUE, 5.000000000000000000 FOO / 30 
days for grant 1 created 1 month, 4 weeks ago by moving-forward ( active: True, billed 1 times, last 
contrib: 1 month, 4 weeks ago, next contrib: 4 weeks ago ); 1 month, 4 weeks ago>, <Contribution: 
id: 3; 0x1f001240... => subs:id: 3; PAST DUE, 5.000000000000000000 FOO / 30 days for grant 1 
created 1 month, 4 weeks ago by follow-er ( active: True, billed 1 times, last contrib: 1 month, 4 
weeks ago, next contrib: 4 weeks ago ); 1 month, 4 weeks ago>, <Contribution: id: 2; 0x2ff05b15... 
=> subs:id: 2; PAST DUE, 5.000000000000000000 FOO / 30 days for grant 1 created 1 month, 4 
weeks ago by follow-er ( active: True, billed 1 times, last contrib: 1 month, 4 weeks ago, next contrib: 
4 weeks ago ); 1 month, 4 weeks ago>, <Contribution: id: 1; 0x62f9f6e5... => subs:id: 1; PAST DUE, 
5.000000000000000000 FOO / 30 days for grant 1 created 1 month, 4 weeks ago by follow-er ( 
active: True, billed 1 times, last contrib: 1 month, 4 weeks ago, next contrib: 4 weeks ago ); 1 month, 
4 weeks ago>]>
```
I want to remove duplicates in this querySet according to `admin_profile`, (you can there are 5 contributions from two person: `follow-er` and `moving-forward`)I am not similar with ORM operation, so I have got to use template tag to do it at first. I have tried some times and searched for solutions, but I still can not use `distinct()` to do it. this really upsets me.

**Comment by octavioamu** [comment]
@Skyge mind solving the conflicts? code look good to me

**Comment by Skyge** [comment]
@octavioamu Sorry for replying so late, I will solve the conflicts later today.

**Comment by Skyge** [comment]
There have been many changes since my last submission, so I have got to review and have a test.

**Comment by thelostone-mc** [comment]
@Skyge looks like this slipped through the cracks and now we've got conflicts again!
Let me know if you can clean em up and we can get it in next week

**Comment by Skyge** [comment]
I am not sure, we have made a lot of changes, maybe this has been fixed. Some of my other PRs were closed because they were fixed.

**Comment by thelostone-mc** [comment]
Alright closing this out ! 
I'll reopen if this ever comes up again 

Thanks @Skyge ^_^ & stay safe

**Pull request closed without merging**
