### PR TITLE
Implemented Spock ears in avatar builder

### PR DESCRIPTION
**Pull request by jakerockland**
##### Description

Adds Spock ears as an ear option in avatar builder.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

avatar

##### Testing

Tested locally, screenshots below:

screenshot 2018-10-23 22 45 47
screenshot 2018-10-23 22 45 51
screenshot 2018-10-23 22 45 55
screenshot 2018-10-23 22 46 01

##### Refers/Fixes
Fixes: #2467

### CODE REVIEW

**Comment by jakerockland** [comment]
@owocki any chance of having this paid with a tip? I goofed and since ETH prices have fallen and I have almost my all my ETH in cold storage that I don't have physical access to right now, I don't have ETH in my Metamask to pay tx fee to submit the bounty for this one 😅 Buying ETH on Coinbase to pay the tx. fee is saying it won't be til October 29th that I can transfer the ETH out of Coinbase and buying ETH with DAI also seems impossible without having ETH to pay the transactions fees 😂😅

**Comment by thelostone-mc** [comment]
> was this more of an optical illusion type

Yeah this was probably it 😅 

> I exported with svgo plugin from Sketch so I believe they are already compressed..?

Looks like it could have been compressed further by running `svgo` via terminal. Did it this time, could you run it next time from your end before pushing it in ?  ^_^

**Comment by thelostone-mc** [comment]
Looks awesomeeee

screen shot 2018-10-24 at 12 29 59 pm

**Comment by jakerockland** [comment]
Hrm that’s very good to know, will stop relying on the SVGO plugin and just install the CLI, thanks @thelostone-mc 😄❤️

**Comment by owocki** [comment]
just sent ya a tip jake

**Comment by jakerockland** [comment]
so rad, thank you @owocki

**Pull request merged**
