### PR TITLE
factors trust bonus into a parameter on profile

### PR DESCRIPTION
**Pull request by owocki**
##### Description

factors trust bonus into a parameter on profile

we should port this into the grants/clr code to manage the trust bonus additions there in a DRY way :)

##### Refers/Fixes

convos with aditya/frank

##### Testing

tested locally

### CODE REVIEW

**Comment by owocki** [comment]
@frankchen07 can we use this code to massively simplify this part of the clr code ??? https://github.com/gitcoinco/web/blob/master/app/grants/clr.py#L207-L222

**Comment by owocki** [comment]
@frankchen07 can you update your code to use this as the source of truth for the users trust bonus?

@thelostone-mc is this ok to ship? i want to ask participants in https://github.com/gitcoinco/skunkworks/issues/187 to update it

**Comment by owocki** [comment]
@frankchen07 @thelostone-mc  pls review. the idena integration blocks on this ( https://github.com/gitcoinco/web/pull/7646 )

**Review by thelostone-mc — APPROVED** [review]
@frankchen07 this looks alright to me !
It just wires in the prop and we'll have to update clr.py to use this prop

**Review by danlipert — APPROVED** [review]

**Pull request merged**
