### PR TITLE
Upgrade cryptography python package to 2.3 - Security

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description

The goal of this PR is to resolve a security advisement from GH regarding the `cryptography` python package.

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)

security, cryptography, dependencies

##### Testing

Locally via Rinkeby on:  https://github.com/mbeacom/test-repo/issues/66

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Merging on monday!

**Comment by pinkiebell** [comment]
Yippie! /This also paves the way for a alpine based docker images. /shameless advertisement

**Comment by mbeacom** [comment]
Live on staging. Testing with @SaptakS

**Comment by mbeacom** [comment]
All on-chain functionality was tested on staging - cc @SaptakS

**Pull request merged**
