### PR TITLE
Improvements codacy

### LINKED ISSUE #6158: codacy improvements on base code
https://app.codacy.com/manual/codingsh/web/dashboard?bid=16864489
Screen Shot 2020-03-06 at 03 15 25

### PR DESCRIPTION
**Pull request by developerfred**
##### Refers/Fixes
#6158

### CODE REVIEW

**Comment by owocki** [comment]
whats the new issue count after this is merged

**Comment by developerfred** [comment]
> whats the new issue count after this is merged

I believe that there are still 1,500 but they are not critical issues.

**Comment by danlipert** [comment]
This affects so many files, is undoubtedly going to have conflicts as new PRs get merged, and is difficult to review to say the least... I'd have to have a extremely good rationale as to why this would be important to get in, and you would have to have thoroughly tested every feature on the site to ensure there were no issues. May I suggest breaking this up into individual high priority issues, or fixing this file by file instead of submitting everything at once

**Comment by thelostone-mc** [comment]
@developerfred closing this out ! It is hard to get review done on this 
If you're up for it -> I'd really like us to batch this out into smaller PR so that it's safer to get in

**Pull request closed without merging**
