### PR TITLE
fixes https://github.com/gitcoinco/web/issues/876

### PR DESCRIPTION
**Pull request by owocki**
https://github.com/gitcoinco/web/issues/876

### CODE REVIEW

**Comment by mbeacom** [comment]
I was intending on tackling the whole lot of this in a PR aimed at adding timezone support to the platform, but this should work fine for serving everything as UTC for the moment.  The postgresql dbs are set to UTC for timezone right now, but I'm not sure what the implications are pertaining to DTs that have been using `SuperModel` timezone specific DTs versus `auto_add`.

**Comment by owocki** [comment]
most of the times on the frontend of the app are relative to current time anyway.. so i dont know if whole timezone support is necessary... what were you hoping to accomplis htere?

**Comment by owocki** [comment]
http://bits.owocki.com/1Y1z3q3t2R0U/Screen%20Shot%202018-04-18%20at%2012.06.01%20PM.png

yay this fixes the issue in #876

**Comment by mbeacom** [comment]
Adding fully baked timezone support, so if a user is viewing details with datetimes, it displays appropriately for their TZ.  My main goal with implementing proper TZ support is to keep aligned with our other initiatives for localization and internationalization support on the platform... seems like it'd make sense to be all in on `i18n` - 🤷‍♂️  than to half implement.  This makes sense as a stopgap for the moment, but it's probably a good idea revisit the way we're pulling `now` and handling DTs throughout the platform, whether we stick with everything displaying in UTC or not.

**Pull request merged**
