### PR TITLE
add violet background and resize Discover Grants section

### PR DESCRIPTION
**Pull request by Jer-Sch**
##### Description

This PR adds additional styling to the Discover Grants section on the grants homepage.

Design:
Screen Shot 2021-12-02 at 11 17 55 PM

This PR:

Screen Shot 2021-12-02 at 11 46 25 PM

##### Testing

Automated tests not required for this change.

### CODE REVIEW

**Review by nutrina — COMMENTED** [review]
Question: since these styling changes only apply to that particular file, would it not make sense to put them in the html file directly? I would try to put only shared stuff in the base.scss.
The `index.html` already has an <style> section, could the scss be added there?

**Comment by thelostone-mc** [comment]
@nutrina has a good point! I'd suggest moving all that scss to it's own file (including the one in html) and updating that

**Comment by ksolo** [comment]
I have this work in another PR related to GITC-602. Was this part of another ticket?

Regarding styles, you can use bootstrap provided classes for nearly everything you are doing here and shouldn't need much if any css.

**Comment by Jer-Sch** [comment]
@ksolo I was told that this work was supposed to be completed with the announcement banner work on this ticket: https://gitcoin.atlassian.net/browse/GITC-568, but I'm happy to close this if it's already been done.

**Comment by Jer-Sch** [comment]
Closing this because this work was handled already in GITC-602

**Pull request closed without merging**
