### PR TITLE
Gov nav WIP - Should be overridden by Alisa/Design Squads design.

### PR DESCRIPTION
**Pull request by owocki**
##### Description

Gov nav WIP - Should be overridden by Alisa/Design Squads design.

##### Refers/Fixes

https://www.notion.so/gitcoin/Add-Gov-Gitcoin-co-to-Nav-9e2db02a58914cb889572d048eb418dc

##### Testing

Screen Shot 2021-06-03 at 3 11 13 PM

### CODE REVIEW

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
indent fix needed and is this still a WIP ?

**Comment by owocki** [comment]
its only a WIP in so far as were waiting for designs from design squad.  i'm fine shipping it but thats really up to the GPG

**Comment by frankchen07** [comment]
@PixelantDesign do you have any comments on this before we push?

**Review by PixelantDesign — CHANGES_REQUESTED** [review]
Looks great! 
Could we change description to:

Help decide the future of Gitcoin

**Comment by gdixon** [comment]
Updated screenshot:

Screenshot 2021-06-08 at 14 51 12

**Pull request merged**
