### PR TITLE
adds the ability to toggle persona on profile

### PR DESCRIPTION
**Pull request by owocki**
##### Description

what:
- adds the ability to toggle persona on profile
- if its not your profile, lets you click through to leaderboard
- simplifies profile so you dont have to look at two diff sets of stats (funder + contributor)

##### Refers/Fixes

https://github.com/gitcoinco/web/issues/4631

##### Testing

external to profile
Screen Recording 2019-07-21 at 11 17 AM

if it's your profile:
Screen Recording 2019-07-21 at 11 17 AM_1

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Screenshot 2019-07-22 at 4 55 15 PM

Hmm I still feel this is cleaner ! 
The click seems a lil cryptic 

cc @frankchen07 @PixelantDesign @willsputra  defer to you guys on this

**Comment by owocki** [comment]
the problem with the above is that it shows contributor stats and funder stats all in one, thus creating information overload for the browser -- who is likely only interested in one of those personas.

**Comment by octavioamu** [comment]
hummm the switcher already exist into https://gitcoin.co/settings/account I think should be something we don't motivate people to be switching between them. 
Also Im with Aditya I really like to have the 2 informations in my profile

**Comment by frankchen07** [comment]
Like Octavio said, the switcher does exist, but it's purely to toggle their designation in the backend / what I see in the data. If we were to use a toggle (this ticket), it wouldn't be for designation, but more for switching experiences. It's like saying "I identify as a funder" (designation), but "because I also contributed to some bounties, I want to see my contributor stats" (hits a toggle switch to "contributor") to see the stats. The designation also takes into account the onboarding experience.

That being said, I'll say that we haven't had anyone give any validation / complaints / asks about toggling between funder and contributor stats or profiles. The proportion of users who are power contributors and power funders is quite a small percentage. 

My case is to hold off on releasing this until we can really hash out a quality, personalized experience on both sides. 

@PixelantDesign for extra thoughts

**Comment by owocki** [comment]
my intent was just to make the profiles simpler (and higher ROI) for the viewer, but i defer to product on this of course.

> My case is to hold off on releasing this until we can really hash out a quality, personalized experience on both sides.

is there a ticket for this?  i'd be happy to jam on this with whomever is writing it!

**Comment by frankchen07** [comment]
@owocki - no in depth ticket yet, but depending on priorities, if we can fit in a workshop somewhere or take it up as a side project, we could do that. I'll bring it up in our product breakout today and see where it falls.

**Comment by owocki** [comment]
i have an action item to present my 'vision' for the profile sometime soon.  would also be down to workshop with @frankchen07 @PixelantDesign @willsputra sometime

**Comment by octavioamu** [comment]
This was reverted and merged on #5214

**Pull request merged**
