### PR TITLE
javascript: convert to es6 and make sure it passes linting

### PR DESCRIPTION
**Pull request by ethikz**
##### Description
This PR adds a base for eslint going forward.  Will need to contribute this going forward and check the changes don't break anything.

##### Checklist
- [x] linter status: 100% pass
- [x] commit message follows [commit guidelines]

##### Affected core subsystem(s)
All subsystems

##### Refers/Fixes
This is a cleean redo of #111.

@mbeacom @thelostone-mc @owocki 

If you want these squashed, just let me know.

### CODE REVIEW

**Comment by owocki** [comment]
looks good to me... @mbeacom ?

also: what do i need to start doing so i dont keep breaking things for the linter? maybe worth an update to the contributing guidelines soon...

**Comment by thelostone-mc** [comment]
@ethikz finally!! :D

**Comment by owocki** [comment]
:shipit: :)

**Comment by ethikz** [comment]
No!! why is there conflicts again lol

**Comment by owocki** [comment]
@mbeacom @ethikz should we 🚢 it ?

**Comment by mbeacom** [comment]
@owocki I'm good with merging this. :shipit:

**Pull request merged**
