### PR TITLE
check if web3Modal is defined before

### PR DESCRIPTION
**Pull request by x5engine**
web3Modal

### CODE REVIEW

**Comment by danlipert** [comment]
Hey @x5engine thanks for this - how was this tested? thanks again

**Comment by x5engine** [comment]
you are very welcome, tag me if you have any other bugs

**Comment by thelostone-mc** [comment]
Closing this out cause we've redone how web3 modal is set up!
Thanks @x5engine  ^_^

**Comment by x5engine** [comment]
Thank you any tip would help

**Pull request closed without merging**
