### PR TITLE
Made the requested changes! 

### PR DESCRIPTION
**Pull request by yash412**
##### Description

Solved the conflicts, made the Elf-Hat little wider and ran SVGO on the svg files. 

I made multiple new items on the previous PR. 
PR for reference - #3825
screenshot 2019-02-23 at 5 56 17 pm

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [x] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [x] Changes don't break existing behavior
- [ ] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

###### Contributor

- [x] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Tested all changes **locally**
- [x] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@yash412 conflicts still persist :P

**Comment by yash412** [comment]
Can you review them again @thelostone-mc! 
Thanks a ton.

**Comment by yash412** [comment]
These are the names of the newer assets, yet it is appearing as a conflict. Can you suggest what needs to be done? @thelostone-mc

**Comment by thelostone-mc** [comment]
Took care of it ^_^

**Comment by yash412** [comment]
@thelostone-mc just out of curiosity, what was the issue?

**Comment by thelostone-mc** [comment]
@yash412 I just pulled it in and resolved the conflicts. 
I'm guessing someone else had touched that line and thus entered the conflicts

**Pull request merged**
