### PR TITLE
Add autotranslate base

### PR DESCRIPTION
**Pull request by mbeacom**
##### Description

The goal of this PR is to add `autotranslate` and introduce `German` locale.

Adds:

- `autotranslate` django app
- `make autotranslate` command for automatically translating/updating existing translations

Langauge support for:

```
[
    ('en', _('English')),
    ('es', _('Spanish')),
    ('de', _('German')),
    ('hi', _('Hindi')),
    ('it', _('Italian')),
    ('ko', _('Korean')),
    ('pl', _('Polish')),
    ('zh-hans', _('Simplified Chinese')),
    ('zh-hant', _('Traditional Chinese')),
]
```

TODO:

Add mechanism to automatically replace poorly parsed special characters for python dynamic vars.
Example:

```shell
#: dashboard/templates/shared/nav_auth.html:54
#, fuzzy, python-format
#| msgid "Claim $%(tip.value_in_usdt_now)s Tip "
msgid "Claim $%(tip.value_in_usdt_now)s Tip "
msgstr "Claim $% (tip.value_in_usdt_now) s Tipp"
```

should be:

```shell
#: dashboard/templates/shared/nav_auth.html:54
#, fuzzy, python-format
#| msgid "Claim $%(tip.value_in_usdt_now)s Tip "
msgid "Claim $%(tip.value_in_usdt_now)s Tip "
msgstr "Claim $%(tip.value_in_usdt_now)s Tipp"
```

##### Checklist

- [x] linter status: 100% pass
- [x] changes don't break existing behavior
- [x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)

##### Affected core subsystem(s)
i18n

##### Testing
Tested locally

##### Refers/Fixes
Ref #814

### CODE REVIEW

**Comment by owocki** [comment]
can we source someone who is german to tell us how good/bad the autotranslate is? if not german, maybe another language?  vivek might be able to help us with sourcing this person

**Comment by mbeacom** [comment]
screenshot 2018-07-11 12 47 02

**Comment by mbeacom** [comment]
@owocki This PR should be good to merge - Test the latest at: https://stage.gitcoin.co -> Settings -> Preferred Language

**Comment by owocki** [comment]
@mbeacom go for it

> Temporarily disabled zh (Chinese) and po (Polish).

How come ?

**Comment by owocki** [comment]
@PixelantDesign @mbeacom Do we want to auto-translate visitors based upon IP addresses?

https://github.com/gitcoinco/web/issues/1695

**Comment by owocki** [comment]
oh also, it might be worth testing the emails @mbeacom

**Comment by mbeacom** [comment]
@owocki We can serve the appropriate language based on their `Accept-Language` header, enable language endpoints `gitcoin.co/en`, `gitcoin.co/es`, etc, use the ip aware tracking based on the locale of the IP, or simply use the preferred language established in settings.  As it stands right now, the majority of the handling is done based on the user's preferences and based on the language header provided by the browser.  I am not 100%, but the copy not displaying in the requested language might be a product of serving over CDN. 🤔 

Also, testing emails now!

**Comment by owocki** [comment]
> @owocki We can serve the appropriate language based on their Accept-Language header, enable language endpoints gitcoin.co/en, gitcoin.co/es, etc, use the ip aware tracking based on the locale of the IP, or simply use the preferred language established in settings. 

i think the `Accept-Language header` stuff is important for conversion (before the user has an account, i.e. upon first landing page visit)

> As it stands right now, the majority of the handling is done based on the user's preferences and based on the language header provided by the browser. I am not 100%, but the copy not displaying in the requested language might be a product of serving over CDN. 🤔


got it.  we should figure out the CDN issue before going live, since the prod site is on the CDN

**Comment by owocki** [comment]
@mbeacom this is a prioroity for decentralland -- any way we can prioritize shipping it?

**Comment by mbeacom** [comment]
@owocki It was my mistake.  I specified `zh` vs with the necessary secondary identifier `zh-hant` or `zh-hans`.  They are present in this PR.

**Pull request merged**
