### PR TITLE
jeremy/update styling for announcement banner

### PR DESCRIPTION
**Pull request by Jer-Sch**
##### Description

Updates styling for announcement banner.

Screen Shot 2021-11-30 at 5 08 49 PM

##### Testing

Tested locally

### CODE REVIEW

**Comment by gdixon** [comment]
I've pushed in some fixes for the responsive view:
Screenshot 2021-12-01 at 01 51 32

Screenshot 2021-12-01 at 01 51 46

**Comment by gdixon** [comment]
I've pushed in some fixes for the responsive view:


Screenshot 2021-12-01 at 01 51 32

Screenshot 2021-12-01 at 01 51 46

**Comment by Jer-Sch** [comment]
Thanks @gdixon ! Sorry I forgot to check that.

**Review by gdixon — APPROVED** [review]

**Review by thelostone-mc — APPROVED** [review]

**Review by Apettinato7 — COMMENTED** [review]
@apettinato7

**Pull request merged**
