### PR TITLE
Adding batgirl mask Refs: https://github.com/gitcoinco/web/issues/3713

### PR DESCRIPTION
**Pull request by kvndlgs**
##### Description

I've designed a batgirl mask for the avatar accessories.

52e8ad0f-1296-4fb8-8fdf-d0db2decca9c

image

##### Checklist

- [x] Read and conforms to the [contributor guidelines](https://docs.gitcoin.co/mk_contributors/)
- [x] Read and conforms to the [style guidelines](https://docs.gitcoin.co/mk_styleguide/)
- [ ] Linter status: 100% pass
- [ ] Added relevant tests
- [ ] Tests pass and code coverage has not decreased
- [ ] Changes don't break existing behavior
- [x] Commit message follows [commit guidelines](https://docs.gitcoin.co/mk_contributors/#step-4-commit)
- [ ] [Code documentation](https://docs.gitcoin.co/mk_contributors/#docstrings)
- [ ] Completed: Code review by core team and any requested changes

##### Affected core subsystem(s)

ui, assets

##### Refers/Fixes

Refs: #3713 

##### Testing and Sign-off

Tested with the template provided to make sure everything's fit, but unable to run the site locally.

###### Contributor

- [x ] Read and followed the [Contributor Guidelines](https://docs.gitcoin.co/mk_contributors/)
- [ ] Tested all changes **locally**
- [ ] Verified existing functionality
- [ ] Ran `make test` and everything passed!

###### Reviewer

- [ ] Affirm contributor guidelines have been followed and requested changes made
- [ ] CI tests and linting pass
- [ ] No conflicts (migrations, files, etc)
- [ ] Regression tested against staging or local deployment

###### Funder

- [ ] Validated requested changes were made to specification
- [ ] Bounty payout released to the contributor

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Could you do the following 

- [ ] use 1 tab == 2 spaces
- [ ] `svgo` on the svgs to compress them
- [ ] resolve conflicts
- [ ] show screenshot/gif of avatar being saved on the local app so that we know it renders alright
- [ ] undo the indentation changes


^ Post that this should be good for merge 🙌

**Comment by kvndlgs** [comment]
hi, i actually have a hard time running locally on windows 10.

**Comment by thelostone-mc** [comment]
Ah this can't be merged in unless all your comments are addressed!
Gonna close this out for now but do re-open it once all the comments are addressed 

Setting up via docker should ensure the app runs locally irrespective of OS. Check out https://github.com/gitcoinco/web/blob/master/docs/RUNNING_LOCALLY_DOCKER.md

**Comment by owocki** [comment]
@kvndlgs seems to me that you could just revert all the changes to the css files and just keep the avatar/utils.py changes and the svg and we should be mostly there..

**Pull request closed without merging**
